== Chapter V

[.chapter-synopsis]
* Attends the Circular Yearly meeting at Warwick
* Visits the families of Friends in Haverfordshire
* Religious services in England
* Attends the National Half-years meeting in Dublin

Through my late long and great bodily fatigues, my constitution was so shaken,
that a season of rest appeared desirable,
and I rather expected it some time before I returned home;
but the Lord was pleased to order it otherwise,
I hope to his own honour and my preservation:
for before and quickly after my arrival in England, divers prospects of duty opened,
which appeared likely to engage me for more than a year;
and which I was favoured to accomplish in the following order.

In about two weeks after my return, I attended our quarterly meeting,
where I was met by many of my dear friends, who rejoiced to see me,
and we were measurably favoured together iri the Divine presence.
Quickly after this I went to the circular yearly meeting for the seven western counties,
which was held this year at Warwick: it was large, and attended with holy solemnity.
My dear friend Samuel Fothergill and myself had
the principal share in the public service,
wherein the Lord favoured us; to whom be the praise of all his works now and forever.
This being the usual time of harvest,
with a prospect of the plentiful crops of grain being much injured by the heavy rains,
Samuel Fothergill in one of his testimonies noted it,
as a threatened judgment from Him who openeth the flood-gates of heaven or stayeth them,
to the effecting of his own righteous purposes.
The rain continued long, so much grain was spoiled or damaged,
as to occasion an extreme scarcity before the next harvest.

A few weeks after my return from this meeting, I went into Herefordshire,
to visit my sister Young and her family.
I there found my mind engaged to visit the meetings of Friends in that county,
which I did, except one of them, and returned home by way of Worcester.

Here it appeared right for me to get an opportunity
with some of the most experienced Friends of that city;
that we might together consider about setting forward the good
work of visiting the families of Friends in this county:
of which I had a view before I reached home from Ireland; and when I came there,
I found that a general visit to Friends`' families throughout the nation,
had been recommended by the last yearly meeting at London.
I therefore found freedom to offer myself to assist in that service,
provided the same could be accomplished so as
not to interfere with my other prospects of duty.
I also recommended to the Friends present,
the establishment of a meeting for ministers and
elders in the quarterly meeting for this county.
We were eminently favoured in this opportunity, and I left the city in peace,
and with a hope of some conclusion being come to at our next quarterly meeting.

I stayed at home a few weeks, being closely engaged in writing.
The 22nd of the eleventh month, I went to Worcester to attend our quarterly meeting,
under a weighty exercise of spirit, having an intention,
if Friends should accede to the aforesaid proposition of visiting families,
to stay and join them therein.
Our quarterly meeting was attended, in a good degree, with the Divine presence,
yet the service of it was hard and laborious.
Friends were backward in regard to giving in
their names to enter upon the visit to families,
concluding themselves unfit for so weighty a work; however some were nominated,
with whom I united, and concluded to stay,
and see how Providence might favour the undertaking.
I had some struggle betwixt affection to my natural parent,
and the pursuit of the service before me;
my dear and aged mother being likely to be left without either of her daughters;
my sister Ann being with my sister Young, whose children had the small-pox;
but I was enabled to pursue my duty,
and to commit her to the care of gracious Providence;
whose regard I found by account from herself, she signally experienced in my absence,
and encouraged me to continue in the service.
I began in great diffidence, and went through the families of Friends in the city;
but the Lord was with me,
and frequently clothed me with strength and wisdom suited to the occasion.
I was considerably favoured whilst in the city in the
exercise of my gift in the public meetings of Friends,
took leave of them in much love, and left it in peace and thankfulness.

The 19th of the twelfth month, being accompanied by Mary Oldbury,
a young woman of Worcester, who had an acceptable gift in the ministry,
I went to Pershore, a town wherein no member of our Society resided;
but Friends having a meeting-house there, held a meeting quarterly, which was this day.
It was large, but mostly composed of people of other societies,
I sat about an hour and an half silent, in which season my spirit was sweetly composed,
and resigned to wait the Lord`'s time to be put forth in service;
wherein I was afterwards much favoured,
the testimony of Truth being exalted in its own authority.
The people were very solid and attentive, and I left the town in peace,
accompanied by the before-mentioned Friend Mary Oldbury,
to visit the families of Friends in Evesham and Shipston,
which we were favoured to accomplish to a good degree of satisfaction.
We sat with Friends in a few of the meetings in Warwickshire,
and so came to my own monthly meeting of Chadwick,
having visited almost all the families of
Friends in the several towns which constitute it,
which were four.
I returned home in peace and thankfulness for the
gracious assistance vouchsafed by Divine goodness,
through this laborious service, the 24th of the first month 1757.

I stayed about home until the latter end of the third month,
in which interval I was closely engaged in attending to
services as they opened in that quarter,
and preparing for those distant ones,
which had been impressed upon my mind to be executed this summer;
viz. the attending the yearly meeting for the four northern counties,
and from that to the national meeting at Dublin; so to the yearly meeting at London,
and the succeeding quarterly meetings in Essex, Suffolk, and Norfolk;
which are styled yearly meetings, because at that quarter in the year,
there are some additional meetings for worship held, which are generally large,
both of Friends and others;
and after these meetings to visit the few Friends remaining in Holland.

My dear friend Lucy Bradley, being engaged to visit Friends in Ireland,
concluded to accompany me to Dublin.
I met her at Stourbridge on the 23rd of the third month,
and left her there for a few days with her relations,
with an expectation that she would meet me the 27th. I took an
affectionate leave of my dear mother and brother,
and went, accompanied by my sister Ann to Wednesbury;
a town at which a meeting was held quarterly, which happened to be on that day.
Here I expected Lucy Bradley to meet me,
and that we should from thence have pursued our journey together,
but being prevented from coming, through indisposition,
she informed me that she hoped to be able to meet me in a few days.

The meeting was large both of Friends and others, and divinely favoured;
and after it I took leave of my sister and divers friends,
and went that night to Rugely in Staffordshire,
and as I had for some time had a view of visiting the families of Friends in that county,
who are not numerous, I entered upon that service the 28th,
and visited such as were in that place, with some satisfaction.

The 29th, I went to Stafford,
at which place the quarterly meeting for the county was that day held,
and I laid before Friends my concern for visiting the families,
and had their concurrence therewith.

Here I met with my friend Samuel Emlen,
who came passenger with me in the same ship from America to Ireland;
in which nation he had travelled as companion to his aged countryman Abraham Farrington,
and had himself appeared in the ministry in that nation, to the satisfaction of Friends.
As he was in a weak, low state of mind, I was inclined to take him with me for a few days.
Accordingly we left Stafford in company,
and having visited several Friends`' families in the country, went to Uttoxeter;
where we proceeded in the same service.
My companion Lucy Bradley came to me here, to our mutual comfort.
We were favoured together with a blessed opportunity in
the friend`'s family where we lodged;
and after committing each other to the protection of Providence,
we parted from Samuel Emlen and went to Leek;
where we also visited the families of Friends,
which we were favoured to finish the 8th of the fourth month,
I hope to the mutual satisfaction of ourselves,
and of the Friends of the county who accompanied us in that service.

During my engagement in this weighty work,
I was surprised with the intelligence that my endeared friend and companion,
Mary Peisley, was removed from mutability.
She had been married but three days to Samuel Neale, a Friend of Ireland,
and went off with a few hours indisposition;
being doubtless removed from the prospect of a settlement on earth,
to a glorious eternal inheritance;
for which she appeared more visibly prepared than many others of the Lord`'s servants.
We had been companions together in many probations,
and our union in the Truth was strong, so that her death affected me deeply,
the more so from being attended with so singular a circumstance;
yet was my spirit thankful that she was taken at an hour when her crown shone brightly.
She had been a great example to me in divers respects,
and I begged to be assisted to follow her, as she had followed Christ.

The 9th we went to Warrington,
where a renewed occasion of thankfulness to gracious Providence was administered,
by the probability of the recovery of our dear friend Samuel Fothergill,
from an indisposition wherein his life had been despaired of.
This had much affected my mind,
from the consideration of the great loss the church would sustain by his removal,
and myself as an individual member thereof;
yet durst I not ask his longer continuance in this state of trials and dangers,
knowing that if Divine wisdom called him out of it now,
it would certainly be in the best time.

From Warrington we went, through divers meetings in Lancashire,
to the quarterly meeting at Lancaster,
which was signally favoured with the manifestation of Divine regard through the ministry.
I remember, before the public meeting, I was sunk so low,
that I scarcely expected ever more to be set at
liberty in the exercise of my gift as heretofore;
yet could not see what I had done to occasion a loss therein;
but in the meeting I was as remarkably raised.
Thus are the poor instruments abased and honoured for their own preservation,
and the good of the church; the one dispensation being as a ballast for the other.

The 26th, we went in company with several Friends towards Penrith,
where the yearly meeting for the four northern counties was to be held.
In our way we called upon that truly honourable mother in Israel, Grace Chambers,
who was very ancient and had been long indisposed,
with whom we were favoured with a refreshing opportunity.
How encouraging it is to young travellers,
to behold and consider such examples of perseverance!
It baffles the efforts of the adversary,
to persuade that it is impossible to hold out to the end;
and raises this language in the soul.
Lord, let my life and latter end be like theirs.
At Penrith we met my beloved friend Abraham Farrington,
another of these ancient worthies, and we mutually rejoiced to see each other.

The yearly meeting was large, both of Friends and people of other societies.
My spirit was bowed before the Almighty,
that I might be preserved acting in my proper place, in the course of my service therein,
and that my conduct might be unblamable; and through mercy,
I had humbling cause of thankfulness administered in the close thereof,
to Him who had exalted his own name and testimony through so weak an instrument;
unto whom be the praise now and forever, saith my soul!
Although this meeting was attended by several able ministers of the male sex,
it pleased the wise Master of the solemnity to employ them but little,
and to lay the weight of the service upon the females; who,
though the weaker vessels by nature,
are at times rendered strong through his Divine power:
and our brethren rejoiced that it was apparently so,
through the course of these meetings.

The exercise of my mind while at Penrith,
was added to by the prospect of my concern for visiting some parts of Holland;
for although before I left home I was resigned thereto,
and had imparted it to my relations, as well as to Friends of the monthly meeting,
that they might consider respecting granting me a certificate;
yet now on its near approach, my want of the language,
the various notions in religion which I knew prevailed amongst that people, my sex,
and for aught I knew, the being exposed to much hardship, revolved in my mind;
and being opposed to my little strength, depressed my spirits,
yet not so as to cause me to turn from the prospect,
or prevent my wrestling with the Almighty for wisdom and strength,
to know and do his will.

After the yearly meeting at Penrith, we went to Cockermouth,
and there attended a large general meeting.
My concern for Holland continuing,
and not expecting to be at home in time to attend our monthly meeting,
I wrote to my brother to procure a certificate for the accomplishment thereof.

The 3rd, we went on board a vessel bound from Whitehaven to Dublin,
and arrived at that city the 5th, having been favoured with fine weather on our passage;
but my spirit was much stripped of a sense of divine good,
and as I drew near the city it became depressed; in which state I landed,
and proceeded to my lodgings at Samuel Judd`'s. At my entering his house,
the remembrance of dear Mary Peisley affectingly occurred.
It was in this house that we separated in our return from America;
and therein we had spent many precious hours, in sweet union of spirit.
The national meeting began the 7th and continued till the 12th.
It was a season of close engagement and hard labour,
both in the meetings for worship and discipline;
but I was favoured in it with the unity of the living members of the Society,
and the helping hand of the Almighty and in the close,
was humbly bowed before him under a sense of his goodness,
variously manifested in sustaining my weak body under such laborious exercises,
and strengthening me spiritually to testify boldly against the sins of the people:
which although it might expose me to their censure,
yielded to my soul the peaceable fruits of righteousness.

After the conclusion of the national meeting,
I requested a friend to go and take my passage, saying,
I must get to our quarterly meeting; on which a friend present said,
I spoke as if I had the wind at command.
I replied, that if the Lord appointed my being there,
he would dispose the wind to favour it, which happened accordingly.

The 14th, I parted from my dear companion Lucy Bradley in much affection,
and quietly went on board a vessel bound for Parkgate,
accompanied by my friends Abraham Shackleton, Thomas Greer, and Joseph Inman,
who were going to the yearly meeting at London.
We landed at our designed port the 15th, and reached Stourbridge on the 17th,
where the quarterly meeting for Worcestershire was to be held;
and the meeting for ministers and elders began soon after we came there.

Here I was met by my dear mother and brother, to our mutual rejoicing;
and my heart was deeply affected with love and gratitude,
under the consideration of the many mercies extended to me;
and strong desires were raised to be enabled so to persevere,
as to be favoured with the continuance thereof.

We had a good meeting,
and many Friends who attended it rejoiced to see me returned in safety,
and after taking an affectionate leave of them, I went home.
