== Chapter VIII

[.chapter-synopsis]
* Visits Cornwall
* Marriage
* Circular yearly meeting for Cornwall
* Goes into Devonshire
* Visits Hampshire and attends the yearly meeting in London
* Visits Friends in Devonshire, Somersetshire and Dorsetshire
* Religious engagements in Ireland
* Letter to a Friend
* Return home
* Circular yearly meeting at Bewdley in Wales
* Letters to several persons

From the occurrences related in the close of the foregoing chapter,
until after I entered into a marriage state, I made no minutes of my religious labours,
although I was as constantly engaged as heretofore,
in attending yearly and quarterly meetings, etc. in divers parts of the nation,
visiting particular meetings of Friends,
as well as appointing some for people of other societies; and in the winters,
I mostly spent some time in London.
Yet so few remarkable incidents occurred,
that my movements appeared scarcely worth' noting;
except that the Lord's hand was revealed for my help and preservation,
through which I was enabled to sustain almost uninterrupted, though varied,
fatigue and exercise, both of body and mind.
After my sister Ann's marriage, a load of domestic concerns devolved upon me.
Through my mother's very great age, and my brother's frequent indisposition,
my times of respite from travelling and gospel-
labours were far from being seasons of rest.

A short time before I married, my left elbow was dislocated by a fall down stairs,
and reduced with considerable difficulty.
As that joint from my infancy had been weak,
and had several times been hurt by falls from my horse, as is before related,
it became from this time so weak, as to render my riding single improper,
and riding double was rather dangerous,
as I could not help myself on horse-back without my arm.

For the fulfilling of every purpose of Divine wisdom there is a particular season;
and although I married rather late in life,
the connection from its beginning was attended with such singular circumstances,
as marked its being superior to nature, although nature had its share in it;
and the restrictions laid upon my mind, and that of my beloved husband,
were too remarkable to be omitted in the memoirs of the
signally providential occurrences of my life.

I have already noted the meeting with William Phillips in 1749, at Swansea.
Before that time we were entire strangers to each other,
I do not recollect that I had ever heard of him.
My mind had been,
and was under strong restrictions in regard to entering into the marriage state,
should I be solicited thereto;
for as it appeared that for a series of years I should
be much engaged in travelling for the service of Truth,
I feared to indulge thoughts of forming a connection, which, from its incumbrances,
might tend to frustrate the intention of Divine wisdom respecting me.
This caution tended to keep me reserved in my conduct,
towards such as might be likely to entertain views beyond friendship,
in their acquaintance with me; and my mind, to the time of our meeting,
had been so preserved,
as never to admit the least impression of affection beyond that line, with any one.

William Phillips was then a widower, and had two young children.
His worldly circumstances I was unacquainted with,
further than that I then learned the place of his residence,
and somewhat of his business, which was, in part, that of an agent to a copper company.

He was considerably older than myself.
So that none of these circumstances could of themselves make a
connection with him desirable.vFor as to his employ,
which might seem the least exceptionable,
it was less pleasing to me than would have been his being his own free man.
It was therefore improbable that temporal
considerations should bias my mind in his favour;
and as to his religious experience, it appeared to be but in its infancy.
Fie had indeed, a frank and open disposition, which, joined to a good, understanding,
rendered his conversation agreeable; but I had but little opportunity to judge of this,
before it appeared that perhaps we might one day unite in the marriage covenant.

Upon observing him strictly,
I had the satisfaction to see that his mind was susceptible of the best impressions,
and bending out of the world, wherein, in some parts of his conduct,
he had taken too great a part.
His behaviour to me was prudently restricted,
though he afterwards confessed that his mind was affectionately disposed towards me.
We were favoured together, especially in one meeting,
with the uniting influence of Divine love, but parted merely as common friends.
Very soon after, a circumstance happened, which, without the least design on either side,
necessarily introduced a correspondence by letters between us;
and we exchanged several in restricted terms, suited to our situations.

In a journey to the western counties,
I had meetings in some towns where none were established,
particularly at Redruth and Truro in Cornwall,
at both of which William Phillips was very serviceable;
and his spirit being dipped into sympathy with me in my service, and mine with him,
under his religious exercises, it tended to strengthen the regard we had for each other;
yet such was the restriction we were preserved under, that no sentiment transpired,
nor was there any part of his conduct, more than was consistent with friendship:
and thus we again parted, and continued our religious correspondence.
But my mind becoming doubtful whether I had such an evidence
that our intimacy would ever rise higher than friendship,
as to warrant my retaining the prospect of it;
and ruminating upon the injurious consequences which might ensue to us both,
should our affections be engaged contrary to the Divine will; and that, perhaps,
the continuing an intimacy with me might prevent
his mind from settling upon some other person,
who might be a suitable companion for him through life; and seeing clearly,
that my religious prospects would not for a long time admit of my changing my situation,
I concluded it safest to relinquish our correspondence,
and to leave the event of the foundation of affection which was laid, to future time;
hoping, that if Divine wisdom designed a nearer union betwixt us,
he would prepare my friend to be a suitable helpmate for me.
My fear of erring on this occasion was proportioned to that superior love,
which bound me to the service appointed me; in the pursuit whereof,
I was desirous to relinquish every prospect and
connection which might retard my fulfilling it:
and I continued closely engaged in it for many years,
and kept an entire distance from my friend.

In this time our minds became so released from each other,
as to be at liberty to entertain other prospects of marriage;
and but for the interposition of a watchful Providence,
we might each of us have been engaged to our hurt.
But however promising the prospect might be to my mind,
I never was favoured with true peace, in looking to a marriage connection with any other;
and as to my friend, although he had entirely lost the hope of a nearer union with me,
however thoughtful he might be respecting its
being convenient for him to change his situation,
he did not find freedom to propose it to any other woman.
Thus we continued separated, and separately exercised;
I in close application to public service; and he in his worldly engagements,
and under various temptations and conflicts, inwardly and outwardly,
which called for the sympathy of a friend; when none was afforded,
save that of the never-failing Helper, by whose hand his head was sustained,
and he witnessed preservation even as from the "`paw of the lion and bear.`"

In the year 1766, I attended the circular meeting,
and visited most of the meetings of Friends in Cornwall.
Previously to my taking that journey, I had an intimation in my mind,
which seemed to point towards a revival of our intimacy.
This happened at a time when I was quite free from impressions
of natural affection towards William Phillips;
for I was deeply engaged in thoughtfulness respecting another friend,
and humbly and earnestly desirous to be informed whether I
might safely remove to the place of his residence.

Under this exercise, my mind was turned with uncommon force to Cornwall;
and the name of the place where William Phillips resided was revived with such strength,
that it was as if vocally spoken in my soul.
At the same time I was favoured with the sweet sensation of Divine love and life.
And although the removing to this poor country afforded no pleasing view,
I was willing to submit, if Divine wisdom appointed it; but as to William Phillips,
I doubted his having advanced in religion,
so as to render a nearer union with him safe but I could only judge superficially,
the exercised state of his mind being hid from me.

Hannah Shipley, of Uttoxeter in Staffordshire, was my companion in this journey,
whose affectionate attention to me, I remember with gratitude;
her service also in the ministry was acceptable to Friends.

When we came into Cornwall,
I was cautious of giving heed to the before-mentioned intimation;
and when I met William Phillips,
I was desirous to be favoured with a sense of the state of his spirit;
and was thankful to find it bending towards the spring of Divine life,
beyond my expectation.
We were frequently together while I was in the county; but never alone,
so as at all to enter into conversation on the subject of our former correspondence,
except when riding on the high road; when one day,
he mentioned the trial it was to him that I should so abruptly drop it;
and said he had cautiously avoided a conduct which might give me umbrage; and added,
that he had never admitted a sentiment of displeasure on the occasion,
as he concluded I had some reason for so doing, which was of sufficient weight to myself:
but if my being in a single station were the cause, I needed not to have feared him,
for although he loved me,
hitherto his mind had been under a restriction from
endeavouring to pass the bounds of friendship.
This was saying more than he had ever done before;
but during his being with me in this journey,
his behaviour was strictly consistent with friendship only.

One circumstance I think worthy of relating,
as it discovered both his sympathy with my religious engagements,
and how Divine wisdom works to the effecting of his own purposes.

After I left Plymouth, in my way into Cornwall,
it appeared that I should have a meeting at Plymouth Dock in my return.
This I intimated to a Friend of Plymouth then with me,
and desired him to inquire whether a proper place could be procured.
This Friend, and another from Plymouth, met me at the circular yearly meeting,
which was held at Bodmin, at which also was William Phillips.

They gave me no encouragement of getting a meeting at Dock;
indeed it was looked upon improbable that a place large
enough for the people could be procured there;
so they proposed that a meeting should be
appointed at Friends' meeting-house at Plymouth,
and that the people of Dock should be invited thereto.

This did not seem to promise relief to my mind;
for besides the Dock's being three miles distant,
the house might probably have been too small for the Plymouth people and them.
My concern for the Dock continued, but I said little about it,
except hinting it to my brother, who, with divers Friends out of Worcestershire,
was at Bodmin.
In the night before I left that place it pressed weightily upon my mind;
but I could see no way to obtain a meeting, unless William Phillips would accompany me;
who I knew had resolution enough to assist in the undertaking.

He designed going homeward the next day,
and I was reluctant to propose his going with us to Plymouth; but desired,
if my exercise for Dock was from the Lord, and it was right for him to assist me therein,
that it might be impressed on his mind to go.
After this, my spirit was relieved,
and in the morning I heard W. Phillips say to the Friends, I must go to Plymouth,
giving as a reason, that he had an uncle there who was unwell.
He afterwards told me,
this was the only reason he could assign for his mind being forcibly drawn to Plymouth,
which it was before he arose;
and when at breakfast he heard me inquiring whether a
place could be procured at Dock to hold a meeting,
he saw the cause of his being drawn to Plymouth, and immediately replied.
There is no doubt of it.

In our way to Plymouth,
we had a large satisfactory meeting in the market-house at Liskeard.
At Dock, my brother.
Friends from Worcestershire, and William Phillips, obtained a large school-room;
which opened into a square.

A window was taken out, and I stood in that, so as to speak to the people without;
and the house being full within, I believe all might hear,
though there was a great concourse of people.

It was a favoured opportunity,
at which the Friends who accompanied me for the promoting of it were very serviceable;
but had not William Phillips assisted them,
it did not appear probable that so large a meeting would have been procured,
and held so quietly: he was peculiarly fitted for such services.

After my return home, our correspondence by letter revived;
but although it soon passed the bounds of mere friendship,
our minds were clothed with caution of stepping forward without Divine direction.
For some years we saw each other but Seldom,
and that only as we met in the course of my service;
and notwithstanding a nearer union was from time to time pointed out,
yet our way not opening clearly to the accomplishment of it,
we did not marry until the 15th of seventh month, 1772; when,
in a large and solemn meeting held at Bewdley,
we took each other in the real fear of the Lord,
and therein had a strong evidence of his favour.

Many of my friends from the adjacent meetings met us upon the occasion;
unto whom my spirit was drawn forth in the best love; wherein,
after we had taken each other in marriage, I was led to advise, caution,
and encourage them.

The parting from my dear mother had been an affecting circumstance,
but it was a great satisfaction to me, that although her faculties were breaking,
she was sensible I was removed from her in Divine wisdom.
The morning I left her, she took a quiet steady farewell of me,
and told me she was satisfied Providence had provided for me,
to whose will she was resigned.
As my brother proposed accompanying me home,
my sister Summerfield staid with our mother in his absence.

After our marriage at Bewdley,
we proceeded on our way to my brother Young's at Leominster, where we staid some days,
and then went to Swansea, my brother and niece A. Young, accompanying us.
In our way to Swansea, we had a meeting at Hereford, and another near Talgarth in Wales,
where the Countess of Huntingdon had established a
college for the education of young men for the ministry.
Some of them came to the meeting, and several behaved rather lightly;
but one sought an opportunity with us afterwards,
and freely expressed his uneasiness in his present situation,
and desired to get amongst Friends.

He requested my husband's assistance to procure hum a suitable place;
but though one pretty soon offered, and he was informed of it, he declined accepting it.
Many are shaken by the power of Truth,
but few are steadily concerned to build upon its foundation:
and therefore it may with sorrow be said, "`Many are called, but few chosen.`"
We had also a meeting at Llandilo, which, though not very large, was satisfactory.

We staid at Swansea some weeks, the wind being contrary for our going down the channel.
During our stay there, the first and weekday meetings were mostly large and favoured.
A particular visitation of Truth was extended to some
who had gone out from Friends by marriage and otherwise,
who were affectionately entreated,
and warned of their danger and trifling with the day of their visitation,
which was hastening fast to a conclusion.

Several of these were much affected, and two of them soon finished their course.
I have admired the mercy of God, even to the backsliders and revolters from us;
from few of whom the witness of Truth is so withdrawn, but that they will confess to it;
and many to the latter stage of life are followed with close convictions,
and tender calls to return to the heavenly Father's house,
and yet continue in a country far remote from it:
having so connected themselves with those who are in the spirit of this world,
as to conclude it impossible to break loose from them.
But, although through inattention to the holy Spirit of light and grace,
they may have rendered their way very difficult, and mingled for themselves a bitter cup;
yet if they would attend to that Divine love which draws them,
they would experience its power to release their spirits from the power of satan,
and bring them into "`the glorious liberty of the children of God.`"

I visited the families of those professing Truth in Swansea;
but the time for holding the circular meeting for the western counties approaching,
and it being to be held this year in Cornwall, my husband was earnest to get home.

Another meeting, also, which was usually very large, held annually near his habitation,
engaged our attention; therefore, the wind not serving for us to go to Cornwall,
we crossed the channel to Ilfracomb in Devonshire,
and through Divine favour landed safely, though not without some danger;
and proceeded directly home to Redruth.
The first-day after we reached it, we attended the before-mentioned meeting at Key,
at which it was supposed there were fifteen hundred people; it was held without doors,
and was a favoured opportunity.

The next week came on the circular yearly meeting, which was held at Helston,
was extremely large, and well attended by Friends;
and in divers meetings the testimony of Truth was
exalted through several of the Lord's chosen servants.
I was largely and livingly opened in his service, by him who alone can qualify for it;
to whom I ever desire to ascribe the praise.

For some time after I came home, a pretty many serious people attended our meetings,
and doctrine suitable to their states was opened;
but most of them were too much under the influence of
human teachers to receive the Truth in its simplicity,
and walk by its light.
I found a concern to appoint a meeting at the place called St. Agnes,
a town on the north sea coast.

Near this place the people were addicted to the barbarous
custom of plundering vessels wrecked upon the coast.
Abundance of people collected, so that we were obliged to hold the meeting in the street,
which was a remarkably quiet solemn opportunity.
Many of the wreckers were supposed to be present,
and I had to reprove the practice very closely;
which might be supposed to have present effect,
for the people exerted themselves to save the cargo of the next vessel that was wrecked.

In a few weeks after the circular meeting,
I went to the quarterly meeting for Devonshire, held at Kingsbridge,
and thence took a turn into the north of the county, accompanied by William Cookworthy,
and several other Friends.

We appointed meetings in several places where none were settled, in all of which,
except at Great Torrington, we had good satisfaction;
and there we had reason to conclude that we appointed the meeting at too late an hour,
through condescension to some who expressed a desire to attend it,
and could not come sooner.

It was first-day, and the evening coming on,
a crowd of disorderly people impeded the service; and my mind was the more pained,
because an earlier hour had been pointed to me for holdings the meeting.
We had a good meeting in the town-hall at Launceston,
after which William Cookworthy went homewards, and I to Wadebridge.
I had a meeting there to satisfaction, and returned home,
under the persuasion of having been engaged in the discharge of my duty,
and assisted by Divine grace in the performance thereof.

I staid at and about home until near the time of the yearly meeting at Bristol, 1773,
which I attended; and thence, accompanied by my dear friend Lydia Hawksworth,
went to that in London.
We visited the meeting of Friends in Hampshire in our way,
and I returned into Cornwall to our quarterly meetings held at Looe,
in the seventh month; where my husband met me,
and we went together to that for Devonshire, held at Plymouth.

The annual meeting at Key was this year large and satisfactory;
after which I went to visit my aged parent and other relations,
and attended the circular yearly meeting at Gloucester.
I visited the meetings of Friends, as I went along, who were truly glad to see me,
and we were favoured together with the sweet influence of Divine love and life.
The circular yearly meeting was very large both
of Friends and other professors of religion,
and was much favoured through the ministry.
The select meeting for Friends was a memorable opportunity.

Plentiful are the showers of gospel rain which often fall upon these occasions;
but in regard to many minds visited, it is like water spilled upon a stone, which,
though it wet its surface, doth not change its nature; but in others,
I hope it is like "`Bread cast upon the waters,`" a very unstable element,
yet it "`may return after many days!`"

From this meeting I returned home with my friend Sarah Tregelles.
In my way I had two large meetings at South Molton to good satisfaction.
There are none professing with us in that town;
but some Friends from Exeter accompanied us,
and others under convincement from the north of Devonshire met us here.
I returned home to our quarterly meeting at Penzance,
and was thankfully received by my dear husband,
whose great affection rendered it hard for him to be so frequently separated from me,
but in resignation to the Divine will he was favoured with peace.

In the first month 1774, I had a satisfactory meeting at Helston, in the town-hall.
The weather was wet, and the seat whereon I sat was very damp,
but on the evening after the meeting I did not find I had taken any cold.

Next morning I was well as usual, but suddenly, I found myself much indisposed,
and was seized with convulsions in my head.
This alarmed my husband, who called upon an apothecary, and I quickly got better,
and we went home, where the disorder returned.
In a few days however I appeared to be much better, but I quickly relapsed;
and in a few weeks was reduced to a state of extreme weakness.

My affliction in this time of indisposition was very great,
but I was preserved in patience, and when I revived a little, wrote as follows:
"`I am now reviving from bodily weakness.
O! that it may be with renewed strength to serve
the bounteous Author of my being and blessings,
who bringeth low and raiseth up in his wisdom and mercy.
He knows when afflictions are needful to his servants; and in this season of weakness,
my soul has thankfully acknowledged his tender care,
to prevent my spirit's settling with too great attention on "`the things which are seen,
and which are temporal.`"

We often want to be awakened to seek with greater earnestness those "`
things which are eternal,`" viz. righteousness and its consequence.

Divine favour; by being put in remembrance,
that the time of our departure hence may be at hand.
"`Blessed,`" indeed, "`is that servant who,
when his Lord cometh`" and calleth from works to
rewards "`he shall find watching:`" and what great,
need is there to watch against the encroaching spirit of this world;
whereby many quickened, enlightened minds have been benumbed and darkened;
and their desires after the food which nourisheth up the soul unto everlasting life,
weakened; until at length they have left the Lord's table,
and fed with pleasure at the table of idols!
The friendships of this world, which are enmity with God,
have been delighted and gloried in, and its interests principally sought.

These, though they may appear orderly in the view of men,
are in danger of becoming as "`trees twice dead;`
" they having been dead in a state of nature,
and quickened by Divine grace.
If these totally fall away from their spiritual exercise,
how shall they be again renewed? Alas! the judgment is determined;
they must be plucked out of the Lord's plantation,
wherein only living fruit-bearing trees can remain with acceptance.`"

"`In this time of weakness my spirit hath been renewedly visited,
and my understanding opened in Divine love and light:
and therefore it rests with me to commemorate it,
as a fresh instance of the love of my heavenly Father who,
in all the dispensations of his wisdom to his children,
seeks their being perfected in righteousness;
that he may more and more bless them with his favour whilst here,
and finally receive them into everlasting mansions of bliss.`"

But although I grew so much better as to get about in the spring,
my constitution still laboured under a heavy load,
without hope of being entirely relieved;
and I was therefore frequently led to pray for patience and
resignation to suffer in the way Divine wisdom might permit;
and, under great weakness,
was enabled in a degree to come up in the service appointed me,
in our little meeting and about home.
I was reduced so extremely low by this indisposition, as to be doubtful,
whether I could have survived it, had I not been removed from my mother's family;
as in that, considering her situation, and my brother's,
it was unlikely I should have been so released from care,
and so tenderly and affectionately attended to, as by my dear husband,
and the assistance he procured for me.

In the seventh month I left home in order to attend the circular
yearly meeting and once more visit my aged and honourable parent,
who had several times expressed a desire to see me.
My husband accompanied me to Torrington,
where we had a meeting of Friends scattered round in that neighbourhood.
From Torrington we went to Appledore, and crossed the Channel into Wales,
and I proceeded to Bristol; where, and in its neighbourhood,
I staid until my husband's business admitted his coming to me;
and thence we proceeded to Dudley,
visiting the meetings of Stourbridge and Worcester in our way.
I found my dear mother extremely weak,
and her faculties so impaired that she did not know me;
yet I thought she was sensible I was one for whom she had a great affection;
and after seeing me several times she recollected me,
and was much pleased with my company.
After I had taken my leave of her, she said,
"`Now I shall not be here long;`" and so it proved, for she died in the following winter.

From Dudley we proceeded to the circular yearly meeting held at Kington, Herefordshire,
which, considering the country not being so populous as some others,
and but few Friends in the neighbourhood, was large, and for the most part satisfactory.
I still continued in a weak state, yet was enabled to take a share in the service,
Divine mercy strengthening beyond my expectation.
After this meeting we went to Bath, Dr. Fothergill having advised me to drink the waters.

In the spring of 1775 I visited some meetings in Devonshire, Somersetshire,
and Dorsetshire, in my way to the yearly meeting at London.
Lydia Hawksworth accompanied me in some part of the journey.
Such was my state of bodily weakness, that my getting along,
and being enabled to go through with the service assigned,
claimed my admiration and thankfulness.
I attended the meetings in London with considerable diligence, though very unwell,
got out of town as soon as I could, and, accompanied by Lydia Hawksworth,
went to her mother's, Deborah Waring, at Alton; where I rested a few days,
and then proceeded to the quarterly meetings for
Hampshire and Dorsetshire held at Ringwood and Poole;
and so to our quarterly meeting at Looe.
Here I met my dear husband, to our mutual rejoicing,
although my languid state affected him painfully.

From Looe we returned home, and through Divine favour I so gathered strength,
as that in the eighth month I again left home, accompanied by my husband,
intending to go through Wales to the circular yearly meeting.
I had several meetings in our own county and Devonshire to good satisfaction,
and we crossed the Channel from Appledore to Swansea.

A circumstance happened at Appledore worthy of observation.
Some sober people of that place were desirous of a meeting;
but I was restrained from having one so public as was wished,
yet was quite free to sit down in a friendly woman's house,
with such as she might think proper to invite.
The meeting was held in an upper room, the window of which fronted the river.
A number of serious people came, and I had a favoured opportunity amongst them.
Immediately as I sat down, one of the persons present stepped to me, and told me,
the vessel we wished to go in was getting under sail.
This was unexpected intelligence, as we were informed she would not sail that tide,
and had not taken our passage in her.
Had we held our meeting in another place,
she had probably slipped away without our knowledge;
as her sailing was perceived by the before-
mentioned person in the meeting from the window.

As I was now free to go, I immediately went out at the back-door, into a boat,
and on board.
My husband went to the inn, and reached the ship, with our clothes, in a boat,
before she got over the bar.
We had a good passage; but had we missed this opportunity,
we should have suffered much in coming in a sloop the next day,
as the weather changed to wet and stormy.

This is one of the many instances of providential direction I have experienced.

We staid at and about Swansea about two weeks; and thence proceeded to Leominster,
Worcester, and Dudley.
From Dudley, after spending a short time with my brother,
we went to the circular yearly meeting held at Coleshill, Warwickshire;
which was large and Divinely favoured.
From Coleshill we went through Coventry to Warwick, spent a little time with my sister,
who, with her husband and son, were now settled there;
and thence we went through Evesham, Painswick, etc. home, where we arrived in safety.

In this winter a concern rested upon my mind once more to
visit Friends in Ireland and in my way to that kingdom,
to attend the quarterly meetings at York, Lancaster, and Westmoreland,
and the yearly meeting for the four northern counties to be held at Keswick.

My beloved friend Lydia Hawksworth was given up to accompany me,
and we accordingly prepared for the journey;
and in first month 1776 my husband accompanied me to Bristol.

The weather was extremely cold, and the snow so deep that the roads in Devonshire,
and thence to Bristol, had been impassable, and were then dangerous;
but through Divine favour we got along safely,
although the cold was so extreme that it was hard to bear.
The road in some places was cut through the snow,
so that it looked like passing through a deep hollow way,
which had a very striking appearance.

At Bristol, my dear husband left me to go to Swansea, where he arrived safely,
although the Severn at the New Passage, where it is three miles over,
was so full of ice as to render crossing dangerous.

Just at this juncture, my companion's mother died, and she went to attend her funeral.
I staid over first-day at Bristol meeting and proceeded,
through some meetings in Gloucestershire, etc. to Dudley, where my sister met me.
We spent some time together with my brother, and I went to Birmingham,
where I was met by my companion, and we proceeded on our journey.

Our first meeting was held in the town hall at Stafford, which was large, solemn,
and satisfactory.
From thence we went to Leek,
and passed through several meetings in Cheshire and Lancashire, to Sheffield,
and so through many meetings in Yorkshire, to the quarterly meeting at York.
After the meeting at York I was concerned to have one at Tadcaster,
where there was no Friends' meeting-house; and another near Harwood,
which was very satisfactory; and another, on the first-day, at Otley, which was large,
and I hope serviceable.

Thence we went, through several meetings, to Lancaster,
attended the quarterly meeting there,
afterwards to Westmoreland quarterly meeting held at Kendal,
thence to the yearly meeting at Keswick, and so to Cockermouth and Whitehaven.

We had travelled from Birmingham in sixty-two days, five hundred miles,
and attended fifty-six meetings; and as much of the service of meetings lay upon me,
my natural strength was greatly exhausted before I embarked for Ireland:
but I had abundant cause to acknowledge that Divine aid was from time to time dispensed;
by which I was enabled to press forward, though under very painful feelings.

We went on board a large vessel at Whitehaven on the 21st of the fourth month,
and landed at Dublin the 25th. Our passage was not without danger.
One night a vessel run so near ours, that they became entangled in their rigging.
The captain and sailors were much alarmed, but we got clear.
How imprudent it is for vessels not to hang out their lights.
As our preservation was great, it claimed our deep thankfulness: a very little more,
and probably one of the vessels had sunk, and the other might have been much damaged.
Another night we lay at anchor near the Isle of Man,
and had reason to conclude ourselves in shallow water upon a sandbank.
Had the wind blown up fresh, it might probably have been of bad consequence.

Our captain had not been accustomed to navigate the Irish Channel;
and when we drew near Dublin Bar, appeared regardless of the danger of crossing it,
wishing to get into port without a pilot, although the wind was rough.
A pilot, however, espying us, came on board, and took the vessel safely in;
but the tide was so far spent, that she threw up the mud with her keel,
as we passed the bank called the Great Bull.

We arrived at Dublin a few days before the national half-year's meeting began.
This allowed us time to attend several meetings with the Friends of that city;
wherein the spring of the ministry was livingly opened
to the states of many professors amongst us:
and although I had to lament the stript state of that city,
through the removal of useful members,
and the weakness of many who remained in the Society;
yet was there cause for thankfulness,
in feeling the fresh extending of the Divine visitation to them.
The half-year's meeting was large,
and signally favoured with an awakening searching visitation;
and I was so helped therein, that many of my Friends,
who had been with me in former services in that nation,
rejoiced that the heavenly Master had again sent me to see how they fared.

I write these remarks in reverence and thankfulness to the
Great Putter forth and Qualifier for the services he appoints;
who, to keep the minds of those whom he favours humble,
permits them to be tried with hidden exercises.
This was my case through the course of this journey,
wherein the spring of gospel-ministry was largely opened;
and I often appeared to my friends as clothed with a royal robe, though, underneath,
I was girded as with sackcloth.

From Dublin,
we proceeded to visit the meetings through the main body of Friends in Leinster province,
to that of Ulster; wherein we visited all the meetings,
except two or three very small ones,
the Friends belonging to which we desired to meet us at another meeting.

We attended the quarterly meetings in both provinces,
and returned back to Dublin the 2nd of the seventh month, where we staid until the 12th:
in which time we attended meetings either for worship or discipline almost every day;
and Divine condescension in opening fresh matter, suited to the several occasions,
was so admirable,
that it appeared as if every state and office in the Society was ministered to.

By this time my natural strength was much exhausted;
yet we pressed on through the counties of Wicklow and Wexford,
and were at a province meeting at Enniscorthy,
which was very large and crowned with solemnity.

Here we took leave of Friends of that province, and proceeded to that of Munster,
wherein there are but few meetings, but the distances mostly long.
My reduced state rendered it hard getting along;
yet I was enabled to visit all the meetings, except a small one at Bandon,
and favoured to discharge my duty therein; although my voice was sometimes so weak,
that it was with extreme difficulty I exerted it to speak so as to be understood.
When we came to Clonmell, and had attended the meeting there,
it seemed proper for us to retire to the house of our
friend John Grubb about two miles out of the town;
whither I went the 8th of the eighth month, and staid until the 14th,
being much indisposed.
Here I was affectionately received and attended,
and the quarterly meeting for the province being held at Clonmell during my stay there,
many Friends came to see me, and we were favoured together.
I was enabled to speak beyond my expectation, to the comfort and encouragement of some,
and caution of others, and took a solemn farewell of them in the love of Truth.

[.asterism]
'''

About this time she penned the following letter, viz.

[.signed-section-context-open]
To a Friend of Ireland, written a short time before I left it, in the year 1776.

[.salutation]
Esteemed friend,

As I have had some cause to doubt the rectitude of
our determination of not spending a night at thy house,
I am inclined to essay a few lines, as a friendly salutation,
as well as to intimate what appeared to me proper to
recommend to thy consideration and practice.
As a member of Society,
disengaged from the necessity of being much employed in worldly business,
it behoves thee to attend steadily to the filling up that station in the church,
for which Divine wisdom designed thee; that, glorifying him with thy body, spirit,
and substance, thou mayest, in the conclusion of time,
receive the answer of "`Well done good and faithful servant;`"
which those are not likely to be favoured with,
who "`dwell in their ceiled houses,`" and settle down
in the enjoyment of their temporal possessions,
while the Lord's house lies waste.

There are so few who are of clean hands,
and are therefore fit to take part in the active services in the church,
that I cannot but regret the loss of some who are seeking concealment,
contenting themselves with preserving a fair character amongst men,
and attending on the external duties of religion; but who,
had they devoted their faculties to the Lord's service, might have been girded for it,
and stood as in the front of the battle.
Thus, clothed with concern for the welfare of their fellow members in Society,
their zeal for the promotion of Truth would, in an especial manner,
be manifested by an engagement to cleanse the camp from
those who bring a reproach on our holy profession;
and for the preservation of our youth from the snares of the enemy.
Well, my friend,
it is with me to query whether thou hast taken thy proper share in this work,
or hast been excusing thyself, and leaving it to others.

I know nothing by outward information,
but as something like a jealously rested on my mind respecting thee,
I am willing to intimate it; at the same time assuring thee of my esteem for thee,
as one of the Lord's visited children; who, I hope,
has been in a good degree preserved "`from the corruptions that are in the
world through lust;`" and hast received a portion of that precious faith,
which in all ages has been delivered to the saints,
through which some in the present day have obtained a good report,
and been rendered very serviceable.

Whether thou mightest not have stood amongst those chosen,
and (shall I say) dignified servants, it behoves thee to inquire.
Must the poor and the illiterate, who are "`rich in faith`" and good works,
be brought to condemn those amongst us who have received much spiritually, naturally,
and temporally? Yea, verily:
some of these have done so little that the sins of omission
must be chargeable upon them whilst others who have had to
struggle under difficulties in regard to temporal things,
and appeared comparatively to be of but low understandings,
have come up nobly in the Lord's cause, and shone as stars in the firmament of his power.
Well, my friend, look to thy part of the work,
and solemnly attend to the filling up thy measure in righteousness.
"`Let no man take thy crown.`"

Something of this sort seemed to point towards thee;
and in that love which seeketh thy increasing in the increases of God,
do I communicate it; and now add a few words in regard to thy wife,
for whom thou art doubtless tenderly concerned, and,
considering her delicate constitution,
mayest justly fear the consequences of her nursing unavailing sorrow.
I wish she would imitate David, who, when the child was dead,
arose and washed himself and ate: for it is no doubt acceptable to kind Providence,
that when we are deprived of one temporal blessing,
we should humbly rejoice in those which remain, and say with Job,
The Lord gave and hath taken away, and blessed be his name.
Hath he not a right to recall what he hath sent us? But
unprofitably to sink under such strokes of his hand,
appears to me to savour of the sorrow of the world, which worketh death,
sometimes both to body and spirit, if persisted in.
I therefore beg she will look from the beloved object, now no more her's;
and consider how graciously the Father of mercies hath dealt with him,
in removing him thus early from this state of conflicts.

When our attention is rightly turned to consider what is lacking in ourselves,
we are not so subject unprofitably to ruminate on circumstances like these; but,
being principally concerned to be prepared to participate in
the happiness of those "`who die in the Lord,`" shall desire
that all may finally "`work together for our good.`"

I now conclude in true love, your friend,

[.signed-section-signature]
Catherine Payton

N+++.+++ B. These Friends had lately lost a young son.

The 14th, we went to Waterford, but I continued so much indisposed,
that it appeared best to go into the country; so we retired to a village called Tramore,
by the sea-side.
Here we staid from the 15th of the eighth month, till the 9th of the ninth month.
My indisposition continued and reduced me very low; but blessed be the Lord,
his hand sustained me, and through all,
my spirit was at times set at liberty in his
service to the admiration of myself and friends;
many of whom from Waterford came to us there,
and we had divers seasonable opportunities with them,
as well as with some who were at the place to bathe in the sea.
My nerves being extremely weak, I was also advised to bathe,
by the doctor who attended me, but I believe it had rather a bad effect.
We had not staid at Tramore so long, had there been a suitable vessel at Waterford,
ready to sail for England.
On our return thither, we had two meetings with Friends in a large parlour,
at the house of our friend Isaac Jacobs,
my voice not being equal to a meeting in the meeting-house.
Thus we visited Friends in that city pretty generally,
and the 12th embarked on board a vessel bound for Minehead.

Our friend Robert Grubb, of Clonmell, accompanied us, being in sympathy inclined thereto;
which we accepted as a favour from Providence.

Our passage was easy as to wind; but my great indisposition,
and my companion's extreme sea-sickness seemed to render such an assistant necessary,
and he was very attentive and serviceable to us.
When we came near our desired port,
the wind turned against us and the weather became rough.
However, the captain got over the bar just in time, for had we been but one hour later,
we must have been driven back to sea, if not to Waterford:
we landed at Minehead the 14th. There is only Robert
Davies's family of our Society in that town.
He was from home, but one of his children met us upon the beach,
from whence it was a long walk to his house.
When we came into the street, we saw an empty cart going up it,
and asked the carter to carry us to our friend's, which he readily did.
My dear husband met us here, to our mutual satisfaction;
though to receive me back in so weak a state was affecting to him.
The 15th was first-day, but I did not attend the meeting at the meeting-house,
but had an opportunity in the afternoon with the Friends belonging to it,
in our friend's parlour.

The 16th, we left Minehead, and travelled homewards by easy stages,
my dear companion accompanying me to the verge of our county,
whence she turned to the circular yearly meeting held at Bridgewater.
She was indeed a most tender affectionate companion, and a deep travailer in spirit,
both in meetings and private opportunities:
and although her public service in this journey was not large, it was very acceptable;
and her private labours in many families were signally under that heavenly anointing,
from which she was concerned to minister.
I hoped to have been able to attend the circular yearly meeting,
and pressed forward in Ireland, in the fore part of this journey,
in order to get to England in time; but after our return from the north of Dublin,
it was much impressed upon my mind,
that I should have but just strength to accomplish the service in that nation,
and so it proved.

I had travelled in this journey in England and Ireland, about two thousand English miles,
and attended one hundred and ninety-two meetings, besides family opportunities,
and visiting the sick.
Sometimes we had several private meetings of this kind in one day,
and seldom were without one, at least.

After my return home, I continued much indisposed,
and my nerves so irritable that I had continual spasms for a considerable time;
and my dear brother James Payton came to visit me, and becoming very unwell,
was detained the winter.
As I gathered strength, I was enabled to attend upon little services about home;
and my friend Lydia Hawksworth coming to see me,
we visited the families of Friends in Falmouth and Marazion monthly meetings,
except one or two of each, whom I afterwards saw:
in this service the Lord was with us of a truth.
Soon after Lydia Hawksworth left me,
Sarah Stevenson came to visit Friends in this county; in company with whom,
I visited most of the families belonging to Austle monthly meeting,
to our mutual satisfaction; my dear husband accompanying us in this service.

Until the seventh month in this year 1777,
I had not been out of Cornwall since my return from Ireland in the ninth month 1776,
which was the longest period I remember to have
been confined within the limits of one county,
since my first journey in the service of Truth into Wales,
in the year 1749. I do not mention this as thinking much of my services;
for although it has been my lot to be more constantly
employed than many others of my fellow-labourers,
I can truly say, I frequently look upon myself as an unprofitable servant;
and when laid by a little, have to ruminate upon my many weaknesses;
under a sense whereof I feelingly acknowledge that what I am,
that is acceptable to the Lord, or honourable in his house, I am through his grace;
and I often admire at his employing me so much in his service.

In the seventh month this year, in company with my dear husband, I went to Swansea,
his business, and to visit his mother, calling him thither.
In our way we had a meeting with Friends in the north of Devonshire;
but being yet very weak,
I was easy to pass along without engaging much in public service.
We had a good meeting at Appledore with some serious people,
and crossed the Channel to Swansea, where we staid about two weeks,
and proceeded to Bristol.

In our way between Newport and the New Passage, which we intended to cross,
we received information that the Passage-house was so full of people
that there was no probability of our getting a lodging there;
so my husband intended going forward to Chepstow,
though neither of us liked the prospect of crossing at the Old Passage; but our minds,
especially mine, not being easy to proceed thither,
we stopped at a small inn about two miles from the New Passage,
and got a comfortable lodging, and next morning proceeded to the New Passage.

We got safely over the Channel, although the wind was squally; but the same tide,
the boat from the Old Passage was lost, even while we were on the water, and several men,
with many oxen, drowned.
Had we gone to Chepstow we should most probably have been in her.
Thus kind Providence signally preserved us.

After about a week's stay at Bristol, and visiting Frenchay meeting,
we went to Worcester, so to Bromsgrove and Dudley.
I was still in a very weak state, yet enabled to attend meetings,
and labour in them to the comfort of my friends and my own peace;
although at times in great bodily pain.
My sister met me at Dudley, and we were glad to see each other.

From Dudley we proceeded to the circular yearly meeting held this year at Bewdley;
and in our way we had a meeting with Friends at Stourbridge,
wherein my weakness was such,
that I could hardly impart what pressed upon my mind so as to be heard.
I was discouraged from looking towards the solemnity at Bewdley,
with expectation of being able to take much part in the public service;
but was desirous to be assisted to labour in spirit for
the help of my brethren and sisters engaged therein.
On the seventh-day evening, the meeting for ministers and elders was held,
wherein I had something to impart, in so low a voice as painfully to affect my friends;
who might reasonably conclude it probable that my strength was so exhausted,
as that I should not long be capable of public labour in the church;
and indeed my own feelings of general weakness coincided with that apprehension;
but in the course of the public meetings the Lord's power was wonderfully manifested,
in strengthening me for service, to the admiration of all who saw my extreme weakness,
and my own also.
Indeed with humble gratitude I may acknowledge that it appeared miraculous;
for I do not know whether I was ever able to speak with
greater strength of voice and sentiment,
than in the last meeting; so that although the booth was very large and crowded,
I believe all might hear:
and to the praise of the Great Name be it commemorated
that his power was signally over the meeting.

This extraordinary manifestation of favour tended to strengthen my mind,
which for a long time had been sorely exercised with many fears,
insomuch that my spirit was weary in the conflict,
and ready to hope for death rather than life.
Yet was I secretly sustained so as to press forward,
and mostly to preserve a cheerful countenance,
so that my friends could not perceive how my spirit was
exercised and abased in the sense of infirmities,
even when I was evidently clothed for service.
Thus it hath pleased Divine wisdom to permit me to be
tried in my passing along from youth to advanced age:
doubtless for some good end,
and I desire thankfully to commemorate his gracious and wise dealings with me,
in humble hope that finally all will work together for good; when,
having filled up my measure of sufferings,
I may be accepted in and through his beloved Son.
It is not for us to query why these afflicting dispensations are appointed,
but patiently to endeavour to wade through them.
We may be certain they will tend to humble our spirits and prepare for service,
as my soul hath many times experienced; and therefore can pray,
that I may be passive in regard to the dealings of the Lord with me,
who best knows what is necessary to effect, the glorious purpose he has in view,
viz. the thorough sanctification of my spirit,
and reducing it into "`the obedience of Christ:`"
concerning whom it is written "`Although he was a son,
yet learned he obedience by the things which he suffered;`" and if so,
his servants can expect no other.

I have sometimes considered what that suffering of Christ was,
whereby he learned obedience; seeing that he could not suffer for disobedience,
being in all things subject to the will of his Father,
But as man he was made like unto us,
and had the same feelings as have the members of his mystical body;
and although he was never overcome of the enemy, was liable to be assaulted by him.
He had to bear the contradiction of sinners against himself; and, no doubt,
in the course of his ministry felt the oppressive weight of contrary and wicked spirits,
as the members of his church now do in their measure.

As man, we may suppose that he had the same reluctance to pain and insult as we have;
but in submission to his Father's will,
did and suffered what he in wisdom and mercy to mankind appointed him.
His followers also must thus "`be made conformable to his death,`" if
they have part with him in his resurrection unto glory.
And although some of them may be left in seasons of extreme conflict,
as he was in the most extreme, without the sensible feeling of the Divine presence;
yet that power which appoints their suffering, secretly sustains under it;
and when they have filled up their "`measure of suffering for his body's sake,
which is his Church,`" with all other afflictions attendant on this probationary state,
they will with him be able to say,
"`It is finished;`" and as good and faithful servants enter into the joy of their Lord.

After the before-mentioned memorable meeting at Bewdley, I recruited in health,
though yet attended with very painful feelings.
We returned home pretty directly, taking the quarterly meeting for Somersetshire,
and some other meetings in our way; and the remainder of this year I spent at home,
attending to services in our own county as they opened.

The 20th of the fourth month 1778, I again left it in company with my dear husband,
intending for Wales, he having business there,
and I had an engagement to attend the yearly meeting for that principality.
We proceeded to Ilfracomb, and, in our way,
had a meeting with Friends in the north of Devon at Newtown,
At Ilfracomb we had a large satisfactory meeting,
amongst a people very ignorant of our principles.
We were detained here by contrary winds until first-day,
and as we sat together in the morning,
I earnestly desired to know whether any further service was required;
as it did not appear probable we should be released that day;
and afterwards as I sat quietly in my chamber,
our Lord's words to his disciples arose in my mind, "`Arise,
let us go hence,`" and soon after,
the captain of the vessel came and told us he intended to sail.
We went on board in the afternoon, and before midnight landed at the Mumbles,
and the next morning proceeded to Swansea.
My husband's mother was lately dead; concerning whom I may say,
that she was an exercised woman, and I believe finished her course with joy,
about the ninety-seventh year of her age; and except her hearing,
she retained her faculties to admiration.
As her furniture, with her servants, remained in her house, we settled there.

The 2nd of the fifth month we went for the Welch yearly meeting,
and were at a meeting by the way at New Inn meeting-house,
which was large and very satisfactory, Samuel Spavold of Hitchin in Hertfordshire,
John Lewis of Haverford-west, and Thomas Carrington, froin North America,
were there also;
and we went in company that afternoon to a meeting which was appointed by John Lewis,
at a Friend's house, not far out of the way to Llandovery,
and to Llandovery the same night.

Here the yearly meeting was held, and began the next day;
and through the various sittings, was a favoured season both to Friends and others.
The weather being very wet, it was not so large as was expected,
but many sober people attended, unto whom the gospel flowed freely.
In the course of my travels before my marriage,
I had two very satisfactory meetings at this place, where none live who profess with us.

My spirit, in the course of the yearly meeting,
was dipped into sympathy with the few Friends scattered about Wales:
and to those who were there assembled, encouragement and instruction were afforded.
In our return to Swansea, we had a large and much favoured meeting at Llandily;
the before-mentioned Friends and John Townsend of London attending it.
They went back to a meeting at the New Inn meeting-house,
and next day we all met again at Swansea.
The afternoon meeting there was large, solemn, and instructive.

We staid at Swansea until the 14th, then went to Cardiff,
and on the next morning had a small meeting there with
a few who met together on the first-day;
several of whom were not in membership with us.
I was very unwell, but was helped to speak to their states,
and was well satisfied with the opportunity.
We reached the New Passage that night,
and next day we got to Bristol to attend the yearly meeting there,
which was large and divinely favoured.

Samuel Spavold, John Townsend, Thomas Carrington,
and other Friends in the ministry attended it.

On the 21st I was at a meeting at Frenchay, with Thomas Waring of Leominster;
and after the meeting,
my friend Lydia Hawksworth and I had a good opportunity with a young woman,
who was likely to marry out of the Society, She was much affected,
yet held her resolution to engage in the connexion.
Her intended husband was a man of property, and had long resided in America,
where he took her, and there she died.

In the afternoon we had a favoured season at Joseph Beck's, with many young people,
and returned that night to Bristol.
The 24th (first-day), we were at Claverham meeting, the 25th and 26th at Bristol;
myself unwell.

The 27th, I was at Bath meeting, which was not large but favoured, returned to Bristol,
and the 30th, we went to Pont-y-pool.
The 31st (first-day), we attended two meetings at Friends, meeting-house at Pont-y-moil,
near Pont-y-pool.

That in the morning was principally for Friends, that in the afternoon was large,
and both opportunities were crowned with the Divine presence.

Sixth month 1st, we had a meeting at Cardiff with a few sober people.
In our way back to Swansea we called upon a convinced woman,
who lived alone near Cowbridge, who was comforted by our visit.
We staid at Swansea, until the 12th, attending the meetings there in their course,
some of which were seasons of Divine favour.
My mind being drawn to visit the few Friends at Haverford-west,
my husband accompanied me there.
The way was long, and my strength much exhausted by the before-mentioned services;
but I was favoured with ability to discharge my duty.
We had a large meeting at Carmarthen the evening we left Swansea,
and next day got to Haverford-west; attended two public meetings there on the 14th,
it being first-day, and in the evening had a private opportunity with Friends.

We had considerable satisfaction in this journey, and returned to Swansea,
accompanied by our friend John Lewis, the 16th.

The 18th was the quarterly meeting at Swansea,
which although very small was a solemn opportunity;
Divine mercy favouring the few assembled from the several meetings,
with counsel and encouragement.
The 19th, John Lewis and myself had a meeting in the townhall at Neath,
which was not so large as we expected, but,
I believe it was a profitable season to some present.
The 20th, we went to Llantriflfent,
and the 21st attended two large meetings at Tref-y-Ryhg, a meeting-house in the country.
The morning-meeting was much favoured.

The few from Cardiff, and the poor lonely woman near Cowbridge, met us,
and we had an opportunity with them and a few other Friends at a Friend's house.
In our return to Swansea, we had a meeting at Bridgend, in a bowling- green,
wherein was an arbour, under which I stood.
The people were very still, and I hope some were benefited.
I was extremely fatigued with this journey, having performed it mostly on horseback,
double; which appeared the best method of travelling in some part of the journey,
but I found my strength was not equal to that exercise in such long stages.

The 28th (first-day) I attended a small meeting held at IVeath, in a Friend's house,
in the morning; and in the evening had a very large meeting at White Rock,
amongst the workmen of the Copper House and others.
This was the last meeting I appointed in Wales,
and left Swansea with peace and thankfulness the 27th of the sixth month,
and returned to it no more.

We reached Bristol the 29th, and got to Wellington the 1st of the seventh month,
attending the first-day meetings there: that in the afternoon was very large,
and both were good meetings.

The 5th, we had a living meeting at Camelford in Cornwall,
amongst a people not professing with us;
but some of whom appeared to me to be near the kingdom.
The 6th, we got home.

[discrete.alt]
=== Extract of a letter to a Member of our Society, who had spent much of his time very inconsistently with his profession of religion, and was favoured with a Divine visitation when far advanced in life.

[.signed-section-context-open]
6th of the Sixth Month, 1778.

[.salutation]
Esteemed friend,

I have several times thought
of writing thee since our return from Bristol,
but till now have neglected it, and as I know not but we may pretty soon turn homewards,
it may appear the less needful for me to do it; but as my mind still bends towards thee,
in an affectionate concern for thy more firm establishment in the Truth,
I am willing to tell thee so,
and earnestly request thy constant attention to- its dictates;
that thereby thou mayest be led out of corrupt self in all its appearances,
and consequently, into that holy simplicity of mind and manners,
which characterises a disciple of Christ.

I have been much afraid lest thou should settle down in a partially converted state,
and after having deeply tasted of the terrors of the Lord for past sins,
which indeed were flagrant, shouldst content thyself with forsaking them,
and neglect to press after inward righteousness.

I hope thou wilt excuse me for being thus plain with thee,
and that I shall explain my meaning in some degree to thy satisfaction, when I tell thee,
that the observations I have made at thy aiming after
grandeur or show in thy appearance and furniture,
have given me pain, as I know it to be the fruit of a mind not truly or fully humbled.

In the general, in the infancy of religion,
when conviction for past offences has gone deep enough,
the mind is very scrupulous and fearful of receiving a fresh
wound by the indulgence of the natural inclination;
and frequently is led into so strait a path,
that when it has been well disciplined by the cross,
a little more liberty is allowed in the use of some things,
which in that state it was restrained from.

This has appeared to me as passing under the dispensation of John the Baptist,
which was preparatory to that of Christ,
and must be experienced in our religious progress.
For, although the necessity of the outward shadowy baptism cease,
we must be plunged in Jordan, the river of judgement:
and as John appeared in great austerity and mortification,
having "`a garment of camel's hair, and a leathern girdle about his loins,
and his meat was locusts and wild honey;`" so
renewed minds must know that life to be slain,
which delights itself in grand appearances and delicacies,
and be content with mean things; so as to walk in contrariety to the world,
and be sequestered from it, as John was in the wilderness.
Under this dispensation of mortification, the mountains and hills are brought down,
and the valleys are exalted, and the way of the Lord is prepared; unto which,
as the soul is reconciled, rough ways are rendered smooth, and crooked paths straight;
and the salvation of God is revealed;
and there is an entering into the innocent liberty of the Lord's children,
in the use of his creatures.
For although "`John came neither eating nor drinking,`" the Lord
Jesus came "`eating and drinking,`" yet in reverence and fear;
and though he was "`Lord of all,
he became of no reputation,`" and took upon him the appearance of a servant.

Well, my friend, these things are written for our instruction,
and are worthy our attentive consideration,
that we may see whether we are endeavouring to enter "`through
the gate into the city`" of the saints solemnities.
We read, "`Strait is the gate,
and narrow is the way which leads to life;`" and alas! "`few find it.`"

The indulgence of the fleshly mind and natural inclination, prevents many from seeing it;
and though some have seen it, they have not steadily persevered in striving to enter in;
and therefore have rested short of that perfected
righteousness they had once a prospect of.
Let not this be thy case,
but earnestly desire that thy understanding may be fully
opened into this holy highway which leads to the kingdom,
and thine eye be preserved single to God's honour,
that thou mayest be enabled so to run as to obtain the glorious crown of immortality.

Consider thou hast set out late in this important race,
and therefore it behoves thee to use great diligence in
endeavouring to overcome thy spiritual enemies;
all of which will be manifested, as thine eye is single,
for then thy "`whole body will be full of light:`" so that thou wilt be preserved
from entering into a league with such of the old inhabitants of thine heart,
as are appointed to utter destruction.

The Israelites were deceived by the appearance of the wily Gibeonites,
thinking them to have come from a far country, when they were near neighbours; as many,
for want of cautious watching in the light,
which maketh manifest what is hurtful in its tendency, have been deceived,
and united with those dispositions, in one shape or another, which were for judgement.

And it just presents further to say,
Beware of that which is without the sacred limits of divine prescription.
So wilt thou be preserved from all the snares of a subtle enemy, who,
so long as he is permitted to tempt us,
can suit his baits to every station and situation of life,
and to every stage of our religious experience;
which manifests the propriety of our Saviour's precept,
not only to one but to all of his disciples;
"`Watch and pray that ye enter not into temptation.`"

[.signed-section-signature]
Catherine Phillips

The 31st of this month I had a meeting at the house of a man lately convinced,
in the parish of Breague; where some hundreds of people gathered,
that we were obliged to hold it without doors.
They generally behaved well, and some were much affected.
It was a favoured opportunity,
and I was truly thankful for Divine aid to discharge my duty therein.

The 13th of the ninth month, the circular yearly meeting for the western counties began.

It was held at Launceston, and was a large and favoured solemnity; and,
although I did not think the ministry rose so high as I
have known it in some of those general meetings,
it appeared to be a serviceable opportunity,
and the people seemed well satisfied therewith.
I spent the remaining part of this year about home and was favoured
in occasional services there amongst Friends and others.
Upon considering the service wherein I have been engaged since I settled in Cornwall,
I see cause for true thankfulness, having therein been owned by the heavenly Master:
and although in regard to uniting with us as a people, much fruit has not appeared;
the testimony of Truth seems to gain ground amongst the inhabitants,
and some of our own Society, and others, are awakened and strengthened thereby;
so that I trust I have not run or laboured in vain altogether.
May the Lord preserve me humble and dependent upon himself, that whatsoever I am or do,
it may be by his grace.

In the first month, 1779,
our quarterly meeting at Austle was a memorable season of Divine love,
wherein many states were ministered to, and many hearts tendered.
The rebellious were warned,
and I believe some of them saw the imminent danger of their states; but,
alas! the prophet's complaint respecting Ephraim,
etc. too well befits many visited minds.
"`Their righteousness is as a morning cloud,
and as the early dew which soon passeth away;`" yet I trust the savour of
love and life witnessed in this meeting rested sweetly upon some minds.

For some time after this meeting,
my exercise for some of the members of our own Society was heavy,
and I was livingly opened in several meetings, and private opportunities,
agreeably to their states; so that whether the labour bestowed hath its desired effect,
or be as water spilt upon a stone, I hope to be clear respecting them:
and great is the mercy of God in visiting and revisiting them.

The 1st of third month, I had a large good meeting at Helston,
which many serious and religious people attended,
and I believe were instructed and refreshed.

[discrete.alt]
=== Copy of a letter to a young man from America, viz,

[.signed-section-context-open]
To a young man, an American.

[.salutation]
Respected friend,

I conclude this will meet
thee preparing to return to thy native country;
and I wish thy mind may be impressed with a due sense
of the mercies of God vouchsafed to thee in this land,
and with an awful inquiry whether thou hast so profited therein, as to return to thy own,
wiser and belter than thou left it.
I am assured that thou hast been favoured with a Divine visitation,
intended to subdue thy natural will, regulate thy affections,
and bound thy pursuits after the acquisition of either interest, pleasures, or knowledge,
merely terrestrial; and so to reduce the whole man, that thy mind,
being bent upon higher attainments than what
would only gratify the natural will and desires,
might become capable of enjoying the one only unmixed supreme good; and,
being devoted to the service of its bounteous Creator and Benefactor through time,
might participate with him in unchangeable happiness when it terminates.
I entreat thee to inquire how far this glorious end has been
accomplished and do not slight that great salvation,
which in infinite mercy has been offered thee.
I fear thy views have been after that honour which is of men,
and that the wisdom which will one day be manifested to be foolishness,
has been preferred to that which is pure,
and which therefore so recommends to the Lord's favour, as to make men his friends.
He has favoured thee with natural gifts, which, if sanctified by his refining Spirit,
might render thee useful in time.
Consider how they have been employed, for be assured, thou wilt one day see that,
where much is given, much will be required, and that,
"`mighty men,`" if they counteract the design of their creation,
will be "`mightily tormented`" with pungent and unavailing remorse.
Therefore prize the day of the Lord's visitation to thy soul,
and solemnly attend to the "`reproofs of instruction,`"
as the alone way to true happiness,
both in time and eternity.

As I intended consigning the inclosed to thy care,
an unexpected inclination arose thus to address thee,
and express my desire for thy preservation and welfare every way.
If thou should be favoured to attain thy native shore,
thou mayest perhaps have to remember my labour of love for thee: and O! saith my soul,
may it, with that of others my fellow-labourers, not be bestowed in vain.

My love to the several branches of thy family with whom I am acquainted.
Thy father's kindness in accompanying me and my dear
companion Mary Peisley when travelling through America,
is fresh in my remembrance.
Remember me also to such other friends of my acquaintance, as may inquire for me,
who am thy real friend,

[.signed-section-signature]
Catherine Phillips

[.asterism]
'''

[.signed-section-context-open]
To B. H.--Yorkshire.

[.salutation]
Dear friend,

Thy affectionate salutation of the 7th ult.
I received and read with a degree of satisfaction,
as it evinced I lived in the remembrance of an absent friend.
When spiritual sympathy is felt with each other,
it strengthens the hope of our being continued in the
holy membership of the living body of Christ.

Sometime before the receipt of thine, I had been closely tried, and,
although I am favoured to know on whom to depend for succour and support,
encouragement from my fellow-travellers Sion-ward, is truly acceptable.
There are seasons, wherein I doubt not but it is a cordial to the most advanced;
but as for me,
I many times fear I am behind some who have not been called to
stand forth so conspicuously in the front of the battle;
but whose hidden life may be with Christ, in a greater degree than mine,
or some others who have moved in an active sphere.
Certainly to be called up into active service, is a token of Divine approbation;
but if any servants who have thus been frequently distinguished,
should measure themselves by the services they have been assisted to perform,
they may and will centre in deception, respecting their real spiritual state;
and may clothe themselves with the Lord's jewels,
when they are not adorned with the truly beautiful covering of humility,
and a fear of endeavouring to appear to be any thing but what they are through his grace.
Thus self-consequence may get up, and if such are not watchful, it will get up,
and occasion pain to the truly feeling, though less active members of the church.
My sincere and earnest desire is, and indeed for a series of years has been,
for preservation from it, and that I may constantly centre in my own littleness,
yea nothingness: for indeed in my flesh dwelleth no good thing.
All good, and the power of showing it forth, is of and from its own Divine source.
Who are great,
but those whom the Lord sees meet to dignify? All is the effect of his wisdom, power,
and mercy: therefore to him be the praise, saith my soul;
and may I ever humbly confess before him, that I am nothing, nor can do any thing,
but as he puts me forth.

Dear friend, the work of purification is a great and deep work.
May we attend to it, and not seek great things to ourselves, either spiritually,
naturally, or temporally, that we may be distinguished among men; but be concerned,
that the inside-work of the temple may be completed;
and the outside will not want the ornaments Divine wisdom designed it;
but we shall move and act in the church in pure gospel simplicity,
which will ever tend to its edification.

I was glad to receive a late account that T. Colley and
his companion were returned from their perilous voyage.
I also hope that there may be some occasion to rejoice,
that the Lord is visiting his people in your county (
once distinguished for its worthies in Israel),
because I hear there are divers late appearances in the ministry among you.
May the spirit of the departed Elijahs, so rest upon some of the present generation,
that they may go forth in the same spirit and power wherein they acted;
and become instrumental to turn the "`hearts of
the disobedient to the wisdom of the just.`"
A truly living baptizing ministry is much wanted among us;
but except the Lord in mercy favour us with such a ministry,
silence in our solemn meetings is far preferable.
Alas! few, very few indeed,
of the present warriors appear to be thoroughly accoutred for the battle of the day.
Some are essaying to go forth as in Saul's armour,
the wisdom of men decorated with literature; but it will not do the Lord's work.
Weapons despised by the worldly wise, are far more efficacious;
and although the users of them may be despised also,
they are chosen to confound the human wisdom of such, and,
if they keep within the bounds of his appointment, will glorify his name.

I doubt not but that many of my friends in Yorkshire,
will be pleased to know that I am better in health than when last in London.
I had a long season of weakness after that journey, and am yet weak,
compared to what I have been.
Remember me affectionately to such of them,
as thou knowest will be pleased to receive that salutation;
particularly to thy brother and sister,
and my cousin S. B. Thy wife and self will receive the same.

[.signed-section-closing]
From thy affectionate friend,

[.signed-section-signature]
Catherine Phillips
