== Letter to a Backslidden Brother

[.signed-section-context-open]
To my brother Henry Payton, Written on board the ship Alexander, 6th of the Tenth month, 1753, at Sea, Lat. 25° North.

[.salutation]
Dear Brother,

Heretofore when absent,
I have been easy in remembering you with sincere desires for your welfare;
but now a desire of writing to you taking place, I am unwilling to stifle it,
were it only for this reason, that I would do all that is justly in my power,
to strengthen that affection which ought to subsist
between persons so nearly united in nature.

But alas! when I consider the difference of our affections, pursuits, and sentiments,
in right and wrong, I am fearful to set pen to paper,
lest I should not be read with candour and understanding;
yet am again encouraged to this conclusion,
that you will at least receive it as the effect of my regard for you.
Regard, did I say? I will alter the term to affection;
which I have felt gently to spring in my soul towards you;
not only as to a creature formed by the same Almighty hand as myself,
and for the same noble end, namely, to glorify him who gave us being,
and who has loaded us with a multitude of his favours,
which loudly call for a grateful return; but,
as to a brother who has strayed from the path of peace and safety,
and is seeking satisfaction in the grasp of empty bubbles; which have assumed the form,
in his sight, of something substantial.
But your own experience, if impartially traced, will tell you,
they have broken when touched, and dispersed in air; leaving nothing real behind them,
but keen remorse, and the painful remembrance that they are lost, with all the time,
pains and anxiety, bestowed in the pursuit of them.
Yet in this idle solicitude,
(O! affecting but too just charge!) has a great part of your life been spent;
ardently traversing the destructive mazes of delusive pleasure,
and industriously avoiding the One only Good,
in the possession of which your soul might have found substantial happiness:
a happiness which would have afforded true contentment, in.
which is conveyed that fulness of joy, which only can satisfy the immortal part,
being itself immortal in its nature.

You will perhaps say that these are my sentiments.
But allow me to ask you,
why they are not yours? Why do we differ in opinion and practice,
but because the desire and pursuit of sensual gratifications have blinded your judgment,
and biassed your actions? I will venture to assert that
it was the kingdom or possessions of this world,
its friendships, vanities, and sensual pleasures, spread in the view of your mind,
that drew it from its early love and allegiance
to Him who is truly worthy of love and obedience.
Nature joined with the well adapted temptation (being fond of present enjoyment,
though it be forbidden fruit),
and renounced submission to the pure law of grace written in the heart; which,
had it been observed, would have rectified her impure and irregular appetites,
and have placed you in the true state of manhood; as lord of, not a slave to,
the creation; and governor of yourself, in happy subjection to the Divine will:
a will which invariably points out the everlasting felicity of mankind.
But, rebel to her own interest, nature, blinded by false affection,
and fraught with pride, like our first parents,
does not like a superior that shall control her perverseness,
and prescribe laws for her direction;
but rather chooses to take the reins of government into her own hand,
and plan out a way for herself.

Here reason, blind fallen reason, enthroned by the power of Satan,
usurps the sovereign seat, as sitting in the temple of God, being honoured as God; power,
wisdom, and discretion to direct, being ascribed unto it.
This false king (who, had he occupied his proper place, had made a good subject),
joins in strict league with the passions,
and prescribes rules directed by these his allies.
"`Shall man (says he) be confined within the narrow rules of virtue and religion? No,
I proclaim him liberty.
Let him indulge himself in what is desirable to him;
let him gratify the sight of his eye, and the pride of his heart,
in endeavouring to make himself agreeable to and admired by mankind;
with whom let him join in full society, and free communion,
entertaining and being entertained.

Why may he not partake of the pleasures of sense, seeing he has appetites for them;
and satisfy his curiosity in knowing evil as well as good?

These are the genuine suggestions of the reasoning faculty guided by the
passions (though I confess that I believe the subtle deceiver of mankind,
sometimes teaches this reason to speak in a language
more concealed than I have here set down);
but I think it will be no hard matter to prove,
that this boasted liberty is real bondage,
and that this acquisition of knowledge is no more than a sense of guilt,
resulting from the loss of that innocence which gave man boldness to
appear before the face of Almighty justice and purity,
void of distracting fear.

Let us examine the extent of virtue and religion,
and mark every passion implanted by Providence in the nature of man;
and we shall find that in them alone it is possible these should be rightly gratified,
and that whenever man breaks from their bounds, he flies from the mark of his happiness.

I have looked upon love to be the governing passion in the soul, which, as it moves,
draws the rest in its train, and being strongly fixed on a worthy or unworthy object,
is the cause of our joy or misery.
This being granted,
it is next to be considered what object is worthy of our entire affection:
in which search let it be remembered, that this principle of love,
or desire of enjoyment, is so seated in the soul, as never to be struck from it;
and it will presently be allowed,
that the object that is worthy of its spending its force upon,
or being united to without limitation, must not be dependent on time,
for that death deprives it of; but durable as its own existence,
and so perfect as fully to satisfy an everlasting desire of possession.
This can be nothing else but the Eternal Excellency,
from whom this spark of affection was struck; and if divine order were not inverted,
it would as naturally bend towards its original as a stone to the centre,
where only it can find a happy settlement.
In this love of God, stands virtue; it is this inspires it.
If we truly love God, who is infinite in purity and wisdom,
we shall naturally hate their contraries, impurity and folly,
and shall hate ourselves because of them; because whatever defiles the soul,
destroys its likeness to the divine Being, and renders it unacceptable in his sight.
Hence, as it is the nature of a true affection to
endeavour after the love of the beloved object,
proceeds an ardent desire of purification, and a filial fear of offending God;
a fear the most rationally founded, in a deep sense of gratitude,
considering him as the Author of all the good we possess, or can rightly hope for,
i.e. everlasting felicity; joined to the knowledge of his power and justice,
in punishing transgressions, which self-preservation would teach us to shun: therefore,
whatever would amuse the senses,
so as to draw the affection from this Fountain of goodness,
is dreaded and renounced as forbidden fruit.

In religion, the soul is enlarged, and set at liberty to exercise its most noble faculty,
in actions, or on an object, worthy the dignity of its nature; when on the contrary,
without it, it is in bondage,
and debased in the pursuit of what scarcely deserves the name of pleasure,
being of no real worth or lasting duration.
Religion teaches us that we do not live for ourselves only;
but that in order to obtain the great end of our being,
we must seek the good of mankind and endeavour to be serviceable in society;
yet mix in familiar converse with caution,
lest instead of rectifying the errors of others, we transplant them into our own conduct.
It instructs us to beware of vain glory, or of seeking the applause of men;
clothing the mind with humility,
under a sense that we have no good thing but what we
have received from the bounteous hand of our Creator;
and raising a desire that all his gifts may be devoted to his service.
In short, religion places man in the sphere the wise Author of nature designed for him;
directing his affections to ascend towards the Creator,
and to descend towards the creation.

If the ascent be but sufficient, the descent will be just.
The creatures will be loved as the work and gifts of the Creator;
yet possessed with due caution from this consideration,
that they are allotted us but for an uncertain season;
and that it is therefore our interest to be able to surrender them when called for,
with as little pain or anxiety as is consistent with our state.
On the reverse,
the immoderate descent of the affections ties us
down to the earth and earthly possessions,
shackles us in sensual gratifications,
effectually prevents the soul`'s ascending towards God,
and destroys its deputed sovereignty over the creation, to which it is in bondage:
so true is that assertion of the apostle, that while some boasted of their liberty,
or promised it to others, themselves were the servants of corruption.
I have sometimes considered how the excuse of
these boasted libertines bespeaks their slavery.
We cannot help such and such conduct, say they,
or had not power to resist such temptations.
If this were true, it were acknowledging that they had lost that valuable blessing,
the freedom of the will; and are utterly destitute of power to withstand evil;
and of consequence are the devil`'s captives.

Such indeed they are, though not necessarily, but voluntarily; for wisdom and power,
through the grace of God, is given to man,
to discover and resist the temptations of his enemy; and if he will renounce both,
his blindness and subjection to the power of delusion is procured by himself,
as is its miserable consequence, namely,
an everlasting separation from the Fountain of all good.

You will easily perceive,
that the intent of the foregoing hints is to influence
your mind in favour of a more strict course of virtue,
than you have formerly pursued.
I will add my earnest wish that it may be answered.
What shall I say to persuade you to turn,
and coolly and impartially look into yourself? Shall I plead your advance in
years? You are now I conclude rather in the decline of life,
hastening towards the gate of the garden.^
footnote:[An allusion to a dream which the party had, wherein,
amongst other remarkable circumstances, he was met in a beautiful garden by two women,
representing (according to the interpretation which
opened in his mind when he awoke) Virtue and Vanity,
who each solicited his company for a walk; and though he strongly inclined to the latter,
the former insisted on his accompanying her, not only for a walk but for life;
which rather than comply with,
he endeavoured to escape out of the garden (which he called the world);
but coming to the gate found it locked, and the key in her possession.
So being forced to a compliance, he accompanied her,
and became gradually charmed with her conversation,
by which he was won to a love of religion,
and in the end much delighted with the prospect of such a companion for life.]
Oh! listen to the dictates of virtue,
before she withdraw her kind invitations and profitable instructions.

Shall I beseech you by the mercies of God (a prevailing
argument with a truly generous and grateful mind,
and which may with great justice be particularly advanced to yourself),
to return to Him from whom you have deeply revolted,
and seek reconciliation by unfeigned repentance, if you can find room so to do;
which I have a lively hope you may, though you have so long, and distantly,
strayed from the fold of Christ.

I shall plead no excuse for the freedom with which I have here treated you,
further than to say, that I think a true freedom in communicating our sentiments,
with a design for each other`'s eternal well-being,
is a part of that charity which should clothe
the spirits of the followers of Jesus Christ.

The copiousness of my subject may apologize for my prolixity.
Upon a review of what I have written it will readily be observed,
that the hints given are but like heads of chapters, which, if fully expatiated upon,
might fill a volume instead of a letter; and,
that the everlasting Minister of the sanctuary may
enlarge them in the view of your understanding,
to lasting benefit, is the sincere and ardent desire of your affectionate sister,

[.signed-section-signature]
Catherine Payton
