== Chapter I

[.chapter-synopsis]
* Some account of her parents
* Early visitations and religious exercises
* Remarks on engaging in the work of the ministry
* First appearance therein

As the dealings of the Almighty with me from my youth have been singular,
and are worthy to be retained in remembrance with thankfulness,
I have committed to writing some remarkable circumstances of my life;
tending to awaken future thanksgiving and watchfulness in myself; and,
considering how wonderfully the divine arm has been manifested for my help,
to encourage me to a steady trust therein, and to perseverance in submission thereto;
in order to leave to my surviving relations,
some memorials of the various exercises and dangers which I have passed through,
and of the merciful support and preservation vouchsafed from the Lord therein.

But first it appears proper for me to leave a testimony to my parents,
who not only professed the Truth, but had it in possession.
My father, Henry Payton, of Dudley in Worcestershire, son of John and Catherine Payton,
respectable members in the Society of Friends,
was called into the work of the ministry about the eighteenth year of his age; and,
when young, travelled much in the service of Truth in many parts of this nation,
Ireland and Scotland, as also in the American colonies;
and from the testimonies of Friends,
I have good reason to believe that his service was
truly acceptable and edifying to the churches;
his ministry being lively and clear,
and his care not to exceed the openings of Truth therein apparent.
His deportment was grave, his conduct clean and steady,
and his charity in proportion to his circumstances, diffusive.
He was an affectionate husband, a tender father, and kind master;
serviceable amongst his neighbours, and beloved and respected by them.

Many years before his decease,
he was disabled not only for public service in the ministry,
but for acting in the private duties of life in providing for his family;
being afflicted with a paralytic disorder, under which his faculties gradually gave way.
I was much his companion in his long weakness, reading to him and attending upon him;
and can give this testimony respecting him,
that he retained the savour of the divine life to the last;
and frequently manifested a religious concern for his children,
and particularly for me his youngest child and tenderly beloved by him.
He would often say,
"`The Lord bless you my children,`" when his speech
faltered so that he could articulate but little.
In the seventy-fifth year of his age he was released from his affliction,
and I doubt not is entered into everlasting bliss.

My mother was the daughter of Henry and Elizabeth Fowler, of Evesham in Worcestershire.
She was a religious woman, endued with a strong and steady understanding,
and many singular virtues, whereby she was fitted for the part she had to act in life.
This was peculiarly exercising in part, through my father`'s incapacity for business,
the care of a pretty large and young family, and a considerable business,
that not of the kind most fit for a woman, devolving upon her.
When my father was disabled from acting for his family,
being engaged in a partnership in one branch of
business which terminated in great loss of property,
his affairs were in a very unsettled state; all which, with other trying circumstances,
my mother passed through with admirable steadiness, fortitude, and patience;
and through a long series of necessary worldly engagements,
she was favoured to retain the best life.
The Lord greatly blessed her endeavours for her children, in temporals;
and I doubt not heard her prayers that the dew of heaven might rest upon them.
She would say, she desired not great riches for her children,
but that they might dwell in the fear of God.
Her steady and strong conjugal affection was
manifested in my father`'s long indisposition,
by tender attention; and after his decease, by her frequently mentioning him in terms,
which evinced that their union was founded in that love, which death cannot dissolve.
She said that when she married him,
she was so far from being intimidated at the thought of his leaving her,
to travel in his ministerial office, that she entered into the solemn covenant,
with a resolution to do her utmost to set him at liberty therein;
and when it pleased divine Wisdom to deprive her of a
husband whom she might offer up to his service,
she was desirous that some one at least of her offspring might be called to the ministry.
This was fulfilled in me, whom she tenderly loved; but,
I believe she as freely dedicated me to the Lord as Hannah did Samuel,
and was always ready to put me forward in his work;
yet was weightily concerned that I might not run before my true guide.
And although, after I was called to the ministry,
it was my lot to be much absent from her, she never repined at it,
but frequently encouraged and incited me to faithfulness:
so that among the many mercies bestowed by bounteous Providence,
I may justly number as not the least, the having such a parent.

She was an affectionate mother to all her children,
yet very quick-sighted to their faults, ready to reprove them;
and not subject to indulge them in childhood; but educated them in industry.
In fine, she was an example of fortitude, cheerfulness, gravity, industry, economy,
self-denial, and resignation to the divine will.
She was generous to her friends;
her house and heart always open to receive the Lord`'s messengers:
for which she would say she thought a blessing was dropped upon her family.
She was charitable to the poor; rather choosing to save from other expenses,
that she might have to dispense.
She died in the ninety-first year of her age;
and retained a considerable degree of soundness
of judgment until near the close of a useful,
but careful life.

Thus descended,
it may be supposed I was in the way to receive religious instruction from my infancy;
and indeed I cannot date the first dawn of divine light upon my soul.
With humble thankfulness I may say,
that early in the morning of life I knew the Lord to be a God nigh at hand;
convincing of evil,
and raising breathings after the saving knowledge of his divine love and power.
Friends who travelled in the ministry usually lodged at my father`'s house.
I loved their company when very young,
and their tender notice of me I commemorate with gratitude.
Here I may remark,
that if our youth prized the favour of the company and converse of
such whose "`feet appear beautiful upon the mountains`" of salvation,
and who have had large experience of the love of God, they might profit much thereby.

But, alas! how often do some avoid their company,
scarcely giving them an opportunity of manifesting to them
that tender affection wherewith their spirits are clothed;
being probably afraid of reproof, on account of their indulging in liberties,
contrary to the pure liberty of Truth; which they think hard,
although it be given in that love which seeks the true happiness of their souls.
I could read well when very young, and spending much time with my afflicted father,
I read to him; and the experiences and sufferings of faithful martyrs,
and of our worthy friends,
with the accounts of the glorious exit of such as launched out
of time in full assurance of everlasting bliss,
made profitable impressions upon my mind; my spirit being often tendered thereby,
and my love of virtue and piety strengthened;
so that I may truly say that such holy persons, "`though they are dead, yet speak.`"
May their language be heard by the youth of the present and succeeding generations;
and incite them to eschew the paths of vanity,
and to follow the footsteps of Christ`'s companions.
So will the song of his redeemed be theirs.

But, notwithstanding these promising beginnings,
as I grew up I yielded to various temptations,
and was allured from the simplicity of Truth;
the evil propensities in nature getting the ascendency.
But even in my childhood I experienced many conflicts,
and my convictions for evil were strong; so that at times my heart was sorrowful,
and my pillow watered with my tears,
although my countenance and deportment were mostly cheerful.
Once, having yielded to temptation, my sense of guilt was such,
that I concluded I had sinned against the Holy Spirit;
and that agreeably to Christ`'s testimony, I "`should never be forgiven.`"
This so affected my tender mind with sorrow and unutterable distress,
that it could not be entirely concealed from the family; although I was enabled,
even in childhood, to keep my exercises of mind much to myself.
I think I must have been about eight or nine years old when it was thus with me;
and as in childhood I was several times visited with fevers, which brought me very low,
I was led to consider how I was prepared for the awful change wherewith I was threatened;
and a weighty sense rested upon my spirit,
that my soul was not pure enough for admittance into Christ`'s holy kingdom.

Sometimes I would covenant with the Lord to be
more circumspect and watchful for the future;
but the airy natural disposition again got the ascendency,
whereby an occasion for repentance would arise.
My natural disposition was very volatile, and my apprehension quick;
and as my faculties opened,
I delighted much in books of a very contrary nature and
tendency to those which had engaged my attention in childhood.
I had a near relation, who,
notwithstanding his having been divinely favoured in his youth,
had slighted his soul`'s mercies, and pursued lying vanities.
He kept house in the town; and through him,
myself and my sisters had opportunities of obtaining plays and romances,
which I read with avidity.

I also spent so much time at his house as to be introduced into
amusements very inconsistent with the simplicity of truth,
and my former religious impressions; so that my state was indeed dangerous,
and but for the interposition of divine Providence,
I had been left to pursue courses which must have terminated deplorably.

I also read history, was fond of poetry, and had a taste for philosophy;
so that I was in the way to embellish my understanding, as is the common phrase,
and become accomplished to shine in conduct;
which might have tended to feed the vain proud nature,
render me pleasing to those who were in it, and make me conspicuous in the world.
But the Lord, in his wisdom,
designed to bring me to public view in a line directly opposite to worldly wisdom,
pleasure, or honour;
and when he was pleased more fully to open to my understanding
his great and glorious work of renovation of spirit,
I saw that I must desist from these publications and studies,
and pursue the one necessary business, namely,
working out the salvation of my immortal soul:
and I esteem it a great mercy that I readily attended to this intimation.
However lawful it may be, in proper seasons, to look into the works of nature,
and become acquainted with the history of former or present times,
my attention was now powerfully attracted to higher subjects;
and had I pursued those lower things,
I might have become as a "`vessel marred upon the wheel.`"
This is, alas! the case with many who have been divinely visited, but who,
not deeply and steadily attending to the instructions of pure wisdom,
but seeking to be wise and learned, in matters which merely relate to this present state,
have not advanced in the simplicity of divine knowledge;
and although it has remained obvious that the Lord`'s hand has
mercifully been turned upon them to form them for his service,
they have not grown up to that degree of usefulness in Christ`'s church,
whereto they might have attained,
had they passively abode the turnings of his preparing hand.
Were the sons and daughters of our religious Society,
who are favoured with good natural understandings, clothed with heavenly wisdom,
they would become and appear truly great,
in the dignified simplicity and humility of the service of the King of kings.
Human knowledge and acquirements too often pufF up the minds of youth;
and indeed some of more advanced age pride themselves therein, when,
as examples to the rising generation, they should be clothed with humility.

It was observed of a truly honourable member of our favoured Society,
that "`he was a divine and a naturalist, and all of the Almighty`'s making.`"^
footnote:[William Penn`'s account of George Fox.]
I have read very little on natural philosophy,
and am not in a disposition to boast of my acquired knowledge of, either human, natural,
or divine things; but I may say,
that I have admired how by one gleam of heavenly light
the understanding is opened into natural things;
so as in degree to behold, as at one view,
the general economy of the divine Former of all things,
as it is displayed in the outward creation.
This produces adoration to him under the humbling sense of his power, mercy, and wisdom,
as well as admiration of his works; and discovers that they are indeed marvellous,
and in their full extent incomprehensible.

Therefore,
let not the faculties of his adopted children be
so improperly occupied in exploring them,
as to prevent an advance in their various stations in his militant church:
when happily their souls are fixed in the triumphant, they will know so much,
as forever to inspire the angelic song of "`Great and marvellous are your words.
Lord God Almighty, in wisdom have you made them all!`"

From these remarks I return to my education, which, while I was at home,
had not been entirely neglected, as to useful and necessary learning; yet,
as through the afflicted circumstances of our family,
I had been kept pretty closely there until I had attained my sixteenth year,
my mother concluded to send me to London,
and put me for one year under the care of Rachel Trafford, who, with her sister,
kept a respectable boarding-school; not doubting her attention to me,
as she when young had spent a considerable time in my father`'s family.

She was affectionately kind to me; and, as a minister as well as mistress,
I believe her mind was frequently exercised for
the religious improvement of her scholars,
which at times was manifested by verbal supplication for them,
as well as advice and reproof.

I improved much for the time I stayed in the school;
and my school-fellows behaved well to me; but being so far advanced towards maturity,
tall, and proportionally grown for my age,
I looked rather too much like a woman for a school;
yet some of my school-fellows were older than myself,
which I believe increased my mistress`'s anxious solicitude for our preservation,
we being, to use her own expression, a school of women,
myself most intimately with my mistress`'s niece, who acted as a teacher,
and with one of the scholars, a sensible, agreeable, well-behaved young woman,
but not of our Society,
who was admitted into the school to qualify herself in needle-work,
for a school-mistress.
As neither of them were much under the influence of religion,
I did not profit by their conversation, in the most essential respect.
But after I had been a few months in the school,
I was favoured with a renewed visitation of divine love,
and grew uneasy with my situation.
Home became desirable, although I knew it to be a house of affliction;
and on my intimating it to my dear mother, my brother James fetched me there,
sooner than she intended when I left her.

Thus far I have commemorated the dealings of the Almighty with my soul,
manifested principally in tender mercy;
but now the day was coming wherein his righteous
judgments were manifested against all that was high,
and opposite to his pure Spirit; in which day my wanderings from Him,
the Shepherd of Israel, were brought to my remembrance,
and my sins set in order before me;
which wrought great humiliation and brokenness of heart, with strong cries to Him,
that he would graciously pass by my transgressions,
and receive me into covenant with himself Although this
dispensation was not agreeable to degenerated nature,
which, like Adam, when he had transgressed, seeks to evade the condemnation; yet,
because of the glory which I was favoured to discover beyond it,
and the divine love which I saw therein, I said, in the secret of my soul,
"`It is good for me to be under it;`" and I was made willing
patiently to abide the judgments of the Lord for sin,
in order that I might witness remission thereof through the baptism of repentance,
and the sanctifying life or Spirit of his Son Jesus Christ.
And this mercy, in the appointed season of infinite wisdom, I experienced;
so that my past transgressions were blotted out of the book of remembrance,
upon the terms of my future steady perseverance in the fear of God;
and in the sensible exaltation of the attribute of divine mercy over judgment,
my soul rejoiced with humble thankfulness.

Yet as when the children of Israel were delivered out of Egypt,
and travelled through the wilderness, they had new trials of various kinds to encounter,
insomuch that they thought their sufferings rather increased than diminished,
and frequently feared perishing in that desert land; so,
being now relieved from the oppressive weight of past actual transgression,
and travelling after the saints promised inheritance,
which is a state of establishment in righteousness,
I had to pass to the attainment thereof.

I soon connected through many deep baptisms and exercises of faith and patience.
I was now brought into my own heart, which,
by reason of the irregularity of its passions and inclinations,
might well be compared to an uncultivated wilderness; through which I must travel,
and wherein I must receive the law for the ordering of my outward conduct,
O! the seasons of hunger and thirst, the tossings and perplexities, the "`thunderings,
lightnings, and tempests,`" which seemed to threaten destruction,
which I had to pass through in that day, are to be had in everlasting remembrance;
with thanksgiving to that divine hand which preserved me from being so far
dismayed at them as to look back with a desire to return to that country,
or state, from which I happily escaped.
The adversary here transformed himself as into an angel of light, and,
under the specious appearance of righteousness, represented the way so strait,
that it was impossible to walk therein and act as a rational being;
thereby endeavouring to discourage me,
or prevent my attaining to the true gospel liberty, in the use of the creatures,
and the course of my conduct.

Indeed, in this season of deep distress,
both the "`earth and heavens were shaken;`" some of those religious principles,
which I had received by education, were called in question;
and I was left without any foundation of certainty respecting them;
nor could I attain to it by the testimony of others,
or the writings of such as had vindicated them to the world;
being to receive my convincement of them, from the deep ground of divine revelation.

All which I have seen was necessary to fit me for the service which was appointed me;
that the foundation of my faith might be laid in certainty,
and that I might be able to testify with boldness,
that I had experienced what I asserted to be the truth;
and be also suitably qualified to sympathize with, and minister to,
such as were in the like states.
I saw early for what station I was designed in Christ`'s Church.
This manifestation of the divine will,
my soul received with a good degree of resignation; nevertheless,
until the Lord`'s time for putting me forth to service was come,
I was frequently assaulted with fears, lest it should be required of me at such time,
and in such manner, as would be doubly hard to flesh and blood:
and the adversary was very busy with his presentations,
intending thereby either to dispirit my mind from pursuing its proper duty, or,
by hurrying me into what had the appearance thereof, to bring me into confusion.

But, in all these "`voices of the stranger,`" there was a lack of that certainty,
which I had concluded should attend such a discovery of the divine will,
and which I was happily led to look for;
and I was at length strengthened to covenant with the Almighty,
that whenever the evidence was clear and strong, I would submit thereto.

And here it may not be unprofitable to remark,
that some minds are more liable to be thus affected than others.
Such as have a strong and quick imagination,
and whose hearts have been deeply affected with the exceeding sinfulness of sin,
and of the love of God to mankind; whose desires are strong,
that the one might come to an end, and the other abound in the earth;
it is difficult for these at all times, especially when young in religious experience,
to keep the quiet habitation,
wherein alone the voice of the true Shepherd is to be heard,
and distinguished from that of the stranger.
But as the will becomes gradually resigned to that of God,
and the imagination in its natural working silenced,
and the soul comes more constantly to worship in the Lord`'s temple,
the adversary in these false appearances is bound, or if permitted to present them,
there is strength acquired to stand still and try the spirits.
This I have seen, in the light of Truth,
to be absolutely necessary before we move in the Lord`'s service;
the lack of which has been productive of much confusion,
and administered cause of reproach on our high and holy profession,
to such who are seeking for an occasion to lay waste the belief in divine revelation.

But to return:--being come to the aforesaid state of resignation,
I waited quietly to discern the puttings forth of the divine hand,
in a state of earnest prayer,
that I might not be permitted to move before the proper time;
which I have good ground to believe was heard and answered;
and that from the motion of divine life I was constrained to
supplicate the Almighty in our little meeting at Dudley,
the tenth day of the second month, 1748,
being then newly entered the twenty-second year of my age.

May such of the Lord`'s children,
whom He appoints to the solemn important service of the ministry,
humbly and patiently wait to know when to move therein;
as through neglect of this some have stepped into it,
before they have fully passed through the dispensation of preparation for it; and,
if ever they have become strong in his service,
they have continued long in a state of weakness.
Yet let none despise "`the day of small things.`"
A few words spoken under divine direction,
are often blessed to those to whom the Master of the solemn assemblies directs them.

I continued to minister, as the Lord was pleased to give me ability,
in great brokenness of heart, and for a time in but a few words;
for great fear was upon my spirit lest I should minister in the wisdom of the creature,
which ever brings death, and begets its like.
In a sense of this danger, strong were my cries to the Almighty,
that what I handed forth to the people might be unmixed,
let it appear ever so simple or despicable in the view of the worldly wise and learned.
And as I continued to move in fear and trembling, the Lord was with me,
and enlarged my understanding, and increased my service in the openings of Truth:
at which his people rejoiced, and, in obedience to his requirings I felt sweet peace.
Yet was my spirit frequently in heaviness, being humbled with many deep exercises,
which I found profitable to establish it in righteousness, although painful to nature.
I leave it as an observation, that I have seldom, if ever, seen any stand,
and arrive to any considerable degree of usefulness in the Church,
whose foundation has not been deeply laid in afflictions and exercises;
whereby they are crucified with Christ,
and shall therefore rise with him to glory and honour,
in the present as well as in a future state.
But in all my afflictions and deep baptisms, the Shepherd of Israel was with me,
and preserved and supported my spirit to the honour of his own name,
to whom alone I could attribute the praise.
For in those allotted days and years of tribulation,
very little instrumental help was afforded me;
my lot being cast in a quarter where there were none near who
were capable of giving me much assistance or wise counsel,
not having trodden in the same steps.
I sometimes thought my case was hidden from some of the Lord`'s servants,
who were concerned to visit his heritage;
or else that they were in part restrained from ministering to it;
and my tongue was much sealed in silence, for my exercises were incommunicable.

All this I saw to be of excellent use,
as the contrary might have led to a dependence on the servants,
which ever brings weakness; or have been productive of confusion,
through my imparting my case to such as were not skilful to minister to it,
and who nevertheless might have advised therein.
I have seen it to be profitable and necessary for such
as are in a state of infancy in religion,
to dwell with their exercises; leaning simply on that arm,
which alone is able to carry through them; and,
until the mind has acquired a depth of judgment
to distinguish clearly who is on the Lord`'s side,
to be very cautious to whom they communicate them; lest they be wounded,
by discovering those, whom they have chosen for their friends,
to be enemies to the cross of Christ.

Yet when the Lord directs, in times of great strait,
to advise with some experienced servant, it will undoubtedly be advantageous,
and a steady sympathizing friend is a great strength and blessing,
when it is afforded in divine wisdom.

I am inclined to close this chapter with a little poem,
which I wrote in my nineteenth year; as it has been handed about in manuscript,
and suffered much by copying.
Between my eighteenth and twenty-second year I penned several small tracts,
all of a religious nature; but soon after I appeared in the ministry,
I dropped my pen in regard to verses.
I do not say it was a sacrifice required;
but the continuing of the practice might have proved a snare in some way.
It might have engaged my attention too much, or tended to make me popular,
which I have ever guarded against;
for I was early afraid of my mind and services being tarnished with vanity.
And here I may add, that from the time I came from school, I read but little,
save religious books; and after I appeared in the ministry, until late in life,
reading even them was much taken from me, except the Scriptures:
all which I believe was in divine Wisdom,
that I might not minister from what I had gathered from religious writings;
but might receive the arguments I was enabled to advance on behalf of the Truth,
by the immediate revelation of the Holy Spirit.
And I can with truth say, that the Lord has been to me, mouth and wisdom,
tongue and utterance, to my own humbling admiration.
May all the praise be given to him now and forever!

[discrete]
=== A Prayer For Wisdom

[verse]
____
Maker supreme, of heav`'n and earth,
Of sea, of air, and sky;
O! you who gav`'st to all things birth,
Lord, hear me when I cry.

To You, invisible, I`'ll pray,
You only righteous God;
And You, omnipotent, obey,
And fear your dreadful rod.

Riches or life, I do not crave,
Nor any transient things;
The one has wings, and in the grave
Are laid the proudest kings.

`'Tis heav`'nly wisdom I admire;
`'Tis this is my request:
Oh, grant, great God, this my desire.
And I am fully blest:

Wisdom to worship you aright,
To understand your will.
To do my duty in your sight,
And your commands fulfil:

That when my fleeting sands are run,
And death shall set me free;
When the short thread of life is spun,
My soul may fly to you:

Where I shall live eternally,
And fear no end of time;
But praise your name, enthron`'d on high,
You pow`'rful God divine.

Not with a weak and mortal voice,
But in celestial strains;
In heav`'n, the centre of my joys,
And end of all my pains
____
