== Chapter II

[.chapter-synopsis]
* Visits Wales
* Circular meeting at Coventry
* Western Counties of England
* Goes to Bath on religious service
* Pays a religious visit to Ireland

Having now entered the list of public combatants in the Lamb`'s army,
I pretty soon became concerned to travel for the promotion of Truth and righteousness;
and for more than twenty years, had but little intermission from gospel labours.

In the fifth month, 1749, old style, I left home, in order to visit some part of Wales;
in which journey my dear friend Lucy Bradley was made willing to accompany me, although,
as she said, she knew not that her call to service was much farther than to assist me;
with whom I travelled in sweet unity, she being a true sympathizing friend,
and deep travailler in spirit, as well as rightly qualified publicly to minister.
We visited the meetings of Friends in Radnorshire, Monmouthshire, Glamorganshire,
Pembrokeshire, and part of North Wales;
and in about seven weeks I returned home in peace and thankfulness,
to my dear mother and relations;
who had been made willing to give me up for Truth`'s sake, and gladly received me back.
In this journey the principal share of the public service fell to my lot;
wherein the Lord was evidently with me,
strengthening for the work of the day to the honour of his own name;
and the testimony of Truth was sometimes exalted, in its own authority,
over the libertine and hypocritical professors of it.

The youth, and tender honest-minded, were visited and refreshed in divine love;
liberty and strength were afforded to declare it to those not of our Society;
and I had ground to hope that our labour was not entirely in vain:
some persons being powerfully affected, who, I hope,
long retained a sense of that visitation; particularly William Phillips from Cornwall,
who was then upon a visit to his relations at Swansea.

In less than a week after my return from this journey,
I went to the circular yearly meeting for the seven western counties,
which was held this year at Coventry, and was very large, and, in the main, satisfactory.
It was attended by many valuable experienced ministers,
who were careful of laying hands suddenly upon me;
although I had good reason to believe that the most weighty of them loved me;
but were fearful of hurting me by discovering too much approbation or affection;
which some minds, in the infancy of religious experience, have not been able to bear.
After my return from this meeting,
I was stripped of that strength wherewith the Almighty had been pleased to clothe me;
which, with some other discouragement I met with, sunk me very low,
insomuch that I was ready to doubt of all I had known,
and to call in question my commission to minister:
and my soul was attacked by the adversary in some of his most subtle appearances,
and baptized into a cloud of darkness.
This dispensation I afterwards saw to be serviceable; the more so,
as before my return from my Welsh journey,
I had a prospect of another into`' the west of England;
for therein I forgot all my former services, was emptied of all self-sufficiency,
and became as weak and depending as when I first
engaged in the weighty service of the ministry:
and it lives in my experience, that thus the Lord will deal with his servants,
for their preservation, that they may dwell in a continual sense,
that the excellency is of Him; from whom proceeds wisdom, power, light, utterance, peace,
and every good gift.

My concern for the west continuing and increasing, I imparted it to my relations,
who being willing to give me up, I sought for a companion,
but could hear of none suitable.
This added to my exercise; for it seemed very dangerous for such a child as I,
to travel alone; but after waiting as long as I dared,
I laid my concern before Friends of our monthly meeting,
and requested their certificate,^
footnote:[Should any one not acquainted with Friends`' discipline read these Memoirs,
it is not improper to observe, that, when a minister, approved amongst them,
believes it his or her duty to visit a distant part of the nation,
etc. a certificate is given of the unity of Friends of
the monthly meeting whereof such minister is a member,
that Friends where they travel may be assured that they do not move in so
weighty a service without the concurrence of their Friends at home:
also that the laying on of hands mentioned in the preceding page,
is only to be understood as a figurative expression.]
but.
told them that I knew of no companion; and if they had not been free to let me go alone,
I believe I should have been easy to have waited longer; but they gave me a certificate;
and in the eleventh month, 1749, I left home in great humility and fear,
being accompanied by my dear brother James Payton,
who went with me to several meetings in our own county,
and left me not without some doubt on account of the natural weakness of my constitution,
which he feared might suffer in this winter`'s journey.
I proceeded to Bristol, and from there, through part of the counties of Wilts, Somerset,
Dorset, and Devon, to Penzance in Cornwall, and returned back to that city in the spring.

Although I went from home alone, I was not much without a suitable companion,
the Almighty putting it into the heart of one or other of his servants to accompany me.
Mary Fry, of Sutton in Wiltshire, went with me through Dorsetshire; and Mary Pole,
of Milverton in Somersetshire, through Devonshire and Cornwall;
who were both very tender of me, and serviceable to me.
The latter was not in the ministry, but a solid sympathizing friend,
and true labourer in spirit in meetings.

I visited the meetings of Friends pretty generally in Dorsetshire, Devonshire,
and Cornwall; some of which were attended by many people of other societies;
before whom the Lord gave me boldness to testify of his Truth with good authority,
and to lay open the false and dangerous opinions of some professed Christians,
particularly that of unconditional election and reprobation;
which dark principle was then likely to gain ground in these parts.

I was concerned to appoint meetings at several places,
where Friends had no meeting-houses; all which I hope had their service.
At Truro in Cornwall, I had a satisfactory meeting,
although the people at that town had heretofore manifested
their dislike to Friends labouring among them;
but they behaved pretty peaceably now,
and I had cause to believe my service in this meeting tended to open
the way for the circular yearly meeting to be held here;
which it was in the year 1752, much to the satisfaction of Friends.
At Bath, in my return, I was concerned to appoint a meeting for the strangers in town,
it being the season for drinking the waters; to which some of them came,
and it was a memorable opportunity,
the power of Truth being exalted to the reducing of their light and airy spirits,
to some degree of solidity;
for which my soul bowed in thankfulness to Him
who calls to and qualifies for his service.
In this meeting a man sat opposite to me, who wrote by intervals while I was speaking,
and I apprehended was taking down what I said;
but my spirit was borne above looking at that, being bound to the testimony of Truth.

After staying about a week at Bristol, I went for the Welsh yearly meeting,
which was held this year at Brecknock, being accompanied by John Curtis,
a valuable minister of Bristol, and several other Friends.
In our way we appointed meetings at Caerleon, Pontypool, and Abergavenny;
at the first of which places, I could not find that there had ever been a meeting before;
but the people behaved well,
and I hope it ended to the satisfaction of the sensible Friends present.
It was held upon a first-day in the afternoon; and while we were in it,
a number of people were going about the street with a fiddle;
it being the custom in some places in Wales, after what they call divine service,
to entertain themselves with music, or other diversions.

What an inconsistency!
That at Abergavenny was large,
and I hope of service in opening the way of the testimony amongst the people.
Here a Presbyterian preacher made some disturbance at the close of it.
I thought his aim was to cloud the doctrine which had been preached,
and so prevent the people from being shaken thereby from their old sentiments;
but he was blamed by them, and I hope missed his end.
I had not much public service at Brecknock, yet was glad I was there,
for indeed it was a humbling time to me.
For although, in proportion to my gift and experience,
the Almighty had eminently favoured me in this journey; yet,
on beholding the service and conduct of some other of his ministers,
and comparing mine with them, I was led to look upon myself but as a mean instrument,
and greatly to esteem these my elders in the Truth.
O! how secretly does the Lord work,
to the purifying of the hearts of such of his servants
who desire to be divested of every high thought,
and humbly to cast down their crowns at his feet.
This was the ardent prayer of my soul,
from the sense of the miserable loss some had sustained,
in being puffed up with self-conceit and the esteem of the people;
which I have seen to be a very fallacious line to measure one`'s self by:
for sometimes that which is highly applauded by them,
is reproved by that Spirit which searches all things.

From Brecknock I returned to Bristol yearly meeting,
from where I thought of returning home; but, to my great disappointment,
a concern rested upon me to proceed to the yearly meeting at London,
in company with Rachel Wilson, who came with me from Brecknock,
and was without any companion in the ministry.

This brought a great exercise upon my mind,
under the consideration of the concern it would bring upon my relations;
who I knew were desirous that I might steadily move in the counsel of God;
and perhaps might fear my running too fast, which I also dreaded;
but finding I could not otherwise be easy, I advised with some friends,
and particularly with my ancient and honourable friend, Benjamin Kidd,
who encouraged me therein.

The Bristol yearly meeting ended satisfactorily, many valuable ministers attended it,
and the testimony of Truth was measurably exalted.

It had pleased the Lord in the several times I had been in this city,
to favour me with considerable liberty in the exercise of my gift,
whereby a door was opened to me in the minds of Friends there;
which favour I hope I received with due thankfulness.

Being clear of Bristol I proceeded to London,
attending several meetings in the way,`'appointed by Rachel Wilson;
at one of which we met with our valuable friend Daniel Stanton from America,
with whom we went in company to London;
where we were affectionately received by many Friends,
and I had good ground to believe my coming to that city,
was in the will and wisdom of the Almighty, though greatly in a cross to my own.

After the yearly meeting, I returned directly home, through mercy in peace,
and was there gladly received by my dear mother, etc.

Upon a review of this journey, I found abundant cause to adore the wisdom, love,
and care, of the heavenly Shepherd; which were eminently manifested in his conducting,
dealing with, and preserving me, a poor weak inexperienced child.
The many dangers I had escaped, the many deep exercises I had been supported under,
with the multitude of favours conferred on so unworthy an object,
struck me with admiration, and raised this acknowledgment,
that He "`had not dealt with me according to my desert,
but according to the multitude of his mercies.`"

My return from this journey was in the fourth month, old style, 1750.
I staid about home until the fall of the year, when I found my mind drawn to Bath,
principally on the account of such as resorted there to drink the waters;
to which city I went, and spent a few weeks therein, and at Bristol, etc.
I hope profitably.
I passed the winter of this year chiefly at and about home, amongst my relations.

In the spring of the year 1751, I attended the yearly meeting for Wales,
held at Newport in Shropshire, which was large and divinely favoured.

My dear friend Samuel Fothergill attended it, to whom I imparted a concern,
which I had for some time been under, of visiting Ireland; in which he encouraged me,
and advised that I should endeavour to get to Dublin half-year`'s meeting.
I had afterwards cause to believe his advice was right;
for although I did not arrive timely to attend it, yet,
had I not come in time to consult Mary Peisley before she left the city,
I might not have been favoured with her company.
Accordingly I very soon set forward, my brother accompanying me to Liverpool,
and seeing me on board a vessel bound for Dublin,
in which he left me to the protection of Providence.
We sailed down the harbour, but the wind proving contrary, lay that night at anchor,
and the next day returned to Liverpool; where I was content to wait,
until He who sent me forth was pleased to afford
the means of my release from my native land;
which was in a few days, when I was favoured with a good passage,
for which my spirit was thankful.
I took up my lodgings at Dublin at John Barclay`'s, by whom, though personally unknown,
I was kindly received.

Soon after I landed I heard that my dear friend Mary Peisley was in town.
I told her that as I was without a companion,
I should be glad if she could find freedom to go with me a part of the journey;
to which she said little then, but before she left the city,
informed me that she had for some time felt drawings to
visit the western and northern provinces,
and was free to join me in these parts; with which I thankfully concurred.
It is worthy of remark, that the evening before I landed,
she being under the influence of heavenly goodness,
and in that state resigned to go this journey,
it appeared to her that a companion would be sent her from England.
Thus does the Lord mercifully provide all things necessary for such as trust in him,
and are willing to follow whithersoever he leads them.

Mary Peisley returned home from Dublin, in order to prepare for the journey.
I staid a few days,
and then left it with an intention to visit two meetings in the county of Wicklow,
and return back to the city.
Several Friends accompanied me in a coach,
which I mention as being singularly providential,
for the day we left town I was taken ill; but as a meeting was appointed at Wicklow,
we went forward, and reached the place that night.
Next day I was much worse, yet attended the meeting and had some little service therein,
though under a heavy load of sickness; which continuing,
I returned the next day to Dublin, where I was laid up for about two weeks.
In all this time my mind was remarkably resigned to this dispensation of Providence;
feeling sweet peace in giving up to come the journey,
even if it were the Lord`'s will I should lay down my natural life in that city;
having a comfortable hope that it would have been in peace;
but as he saw fit in wisdom and mercy, to raise me from this state of weakness,
my earnest desire was,
that my longer continuance in mutability might be to the honour of his ever worthy name.

[.blurb]
=== Letter from her mother received about this time.

[.signed-section-context-open]
Dudley, 8th of Fourth month, 1751.

[.salutation]
My dear and tender Child,

Yours, with the agreeable account of your arrival at Dublin,
your brother has wrote you we received.
Your other dated the 28th ult.
which brings the news of your illness, also came safe;
which you may suppose was a great trouble to me to hear;
but although at present it is a hard trial to have you ill so far separate from us,
yet I esteem it a favour that your lot is cast among such careful and good friends,
which I desire to be thankful for.
It is no small satisfaction to me that you have been so easy in yourself,
and I would have you labour against every thing which
the enemy in the time of weakness may present,
and I doubt not but the same peace will be continued to you.

Do not think, my dear child, of my affliction on your account;
for as you were satisfied it was your duty to go,
and I thought it my duty to give you up; I trust you will be restored to me,
and to your health,
and answer the service the Almighty has sent you upon to the honour of his great name:
then whenever we meet again it will be so much to our comfort and your satisfaction,
that with hearts filled with gratitude, we shall, I hope, for we shall have cause,
return thanks to Him who is alone worthy.

Although you know that I am very short in expressing myself, yet, my dear child,
when I find my mind rightly exercised,
my prayers are night and day for your preservation, as I believe yours are for me,
I desire, when you get well enough to go on your journey,
you will consider your weak constitution,
and not overdo yourself My very dear love is to the friends with whom you lodge,
not forgetting their care of you.
I shall now conclude with my dear and tender love, your afflicted, but not without hope,
affectionate mother,

[.signed-section-signature]
Ann Payton.

In the time of my indisposition, I lodged at Robert Clibborn`'s,
whose wife was exceedingly tender of me.
John Barclay and two more in his family were ill,
which rendered it improper for me to return to his house.
I staid some little time in Dublin to recover my strength,
and my friend John Barclay`'s indisposition proving mortal,
I attended the meeting held on account of his funeral; which was very large,
and attended with a good degree of solemnity.
After this I left the city, accompanied by a solid young woman, named Elizabeth Carleton,
not in the ministry, who was with me about three weeks;
in which time I passed through the meetings of
Friends in the counties of Carlow and Wexford,
to Waterford; where I was met by my dear friend Mary Peisley,
who was my companion through most of the remainder of this journey.

I had cause thankfully to acknowledge the mercy of Providence
in affording me one so steady and experienced,
from whose conduct I might gather instruction.
We travelled together in great unity and affection,
which rendered the trials we met with in the journey the more easy.
These were considerable, resulting in part from the nature of our services;
which were mostly pointed to the states of persons or meetings,
and exposed us to censure from spirits unsubjected to the power of Truth;
but our good Master supported us through all,
and nearly united our spirits to the living conscientious professors of it,
in that nation.
It was sometimes my lot in this journey to appoint
meetings in places where there were none of our Society,
in which I had the unity of my companion and friend;
and they mostly ended to satisfaction,
the Almighty proportioning wisdom and strength to the occasions.

The 27th of the seventh month I returned to Dublin,
in hope that I might in a few days take my passage for my native land;
but two women Friends from England, who had been visiting Ireland,
being expected in town soon, and to return home,
I was free to wait a little for their company; but therein was disappointed,
for one of the Friends got a fall from her horse in Dublin street,
by which she was disabled from pursuing her intention of going home.
So I put to sea, but the wind proving contrary, we were forced back,
after having been beating against it almost four days.

This sunk my spirits considerably, but on my return, service opened for me,
and the wind being still contrary, I took a little turn in the country to satisfaction,
and attended the province meeting for Leinster,
where I was met by my dear friend Mary Peisley; with whom I went to her father`'s house,
and stayed about a week, and we went in company to the half-year`'s meeting at Dublin;
in which solemnity I was favoured to minister in the authority of Truth;
and after taking an affectionate leave of my near friends,
and especially of my companion,
who was still more near to me in the union of the divine Spirit,
I sailed for England the 12th of the ninth month, 1751,^
footnote:[It seems worthy of noting,
that although I did not make my passage when I first went to sea,
my attempting it might have been of use to the captain, who was a religious-minded man,
with whom I had conversation.
He allowed no profane language aboard his vessel.
He said he had difficulty to prevent it, but he made it a rule;
and that the sailors might obey his orders, sometimes asked their advice,
and when they concurred with him in judgment, they quietly submitted to orders.]
arrived at Parkgate the 14th, and reached home the 16th,
to the mutual rejoicing of myself and relations.

After my return my spirit rested some time in a quiet settlement,
and great enjoyment in the Truth;
which was an abundant compensation for all my
labour and sufferings attending the journey.

[.blurb]
=== Copy of a Letter to that truly great minister, my ancient friend, Abigail Watson of Ireland.

[.signed-section-context-open]
Dudley, 18th of Eleventh month, 1751.

[.salutation]
My Dear Friend,

It was not because I had not a due esteem for your letter,
that I did not answer it from Dublin; for indeed I read it with pleasure,
and am thankful you count me in any degree worthy of your friendship;
but being pretty much hurried, could hardly get a quiet hour to write.
I now make use of the first convenient opportunity to inform you, that,
through divine favour, I have safely reached my outward habitation,
and was gladly received by my dear mother,
etc. whom I found in as good a state of health as I expected.
My mind, for the most part since I came home, has been quiet and easy,
resting under the enjoyment of peace in discharging my duty to your nation;
which service, as you hinted, was not undertaken in my own will,
nor performed in my own strength; but He who sent me forth, vouchsafed to accompany me:
and though he many times saw fit that I should be deeply tried,
he was with me in the deeps, as well as in the heights,
preserving in danger and distress.
Unseen he helped me, because he knew my soul looked to him for assistance,
desiring to be guided by his unerring counsel.

I write not this boastingly, for my spirit is humbled,
under a sense of his goodness and unmerited love.
What am I, that the Majesty of heaven should thus condescend to visit me? A poor, weak,
unprofitable servant, unto whom belongs fear and confusion of face.

Ah! my dear friend, what are the best of us all,
without the divine presence or assistance? It is that is our strength, our crown,
and rejoicing; by that are we made beautiful; and, divested of that, become as nothing.
O! may I ever live in a just sense of the necessity of seeking after it.
O! my God, sooner cut the thread of my life,
than allow me to fall from tasting your goodness:
let me not bring dishonour on your great name, which I now reverence and adore.
These, my dear friend, are the secret desires of my soul, in joy and in affliction;
which in freedom and tenderness of spirit, I at this time communicate.
Whenever you or your husband find freedom to write me a few lines, I hope,
if health permit, you will not forbear.
My lot is cast in a barren land, and I need all the help that can be afforded me:
I am persuaded I need not request you to remember me,
since I have good reason to believe our spirits are united in gospel- fellowship;
in which I at this time both salute and bid you farewell,
and am your affectionate friend,

[.signed-section-signature]
Catherine Payton

Before I left Ireland,
I found my mind drawn to visit the quarterly meeting of
ministers and elders in the province of Ulster by an Epistle;
and soon after my return home,
I was also concerned to write a few lines to a people at Cardiff in Wales,
who had in part relinquished their former professions of religion,
and sat together in silence, but were in an unsettled state.

[.blurb]
=== To the few who have been convinced of the rectitude of waiting upon the Lord in silence, and accustomed to meet for that good end, in Cardiff.

[.salutation]
Friends,

In the love of my heavenly Father, joined with a sense of duty,
am I engaged thus to salute you; desiring your steadfastness in the unchangeable Truth:
that being grounded in right faith,
you may not be carried away with every wind of doctrine, but in stability of mind,
may be able to distinguish between what proceeds pure from the Fountain of wisdom,
and what is mixed with human policy, and the traditions of men;
which tend to alienate the mind from the simplicity of gospel worship,
and fix it in outward performances,
amusing it with bodily exercises which profit but little.

By this means, many times, that tender spiritual sensation, with which the soul,
in the infancy of religion, is blessed, in measure is lost,
and the understanding clouded; the mind being either plunged in a labyrinth of thought,
or exalted above that diffident childlike state,
in which the humble followers of the Lamb delight to abide:
because therein they are capable of knowing his voice from that of a stranger;
and receive strength to follow him through the several
dispensations of probation he is pleased to allot them.

Many times since I saw your faces have I looked towards you,
and I wish I could say I have beheld all keeping their habitations in the Lord.
But, alas! instead of that, has there not been a swerving aside,
and building again that which you had taken some good steps towards abolishing; which,
whosoever does, makes himself a transgressor? May I not query,
Why halt you between two opinions? I believe this to be one cause of your weakness,
and I fear, if persisted in, will prove your destruction.
I believe it was the merciful design of the Almighty to
redeem you from a dependency on mortals,
and to bring you to wait for the immediate teachings of his Spirit,
and to confide in his power, from a lively sense of its sufficiency:
and had you simply followed Him,
his Almighty arm had been exalted to the bringing down of your enemies,
and the enlarging of your understandings;
so that you would not only have seen that there was light,
but the miraculous cure of blindness had been perfected,
and in the light you would have discerned objects clearly.
Here you would have grown in Christian experience, and having received the holy unction,
you would have found as you abode under it,
that you needed not that any man should teach you,
for that this anointing was sufficient to instruct in all things.
And here you would have been able to distinguish between words accompanied with,
and those without, the power of God, by the different effects each had in the soul:
the one tending to quicken unto God,
and the other to bring death over the spiritual life.

According to the nature of things,
a ministry out of the life of the gospel can only beget its likeness:
it may fill the head with notions, but can never replenish the soul with grace.

But, as it is the business of the enemy to delude the judgment with false appearances,
he will endeavour, by puffing up the mind with vain conceits,
to make a likeness of the effects of the Truth.

The head being stored with knowledge, and Christianity in part understood in theory,
by working upon the imagination,
the poor deluded creature may boast of visions and enjoyments, and,
soaring on the wings of deception, may abound in rapturous expressions;
but though he may talk of God and Christ from morning till evening,
it is but warming himself at a fire of his own kindling,
being destitute of the efficacy of grace.

Truth has a natural tendency to humble all the faculties of the soul,
to make it "`rejoice with trembling,`" and to clothe it with meekness, resignation,
and contrition; in which state it seeks to repose itself on the breast of the beloved;
or in silent adoration to bend before his throne,
and in tenderness pour forth itself in mental prayer, or praises;
but to address him verbally with awful reverence and diffidence,
knowing it is presumption so to do but from the movings of his Spirit.
If it be long deprived of his presence, it seeks him sorrowing;
but as it advances in experience,
is cautious of disclosing its condition (as in
the night) to the various reputed watchmen;
lest by unveiling to the unregenerated the secret conflicts it endures, they,
either through uncharitableness or unskillfulness, wound instead of heal;
or direct it to other objects, instead of informing it where to find him whom it seeks.

These observations occurring to my mind, I hope you will receive them in gospel love,
in which I think they are communicated.
I now conclude, with desiring that if any instability has appeared in your conduct,
you may for the future keep more close to the divine Guide;
that you may be clothed with wisdom and strength,
and witness salvation and peace to attend you.
I am your real friend,^
footnote:[I note upon this epistle, that,
although for a time there appeared a degree of
convincement of the Truth amongst these people,
that were so scattered,
that scarcely one of them steadily and uniformly abode upon its foundation to the end.]

[.signed-section-signature]
Catherine Payton

[.signed-section-context-close]
Dudley, 16th Third month, called March, 1752.

This winter I found my mind drawn in the love of
Truth to visit the meetings of Friends in London,
and experienced true peace in the discharge of that duty.
My service was acceptable to Friends,
and I returned home in thankfulness of heart to the Lord,
unto whom is due the praise of all his works.
I lodged with my former schoolmistress, Rachel Trafford,
who now rejoiced in receiving me as a minister of Christ.

Thus far have I written as things have been revived in my remembrance,
having made few or no minutes, while on my journeys, of my labours and exercises;
but in my next journey, which was into Scotland,
my mind seemed directed to make some remarks as I went along; which,
as they are expressive of the nature of my service,
and the manner wherein divine Wisdom led me in the various changes of seasons,
I insert almost entire.
