== Chapter III

[.chapter-synopsis]
* Goes into Scotland in the work of the gospel
* Visits the meetings of Friends there and some meetings in England
* Prospect of paying a religious visit in America
* Letter to Mary Peisley and her reply

On the 3rd of the fourth month, 1752, new stile, we went to Colebrookdale,
and had a meeting there the same evening, in which we had good satisfaction:
the testimony of Truth flowed to the youth,
some of whom were carried away with the vanities of this world,
and the tender seed of life in them was oppressed.

The 4th, we went to Shrewsbury, and that evening,
accompanied by some Friends of the town,
visited two Friends who were imprisoned for tithes:
in which visit we were favoured with the flowing
of the refreshing streams of divine love,
wherein the spirits of some of us were united and comforted.

The 5th, being the first of the week, we attended two meetings in that town.
In the morning,
the testimony of Truth was in a good degree set over the minds
of the people of other societies as well as of our own;
although there is in this place a dark spirit;
but the Lord was graciously pleased to bear our spirit above it.

In the afternoon, many people of other societies came in;
but it consisted with infinite Wisdom to disappoint their expectations;
and as I abode in silence, I had peace.
I thought the cause of this trial might be an example to one of that place,
who was forward to minister, but without divine authority.

In the evening we again visited the prisoners; and the 6th, went towards Warrington,
and so proceeded the 8th and 9th to the quarterly meeting at Lancaster;
wherein I thought the expectation of the people was considerably towards me,
who was a stranger in the country; under which I suffered,
but patiently bore my testimony in silence;
being deeply affected with a sense of the prevalence of
that spirit which would exalt the creature.
I was refreshed under the ministry of that deep and experienced servant of Jesus Christ,
John Churchman of America, whom, with his companion John Pemberton, we met at this place.

The 11th, we went to Kendal, where the quarterly meeting for Westmoreland was held;
wherein John Churchman had good service, but I was still pretty much silent;
in which dispensation I felt the refining power of the Almighty near,
and was sensible of its service, in emptying my soul of old things,
and preparing it for the fresh reception of the openings of Truth.

The 13th, in company with John Churchman, and many other Friends,
we set forward for the yearly meeting for the four northern counties,
which was held this year at Carlisle.
In our way there myself and companion staid a meeting at Penrith,
which was previously appointed by Kendal Friends,
and was attended by many people of other societies;
and I believe would have been of good service, had it not been for some,
with whom discerning Friends had not unity, intruding into the service of the ministry.

At Carlisle, my spirit was set at liberty, and I laboured weightily,
and was much favoured in the enlargement of Truth.
There seemed a great struggle between the two powers of light and darkness,
and what greatly added to the exercise of sensible Friends was,
that the power of darkness discovered itself in the appearance of ministry,
through some deluded spirits; but, through divine favour, Truth had the ascendency.

We staid at Carlisle over the next first-day,
in which time we visited several families of Friends to satisfaction.
The meetings on first-day were attended by many of the town's people,
and we were favoured with an evidence of being in our proper place and service,
which was renewed cause of thankfulness.

From the 20th to the 23rd, we visited several meetings in Cumberland,
wherein the expectation of the people was great;
but my satisfaction and rejoicing stood in abiding with the seed of God,
which being oppressed in the souls of some professors of Truth,
the testimony of it did not rise in such authority, as at some other times.

The 24th, we went a long day's journey to Kelso in Scotland,
at which place my spirit was sorely distressed on account of
Truth's being almost forsaken by its professors,
who were but few in that town.
We got some comfort in visiting a sick Friend,
whose son and husband we thought in a hopeful way.

The 27th, we went to Ormston, and in the way there, my mind was drawn to the eastward;
but when we came to our quarters, I could see but little likelihood of getting,
any assistance in visiting the people that way.

The 28th, we had a meeting at Ormston, which was exceedingly crowded, but satisfactory.
Being still thoughtful about the people to the eastward, John Christy,
at whose house we lodged, told me that if I would stay till the 30th,
he would accompany me to any place I should choose; which I was free to do,
and we went to North Berwick,
where I knew not that any meeting of Friends had been held before.

We had a dark spirit in some to encounter, before we could get a place to meet in,
but at last we got a large granary.
My spirit was inexpressibly loaded before meeting,
but in patience bent towards the centre of its strength,
in which state I went to the meeting.
There came many people, and I admired at the solidity of their behaviour.
The Lord was with us, and exalted the testimony of his Truth,
and we left the town in great satisfaction, and I hope true thankfulness.

We returned that night to Ormstoh, and the next day, the 1st of the fifth month,
went to Edinburgh, where we lodged at William Miller's.

We attended the meetings in that city on the next first-day.
That in the morning was pretty large,
there being very few who profess with us in that city,
and although cloudy in the beginning,
yet the Almighty was pleased to favour in the conclusion,
in exalting the testimony of his Truth.
In the afternoon the house was exceedingly crowded, and the people very unsettled;
but after a long time of exercise, life rose measurably,
wherein the spring of gospel ministry was opened.

The 5th, we went to Linlithgow, where was no meeting of Friends.
We got a small meeting in an inn with the town's people, which was low,
though not quite dead; and returned at night to Edinburgh,
having travelled about twenty-eight Scotch miles that day.
In the morning before I set out, I found myself very poorly,
and in the journey I got worse, and the next day still worse;
yet I attended a meeting which was appointed for the professors of Truth only,
whose states were mostly distressing, a libertine spirit having carried away the youth,
and an easy indifferent one prevailed amongst those further advanced in years;
both which were spoken to.

My illness still increased, and, proving a fever,
reduced me to a state of great weakness, and I experienced much poverty of spirit;
but my frequent petition to the Almighty was for patience,
and he was pleased to favour me with quietness and resignation.

The 25th, we went from Edinburgh towards the north.
I was still very weak, but gradually gathered strength,
and was encouraged to press forward;
which I did as far as there were any meetings of Friends,
and returned to England by way of Perth and Glasgow.
The number of Friends in Scotland is small, and the life of Truth low in some of them;
but among the few, there are some who stand as monuments of the divine power,
in this barren and almost desolate land; wherein, however,
there is an open door in many places,
to preach the gospel to those not professing with us.

From Glasgow we went to Carlisle without holding any meetings.
The first night we lodged at Stirling,
where my spirit was exercised respecting the holding of a meeting;
but having only one young man with us, not the most steady as a Friend,
and it appearing to be a high professing place, I allowed cowardice to prevail,
which occasioned future distress:
there was time enough for an evening meeting after we came to our inn;
and I think the landlord would have granted us his large dining-room.

In the morning we proceeded forward, a long day's journey, and dangerous roads;
lodged at a very poor lonely Scotch inn upon a chaff bed; our bed-room a ground floor,
and no fastening to the door; and there being men in the house drinking,
we were not quite easy with our situation, but through divine favour, we went to sleep,
and were preserved from harm.

We rode through much heavy rain from Glasgow to this place,
which had swelled the river Erisk so much,
that it was not thought safe to attempt to pass it the night we came there;
but next morning we crossed it in two branches: it had a dreadful appearance,
the water looked very muddy, the stream wide, deep, and rapid; but we had careful guides,
and through favour of Providence got safely over the 17th of the sixth month,
and came to Carlisle the same day.

And here I may note to the honour of Scotland, that in all the time I was in it,
I do not recollect hearing an oath or a curse uttered,
(except the word faith might be accounted an oath,
which was spoken by a soldier.) Alas! for England! the
streets of whose towns echo with most profane language,
to the shame and condemnation of its magistrate?, as well as its wicked inhabitants.
At Carlisle I parted from my companion,
who was concerned to visit some of the northern counties, and I,
to attend the quarterly meeting at York; where I came the 22nd,
taking meetings in my way, at Penrith, Raby, and Haby.
The last being a monthly meeting, was pretty large,
and I believe many souls were refreshed therein:
the testimony ofTruth rose in considerable strength and clearness;
and the meeting concluded in a sense of heavenly sweetness,
which was again renewed in the women's meeting.
My spirit was humbly bowed in thankfulness, that my lot was cast there that day.

At York I met with my dear friend Ann Fothergill from London,
and many other friends whom I dearly loved,
who were glad to see me returned to my native land,
the more so from a report having prevailed in England, that I was dead.^
footnote:[I think it worthy noting, that Samuel Fothergill,
being at London yearly-meeting, when this report was current,
on a Friend's bringing him a supposed confirmation of the truth of it, paused awhile,
and bid her tell the person who informed her, from him,
"`She is not dead;`" which was soon confirmed by an account from Scotland.]
My mind was turned to consider the wonderful loving-
kindness of Providence manifested in this journey;
and,
considering my weak state of health through a great part of it,
I thought it miraculous that I should so soon accomplish it;
such a fatigue seeming no way proportioned to my strength.
But with God all things are possible;
therefore have his servants cause to' trust in his holy arm of power.

The quarterly meeting at York was mercifully attended with the
presence of the Master of our solemn assemblies;
the testimony of Truth was exalted,
and the spirits of his people united in gospel fellowship.

The 25th, I went to Malton, accompanied by my dear friend Sarah Taylor of Manchester.
We had a meeting there that evening, and the 26th went to Scarborough,
and that evening visited a young man, who I thought was near his end;
but we had little to say to him, his condition being lamentably stupid.
I thought intemperance was the cause of his indisposition,
and found afterwards I was not mistaken.
O! the deplorable effects of this degrading vice on the body, soul,
and temporal substance, of numbers who unhappily indulge in it;
whose faculties are debased below those of the brute animals;
and so stupified as not to be roused to the most important work of their souls salvation.

It lays men open to every temptation,
and reduces many from opulent circumstances to extreme poverty.
It is destructive of every delicate social enjoyment; it often emaciates the body,
deprives the soul of its highest good, the divine Presence, while in time;
and if continued to the end of it,
finally excludes it from Christ's pure kingdom of everlasting bliss.
Alas! that men should indulge in it to their shame.

Solomon says truly, "`Wine is a mocker, strong drink is raging,
and whosoever is deceived thereby is not wise;`" again,
"`Who has woe? who has sorrow? who has contentions? who has babbling? who has
wounds without cause? who has redness of eyes? They that tarry long at the wine,
that go to seek mixed wine.
Look not you upon the wine when it is red, when it gives his colour in the cup,
when it moves itself aright.
At the last it bites like a serpent, and stings like an adder.`"^
footnote:[Prov. 20:1; Prov. 23:29-32]

The 27th, being first-day, we attended the meetings.
In the morning, we were much favoured with the evidence of Truth in our service:
several were there not of our Society who behaved well,
and I believe went away satisfied.
My concern was to show them the difference between true and false faith,
and the tendency of each; with some other truths,
which immediately opened in my understanding.
In the afternoon, the meeting was large,
but the Lord saw fit to disappoint the expectations of the people,
and manifest both to them and us, that without him we can do nothing in his service;
for neither of us had a word to say to them but I was concerned in supplication,
and was abundantly rewarded, in submitting quietly to this dispensation of divine Wisdom.
In the evening, we visited two Friends who could not attend meetings,
by reason of age or indisposition; and next morning,
another Friend in a very low state of mind, with whom we had a good opportunity,
and left him better than we found him;
and I afterwards heard that from that time he was restored.
That afternoon we departed in peace from Scarborough, and returned to Malton, so to York,
Leeds, Rawden, Bradford, and Halifax;
in all which places I met with a share of exercises, and, I thought,
was mostly very low in the ministry;
but had the consolation to believe that what I stammered out,
was suited to the states of the people which is a proof of true ministry.

The 7th of the seventh month, we came to Manchester, where I left Sarah Taylor; the 10th,
I went to Warrington, and had a meeting there that evening,
wherein I was silent as to testimony.

The 11th, I went to Liverpool; in my way stopped to take some refreshment at Prescot,
and found my mind exercised for the people of that town,
wherein there was no meeting of Friends; but went on for Liverpool,
and next day was at two meetings there, and visited a Friend in distress,
in all which I had good satisfaction.

In the evening, finding a concern for Prescot still to remain, I proposed to Friends,
having a meeting there the next morning, in my way to Warrington; which,
though some difficulty was started, was accomplished, and a blessed opportunity it was;
the Lord's power being largely revealed, and the people behaving solidly,
although I suppose,
a meeting of Friends had not been held in the town for very many years.
In the evening, I had a meeting in Warrington.

The 14th, I went to Morley,
my dear friend Samuel Fothergill and several other Friends accompanying me,
and several others meeting us from Manchester: and the Lord, in his wonderful mercy,
was pleased to open the fresh spring of his love,
and favour us with a sweet opportunity together therein:
in a thankful sense whereof we parted from each other
and I came by way of Stafford and Atherston,
home the 20th, where I was gladly received by my dear and worthy mother, etc.
After some little time of settlement,
my mind was directed to take a view of my late journey,
in the course whereof I discovered the wonderful
lovingkindness of God largely manifested;
but was for a time much distressed on account of not having had a meeting at Stirling,
as before hinted:
under which distress my soul ardently desired that for
the future I might be careful to discharge my duty;
for I found it a heavy burden not to be clear from the blood of the people.

In a few weeks after my return from this journey
I went to our quarterly meeting at Shipston;
which was eminently favoured with the presence of the Most High,
In the fall of the year I was obliged to accompany my sister to Bath,
for the benefit of her health;
in which city I was the most affectingly dipped into a state of poverty,
that ever I had known myself to be, which, being joined to great weakness of body,
was hard to bear, yet I believe not without its peculiar service.

I visited Bristol meeting twice in this journey,
where I was made to taste of the poverty and weakness which appear in many there,
through unfaithfulness.
It was indeed a time of mourning to the servants of the Lord,
while those who were the cause of it required of them a song;
but they were constrained for the most part to bear their burdens in solemn silence.

At Bath I suffered much under a libertine spirit,
which was very apparent both amongst those who professed Truth, and others in that place.
I had several testimonies of close reproof to bear to Friends,
and some pretty open service with strangers in town,
and upon the whole had cause of thankfulness administered;
the Lord rewarding my faithfulness and sufferings with peace in the end;
and I returned home in a much better state of health than I left it;
the use of the waters having been of service to me, though of little to my sister.
But now another trial of faith came upon me,
which was the near approach of a visit to Friends in America,
which had appeared in prospect for about a year;
with an apprehension that I must go with my dear friend Mary Peisley,
who I believed was preparing for that service:
yet I never gave her any hint of accompanying her,
being desirous that if it must be my lot,
it might be evidently pointed by the finger of Providence.

On my return home I received a letter from her, wherein she desired to be informed,
whether I knew of any woman Friend going to America from England,
and hinted her concern for that quarter of the world.
This stuck closely to my mind, yet I kept it to myself for several weeks,
and then communicated it to my dear mother, who heard it with a becoming resignation,
telling me it was not entirely unexpected to her.

And although it was exceedingly hard, to the natural part in her,
thus to part with me in her declining years;
especially as she so tenderly loved me as a child, as well as in the Truth;
she freely gave me up to the divine requiring,
earnestly desiring that the Lord might be my director and preserver.

Upon this I wrote to my dear friend Mary Peisley.
Some extracts of my letter to her, with her answer, follow.

[.letter-participants]
Catherine Payton to Mary Peisley

[.salutation]
My Dear Friend,

It is not because I forgot your
affectionate request of hearing from me soon,
that I have so long postponed a reply to your last acceptable favour;
but when it came here I was from home,
as I hope you are already advised by a few lines I wrote from Bath,
and the sequel of this will discover my reason
for not writing you immediately on my return.

With pleasure I observed that your health was better than heretofore,
and hope the blessing is still continued, so that by the assistance of heavenly goodness,
you have been and still may be capable to perform the duty required,
with a degree of ease and cheerfulness,
to which a good share of health greatly contributes;
although it must be confessed with humble gratitude,
that the Lord is to his servants strength in weakness of body as well as mind.

What we have seen of the exaltation of his arm of power in this respect,
may encourage us to perseverance, and a steady dependency thereon;
and silence the voice of nature,
which sometimes insinuates that we are not able to perform what is required;
for we have good cause to believe nothing is impossible with Him who has called us; but,
through his power communicated, we may perfectly perform his will.
And suppose our race to be attended with weakness, pain, anxious concern,
travail of soul, and inconvenience to the body;
can it ever equal the incomparable sufferings of the Captain of our salvation? Oh!
how does the consideration of the tribulated path he invariably trod,
stifle the pleadings for ease and pleasure?
For, shall we who dare to aspire to no higher title than servants,
expect to be better accommodated than was our Lord? Shall,
we supinely settle in the outward possessions afforded us,
when he laboriously trod the wine-press alone,
and that for our sakes? He was destitute of a place of residence,
and had not where to lay his head, though Lord of all;
and although he could limit the power of Satan, yes, totally bind him,
yet permitted the contradiction of sinners against himself,
as well as a series of deep temptations.
Let us be united to the sufferings infinite Wisdom allots,
remembering the blessing dropped on such as endure afflictions.

I know to whom I am writing,
and believe that you are much farther advanced than
myself in this glorious resignation to the divine will;
but thus much I may say, that, as I have seen, in a degree,
into this happy state of constant devotion,
I ardently desire to be made a partaker therein.

I rejoice to find that unity and sympathy of spirit,
which so remarkably attended us when present, subsist now absent;
and thought riiy wish in my last was answered in the sense you had of my state.
Oh! may we both be preserved near to the Fountain of life,
and then we must be near each other in the fellowship of the gospel,
which distance of space cannot hinder, nor time efface;
but it will centre with our spirits in that
unchangeable state of felicity we humbly hope for.

I now come to answer your last request, which will show the cause of my silence, that is:
Whether I knew of any woman Friend who was going from England to America.
I told you I had a hint of _______'s inclination, the same I had of _______,
but know not that either is more than supposition,
for I do not hear that either are preparing to set forward,
and have heard of no one else.

But my dear friend,
I am almost at a loss to find terms to express the
laborious thought which has possessed my soul;
for it seems to me; that Providence designs I should accompany you; unto which,
if way may be made for me, and an unquestionable evidence given that it is right,
I am at last resigned; although it be but to be a servant of servants;
but He only knows who discovers the inward struggle between flesh and spirit,
with what reluctance I shall, if it must be so, part from my dear relations,
especially my dear and honoured mother, to whom I have communicated the painful thought.
She heard it with becoming resignation,
being determined to give me up to the divine requiring;
only desires to be convinced it is such, which I hope is but an allowable request.
I have waited to have the thing a little settled on her mind,
and she yesterday gave me leave to inform you of it.

And now my dear friend, I entreat you to weigh it well,
and as disinterestedly as possible,
and give me your thoughts thereupon with all the freedom which
our friendship and the nature of the case require,
not concealing one doubt; for I am exceedingly afraid of being deceived,
and would willingly be convinced,
if this appearance is but for the proving of my submission.
But however it may be, I find peace in standing resigned,
and trust my good Master will rightly conduct me.

Notwithstanding what I have before said,
if any companion offers with whom you have freedom to join, pursue your journey,
and leave me to Providence, who, I believe will take care of me.

[.signed-section-signature]
Catherine Payton

Some extracts of Mary Peisley's letter to Catherine Phillips, in answer to the foregoing.

[.salutation]
My Dearly Beloved in the Lord,

This goes with the salutation of my best love,
and may inform you,
that I received your two very acceptable favours of the tenth and twelfth month.
The last came first to hand, for I did not get that from Bath till last week;
yet was it very acceptable to me,
and a stronger confirmation of what you mentions
in the latter part of your last being right,
if my concern is so.
For the baptism you there describes as into a cloud of darkness,
bears a just resemblance to what my spirit passed through,
before I had a distinct discerning of the near
approach of the journey which is now before me:
and agrees with the experience of that great instrument John Churchman,
as he wrote to me before he had any knowledge of my concern,
but what he received by sympathy; which was some strength to me,
and what I greatly desired.
Your last came to hand about two weeks after its date,
which I should have answered sooner, but that I waited for his answer,
being willing to comply with your request^
footnote:[That part of my letter to Mary Peisley I
omitted to transcribe in the before-written abstract.]
in consulting him, which I had not done before:
and notwithstanding his writing as he did; his reply was,
"`That he had thoughts of my being under such an exercise,
and therefore my letter was not surprising to him; but that he had little to say to it,
well knowing that it is safe for us all to attend to that divine instruction
which can alone make truly knowing in our least acceptable services at home,
as well as the most weighty we may be called to
abroad;`" but what he did say was very edifying,
and although the concurrence of such as he is what we must naturally desire;
yet to our own Master we must stand or fall.

I find it a great trial to my poor father to part with me,
but the thoughts of your going with me has made it much easier to him;
and for my part I may acknowledge it as a favour, neither looked for, nor expected;
it being like forbidden me to take any thought about a companion,
as well indeed it might, when my kind, good Master was providing so agreeably for me.
To my kind and good Master I owe first and chief my hearty thanks,
for all the benefits received from secondary causes.

But you may remember, my dear,
though I wrote to you to know if any Friend from your nation was likely to go,
it was not by way of querying for a companion; but it springs in my heart to say,
"`You are the woman,`" and I really believe the thing is of the Lord;
and as we abide in his counsel, I firmly hope that he will bless us together,
and make his work to prosper in our hands, if our eye be but single to his glory,
seeking, hoping, nor desiring, anything but the advancement thereof:
and I can assure you my dear friend,
notwithstanding the love I have for you in the Truth,
and the affection which I bear to your person,
with the likeness of souls I had discovered; yet,
did I feel any obstruction or doubt in my mind of the thing's being right,
I dare not conceal it from you, nor take one step knowingly,
out of the light and counsel of Truth, in so important an affair.
It is just with me to say,
"`Tempt not the Lord your God,`" in seeking more strong and
convincing manifestations than he may see fit to give you:
but be willing to go in faith, leaning on your staff; for I must tell you,
I think I have brought sufferings on myself for so doing; for,
since the time that it was clearly manifested unto me as a duty,
till within these few weeks, I have been peaceably resigned;
in which state was favoured with great tranquillity of soul,
which made me look on the difficulties and dangers of the journey, with such eyes,
that I began to fear that I had a will to go, and set my face against it,
till I had a further manifestation of its being right.

And here nature began to please itself with many pleasing prospects in my stay;
and the enemy was at hand to suggest that the former
manifestation was but to try my love and obedience;
and here I lost faith,
and without it could no more think of going than of removing mountains.
Thus did the enemy work as in a mystery,
till my spirit was brought into such darkness and distress,
as is better felt than expressed.

I am now again, by the mercy of God, and by that faith which is his gift,
fully resigned without any further manifestation;
than in looking that way wherein I see a little light, peace and comfort to my poor soul;
arid in turning any other, fear, pain, and darkness, meet me.

Thus, my friend,
have I given you a short but true account of the dealings of the Lord with my soul;
which has been the cause of my silence till this day,
for the forepart of this letter was written more than three weeks ago,
but could not find strength to finish it till now;
yet in all that trying season had no doubt of your concern being right.
Ah! what states and dispensations must we pass through,
who are fitting to speak of the Lord's wonders which are seen in the deeps!
If it be my lot to go, the way which now seems pointed to me is,
to spend some time in Dublin:
to go from there with Friends to the yearly meeting at London; and,
when clear of that city, to take shipping from there:
this I hope will be acceptable to you,
but if you have any call to Ireland before you goes, let not this prevent you.

[.signed-section-signature]
Mary Peisley

After the receipt of this letter I continued to make preparation for the journey,
my way being open both in the minds of my relations and friends;
though it was a trial to both to part with me.
