== Chapter IV

[.chapter-synopsis]
* Embarks for America
* Voyage to Charleston, South Carolina
* Letter to her brother Henry
* Travels through the Southern, Middle, and Eastern States
* Sails for Dublin
* Returns home

On the 4th of the sixth month, 1753,
I took an affecting and affectionate farewell of my dear mother and relations,
leaving her and them to the protection of Providence; and went,
accompanied with my sister Ann, to Worcester.
I was at a monthly meeting there the next day, which was laborious and exercising,
some Friends being sunk into a state of indolence,
and though sometimes favoured with a feeling sense of divine good,
not quickened thereby to action in the affairs of the Church:
thus the visitation of heaven is rendered fruitless,
while the things of this world are pursued with industry and ardency.
Against this spirit, I, with some others, had to testify in close doctrine and advice;
and, although the meeting was dull and painful in the beginning,
it ended m a sweet living stream of supplication and praise: in which the living present,
committed each other into the hands of the Almighty for preservation.

In the women`'s meeting, I endeavoured for a regulation,
that our Christian discipline might be revived,
for which a concern had rested upon my mind for some years:
and some women Friends of this city being under a like exercise,
it afforded a comfortable hope, that the Lord would qualify instruments for this service.
In the evening, the visitation of infinite Goodness was renewed to us,
and to a few Friends who came to visit us at my dear friend Ashby`'s,
in the sense of which we parted.

The 6th we went to Evesham, where we were met by my brother James,
and several Friends from Ireland, who were going to the yearly meeting at London.
We stayed over the monthly meeting there the next day, and so proceeded on our journey,
Ann Ashby going forward with us, and reached London the 9th,
where I met with my dear friend and companion, Mary Peisley.

The yearly meeting was large, and attended by many weighty Friends;
who were divinely assisted to labour for the promotion of Truth,
and the ordering of the affairs of the Church.

My brother and sister left me in London; and,
my companion Mary Peisley having a concern to attend the meetings at Colchester,
Woodbridge, and Norwich, I spent a little time at Chelmsford,
at the house of John Griffith,
the state of my health and spirits being such as seemed to call for rest and quiet,
and returned to London in about two weeks.
Being still poorly in health,
I went to the country house of my worthy friend John Hayward,
accompanied by Ann Fothergill; where I was indisposed,
and confined to my bed and the house, for about a week.
Recovering a little strength, I returned to London; where the disorder returned,
and continued for nine or ten days; and being succeeded by the jaundice,
it brought me very low; but through the kindness of Providence,
I was preserved patient and resigned under this dispensation.
In this time my companion returned to London,
but did not find her way open to leave England;
so that my trials were increased with the prospect of being longer detained,
and at a distance from my dear relations.
But infinite Wisdom knows best how to plan out the way for his people,
the secret workings of whose Providence I thought I clearly discovered,
in this succession of probations being permitted to attend me where they did.
Had it been at home it would have been much more afflicting,
both to my relations and myself;
as it would have rendered their parting with me
in such a weak state of health the more painful,
and my leaving home the more difficult: no, I have questioned,
if I had not left it as I did, whether, considering the discouragement,
I should have gone the journey.
Nor was my indisposition without a singular service;
for my health had languished under the oppression of
the remains of the fever which I had at Edinburgh;
which by this disorder were, in a good measure, carried off,
and my body the better prepared to sustain the
fatigues and trials of the ensuing journey,
arising from the difference of climate, etc.
So that in this painful allotment,
I had`' renewed cause to bless and praise the name of my God, and to acknowledge,
that whatever he does is best.

Almost as soon as I recovered strength to get abroad, the cloud dispersed;
and we found our spirits at liberty to take our passage on board the Alexander,
Captain Curling, bound from London to Charleston, in South Carolina;
which sailed in about a week after we agreed to go in her.
The last first-day we were in London,
we were favoured to take a comfortable farewell of many of our friends,
in the feeling sense of divine goodness; wherein also,
we were enabled to resign and commit each other
into the hands of the Almighty for preservation.

We left London the 21st of the eighth month, 1753; and,
as our vessel was to stop at Portsmouth to take in some of her passengers,
our friends thought it best for us to go there by land: which we did,
and several of them freely accompanied us.

We came to Portsmouth the 24th, and went on board our vessel the 25th,
where we took leave of our friends with affection.
Being settled in our vessel, a sweet composure came over my spirit;
which strengthened my faith that I was moving by divine direction.

The next day the wind turned against us, and we came to an anchor in Yarmouth Road,
Isle of Wight.
Being first-day, we were a little thoughtful about having a meeting with the passengers;
but one of our company being a clergyman,
and the ship`'s crew busy in settling the vessel,
we concluded it would not be very easily obtained,
and were content in sitting together in our own apartment;
during which time the parson got some of the people together in the great cabin,
and read prayers to them.

I had purposely left our room door open, in order that, if any duty presented,
I might have an opportunity of performing it; and after they had done,
I found a concern to call upon the Lord in humble supplication, to which I gave up;
but a part of the company went on deck, being I supposed exampled by their teacher;
however I was favoured with a pretty satisfactory opportunity,
and the strengthening evidence of peace in the conclusion.

The 27th, we set sail, and passed the Needles the 28th. The 29th,
the wind came against us, and blowing hard we anchored in the evening in Portland Bay,
where we lay till the 3rd of the ninth month; when we set sail,
and got clear of the land the 5th;
from which time we were mostly favoured with gentle favourable winds,
till we came near the coast of South Carolina.

The 18th of the tenth month, we got into soundings; but the wind blowing very hard,
and the sea running high, our captain dared not attempt to go over Charleston bar,
so stood off, in hopes the wind might fall; but instead of that it turned against us,
and continued to blow very hard till the 22nd:
all which time we lay with our helm lashed, driving with the wind.

The 22nd, the sea and wind fell very much, the weather,
which in this time had been very foul, cleared up, and the wind became favourable,
we got within sight of land; but it being to the southward of our designed port,
the captain tacked about to the northward,
hoping thereby to gain so much in the night as to be
able to run in with the tide in the morning;
but we were again beaten back to sea by a contrary stormy wind.

Thus were we tossed to and fro, almost within sight of our harbour;
but through prevailing grace our minds were wonderfully
preserved above either fear or complaint,
enjoying a calm within, in the midst of a storm without;
being happily resigned to suffer in this way, if it were the Lord`'s will so to appoint:
which blessed disposition, attended us through the voyage,
and helped to alleviate our bodily hardships,
which would otherwise have appeared considerable.

We were sea-sick, though not so extremely as we expected;
and we suffered much from the excessive heat of the weather, steering within one- degree,
as far south as the tropic of Cancer;
in which latitude I believe we continued nearly three weeks, being becalmed; and,
neither I nor my companion being very strong, nature had a considerable struggle,
to surmount the expense of spirits we sustained.
But we had cause to be thankful that we escaped a violent fever,
which frequently seizes those who pass through this climate,
and have been used to one much colder.

During the storm, the seams of our vessel, being opened on the side where we lay,
let in the wet, and our apartment was in a manner flooded.
My bed was so wet that I could not lie in it,
so I threw myself down for several nights upon
some blankets in a birth in the great cabin,
and slept better than I could have expected;
but the spray of the sea drove upon it even there, and my linen was so damp,
that I esteemed it a singular mercy I was not exceedingly ill.

Indeed we were both of us brought very low,
but recruited again as the weather cleared up; which it did the 24th,
and we set sail in the evening.
The 25th got our pilot on board,
who intended that night to run as near the bar as prudent,
and wait for another tide to carry us into port.
But here we apprehended ourselves to be in imminent danger; for,
the man who sounded mistaking; the length of the line which he let go,
the vessel ran too far before they dropped anchor;
so that we lay all night in very shallow water, so near, if not upon the breakers,
that had the wind sprung up fresh,
it seemed questionable our`' having room to turn the vessel from them,
when the anchors were weighed: but the Lord preserved us,
and we landed at Charleston the 26th in the morning,
under a grateful sense of his merciful Providence having attended us through the voyage.
We were upwards of nine weeks on ship-board.

We had several meetings while on shipboard with the sailors and passengers,
who were of different countries.
There was a South Carolina woman and her negro maid, a man and his wife,
the one a German and the other a Swiss; a Scotch schoolmaster,
our captain and his brother of French extraction, if not born in France.

Our first meeting was with the sailors and steerage passengers,
on the afternoon of the first-day wherein we lay at anchor in Portland Bay.
The priest, in the morning, read prayers to the cabin passengers,
but took no care for the others on board.
The captain offered us the cabin to meet in,
but we rather chose to go to them in the steerage;
from which the priest would have dissuaded us, by telling us,
they would be likely to insult us; but,
on our sending a message to the sailors that we intended them a visit,
they returned for answer, that though they had not had college education,
they should be glad to hear the word of God, and would readily admit us.
The meeting was attended with a good degree of solemnity,
and afforded satisfaction to ourselves.
My companion was favoured in testimony suited to the states of the people,
and I was graciously admitted to supplicate the Lord for them.

Our other meetings were held in the cabin,
which we had the use of for that purpose on the afternoons of the first-days,
as the parson had, in the mornings.
They were generally attended by most of the passengers and some of the sailors;
but there being but little entrance for the word, made it hard labouring among them.
We were, however, favoured with peace, in endeavouring to promote their good;
and blessed with the incomes of divine life in our own souls,
not only on those occasions, but at many other times:
so that it was a season to be had in lasting remembrance, with thanksgiving to the Lord,
whose good presence accompanied us when on the mighty ocean,
and rendered our separation from our dear relations and friends easy.

The parson, observing that in our ministry, we spoke extempore,
told me that he could preach extempore,
and we should hear him if we pleased the next Sunday, Accordingly when the day came,
we were all seated in the great cabin, and he preached without notes.

His subject was the transfiguration of Christ,
which he found a wonder,--expatiated upon it as a wonder,--and left it a wonder;
without entering into the spirituality of the text:
indeed I doubt he did not understand it.

From this time he read prayers and preached on first-day mornings,
when the weather permitted, and some times we sat in the cabin with them;
and although the inconsistency of their prayers and professions with their own states,
as well as of the manner of their offering them,
with the nature of the solemn duty of calling upon the Lord,
joined to the priest`'s laboured, dry discourses, could not but painfully affect us;
yet in the time of their worship, the Almighty by his power broke in upon our spirits,
and bowed them in contrition before himself: so that, in the enjoyment of his goodness,
we had a silent testimony to bear to that living worship which he inspires, and accepts.

And although both by word and conduct we differed from the priest,
we heard that when he came on shore he spoke well of us,
acknowledging that we had been instruments of good to him;
and particularly that my companion had convinced him of the evil of gaming;
which he appeared to like while on the voyage,
but which we also heard he afterwards preached zealously against,
as well as other vanities.

Indeed he became much changed,
and while in Carolina appeared conscientiously concerned for the people`'s welfare.
Some time after we left America he returned to England,
and I think I heard that the people did not like his close doctrine.

[.asterism]
'''

[.blurb]
=== To my brother Henry Payton, written on board the Alexander, 6th of the Tenth month, 1753, at Sea, Lat. 25° North.

[.salutation]
Dear Brother,

Heretofore when absent,
I have been easy in remembering you with sincere desires for your welfare;
but now a desire of writing to you taking place, I am unwilling to stifle it,
were it only for this reason, that I would do all that is justly in my power,
to strengthen that affection which ought to subsist
between persons so nearly allied in nature.

But alas! when I consider the difference of our affections, pursuits, and sentiments,
in right and wrong, I am fearful to set pen to paper,
lest I should not be read with candour and understanding;
yet am again encouraged to this conclusion,
that you will at least receive it as the effect of my regard for you.
Regard, did I say? I will alter the term to affection;
which I have felt gently to spring in my soul towards you;
not only as to a creature formed by the same Almighty hand as myself,
and for the same noble end, namely, to glorify him who gave us being,
and who has loaded us with a multitude of his favours,
which loudly call for a grateful return; but,
as to a brother who has strayed from the path of peace and safety,
and is seeking satisfaction in the grasp of empty bubbles; which have assumed the form,
in his sight, of something substantial.
But your own experience, if impartially traced, will tell you,
they have broken when touched, and dispersed in air; leaving nothing real behind them,
but keen remorse, and the painful remembrance that they are lost, with all the time,
pains and anxiety, bestowed in the pursuit of them.
Yet in this idle solicitude,
(O! affecting but too just charge!) has a great part of your life been spent;
ardently traversing the destructive mazes of delusive pleasure,
and industriously avoiding the One only Good,
in the possession of which your soul might have found substantial happiness:
a happiness which would have afforded true contentment, in.
which is conveyed that fulness of joy, which only can satisfy the immortal part,
being itself immortal in its nature.

You will perhaps say that these are my sentiments.
But allow me to ask you,
why they are not yours? Why do we differ in opinion and practice,
but because the desire and pursuit of sensual gratifications have blinded your judgment,
and biassed your actions? I will venture to assert that
it was the kingdom or possessions of this world,
its friendships, vanities, and sensual pleasures, spread in the view of your mind,
that drew it from its early love and allegiance
to Him who is truly worthy of love and obedience.
Nature joined with the well adapted temptation (being fond of present enjoyment,
though it be forbidden fruit),
and renounced submission to the pure law of grace written in the heart; which,
had it been observed, would have rectified her impure and irregular appetites,
and have placed you in the true state of manhood; as lord of, not a slave to,
the creation; and governor of yourself, in happy subjection to the Divine will:
a will which invariably points out the everlasting felicity of mankind.
But, rebel to her own interest, nature, blinded by false affection,
and fraught with pride, like our first parents,
does not like a superior that shall control her perverseness,
and prescribe laws for her direction;
but rather chooses to take the reins of government into her own hand,
and plan out a way for herself.

Here reason, blind fallen reason, enthroned by the power of Satan,
usurps the sovereign seat, as sitting in the temple of God, being honoured as God; power,
wisdom, and discretion to direct, being ascribed unto it.
This false king (who, had he occupied his proper place, had made a good subject),
joins in strict league with the passions,
and prescribes rules directed by these his allies.
"`Shall man (says he) be confined within the narrow rules of virtue and religion? No,
I proclaim him liberty.
Let him indulge himself in what is desirable to him;
let him gratify the sight of his eye, and the pride of his heart,
in endeavouring to make himself agreeable to and admired by mankind;
with whom let him join in full society, and free communion,
entertaining and being entertained.

Why may he not partake of the pleasures of sense, seeing he has appetites for them;
and satisfy his curiosity in knowing evil as well as good?

These are the genuine suggestions of the reasoning faculty guided by the
passions (though I confess that I believe the subtle deceiver of mankind,
sometimes teaches this reason to speak in a language
more concealed than I have here set down);
but I think it will be no hard matter to prove,
that this boasted liberty is real bondage,
and that this acquisition of knowledge is no more than a sense of guilt,
resulting from the loss of that innocence which gave man boldness to
appear before the face of Almighty justice and purity,
void of distracting fear.

Let us examine the extent of virtue and religion,
and mark every passion implanted by Providence in the nature of man;
and we shall find that in them alone it is possible these should be rightly gratified,
and that whenever man breaks from their bounds, he flies from the mark of his happiness.

I have looked upon love to be the governing passion in the soul, which, as it moves,
draws the rest in its train, and being strongly fixed on a worthy or unworthy object,
is the cause of our joy or misery.
This being granted,
it is next to be considered what object is worthy of our entire affection:
in which search let it be remembered, that this principle of love,
or desire of enjoyment, is so seated in the soul, as never to be struck from it;
and it will presently be allowed,
that the object that is worthy of its spending its force upon,
or being united to without limitation, must not be dependent on time,
for that death deprives it of; but durable as its own existence,
and so perfect as fully to satisfy an everlasting desire of possession.
This can be nothing else but the Eternal Excellency,
from whom this spark of affection was struck; and if divine order were not inverted,
it would as naturally bend towards its original as a stone to the centre,
where only it can find a happy settlement.
In this love of God, stands virtue; it is this inspires it.
If we truly love God, who is infinite in purity and wisdom,
we shall naturally hate their contraries, impurity and folly,
and shall hate ourselves because of them; because whatever defiles the soul,
destroys its likeness to the divine Being, and renders it unacceptable in his sight.
Hence,
as it is the nature of a true affection to
endeavour after the love of the beloved object,
proceeds an ardent desire of purification, and a filial fear of offending God;
a fear the most rationally founded, in a deep sense of gratitude,
considering him as the Author of all the good we possess, or can rightly hope for,
i+++.+++ e. everlasting felicity; joined to the knowledge of his power and justice,
in punishing transgressions, which self-preservation would teach us to shun: therefore,
whatever would amuse the senses,
so as to draw the affection from this Fountain of goodness,
is dreaded and renounced as forbidden fruit.

In religion, the soul is enlarged, and set at liberty to exercise its most noble faculty,
in actions, or on an object, worthy the dignity of its nature; when on the contrary,
without it, it is in bondage,
and debased in the pursuit of what scarcely deserves the name of pleasure,
being of no real worth or lasting duration.
Religion teaches us that we do not live for ourselves only;
but that in order to obtain the great end of our being,
we must seek the good of mankind and endeavour to be serviceable in society;
yet mix in familiar converse with caution,
lest instead of rectifying the errors of others, we transplant them into our own conduct.
It instructs us to beware of vain glory, or of seeking the applause of men;
clothing the mind with humility,
under a sense that we have no good thing but what we
have received from the bounteous hand of our Creator;
and raising a desire that all his gifts may be devoted to his service.
In short, religion places man in the sphere the wise Author of nature designed for him;
directing his affections to ascend towards the Creator,
and to descend towards the creation.

If the ascent be but sufficient, the descent will be just.
The creatures will be loved as the work and gifts of the Creator;
yet possessed with due caution from this consideration,
that they are allotted us but for an uncertain season;
and that it is therefore our interest to be able to surrender them when called for,
with as little pain or anxiety as is consistent with our state.
On the reverse,
the immoderate descent of the affections ties us
down to the earth and earthly possessions,
shackles us in sensual gratifications,
effectually prevents the soul`'s ascending towards God,
and destroys its deputed sovereignty over the creation, to which it is in bondage:
so true is that assertion of the apostle, that while some boasted of their liberty,
or promised it to others, themselves were the servants of corruption.
I have sometimes considered how the excuse of
these boasted libertines bespeaks their slavery.
We cannot help such and such conduct, say they,
or had not power to resist such temptations.
If this were true, it were acknowledging that they had lost that valuable blessing,
the freedom of the will; and are utterly destitute of power to withstand evil;
and of consequence are the devil`'s captives.

Such indeed they are, though not necessarily, but voluntarily; for wisdom and power,
through the grace of God, is given to man,
to discover and resist the temptations of his enemy; and if he will renounce both,
his blindness and subjection to the power of delusion is procured by himself,
as is its miserable consequence, namely,
an everlasting separation from the Fountain of all good.

You will easily perceive,
that the intent of the foregoing hints is to influence
your mind in favour of a more strict course of virtue,
than you have formerly pursued.
I will add my earnest wish that it may be answered.
What shall I say to persuade you to turn,
and coolly and impartially look into yourself? Shall I plead your advance in
years? You are now I conclude rather in the decline of life,
hastening towards the gate of the garden.^
footnote:[An allusion to a dream which the party had, wherein,
amongst other remarkable circumstances, he was met in a beautiful garden by two women,
representing (according to the interpretation which
opened in his mind when he awoke) Virtue and Vanity,
who each solicited his company for a walk; and though he strongly inclined to the latter,
the former insisted on his accompanying her, not only for a walk but for life;
which rather than comply with,
he endeavoured to escape out of the garden (which he called the world);
but coming to the gate found it locked, and the key in her possession.
So being forced to a compliance, he accompanied her,
and became gradually charmed with her conversation,
by which he was won to a love of religion,
and in the end much delighted with the prospect of such a companion for life.]
Oh! listen to the dictates of virtue,
before she withdraw her kind invitations and profitable instructions.

Shall I beseech you by the mercies of God (a prevailing
argument with a truly generous and grateful mind,
and which may with great justice be particularly advanced to yourself),
to return to Him from whom you have deeply revolted,
and seek reconciliation by unfeigned repentance, if you can find room so to do;
which I have a lively hope you may, though you have so long, and distantly,
strayed from the fold of Christ.

I shall plead no excuse for the freedom with which I have here treated you,
further than to say, that I think a true freedom in communicating our sentiments,
with a design for each other`'s eternal well-being,
is a part of that charity which should clothe
the spirits of the followers of Jesus Christ.

The copiousness of my subject may apologize for my prolixity.
Upon a review of what I have written it will readily be observed,
that the hints given are but like heads of chapters, which, if fully expatiated upon,
might fill a volume instead of a letter; and,
that the everlasting Minister of the sanctuary may
enlarge them in the view of your understanding,
to lasting benefit, is the sincere and ardent desire of your affectionate sister,

[.signed-section-signature]
Catherine Payton.

[.asterism]
'''

We lodged in Charleston at John Sinclair`'s, who was educated amongst Friends,
but had married one not of our Society.
Both he and his wife received us kindly,
and treated ns while with them with great hospitality and generosity.

The meeting of Friends here was very small;
and most of those who attended it were rather stumbling-blocks, than way-marks,
to other professors of religion; yet we found a few to whom we were measurably united,
and who, I believe were thankful for our visit.
During our stay in this place, we were treated with great civility and kindness,
by the inhabitants who did not profess with us;
but we saw it necessary to be strictly guarded in our conversation with them;
lest their very respectful behaviour should betray us
into a familiarity injurious to ourselves.
Many of them are ready to hear the testimony of Truth,
but there is a certain lightness of disposition which
greatly obstructs its progress amongst them;
and if not carefully watched against,
will infect the minds of persons who converse with them.

Many of them attended our meetings, and mostly behaved soberly in them;
but what with ignorance of the spirituality of religion,
a high professing spirit in some,
and libertinism both in principle and practice in others,
it was very hard to labour amongst them: however,
the Almighty was pleased so to favour us, that we were not without hope,
that the testimony given us to bear affected some minds, and in the general,
commanded their assent.

We had two select meetings for Friends,
and paid a religious visit to most of their families;
in which service we were owned by the power of Truth,
though in some places we were very closely exercised; insomuch,
that one man absented himself from meeting,
not liking any longer to sit under our doctrine;
but we found we had rather cause to rejoice than to be uneasy,
in being instrumental of separating him from the Society, if so it should prove,
his conduct being a scandal to his profession,
though he pretended to join it by convincement.

We took a little turn to the south of Charleston, and had meetings at James`'s Island,
John`'s Island, and Stones.
The first was the most satisfactory.

At Stones, we had a close exercising time in the family of a young man,
whose father had formerly made profession of Truth; but he was quite gone from Friends,
and I fear was tinctured with libertine principles; but he entertained us freely,
and did not seem to take offence at what we had to deliver.
I heard he died soon after.
We had also a satisfactory opportunity with a family not professing with us,
in Charleston, but whose ancestors by the father`'s side were Friends.
It seemed as though the Almighty had sent us peculiarly
to seek the lost sheep of the house of Israel:
that his merciful visitation may be accepted by them, is the sincere desire of my soul.

I was engaged to return to James`'s Island, but,
my companion having no concern to accompany me, I went alone,
and had a much larger meeting than when there before:
and I hope it was well that I went back, as, through divine favour,
many gospel truths were opened to the people, in a degree of life and authority.

My friend John Witter of the Island, sent with me over the Sound a negro man,
who was to attend me to my lodgings.
He was well-dressed, and looked well-fed.
I entered a little into conversation with him respecting his situation as a slave.
He appeared easy in it, and said that he had a good master,
but that many negroes were treated no better than dogs.
Indeed we could not but lament over those poor people, as we passed through the colonies.
Several of our Friends were then in possession of some negroes,
either by inheritance or purchase;
and the negroes who had them for masters rejoiced in their lot.
But about this time a concern arose amongst Friends,
to abolish slave-keeping in our Society;
which concern has since prevailed in the American Colonies;
and many Friends have given up large possessions in negroes,
but employed many of them as hired servants after they had given them their liberty.

We left Charleston the 26th of the eleventh month, accompanied by James Verree,
a young man, a Friend, residing there;
and went towards a small settlement of Friends on the Wateree River,
which is on the north side of the Province.
They were lately come over from Ireland.

In our way we had meetings in the families of Isaac Perinoes,
and John Lloyd where we lodged, who were neither of them of our Society,
but they readily gave us an opportunity with them, and Truth favoured us.

Several difficulties attended us in this journey.
We had appointed a Friend to meet us with horses,
about a hundred and twenty miles from Charleston; and being set to a time,
we dared not stay to discharge our minds of that duty of love,
which seemed to point towards the people as we went along.
Secondly, we had poor accommodation, especially as to lodging;
some of the houses being so open to the air,
that I could attribute our preservation from great indisposition,
to nothing short of the immediate interposition of Providence;
but as the people behaved very civilly towards us,
and we enjoyed some liberty of spirit among them, it was rendered the more easy.
When we came to the place where we had appointed to be met,
we found neither the Friend nor the horses; and those which we brought from Charleston,
being borrowed, and the Friend who came with us being earnest to return,
we discharged him from any further care of us, sent the horses back with him,
and concluded to stay at the house of the before-mentioned John Lloyd;
who was a substantial planter, and very freely gave us an invitation thereto,
till our friends from the Wateree could meet us with horses;
to whom we had an opportunity of sending an account of the strait we were in,
by a neighbour of theirs, whom we met at the house of this planter,
and who was then going home.

However, kind Providence soon opened a way for our release.
A poor Friend who lived between this place and the Wateree,
and was going to Charleston with goods for the market, stopped at John Lloyd`'s;
and seeing the circumstances we were in, left his load in John Lloyd`'s warehouse,
and returned back with us to his own house; where we got a very poor lodging,
but received it thankfully, as the best he could provide us with;
and the next day he accompanied us to the Wateree, through a wilderness country,
wherein it was dangerous for women to travel, by reason of the swamps and deep creeks,
which are difficult and very frightful to pass;
but we were mercifully preserved from hurt.

We crossed one creek upon the trunk of a tree laid from bank to bank,
and the water was so deep, that if the trunk had broken, we had probably been drowned.
When we got on the other side we saw it was decayed;
and when our friends came over with our saddles upon their backs,
we observed it bend with their weight.
Our horses were driven through a part of the creek where the water was shallower,
yet perhaps there it was out of their depths.
Providentially, before we crossed this creek, we were met by our friend Robert Millhouse:
had it not been so, I know not how the poor Friend would have got us over.

Robert Millhouse had brought horses for us, and gladly took us to his house with him.
My companion`'s former acquaintance with him in Ireland,
rendered their meeting very agreeable.
We found his not meeting us according to appointment,
was occasioned by our letters not reaching him timely; which had we known,
our spirits might have been more at liberty to have attended
the before mentioned pointings of love towards the people;
but inasmuch as we had not wilfully omitted our duty, divine mercy was extended,
and our minds soon became easy on that account.
We came to the Wateree River the 1st of the twelfth month, and stayed there till the 12th;
in which time we attended Friends`' meetings as they came in course, both on the first,
and other days of the week,
and paid a religious visit to every family of Friends in the settlement;
in which service we were evidently owned by our Master; or at least my companion was so,
who had most of the service in this place.
The state of the Friends settled here was mostly low, as to religious experience;
but some of the youth were under a divine visitation, which afforded us some comfort.

Some people not professing with us attended our meetings, and behaved soberly;
but in general,
the people in this part of the country were lamentably ignorant and wicked: indeed,
they had very few opportunities of religious instruction, no place of worship being near;
perhaps not nearer than twenty miles.
Seldom, if ever, any clergyman came amongst them oftener than once a year,
to sprinkle their children.

Alas! what will these pretended and hireling shepherds
have to answer for? Of whom it may well be said,
"`They feed themselves but not the flock,`" Indeed, none can feed the flock,
who have not themselves been fed by the heavenly Shepherd.

Part of the time we spent here, was to me a season of deep inward trials;
the enemy being permitted so to beset me, that my soul was distressed both night and day;
and though sometimes a ray of hope of deliverance and
preservation would break in upon it,
and I was favoured with a taste of divine love; yet when that was withdrawn,
I was left as weak and unable to resist him as before;
so that my spirit was in inexpressible bitterness.
I had very little share in the ministerial service;
sometimes perhaps a few simple expressions.

But before we left the Wateree, the load was in part removed,
and my spirit brought into a greater calm, in which I desired to wait the Lord`'s time,
to be put forth to service.
He had clothed me, and he had a right to strip me at his pleasure;
and I could say with Job, "`The Lord gave, and takes away, blessed be his name.`"
The incomes of his love and peace in my heart,
were more to me than to be honoured before the people.

And here I cannot but again observe the various baptisms which
the ministers of Christ have to pass through,
in order to their being renewedly fitted to
minister to the different states of the people.
What deep poverty and distress, doubts, fears, and temptations.
I was sometimes however in mercy admitted to taste of the cup of heavenly consolation.
All is consistent with the wisdom of God,
and tends to bend the mind more effectually towards Him,
and to mortify the flesh with its corrupt affections;
so that the spiritual life is often strengthened by these afflicting dispensations.

We bought horses at the Wateree, and accompanied by Robert Millhouse and Samuel Kelly,
set forwards towards the River Pedee,
where we had heard there was a settlement of Friends.
We travelled through a wilderness country for several days,
carrying provisions for ourselves and horses.
In the day we took our repast in the woods, and at night got lodging at some planter`'s;
who, though not of our Society, readily gave us admittance into their houses,
and freely entertained us according to their manner of living:
and although it was very different from what we had been accustomed to,
and the lodging in some places very cold and poor,
we were content and thankful to the Almighty for it,
as well as for his providential care,
variously manifested in preserving us from the dangers which attended us,
in passing swamps, deep creeks, etc.
And although we lived low, our spirits were preserved pretty cheerful, and our health,
tolerable.

One particular instance of divine protection, I think worthy of commemoration.
The 14th in the evening we came to a swamp, which appeared very dangerous to cross;
but a friendly man on the other side directed us where to turn our horses over,
and came himself and assisted us over some trees which lay across it.
Having got over, we asked him how far it was to the place where we intended to lodge,
and whether the way was easy to find.
He told us it was twelve miles, and that the latter part of the way was intricate; and,
after walking by our side a little time, he offered to conduct us,
which offer we readily accepted.
If he had not accompanied us,
I know not but that we must have been all night in the woods;
for the way being so difficult to find, and night coming upon us,
we should probably have missed it; and the weather being frosty,
and we unprovided either with materials to strike fire, or blankets to cover us,
we should have suffered much, if we had escaped with our lives.

Our kind guide brought us to the house of James Gillespy, upon Pedee River;
who was a substantial planter, and a hospitable man,
I think by profession a Presbyterian.
His heart seemed opened towards us.
Of him we inquired after the settlement of Friends, which we had heard of,
but could get no intelligence of it;
yet were our minds mercifully preserved pretty easy and quiet,
although we knew not which way we should steer our course from this place, being,
all of us strangers in the country.
In a short time, I found freedom to propose to my companion,
our having a meeting in the neighbourhood; with which she concurring,
we asked our kind host, before we went to bed,
whether he thought we might have a religious opportunity with some of his neighbours.
He made but little reply then, but in the morning told Robert Millhouse,
that if we would stay till first-day,
we should be welcome both to what entertainment he could give us and our horses,
and also to have a meeting in his house;
and he would send his servant to acquaint his neighbours.
To this we assented, and spent the next day peaceably there.

On the first-day we had a meeting, which was not large,
and by reason of the ignorance of the people in divine truths,
was exercising to our minds.
A young man, who came from the settlement of Friends which we were in quest of,
being in the neighbourhood on business, and hearing of the meeting, stayed to attend it.
After it was over, he informed Robert Millhouse,
that several families of Friends were settled about twenty miles up the river,
to whom he was going the next day, and should be glad of our company.
To this we readily assented, and being thus providentially instructed in our way,
we next morning took leave of our kind friend James Gillespy,
who had generously entertained us while at his house.
We called at the house where we had appointed to meet our expected guide;
but it being a very wet morning, he concluded we should not move, and was gone; however,
we had got such intelligence from him of the way,
that with a little more which we obtained as we went along,
we found the Friend`'s house to which we intended to go.
He was a poor man lately convinced, but he gladly received us,
and freely gave us such entertainment as his circumstances would afford;
which though very mean, was made easy and pleasant to us,
being sweetened by the gentle flowings of divine peace in our hearts.

We found here a few newly convinced Friends, and some others under convincement;
with whom we had two meetings to good satisfaction,
many things suitable to their states being opened,
both by way of doctrine and encouragement;
and we were glad that we were thus directed to find them in this desolate spot;
which was very distant from any Friends; but they were under the divine regard.
They had not settled a meeting; but as our guides from the Wateree were returning home,
they found them busy in building a meeting-house;
and we afterwards heard that a meeting was settled amongst them.

The 20th, we left Pedee River, accompanied by John and Charles Moreman,
and the two Friends who came with us from the Wateree,
and set our faces towards a settlement of Friends on the Waters of Haw River.

The morning was wet when we set out and I was very poorly;
but in a little time the weather cleared up, and I grew better.
We rode that day about forty miles through the woods, without seeing any house;
and at night took up our lodging in the woods, by the side of a branch or swamp,
which afforded plenty of canes for our horses.
Our Friends made us a little shed of the branches of pine-trees,
on a rising sandy ground, which abounded with lofty pines.
We made a large fire, and it being a calm, fair, moon-light night,
we spent it cheerfully, though we slept but little.
Our saddles were our pillows; and we had in company a man,
who came from Pedee and was going a part of our next day`'s journey,
whose wife had sent a blanket; which, with one our Friends had brought,
being thrown at our backs upon our shed sheltered us much;
so that we still saw kind Providence cared for us.
In the morning we pursued our journey, and went that day about forty-five miles;
and at night took up our lodging again in the woods,
but did not meet with so advantageous a spot as the night before, for the ground was wet,
and the shelter bad, and poor wood for firing.

The weather also being very cold, and my companion ill with a pain in her face,
and myself but poorly, we spent the night very uncomfortably as to the body,
but through divine favour were preserved quiet and resigned in spirit.

We set out next morning in hopes of reaching a
settlement of Friends at New Garden that day;
but the pain in my companion`'s face continuing,
we thought it best to stop at William Rinald`'s at Polecat,
who was under the profession of Truth; and the next day, being the first of the week,
we had a meeting there with a few Friends, and some of the neighbours;
which was exercising, yet ended in a sense of divine sweetness.

The 24th, we went to New Garden,
and stayed amongst Friends in that settlement till the
28th. This was a new settlement of Friends,
and we were the first from Europe that had visited them,
or travelled in these parts in the service of Truth.

We had pretty close service among them,
and laboured for the establishment of a meeting for
ministers and elders in their monthly meetings;
which we found was much lacking:
and we had reason to hope that the proposition would be adopted;
many Friends being convinced of its usefulness,
and seemed glad that it became our concern to recommend it.
We found a sincere- hearted remnant in this meeting, unto whom the Lord united us;
but there was also a dead, formal, professing spirit,
under which the living were sorely oppressed; as well as under a flashy wordy ministry.

The 29th, we got to Cane Creek, another new settlement of Friends;
with whom we had a meeting the 30th, wherein we were rather low in our spirits.

The 31st, we went about 30 miles to a very small meeting on the river Eno,
which was very exercising; for though their number was small, their states were various,
and some of them widely distant from that pure, humble, living,
sensible disposition which Truth produces.

And as it was the will of the Almighty,
measurably to baptise us into the states of the people,
we could not but suffer in spirit with his pure seed;
and it seemed as though a drawn sword was delivered to
us in this the beginning of our journey,
which we were to use against spiritual wickedness; and not to spare,
though it were exalted in high places.
Here we laboured for the establishment of a weekday meeting.

The 2nd of the first month, 1754, my companion returned to Cane Creek,
in order to be at their week-day meeting; and I went about six miles up the river,
being engaged to have a meeting amongst a people not professing with us.
Many came to it, and behaved soberly,
but most of them seemed very ignorant of spiritual things;
and some were heavy laden with many sins; but kind Providence so favoured me,
that I left them pretty easy, and returned to my companion at Cane Creek,
the 4th. The same day we had a meeting at Rocky River, which was satisfactory,
and we returned to Cane Creek, and were at the first-day meeting there.

The 7th, we set out for Carver`'s Creek, a journey of about 160 miles,
through an almost uninhabited country.
We were accompanied by John Wright and J. Pigot, Friends.
The accommodation we met with was very mean, but rendered easy,
under a sense of our being in the way of our duty.
At one place where we lodged,
the room wherein we lay was exposed to the weather on almost every side,
and it being a wet night, the rain beat in upon us in bed;
but my mind was preserved in sweet peace, and under some sense of divine favour.

The woman of the house was of a tender spirit,
and appeared to be seeking after substantial good.
I had considerable freedom to speak to her on religious subjects; which she took well,
and I was thankful that our lots were cast under that roof.

Another night we lay in the woods, with tolerable comfort, though the weather was cold,
and the ground damp.
About two hours before we stopped,
as I was attempting to cross a swamp on some loose pieces of wood, one of them rolled,
and threw me backward into it.
One of our friends was leading me, and the other, seeing me in danger of falling,
stepped behind me into the swamp, and caught me, so that I was wet but on one side,
except my feet: and,
although I mounted my horse immediately after putting on a dry pair of stockings,
rode in my wet clothes, and lay down in them, I was preserved from taking cold.
In the night two of our horses^
footnote:[When travellers who lodge in the woods turn their horses to graze,
they fasten a bell about each of their necks, and if they miss the sound of any of them,
they go to see whether they are not strayed far from the shed.]
strayed away from us, and our guides were obliged to leave us and go in quest of them;
so that we were several hours by ourselves in this wilderness, surrounded,
for aught we knew, by bears, wolves, and panthers.

Before we pitched our tent,
I had been intimidated by an account which had been
given me respecting the panthers infesting that quarter;
one of which it was said had killed a person not very far distant from this spot;
but when we were thus left, all fear was removed,
and we spent the time of our friends`' absence cheerfully.
I went without the shelter of our shed,
and renewed our fire with some wood our friends had gathered.
The fire, under Providence, was probably our preservation from those ferocious animals.

It was a fine moon-light night,
our friends tracked our horses`' footsteps in the sand
for about three miles in the way we had come,
and found them feeding on some luxuriant canes.
The sagacious animals probably observed them as
they came to the spot where we pitched our tent,
and having but poor feeding there, went back to fill their bellies.
As we proceeded on our journey,
some of our company discovered the track of a wild beast in the sand,
which gave room to suspect that they had been near our tents in the night;
but we were preserved both from their fury,
and from being affrighted by their hideous howl.
However, as we rode through the woods in the morning,
we heard the barking of wolves at a small distance from us,
but a rising ground prevented us from seeing them.

We breakfasted at a miserable inn, about eight or ten miles on our way;
where we met a wicked company, who had spent the night there,
and we concluded it providential that we did not press forward to lodge there;
respecting which we were considering before we pitched our tent.
It appeared much more comfortable to be under the open canopy of heaven,
and the protection of Providence, though among the wild beasts,
than among those of the human race,
whose natures were so depraved as to render them more terrible and dangerous:
the first only, or at least generally, assaulting mankind of necessity,
or by provocation; but the last from the incitements of their depraved passions.

We went forward to Dunn`'s Creek, and had a small meeting,
with a few under the profession of Truth;
and from there to Carver`'s Creek the same night, being the 12th. The 13th,
we had a meeting there, and the 14th, went to Wilmington, on Cape Fear River,
where we had two meetings the 15th.

There are none in this place who can properly be called members of our Society,
but many people came to the meetings, and behaved civilly;
and the testimony of Truth ran pretty freely towards them in doctrine, reproof,
and counsel; though I believe many of them were of very loose conversation.
The 16th, we returned to Carver`'s Creek, so to Brompton, Dunn`'s Creek, and Cape Fear.

The 20th, we proceeded towards Perquimans River,
being accompanied by our friends William Hall and B. Cooper.
We calculated our journey to Perquimans at 273 miles;
going across the country to visit several small meetings of Friends; amongst whom,
and the people of other societies, we had some satisfactory service.
No women ministers had visited part of this country before us,
so that the people were probably excited by curiosity
to attend some of the meetings we appointed.

We found a few seeking people in these back settlements, who had very little,
even of what they esteem, instrumental help, in this wilderness country;
which appears too poor for priestcraft to thrive in;
but I hoped the Lord would gather some of them to faith in his own immediate instruction.
In this journey we met with considerable hardships,
the people amongst whom we were being very poor, their houses cold, and provisions mean.
One night we lodged in a void house on the river Neuse.
A man who kept a store on the other side of the river, gave us the liberty of it,
sent his negroes to make us a fire, and lent us a bed and coverings for it.
We were content,
although our provisions were so nearly spent that we
had very little to refresh ourselves with,
after a hard day`'s journey; and we could get neither bread for ourselves,
nor corn for our horses, for our money; as the man who lent us the house and bed,
would let us have none, though we sent to request it.

Our friends William Hall and B. Cooper accompanied us more than 100 miles in this journey.
On the 6th of the second month, we reached Perquimans River, on which,
and the River Pasquotank,
the main body of Friends in the province of North Carolina was settled.

Our first meeting among them was at the Piney Woods meeting-house,
which was pretty large considering the shortness
of the time I allowed to give notice of it;
and the Lord was pleased to favour us with a good opportunity:
the spirits of sensible Friends present were in a good degree settled,
and I hope refreshed.

We visited two other meetings in this quarter,
in one of which neither of us had much public service.
There is a number of valuable Friends in this country,
who were under suffering from the prevalence of a spirit of carnal ease,
and also from the ministry of some who will not be restrained by wholesome counsel,
wherewith a number are amused rather than profitably fed;
and instead of being solidly settled in a silent exercise of spirit,
they are in a continual expectation of words,
and remain in sorrowful ignorance of the operation of Truth in themselves.

Here it seems necessary to go back a little,
and give some account of an exercise which attended my mind, when about Carver`'s Creek.

It was to part from my companion, and go the lower way through Bath Town,
to the county of Perquimans; but the difficulty of getting guides suitable for us both,
and an unwillingness to part from my companion,
considering the desolate journey she would have to go,
and not being quite well in her health, determined me to accompany her; nevertheless,
I stood open to be turned back when I had a suitable evidence of its being required.
Here, an exercise respecting those places being again revived,
and being fearful of omitting my duty,
I mentioned the going back to them to my companion, who,
although she was not free to accompany me, was easy with my going,
and rather disposed to encourage me.
Her health seemed to require a little rest,
which she purposed to take at the house of our friend Thomas Nicholson of Little River,
who had not long since paid a religious visit to Friends in England.

I then proposed it to Friends to set forward the 11th, and if Providence permitted,
to return to their quarterly meeting in Pasquotank county; to which they only objected,
that they feared the notice was so short,
that they could not procure suitable companions for me.
However, they resolved to mention it after the meeting on the 10th,
and see if any Friend would offer to go with me, to which I agreed;
but told one of the most sensible amongst them,
that if the way did not pretty readily open, I dared not push much for it; which,
considering the event, I was glad I had said.

After meeting, I was informed that two young men, and Rebecca Tombs, a valuable Friend,
and an acceptable minister, were willing to accompany me.
I did not find any objection in my mind to accepting her company,
though I had not requested it; but an uncommon sense of sorrow seized my spirits;
though I did not see that I ought to omit the journey,
nor yet comprehend the cause of the exercise.

Next morning I took leave of my companion Mary Peisley,
in pretty much the same state of mind; and after crossing Perquimans River,
we rode that day to Edenton.
On the road my mind became quiet, yet was low.
The names of the young men who accompanied us were Nathaniel Newby and John White.

The 12th we had a meeting at Edenton,
which on account of the excessive coldness of the weather was not large,
and it was much disturbed by a wicked drunken man, while I was speaking; with whom,
being a litigious lawyer, the town`'s people were afraid to meddle,
lest he should have an action against them; so I was obliged to bear it,
and the meeting concluded with less solemnity than I could have wished.
I observed a serious looking woman in the meeting,
and thought if she asked me to her house I should go; which she did,
and in the evening I went, accompanied by my companion.
We found both herself and her husband under a religious exercise;
and several things were opened in me to speak to them, which were well received,
and I left them in a good degree of peace;
believing that the seasoning virtue of Truth had been felt in our conversation.
There was no meeting of Friends in this town, and we lodged at an inn.

The 13th, in the morning we crossed a ferry eight miles over.
The weather was extremely cold, which affected Rebecca Tombs much.

The frost was so hard,
that the water in the Sound we had crossed was
frozen some distance from the shore on each side,
but we got through it safely.
We rode about twenty-five miles, lodged at a mean inn,
and next morning early we set out for Bath Town.
When we had rode about seven miles, I had a fall from my horse,
occasioned by the horse`'s starting at a bird flying out of a tree.
I fell over the saddle, on my right arm, and the ground being very hard from the frost,
it was much hurt; but I esteemed it a great favour that the bone was not broken.
"`When we came to the next inn, my companion procured some wormwood with vinegar,
and bound it round my arm; and we proceeded to Bath Town,
though my arm gave me much pain.

I had some thoughts of crossing the ferry here, which is four miles over,
and so proceeding to Newbern; but having received this hurt, and the wind being contrary,
I became inclined to have a meeting here the next day.
Just as we alighted at the inn, a respectable looking man,
who I afterwards found was an attorney, and lived about two miles out of town, came in;
to whom I found freedom to impart our desire of having a meeting,
and to consult him about a proper place to hold it in.
He appeared well pleased with the proposition,
and we concluded to hold it in the morning in the court-house,
if the weather were warm enough to admit of the people`'s sitting there; if not,
our landlord gave us the liberty of a room in his house.
I had much pain from my arm this afternoon; but fomenting it as before,
it became easier towards evening.
Our meeting was attended next day by a pretty many people,
most of whom behaved with sobriety;
but the life of religion was scarcely so much as known by many of them;
yet the Lord was pleased to open many gospel truths to them;
which were delivered under a feeling sense of their low ignorant state,
and I trust had their service.

After this meeting, as I was returning to my inn,
my mind seemed drawn to return back to my companion Mary Peisley;
and when I came to the inn, I found Rebecca Tombs, who had got there before me,
seized with an ague; which brought a heavy weight of exercise upon my spirit,
and I soon became apprehensive of her being removed by death.
The same evening also one of the young men who came with us,
was taken ill in the same way, and I was myself very poorly with a cold,
which affected my head and throat.
Next day Rebecca Tombs`'s indisposition increased,
and I became very thoughtful whether I had best endeavour to remove her homewards,
or continue her at Bath Town.
There appeared to me danger of my incurring censure from her relations,
in acting either way.
I therefore concluded it best to refer it to Providence,
and see what turn it would take in her own mind.
In the afternoon she discovered a desire to be removed,
and I found most ease of mind in acting accordingly.

I met in this town, to my surprise,
with a young woman who was daughter to a principal tradesman,
of the neighbourhood of Dudley.
She had been my school-fellow.
Her husband, whom she married in England, kept a store in this place.
They seeing our afflicted situation, readily furnished us with a chaise for our return;
so we prepared for going, and the attorney before-mentioned generously lent us a horse,
and a negro-man to bring it back.
He was at our inn in the evening.
I went to him, and acknowledged his civility and kindness to us; and before we parted,
we fell into a religious conversation, which I hoped might have its service.
Several persons were present, one of them the sheriff of the county,
who had some share in the discourse and offered his house to have a meeting in.
The attorney spoke with great moderation,
and made considerable concessions respecting the ceremonial part of religion,
and seemed pleased with the information I gave
him of the principles and discipline of Friends;
which I was remarkably opened to give some account of, and we parted friendly.

After he got home,
he sent me some wine to assist the friend in our
journey (which necessity made an acceptable present,
as we could buy none that was good in town), with a letter to request that,
if I stayed longer in the country than I expected, I would come to his house;
which I took kindly, and suitably acknowledged his civility.
I just add respecting Bath Town, that the man of the inn,
though he behaved civilly to us, appeared to be of a dark ferocious disposition.
One night a poor negro girl fell asleep at the top of the stairs, near our chamber door,
and he seeing her there kicked her down them.
The poor girl cried out, but I did not hear that she was wounded by the fall.
Indeed darkness seemed to surround us in this house.

The 17th, being the first-day of the week, we set forward in the chaise,
and got eighteen miles on our way and lodged at the
same house of entertainment as we did when we came down;
where we had very poor accommodation.

My friend was greatly fatigued, she grew much worse that night,
and next morning the young man that was unwell went to
acquaint her husband with her indisposition;
but the Almighty did not see fit to continue her in pain till her husband came to her.
Her pain was indeed extreme, and soon effected the end for which it was designed;
for the 20th, in the morning, she quietly expired.
From near the first of her being taken ill, she had a sense that it would end in death,
and was enabled to resign herself and her near connections into the hands of Providence.
She desired me to pen some memorandums of love and advice, to her husband, children,
and relations; and then said, she had nothing to do but to die.
She several times expressed her satisfaction in having a clear conscience,
and I was convinced of her spirit`'s centering in everlasting blessedness.
About twenty-four hours before she departed,
I was concerned to supplicate the Almighty on her behalf,
that he might be pleased to mitigate her pain,
and grant her spirit an easy passage out of its afflicted
tabernacle--for which she expressed thankfulness;
and in a short time her pain gradually abated, and her death was remarkably easy.
Her disorder appeared to be pleuretic.
We got her bled, and made use of such other means as our circumstances admitted;
but she was averse to having a doctor,
nor do I think that one would have been of any service to her.

Through this uncommon trial,
my spirit was singularly preserved in patience and stability,
though sometimes inexpressibly loaded.
My health being but poorly, the fatigue I sustained bore hard upon me;
but I was enabled to discharge my duty to my friend,
and in the end witnessed the return of peace.
My lodging was in the same room with her.
I lay down in my clothes upon a bench by the fire-side,
whereon the landlady laid something to render it the more easy.
The young man who continued with us behaved with remarkable composure, patience,
and affection to the Friend, who was his aunt,
and I had reason to hope that the journey would be of lasting service to him.

The day she departed we got a coffin made, and put the corpse into it.
While it was making,
my neighbour Turton (brother to the young woman who kindly
furnished us with the chaise at Bath Town) came in,
and was surprised to meet me here.
As we had sent back the chaise, and he was going to his sister`'s, he took charge of it.
In the evening, I got a religious opportunity with the family at the inn;
and the next morning set off with the corpse of my deceased Friend.
We had procured the wheels of a cart to carry it on, and a man to drive it.

We got well to the Sound, over which we were to cross to Edenton;
but before we got into the boat we met the husband of our deceased Friend,
who bore the shock full as well as I expected; and it must have been great,
to meet in so unexpected a manner the corpse of an endeared, affectionate wife.
The same evening we crossed the ferry, and proceeded to the house of a planter,
who had brought home the corpse of his^
footnote:[In this country the changes of the weather are so sudden,
and so extreme from hot to cold, that when a hard frost lasts for a pretty many days,
the people frequently drop off suddenly, with pleuretic disorders.
I thought their manner of living might in many instances contribute to their sudden death.
They eat pork, or other flesh, at almost every meal, not excepting breakfast,
and such as can get it (too generally) drink neat rum.
Frequently, they rather choose to drink water alone, and take their drams,
than mix them together.]
mother about two hour before we came into it.

The 22nd, we crossed Perquimans River, and got the corpse home;
but the affecting sorrowful scene of meeting the poor motherless children,
of which there were seven, and other near relations and friends of the deceased,
is difficult to describe; nor shall I attempt it,
as the ideas it must raise in a sensible mind, will sufficiently represent it.

That night I went to my companion Mary Peisley,
and through mercy found her well at Thomas Nicholson`'s;
and next day we went to the quarterly meeting of
Friends for the province of North Carolina,
held at Old Neck in Pasquotank county.
The meeting was large but exercising, weakness being sensibly felt.
I was favoured with a good opportunity amongst Friends,
wherewith I had reason to believe the sensible part of them had unity,
and were thankful for it.

The 25th, we attended the meeting for ministers and elders, and a large public meeting,
which though very exercising in the beginning, ended well;
for which favour we had renewed cause to bless the Almighty,
who baptizes his ministers into the states of the people,
and enables them to minister thereto.

The 25th, we attended the funeral of Rebecca Tombs;
and the meeting was large and crowned with solemnity.
After the meeting, a young man who kept the ferry at Perquimans River,
desired to speak with me.
When I came over the ferry with the corpse of Rebecca Tombs, he was with us in the boat,
and while we were upon the water, my mind was affected on his behalf, so much,
that when we landed I took him aside and spoke closely to him.
What I said had such an effect, that he told me,
he could do no less than acknowledge the truth of it; and withal,
that his mind was so awakened thereby, that he could take no rest since.
I said what then arose in my heart to encourage
him to endure the chastising hand of the Lord,
until his judgments had wrought their proper effect; and left him with thankfulness,
that I had been made instrumental to awaken a poor prodigal to a sense of his outgoings:
for such I afterwards heard he was, though the son of a Friend in good esteem.

Although I had been almost miraculously supported through the before recited trials,
and had been enabled to minister to many people
as I passed along in my journey to Bath Town,
and my return; yet considering all the circumstances attending it,
much cause for painful rumination was administered.
I might naturally query whether it were right for me to turn back,
as the ends I had in view, namely, the visiting a few Friends in a desolate situation,
as well as having meetings at Edenton and Bath Town, were in part frustrated;
and the afflicted case of the deceased friend`'s numerous family, who,
perhaps might have been spared a little longer with them, had she not gone with me,
bore so hard upon my mind, that like Jonah, I wished to die; but I quickly saw,
that in so doing I erred greatly;
for in that impatient state of mind I was not fit to enter into the saints`' rest.
After some time my mind settled in a good degree of quiet,
and it appeared that perhaps the design of infinite Wisdom, in engaging me to move,
as before mentioned, might, in a good degree, be answered.
And as to Rebecca Tombs, she appeared to be in so weak a state when she left borne,
that had she stayed there,
her surviving that pinching season of the weather might well be doubted.

The 26th we left the province of North Carolina, and came into Virginia,
and the Lord was pleased to cause his peace so to rest upon our spirits,
that we were renewedly convinced we were moving in his counsel.
We had travelled upwards of a thousand miles in North Carolina,
and been preserved through various jeopardies and trials,
to the praise of his adorable name.

The 27th we had our first meeting in Virginia,
wherein the testimony of Truth was borne in a close manner by both of us,
against a dull inactive spirit, and appeared to have some present effect.

The 28th we went to Nancemond River, and visited several meetings on it,
and adjacent to it;
wherein we were still exercised to speak closely to the members of them;
which I believe tended to the relief of the sensible part of Friends.
In one of these meetings, having been closely engaged in testimony,
I cautioned Friends to beware of judging me for the liberty which I took amongst them,
in laying open the state of the Society, although some of other societies were present;
remarking, that it was more likely to convince considerate people of the Truth,
than to hear them salved over in their sins.
I concluded with some short remarks and hints of
advice to such as were not under our name,
which I suppose had its effect on a pretty high professor of the church of England,
who accidentally came into the meeting;
for the next day he followed us seven miles to a meeting,
wherein I was told he was much broken into tears;
and the day following he came about twelve miles to another meeting;
I therefore hoped that the Truth had been at work in his heart.
I record this passage as an incitement to a faithful discharge of
duty in the line the All-wise Director of true ministers points out.
He can make effectual a few simple expressions to the gathering of those who are without;
or even sanctify to them the doctrine which may be lost
on the unfaithful professors of his Truth.

The 17th of the third month, we had a meeting at Surry Black Water, which was large;
Friends from the neighbouring meetings, and many persons of other societies,
collecting at it.

After the meeting,
a pretty high professor of the church of England (his name Peter Worrel),
but who for some years had been dissatisfied therewith,
and had been seeking the way of Truth, sought an opportunity of conversation with us.
He had followed us to several meetings, and being serious in his inquiries,
and free in expressing his sentiments, he told my companion,
who had had most of the service in the meetings he had attended,
that he could not discover much difference between the
ground of the doctrine he had heard from her,
and the fundamental principles of the church of England.

I saw his state, that he heard with his bodily ears,
and judged by his natural understanding, of which he had a good share, and had read much.
I therefore told him, that if he would attain the knowledge of the Truth,
he must not only understand the words which were spoken,
but the power whereby they were given forth; for that,
according to the Apostle`'s testimony, "`The kingdom of God stands not in words,
but in power,`" which, with something else I said, adapted to his case,
was carried home beyond my expectation.
He followed us to another meeting, and then sought an opportunity with me alone;
when he told me, that what I had dropped in conversation, and that day in my ministry,
had so affected him,
that he was now convinced that a divine power accompanied true gospel ministry,
and that he thought he should join with us in society;
but that he was under some discouragement on
account of the degeneracy of many of our members.

I said what then arose in my heart, by way of inciting him to faithfulness;
and he parted from us in much love;
indeed he was remarkably changed from the time we first saw him;
his very countenance bespoke him to have been with Jesus.
He was silent, solid, and weighty in spirit,
though before talkative and full of head-knowledge in religion.
I afterwards heard well of him, and I think he settled amongst Friends.

I could not but remark on this occasion, how secretly, and almost unknown to ourselves,
the Almighty sometimes makes use of us in effecting his gracious purposes:
for in the meetings this man had attended, previously to our conversation with him,
I was much shut up as to ministry;
and my companion was favoured in the exercise of her gift; in one of them remarkably so;
and yet it appeared that I was made the principal
instrument of good to this poor seeking soul.

We then visited several meetings upon Appomatox River; and the Lord was with us,
blessed be his name; from there to the South-west Mountains,
where we were led in a very low track, myself especially.
From there we proceeded through many meetings to James River,
and so to the quarterly meeting at Waynoak Swamp.
By the time I came to James River, I was sunk exceedingly low in mind;
but as I abode in the patience, the Lord, in his time,
was pleased to raise me again to his own honour.
From James River, we went through many meetings in Caroline County, up Shenandoah River,
and by Opeekan Creek to Fairfax, which was the last meeting we had in Virginia.

In this Colony we had much suffering of spirit, for,
although in many instances we were favoured with a good degree of strength and wisdom,
to speak to the states of the people;
yet we could not but sympathise with the seed of life,
which in many of their souls was oppressed by a dark carnal spirit;
wherein the discipline is too much conducted, or rather in some places so perverted,
that this designed wall of defence is rather a stumbling-block to sober inquirers.
There are a number of truly valuable Friends among them; but in some particulars, who,
had they kept to the simplicity of Truth, might have been serviceable in the ministry;
sound and flight are grievously mixed therein, which will never convince the judgment,
or settle the mind in the stability of Truth, although they may please the ear,
and affect the passions.
After leaving the province, we sent them an epistle,
which was principally penned by my companion.

I think a providential preservation which we
experienced in this province worthy recording,
but, not having retained it in the memorandums I have preserved,
I cannot ascertain the name of the river at which it happened.
After a long day`'s journey, wherein we had dined in the woods on a scanty meal,
we came in the evening to the ford of a broad, rapid river, which,
from the appearance of the waves, we might suppose had a stony bottom.
Neither of our guides were acquainted with the ford,
and we were afraid to attempt to cross it until it was tried by one of them:
so the youngest of them, about 19, went rather beyond the middle of the stream;
and not finding it very deep, called to us to follow, which we with the other guide did,
when each of them took charge of one of us.

My companion followed him who went first,
and they kept a pretty straight course across the river; but my horse,
and that of the other friend, bended down the stream,
which I concluded was occasioned by its force and rapidity.
When we got over, we learned that the bed of the river, which was of large pebbles,
was so uneven as to render it dangerous.

To ford it safely, the horses should have gone a little way down the stream,
and turned up again to the landing place; for by going straight across,
the edge of a pit in the bottom must be gone over, which was accounted thirty feet deep,
so that my companion was in considerable danger.
Surely much caution is necessary for travellers in crossing unknown waters.

The 25th of the fourth month we had a meeting at Manoccasy in Maryland,
wherein Truth measurably favoured; from which we proceeded to West River,
taking the meetings in our way.
We came to West River the 29th,
and could not get a release from there till the 8th of the fifth month.
The professors of Truth in this settlement are
principally of the offspring of faithful ancestors;
but several of them have taken their flight on the wings of vanity and earthly riches,
and slighted the truly valuable eternal inheritance; and I fear,
some even despise that precious faith which was once delivered to the saints.
We had six meetings with them, in four of which I was silent;
and my companion had not much liberty of spirit until the last meeting;
wherein the testimony of Truth was raised in its own dominion.

The yearly meeting for this part of Maryland was held during our stay; which, as usual,
was attended by people of other societies,
and I heard there was a great desire to hear me speak in this place;
but the Lord was pleased very much to disappoint their expectation.

The 8th we went to Gerard Hopkins`'s, upon South River:
in the way I had a dangerous fall from my horse, whereby my left arm was much hurt, but,
through divine favour, no bone was broken or dislocated.

The 9th, we proceeded on our journey,
although my arm was so weak and painful that I was obliged to carry it in a sling.
We passed through several meetings in Baltimore county, to Duck Creek and Bush River,
and in many places my companion had good service;
but great were my trials of spirit about this time,
under which the divine arm secretly sustained me.
Oh! what need there is to stand still in these stripping, dipping seasons,
and wait low to discern the way whereby we may
escape the temptations of the subtle enemy.
As I was favoured to abide here, a little light and strength were afforded;
whereby I was encouraged to trust in that arm of
Almighty sufficiency which had hitherto preserved me;
and was resigned to travel forward, although I might be led in a low despised track.

The 18th, we came to Susquehanna River, and the 19th, to East Nottingham in Pennsylvania,
to the house of my dear and worthy friend John Churchman,
who was not yet returned from a visit to Friends in England;
but his wife and son gladly received us.
The 22nd we reached Philadelphia,
and took up our lodging with our worthy ancient friend Rachel Pemberton.

Here my dear companion met with a trial very affecting to nature,
an account of the death of her father;
which however she was the better prepared to receive,
from a remarkable sense having for some time rested upon her mind that it was so;
and she was assisted to bear it with Christian resignation and fortitude,
being favoured with the cheering hope that he went well.

We stayed in Philadelphia till the 29th,
attending the meetings of Friends as they came in course, wherein I had some service,
and was favoured with peace in the discharge of my duty, though led in a low track,
very contrary to the expectations of the people, which were to be disappointed.
My companion was silent during our stay in this city.

The 29th we left Philadelphia, and set our faces towards the eastern colonies.
We appointed but one meeting between Philadelphia and New York;
where we had two large public meetings,
which were attended by many people of other societies, who behaved well;
and the testimony of Truth was borne to them by us both.
In the evening my companion had an inclination to have
a select opportunity with Friends in that city;
which, I believe, was memorable to some present, for she was much favoured amongst them.

On the 3rd of the sixth month, we crossed the river to Long Island; and the 5th,
had a small meeting with a few who professed the Truth at Setoket,
and so proceeded to the east end of the island,
intending to go from there to the yearly meeting in Rhode Island.
We were accompanied by two Friends from Philadelphia, John Aimil and Thomas Lightfoot,
and one from Setoket.
Here we were detained near two days by contrary winds,
and lodged at the house of a friendly man, a Presbyterian,
but more generous in his way of thinking than are many of that profession in this Island.
I had a concern to have a meeting with the neighbours,
and a young man kindly offered his house; which we accepted,
and a pretty many people came, and behaved well while I was speaking;
but very soon after I had done, most of them went away,
although the meeting was not yet concluded.
The Almighty was pleased to cause many gospel truths to be opened to them,
and although it seemed to take too little effect,
I had peace in the discharge of my duty.

On the 8th, we set sail in a sloop, but the wind not favouring,
we dropped anchor that night, and next day, being the first of the week,
went on shore at a place about two miles distant from which we embarked.
Here we were received by another Presbyterian,
and that day were favoured with a comfortable religious opportunity together.
The wind continued contrary to the 12th,
in which interval we had a meeting with some of the neighbours;
which although exercising by reason of the hardness of their hearts,
was favoured by Divine condescension; many gospel truths being testified to therein,
which I hope had admittance in some minds.

The 12th, early in the morning we sailed, accompanied by the before-mentioned Friends,
and landed on Rhode Island in the afternoon.

The 13th, we attended a large meeting at Portsmouth.
The 14th, the yearly meeting began, which was held at Newport,
and continued till the 17th. It was attended by a large number of Friends and others;
and the Lord was pleased to manifest his ancient love and power amongst us,
whereby our spirits were set at liberty in the exercise of our gifts.
I had particularly, at several times,
to oppose that dark principle of unconditional election and reprobation,
and had cause to hope the testimony against it had weight with some of its professors.
We were exercised for the restoration of the discipline,
which had been much neglected in this quarter;
and our endeavours for its establishment were measureably crowned with success; so that,
upon the whole,
at this yearly meeting abundant cause was administered
for thankfulness to the bounteous Author of all good.
We visited the prison;
we also visited several Friends who were confined through indisposition;
in which charitable service we had peace and comfort.

The 19th, we went to Tiverton, and so, through several meetings in that quarter,
to the monthly meeting at Poniganset, wherein we were exceeding closely exercised;
the testimony principally directed to Friends, r After we left Newport,
my mind was much distressed, and drawn back to that place,
but my companion not encouraging me, and I being fearful, did not return,
which I had afterwards reason to believe I ought to have done; for after our leaving it,
a young man whom we had visited in his illness died.
He was of considerable account in the world,
and just upon the point of marriage with an agreeable young woman of the same meeting.
Had I moved in faith, I might have got to his funeral.

It is worthy remarking, that while I was under the exercise for returning back,
two Friends came to visit us, and my companion being engaged above stairs,
I was with them alone a short time.
We sat a few minutes in silence, when one of them said,
"`Go down to the camp and see,`" without any comment upon the expression.

I had doubtless been ruminating, why my mind should be drawn back;
and had I attended to this intimation, and set off immediately, I might,
with close riding, have reached the before-mentioned funeral,
and have returned in season to the monthly meeting at Poniganset; whereto,
as Friends of the particular meetings resorted,
all the service required of me might have been answered.

The 28th, we went on board a sloop, and sailed for the Island of Nantucket.
We intended, by Divine permission, to attend the yearly meeting there,
but the wind proving contrary, we did not get there till the 30th,
when the meeting was in part over.
We went on shore for a few hours on Elizabeth Island, where we saw no inhabitant;
but it being a fine sun-shine day, and the ground rising from the sea,
we laid ourselves down upon the turf, and got a little sheep;
for the sloop was so crowded, being small, that we could get very little on board.
At Nantucket we met our friends Daniel Stanton, Israel Pemberton, etc. from Philadelphia,
who had all been with us at the yearly meeting at Rhode Island.
We were mutually refreshed together, and the Lord favoured us in his service,
both in the work of the ministry and in discipline;
to the satisfaction and relief of the sensible body of Friends,
and I hope to the edification of some others.

The inhabitants of this Island were favoured with wonderful visitations from on high,
at the time when our valuable friend John Richardson and others visited America;
by whose labours as ministers,
a large meeting was gathered to the praise of the Lord`'s name;
which wrought powerfully to the turning the people from "`darkness to
light:`" and many worthy professors of Truth then belonged to it,
men and women zealous for the honour of it,
who walked in that true light wherein they had believed.

But most of these being removed to their eternal mansions,
and their offspring not generally walking by the same rule,
our Society was in a state of weakness, although the meeting was yet large,
and there remained a living remnant in it.
Some of the youth, especially of our own sex, appeared hopeful;
but having been left much to themselves,
and the work of the discipline having been neglected, they were unprepared for it,
and ignorant of its weight and necessity;
so that the meeting seemed in a dwindling condition, as to the life of Truth.

We laboured for an amendment in these respects; and in order thereto,
recommended their bringing the young people of orderly
conversations to their meetings for business,
which had been too much neglected; with which Friends concurred,
and also with the proposition ibr their holding
two meetings for worship on the first-day;
whereby the time, which was too frequently squandered away unprofitably,
by at least many of the younger sort, might be better employed.
Some of the members of the meeting living distant from it,
had probably prevented their holding two meetings heretofore on the first-day;
but that was no excuse for those who dwelt in the town.

We left the Island in peace, in the afternoon of the 1st of the seventh month,
in company with our aforesaid Friends from Philadelphia,
and landed at Woods Hole the same evening;
from which Daniel Stanton and Israel Pemberton returned homewards,
but the other Friend not being quite easy to leave us, concluded, with our permission,
to accompany us a little further.

He was one of those who came with us from Philadelphia as guide,
and had accompanied us to Rhode Island, and while with us,
had been remarkably under the baptizing power of Truth;
which raised a tender regard in our minds towards him,
and we were not easy to refuse his company, although he was in a single station.

Our friends also of Philadelphia, who left us here, concurred in his stay,
and that the more freely,
as some assistance might be needed in some places we were about to pass through.

Here I suggest some caution necessary to be observed by young women in a single state,
who travel in the service of the ministry, towards those of the other sex,
who are also unmarried.
First, to guard their own minds, lest they admit of any pleasing imagination,
and stamp it with the awful name of revelation;
and so slide into a familiarity and freedom of conversation and behaviour,
which might tend to engage the affections of young men.
Secondly,
to endeavour to retain a feeling sense of the state of
the spirits of those with whom they are intimate,
and strictly to observe their conduct and behaviour towards them:
so will they be the better able to judge of their motives for accompanying them,
or of any other act of kindness;
and may wisely check any forward thought which looks beyond friendship;
which may easily be done by prudent remarks in conversation.

Thirdly, to beware of hurting any of these tender plants by an austere conduct.
When we are singularly made instruments of good, in the hand of Providence, to any soul,
there is a natural aptitude to lean a little to the instrument,
and to prefer it above others, which for a time may be allowable.
The Lord,
leading the mind by gradual steps from the love
of other objects to the entire love of himself,
the one only pure, eternal Excellency,
may permit it for a season to lean to an instrument;
in which case a prudent reserve is necessary,
as well as a tender regard to the growth of the party thus visited.
I confess, it is sometimes a nice point, to be ready to be of service to such,
and preserve the unity of the Spirit, free from mixture of natural affection;
a distinction which I fear has been overlooked by some to their great hurt,
but which Truth, if adhered to, will make;
and will also direct to steer safely between these dangerous extremes.

From Woods Hole we went to Falmouth, and so to the quarterly meeting at Sandwich,
which began the 5th of the seventh month.
It was small and exercising, but we were favoured with Divine assistance,
through which the testimony of Truth was set over the heads of the gainsayers.

From hence we went to Yarmouth, where we had a good meeting with a few Friends,
and a pretty many of the neighbours, and returned back to Sandwich.

The 10th, we had a meeting at Pembroke,
which was attended by many people of other societies,
who were much displeased because we were silent.
In the evening we had a meeting with a few Friends;
the principal service whereof was to strengthen their hands in the discipline.

The 11th, we went to Boston,
and had a meeting there with Friends and some others the same evening,
which ended comfortably.

The 12th, our friend of Philadelphia left us lo return home,
and we pursued our journey towards the quarterly meeting,
to be held at Hampton the 13th and 14th,
and with hard travelling we reached it in due time.
But such a scene of confusion and distraction I never was in before;
occasioned by a company of Ranters,
who had gone out from Friends in a spirit of separation; but who, in reality,
were never properly of us, having been injudiciously taken into membership,
before Friends knew on what foundation they were; and being high-minded, heady,
and exceedingly wild in their imaginations, which they accounted revelations,
would not submit to the sense of Friends in the discipline, and were therefore disowned.

These frequently made it their practice to disturb the meetings of Friends,
with their wild disorderly appearances; and many of them came to this quarterly meeting,
against whom we had to testify,
being in the course of the meetings exceedingly
burdened with their spirits and public appearances,
under pretence of preaching; but we were obliged to suffer under their spirits,
until our concluding meeting, whereto many of them came.
After a time of silence therein, my companion stood up,
and one of their company began haranguing the people in the grave-yard,
and others were disturbing Friends in the meeting house;
wherein I think a form broke down, whereby the disturbance became so great,
that she sat down in discouragement, and the meeting continued in disorder.
In a short time I stood up with a view to inform the people present,
who did not profess with us, who were numerous,
of the reason of our conduct towards these Ranters.

I had said but little before I was sensible of the spring of Divine life being opened;
from which I was enabled to minister,
though I had no view of what was given me to speak before I stood up;
but I was immediately and mercifully clothed with such a degree of authority,
that it might indeed be said, the Truth was over all,
and the meeting ended in awful solemnity:
for which my soul was humbly thankful to the Lord,
who gave us victory over these deluded spirits.

The 16th, we went to Dover, and had two meetings with Friends in that quarter,
in both of which I was shut up.
We attended the funeral of a Friend whose relations were Presbyterians,
and had a seasonable opportunity among the people,
wherein the testimony of Truth was exalted.

The 20th, we had a meeting with Friends at Thomas Henson`'s;
and from there went to Berwick and Winter Harbour,
from which we crossed part of Casco Bay in a canoe,
to visit a few Friends on some islands therein.
Several Friends from Dover, etc. accompanied us in this journey;
wherein had human fears prevailed,
we might have apprehended ourselves in danger from the Indians,
who sometimes annoy the inhabitants, killing some,
and carrying others captives to Canada;
but our spirits were mercifully preserved above fear,
and comforted with the hope of Truth`'s prosperity among the few Friends in that quarter;
several of whom were under its humbling visitation,
and therefore were near to our spirits; from whom we parted in gospel love,
and returned to Dover the 30th.

The 1st of the eighth month, we went to New Town, had a meeting at Nathan Hoeg`'s,
wherein much instructive doctrine flowed to several states,
particularly to that of the before mentioned Ranters;
and we found that there were present two young women who sometimes went among them,
with whom, after meeting, we had some discourse.
They behaved civilly to us, and told us they had heard many lies of us;
and one of them was considerably tendered in spirit,
but the other was high in imagination.

From hence we proceeded to Araesbury and Newbury,
where a concern rested upon my dear companion to go back,
and pay a visit in the love of the gospel to these Ranters,
for whom she had for some time been exercised,
and particularly for their leader James Bean; a man of great cunning and a strong will,
who had heretofore been permitted to minister amongst Friends.
She laid this concern before Friends, wherewith they concurring,
we went on the 5th to Brentwood, the place where they held their meeting.
Many Friends accompanied us,
who I believe were earnestly desirous that we
might be rightly conducted among these dark,
crafty spirits; who readily gave us an opportunity with them at their own meetinghouse.

In the forepart of the meeting several of them spoke something,
but at length my companion got liberty,
and was favoured with the openings and power of Truth,
directly pointed to the confused deluded state wherein they were.
I was also exercised in the like manner, and we had good tidings for some of them,
namely, that there was a way open for them to return,
if they would allow their wills and works to be tried, judged, and condemned;
which I believe a few of them received well;
for there appeared to be some simple-hearted deluded souls among them; who,
being taken with the more than ordinary show of righteousness,
and high pretensions to enjoyments, visions, and revelations;
and not having their spiritual faculties sufficiently strong
to discern between the reality and the image of Truth;
had been inadvertently catched by them.
We had reason to hope that our labours and sufferings
among these ranting spirits had its service;
for after we left them,
we heard from that time they had been less troublesome to Friends in their meetings.

The 7th, we had meetings at Lynn and Salem.
The first was large, and greatly mixed with people of other societies,
wherein the Lord was pleased to favour me in the exercise of my gift:
the last was of Friends select, and the service principally fell upon my companion,
whose concern chiefly pointed to Friends.

The 8th, we went to Boston, and attended the monthly meeting there the same day,
to which came many people of other societies, but we were wholly silent.
We stayed over the first-day meetings,
which were attended by abundance of people not professing with us;
but neither of us had much to impart to them, which was matter of wonder,
both to them and to some who professed with us;
there being now a willingness in the people of this city, to hear the testimony of Truth.
We were engaged to pay a religious visit to most of the families of Friends there,
wherein we were favoured with the satisfactory evidence of being in the way of our duty;
and from which we hoped some good would ensue,
for it seemed to have considerable effect upon some, especially to the youth.

The 14th, we went to Mendon,
and after having visited a few little meetings to the northwest,
we passed through several, to Rhode Island.
We were painfully exercised in this quarter,
being engaged for the establishing of a right discipline;
and in the discouragement of a ministry in words,
which was not accompanied with the power of Truth;
wherewith some of the people were amused, but not profitably fed,
and the truly sensible were distressed.
In several places we were mostly or wholly silent, in large mixed meetings,
perhaps for examples to these forward spirits.
It raised the displeasure of some against us;
but we were mercifully preserved patient and resigned,
and I hope ready to do good for evil.

The 27th, we came to Newport on Rhode Island,
and were affectionately received by our friends
Thomas and Mary Richardson and their children,
with whom we lodged both now and when there before.

The 28th, we were at their week-day meeting,
which was pretty much mixed with people of other societies;
but our concern at this time being principally to Friends,
their coming rendered it difficult for us to discharge our duties.

We therefore requested a meeting of Friends select, which we obtained,
and I believe it ended to the general satisfaction of the sensible minds present;
the Lord`'s power being exalted therein,
under the tendering effects whereof some of the youth were bowed.

From Newport we went through several meetings on the Island of Poniganset to Greenwich,
wherein I had but little share in the ministry;
but my companion had good service in this quarter.
Here we parted from many Friends who had been made near to us in the Truth;
and on the 8th of the ninth month, set our faces towards New York government;
but my companion, not finding her spirit released from Greenwich,
we returned back the next morning, and had a meeting with Friends there the same day;
and the l0th, had one at Machanticut.
We had some painful labour in both these meetings,
the cause of which I forbear to mention,
but in the end had to point out one of the parties that had occasioned it.

The 11th, we proceeded on our journey through Connecticut Province,
to Oblong in New York government, about one hundred and fifty miles,
having no meetings by the way but at New Millford,
where there are a few under the profession of Truth.

From there we went to Salisbury and Nine Partners;
where my companion was confined by indisposition,
and I was obliged to attend the meetings in this quarter alone;
wherein I was favoured with a degree of divine help.

The 23rd, we returned to Oblong, and were at the meetings there on the first-day,
which were large, and I hope serviceable.

From hence we had thoughts of passing through the other
meetings of Friends on the main land in this quarter,
and so of proceeding to Long Island; but soon after we left Oblong,
a cloud came over our spirits; and being divested of a capacity for service,
we concluded to go directly to Long Island,
and there to rest until the cause or end of this dispensation should be manifested to us;
which proved to be a separation from each other.
I had long seen it would be so, and some of our friends before we left Europe expected,
and rather pressed it;
fearing that our service would be less to the church by our keeping together,
than if we separated.
We had now travelled together as companions in the most
difficult parts of the country--had shared so many trials,
sufferings and dangers, and had been favoured with great unity of spirit therein,
that it appeared hard for us to part; but when we were convinced of the propriety of it,
we submitted, in hope that it might tend to the benefit of that glorious cause,
for which we left our native land.
after patiently waiting some days, my companion`'s way opened to Philadelphia;
but I not being quite clear that the time for my leaving this quarter was fully come,
concluded to stay behind her; which she, as well as myself, being most easy with,
we imparted our exercise to Friends at their monthly meeting,
and had their approbation in our separation.

The 3rd of the tenth month,
we took an affectionate leave of each other at the house of our friend John Bowne,
of Flushing; and she, accompanied by some men Friends, proceeded towards Philadelphia.
My view was to turn back to the few meetings we had not visited on the main land,
and John Bowne`'s wife being willing to accompany me, we, with two men Friends,
left her house the same afternoon.
We had a pretty broad ferry to cross, and the tide not serving until evening,
it was near night when we got over.
We did not go in the same boat with the horses,
but one of the men Friends stayed with them,
and we could not expect them over for a considerable time.
The ferry house seemed a poor place to lodge at,
and it appeared proper we should that night get to the house of a Friend,
who was a member of the meeting I wished to attend next day,
that notice might be given of it;
and if we stayed for our horses the family might probably be gone to bed.
We therefore inquired for horses to proceed forward, but could procure only one,
upon which I determined to go with a man to ride before me,
who was to bring the horse back.
My friends who were with me knew the people of the ferry, so I set out without fear,
although I had no pillion.
We had but about two or three miles to ride, and it was a fine, clear, moonlight night,
and most of the way on an even sand.
I soon found the horse was a stumbler--indeed the poor beast had no shoes on,
a common case on Long Island, and other even,
sandy parts of the country--and when we had gone perhaps half way, down he came,
and threw us both;
but we were thrown far enough from the horse to receive no hurt from him.
The horse rolled upon his back, and when he arose I found the saddle had no girth to it,
and I knew before that it had no crupper,
so it was unlikely that its rider should have any command of him when he fell.
We had a kind of a wash-way to pass before we got to the Friend`'s house,
so I could not well walk it; therefore I mounted again at some high rails,
and we reached the house before the family was in bed;
and my friends came safe the same night.
I visited the meetings on the Main, which I had a view of,
and returned to Flushing the 5th.

I wished to visit the meetings on Long Island,
that I might be excused from returning back thereto;
but not having ease of mind in the prospect,
I concluded to follow my companion to Philadelphia; in which I believe I was right,
as it tended to convince Friends in general that our
separation was not occasioned by any difference between us,
or other improper cause or motive: so I proceeded accordingly,
accompanied by one man Friend.

On the 7th, we stopped to refresh ourselves at New York,
and my affectionate friend Margaret Bowne, at whose house we had lodged before,
concluded to take me in her chaise to Philadelphia:
a seasonable relief from riding on horseback.
We crossed the Sound that afternoon, and reached Philadelphia the 10th,
a journey of about one hundred miles from New York.
My companion had gone a little round,
in her way from Long Island to visit a general meeting,
and came to Philadelphia the same day; and after having conversed with each other,
we were mutually satisfied with meeting,
although we could not see that we should unite again in the
service through the provinces of Pennsylvania and the Jerseys.

At Philadelphia she received the following letter:

[.signed-section-context-open]
Dudley, 27th of Fifth month, 1754.

[.salutation]
My near and dear Child,

As I believe that a line from my hand will be very acceptable to you, I send this,
by which you may have the agreeable account, that through divine goodness I am as well,
both in body and mind, considering what I have gone through since I saw you,
as I could have expected, and beyond what I fear I have deserved.
And, dear child, I am ready to say in my heart at times, "`Lord, what am I,
that you are thus favouring me with your goodness? O!
that I and mine may ever dwell in nothingness of self,
that you alone may have the praise, who are forever worthy, says my soul!`"

And, my dear child, although I count the time, and desire your company at home,
and in our poor little meeting,
I dare not desire it before you find yourself clear of your service,
which I desire you may truly observe.
The reading of yours,
notwithstanding it brought an account of the hardship you have gone through,
although it affected me greatly, I was not cast down;
but on the contrary rather comforted,
that you have been so truly given up and supported in spirit,
to answer the requirings of the Almighty; who, if you continues faithful to the end,
will be your exceeding great reward.

Then you will receive that peace which the world can neither give nor take away,
and a crown of righteousness.

Dear child, I believe in the reading of this you will find me near to you,
as you are to me, in that love, distance of place cannot separate;
in which love I dearly salute you, and when my spirit is bowed before the Almighty,
I believe I shall have you in remembrance, and now remain Your near and dear mother,

[.signed-section-signature]
Ann Payton.

We stayed in Philadelphia more than a week,
and our friends were unanimous that it was best for us to separate.
My way opened to go to the yearly meeting to be held at Shrewsbury.

In the way thereto, I fell in with several weekday meetings,
and with one appointed by Joshua Dixon, a Friend on a religious visit from England.

I had also some service in the families of Friends, for which I had my reward.
The meeting at Shrewsbury began the 28th, and was attended by several valuable ministers;
and indeed I thought there was need of weight to counteract
the light frothy spirit which appeared in the people,
both in some of those who made profession of Truth, as well as many of other societies;
whose motive in attending that meeting being more to please the natural mind,
by getting into the company and conversation of each other, than for the honour of Truth,
they added no weight to it.
However, the Lord was pleased so to favour,
that the testimony of Truth was several times set over them in good authority.

I was particularly engaged for the welfare of my fellow members in society,
and desired an opportunity with the heads of families; which was procured,
and I had good satisfaction in it.

The 30th, I left Shrewsbury, and the 1st of the eleventh month returned to Philadelphia,
a journey of near ninety miles.
I met my companion here well, and also my dear friends John Churchman,
who was returned from his visit to Friends in England, and Samuel Fothergill,
who was entering upon one to Friends in America.
We were mutually refreshed in beholding the faces one of another,
our union in the Truth being strong,
which was now renewed in the fresh springing up of its life.
We all attended the quarterly meeting at Philadelphia, which was large,
and eminently crowned with the divine presence; wherein my companion and self rejoiced,
though we had but little share in the public service.

As we found it right to part for the gospel`'s sake,
on the 8th we took leave of each other in a degree of cheerfulness,
and in the unity of the Spirit; committing each other to the divine protection,
under a feeling sense of his humbling goodness.
My views pointed to West Jersey, so I crossed the river Delaware at Philadelphia,
being accompanied by Sarah Barney, a religious young woman of the island of Nantucket,
who had come to Philadelphia to spend some time among Friends there,
and found freedom to go with me for a while, as I did to accept of her company.
She was not in the ministry.

I passed through a train of meetings to the quarterly meeting at Salem,
and my concern principally bending to the members of our own Society in that quarter,
I was pleased that the meetings were not mixed with others;
and was sometimes favoured with a degree of enlargement in the heavenly gift,
though at others poor and low.

The quarterly meeting at Salem began the 16th and ended the 19th,
wherein I had close hard exercise in spirit,`' as well as in ministerial service,
in which I was not much enlarged.

The 20th, I had a meeting at Greenwich,
where there is a promising prospect among the youth,
on several of whom the solidity of Truth is deeply impressed.
My spirit was closely united to them, but could minister but little.
It appeared to me, that the Almighty would more perfect his work in them,
by the immediate operation of his own Spirit, than by the help of instruments.

The 21st, we rode between fifty and sixty miles to Cape May,
visited the few Friends there, and so proceeded to Great Egg Harbour,
visited the several meetings there, and the 28th went to Little Egg Harbour.
We went a considerable way between these two harbours
in a canoe just wide enough for one person to sit in:
there was ice in the bottom of it, which being broken,
some straw was laid for me to sit on.

Hence we proceeded through Upper Springfield to New York.
In our way we lodged at Amboy, at the house of a widow,
who was under the profession of Truth.
Here we met with a young woman, to whose person and character I was an entire stranger,
on whose account I became concerned, suspecting that all was not right with her:
and in the morning after breakfast, I spoke to her in a very close manner,
and gave her such advice as in the openings of Truth arose in my heart.
I thought I could partly have pointed out her crime,
had not delicacy and fear kept me back.

She wept much, and hastily retired in great confusion and agitation of mind;
and I afterwards heard that she had come here to be sheltered from public notice;
but the Lord followed her,
and I had reason to hope that the extendings of his grace were towards her,
although she had been so great an offender.
After some more close and very particular service with the woman of the house,
I left it in peace and thankfulness to the Almighty,
who had enabled me to discharge this hard piece of service; for so indeed it was,
to speak thus to individuals and strangers:
but in the day of his power his people are made willing to execute his commands.

I went to Rahway and Ryewoods meetings, and got to New York the 5th of the twelfth month;
and after a meeting there went on Long Island,
where I visited all the settled meetings of Friends, save one,
which I had been at before.
My concern at this time principally bended towards the members of our own Society;
and sometimes when meetings were much mixed with others, I had nothing to say to them;
which gave offence, not only to them, but to some carnal professors of Truth;
but I endeavoured to rest satisfied in the divine will,
well knowing Infinite Wisdom knew best what to administer for their good.

At Flushing the people not professing with us, had a great curiosity to hear me preach.
Many of them had been with me at two meetings when I was before on the island,
at both of which I was silent, and now came again, and were a third time disappointed,
I believe in wisdom; for they being still dissatisfied,
a number of young people came in the evening to my lodgings,
I suppose with an intent to know whether I had any private meeting in the family,
with whom I sat down in retirement; and others of the neighbourhood hearing of it,
by means of some of the family whom they had desired to give
them intelligence if there were such an opportunity,
came in, and I had a remarkable testimony amongst them, directed to their states;
the force of which some of them could not evade, as the opportunity was so select.
I found afterwards that several of them were Deists,
against whose principles I had to strike with much strength and clearness.
Friends present were comforted in the feeling of divine goodness;
for the power of Truth was exalted--blessed forever be the name of the Lord;
who in his own time, will honour such as honour,
him by manifesting that they are nothing, nor can do anything,
but through his divine assistance.

The 18th of the twelfth month we left Long Island,
in a thankful sense of the providential care of our heavenly Father,
in preserving and sustaining us through the many dangers and
difficulties attendant on this journey in the winter season;
when the roads in many places were bad, and we had many broad, wild ferries to cross,
which are sometimes rendered very dangerous through the frost and strong gales of wind;
but the weather was always favourable when we crossed them.

The 19th, I attended a monthly meeting at Woodbridge, which was small and exercising,
wherein I had little service,
except to strengthen the hands of Friends in the discipline,
the line whereof should have been further stretched over some transgressors.
We rested a day or two at Rahway,
at the house of our kind friends Joseph and Sarah Shotwell, and the 22nd,
went to Plainfield, and from there, through several small meetings,
to a number of meetings about Burlington, which were mostly large,
and some of them satisfactory, being attended by the power of Truth;
but the doctrine was mostly close, for which there was sorrowfully a cause.
The 13th of the first month, 1755, we crossed the river Delaware,
and were at a meeting at Bristol, in Bucks county, Pennsylvania; which was not large,
but attended with a degree of the divine presence.
The 15th, we were at the Falls meeting, in which I was silent,
and which was a comfortable season to me.
The 16th, I parted from my companion Sarah Barney,
who having received a hurt upon her arm by a fall from her horse,
was prevented from accompanying me further.

She was a tender affectionate companion, and very exemplary in her conduct;
which together with that sincere love to Truth which dwelt in her,
united her to my spirit.

Grace Fisher, a Friend in the ministry from Philadelphia,
accompanied me through the rest of the meetings in Bucks county, which were five.
In some seasons of silence the people appeared to be too generally in a dull,
sluggish state.
In some of these meetings the Almighty was pleased to open the spring of the ministry,
which I believe flowed in a manner not quite agreeable to some, who wanted smooth things,
although they were not their portion; and may I never minister so deceitfully,
as to cry peace, when his holy Spirit is grieved.
There is in this county a weighty, living number of Friends,
unto whom my spirit was closely united in the covenant of life,
but there are many dwellers at ease.
Some of the youth appear promising,
and the divine visitation was largely extended to many.
Oh! that they may embrace and dwell under it,
so as to become partakers of the glorious privileges of the gospel dispensation.

The 21st, I again crossed the river Delaware, accompanied by Grace Crosdale,
a Friend of Bucks county, who had a gift in the ministry, and went to Bethlehem,
and from there to visit a few families about twenty miles back in the woods;
with some of whom we had a meeting which was attended by several of their neighbours;
to whom I was drawn to minister freely in the love of the gospel,
and believe it had its effect amongst them.

The 23rd, we again crossed the river Delaware, which was pretty full of ice,
and our men Friends were a little doubtful that if they
went over with us they could not return the next day,
should the frost continue; as the ice might be united,
though not strong enough to bear them; and I being unwilling they should be detained,
concluded to go with two men--strangers to me,
but one of them known to Friends in general--who
were waiting for a passage over the river;
they accompanied us to a Friend`'s house about five miles on the other side,
where the next day we had a small meeting with a few Dutch people,
and then proceeded to the upper part of Philadelphia county and Berks county,
in which part the meetings are mostly small.
I had some painful labour of spirit in this quarter, and also a comfortable prospect;
for the Lord has amongst Friends here, a remnant of the ancient stock, who have,
in a good degree, kept their habitations in the Truth;
and a few of the youth are brought under its humbling baptism;
and I thought the extendings of his divine visitation were to the careless.

The 31st, we crossed the river Schuylkill in a canoe, and our horses were swum over.
We attended a meeting at Nantmill in Chester county, the 1st of the second month;
and passed through several meetings to the quarterly meeting for Chester county,
held at Concord.

About this time I was under a very heavy exercise of spirit,
being environed with darkness,
and made to stand as in the state of such as despise religion,
and call in question divine justice and mercy.
Under this painful baptism I continued many days,
whereby all the blessings of kind Providence were embittered,
and my life seemed a burden;
yet sometimes a glimpse of light would dart through the cloud,
and I conceived a hope of deliverance thereby,
and that this dispensation was allotted renewedly to
fit me to minister to some in this state,
as well as to sympathize with the afflicted and tempted.
It appeared to me remarkable, that although I was thus exercised when out of meetings,
both by day and by night, and perhaps for a considerable part of the time I was in them,
yet was I not entirely disabled for service; the cloud would break as in an instant,
and I had just light and strength afforded to see and discharge my duty;
and after a while it would close up again as before.
My soul has abundant cause to bless the name of
my God in this and such like painful seasons,
which I desire to retain in lasting remembrance;
for had it not been for the support of his powerful merciful hand,
I had been as one who goes down into the pit; being as it were entered, in thought,
into the dark avenues which lead to destruction;
yet faintly--as I thought--adhering to that faith which was once delivered to the saints.
These are the seasons of the "`trial of our faith,
which is more precious than that of gold which perishes.`"

The quarterly meeting at Concord began the 7th of the second month,
where I met my dear companion Mary Peisley.
Our meeting was attended with divine consolation,
under a sense of the protection of Providence having
been over us in our absence from each other;
and our union in the Truth was renewed and strengthened.
The quarterly meeting was large and divinely favoured,
and the testimony of Truth therein exalted in strength and clearness.

The minds of some members of our Society,
were at this time much unsettled through government affairs.
A war with the French seemed likely to break out;
and some were for deviating from our Christian testimony, which is against defensive,
as well as offensive war; consistently with that pure charity which "`bears all things,
and seeks not its own`" by means,
contrary to the tendency of the peaceable gospel dispensation.
Against this spirit we had to testify, I hope to good purpose,
for the power of Truth was over the meetings in an eminent degree,
whereby the doctrine preached was enforced: glory be to the Lord forever!
He brings down and raises up, for the honour of his own name,
and the establishment of his servants in righteousness and truth.
The Scripture given me to comment upon in this meeting was Joel ii, 15,
and some following, whereon I was opened to my own humbling admiration,
and that of some of my friends.
Here we met our friends John Churchman, Joshua Dixon, and many more,
with whom our spirits were comforted in the divine presence.

The 12th, we came to Philadelphia, where we spent a few days,
and were principally engaged in visiting some Friends`' families,
and the girls`' school for Friends`' children.
We also visited the prison, wherein several were confined; one for debt,
and three boys for theft, who, with a fourth, their accomplice,
were much broken in spirit.
This was to me one of the most affecting services I had ever been engaged in,
from the consideration of their deplorable circumstances;
for although their lives might be spared,
a lasting stain might remain upon their reputation;
but we were comforted in the hope of their being brought to repentance,
as divine mercy was extended unto them.

Oh! how careful ought young people to be of the company they keep;
for if they are fainiliar with the children of darkness, they too often,
by almost imperceptible degrees, contract their vicious inclinations,
and are led into acts of wickedness, from which they would once, perhaps,
have shrunk back with horror.

The 18th, we went in company to Frankford, where we had a good meeting,
and parted in the comfortable sense of the divine presence;
my companion going to some meetings in Bucks county, and myself to Abington, Horsham,
and Plymouth, accompanied by Sarah Morris of Philadelphia, and Anna Logan.

The 22nd, I again met my companion at Burlington,
where we attended the quarterly meeting for the upper part of West Jersey;
which was a solemn season,
and the spring of the ministry was opened to edification and comfort.

The 26th and 27th, we attended the quarterly meeting in Bucks county, Pennsylvania;
which was large and satisfactory, divine help being extended to the encouragement of us,
and of the faithful present.
Here my companion and I again separated in a sense of our heavenly Father`'s love;
and myself with Sarah Morris proceeded to visit
some meetings in Bucks and Philadelphia counties,
and came to Philadelphia the 8th of the third month.
I stayed in and about the city till the 24th, visiting some of the families of Friends,
as my strength which was but low, would permit;
but I had solid peace in spending a few days in this service.

On the 24th, I went to Newtown in West Jersey,
so to Evesham and Haddonfield to the quarterly meeting for that province;
wherein I was low both in body and mind, and had not much public service.

The 28th, the half-year`'s meeting at Philadelphia began.
Here I again met my dear companion Mary Peisley.
The meeting was large and solemn; there was much silence in it,
which was perhaps not less profitable to many, though less pleasing, than preaching.

The 3rd of the fourth month we again separated,
and I went towards the eastern shore of Maryland,
having for a companion Hannah Foster of West Jersey, also Joshua Fisher of Philadelphia,
who went to assist us,
it being a quarter wherein it might have been difficult always to procure guides.
We were obliged to travel hard,
and I having also hard service amongst a few unfaithful professors of Truth,
who were scattered about in this quarter, and my health being poor,
it was painful for me to pursue the journey;
but divine goodness secretly sustained my soul,
and assisted to discharge my duty according to knowledge;
and in the end afforded a comfortable hope that my labour was not entirely fruitless.
We attended a half-year`'s meeting at Chester in Maryland, and another at Duck creek;
at the last we met John Churchman.
We had laborious travail of spirit, the life of Truth being low in that quarter,
but through infinite goodness,
the testimony of it was raised in a good degree of authority.

We had comfortable hope respecting some young people hereaway,
and parted from the living amongst them under a sense of divine favour.
We proceeded through several small meetings of
Friends--wherein I had painful labour of spirit,
yet I hope some solid service--to Lewistown.
There is no meeting of Friends established here,
but we had a large one in the court-house,
wherein the power and testimony of Truth was raised in
dominion to the praise of the great Name.

The 29th, we returned to Duck creek, myself in a very low state, both of body and mind;
but as I endeavoured to keep my mind to the Lord,
he was pleased as in an instant to dispel the thick cloud of
darkness which for some days had encompassed me;
and so to lift up the light of his countenance upon me,
that I rejoiced exceedingly in the hope of his salvation.

The 4th of the fifth month my companion Hannah Foster left me at East Nottingham,
and my valuable friend Margaret Churchman, wife of John Churchman,
accompanied me to some meetings in Lancaster and York counties;
and so to the yearly meeting held at West river, for the western shore of Maryland,
at which I had been with my companion Mary Peisley, in 1754,
but had then but little public service amongst the people.
I met with some opposition in my endeavours for the revival of discipline,
from apostate and libertine spirits; but the Lord supported me above it.

The yearly meeting was large, and divinely favoured.
Several Friends came over the bay to it,
and I was favoured to see a little fruit of my painful labour when on the other side,
by the change which was apparently wrought in a young person,
who was then of a light conversation.

William Brown, from Philadelphia, attended this meeting, and had good service therein.
Love seemed to spread amongst Friends at this time, and we left them in peace,
and returned the 26th to East Nottingham; where I met Sarah Morris, from Philadelphia,
who proposed to accompany me through Chester and Lancaster counties, etc.
She was a truly exemplary woman, and sometimes highly favoured in the ministry.

We left Nottingham the 29th,
and passed through the rest of the meetings in Lancaster county,
wherein I had much close service.
We visited Chester county pretty thoroughly,
wherein is a very large body of professors of Truth,
but many of them are deficient in regard to its sanctifying operation upon the spirit.
Many noble pillars have been removed from amongst them,
and some of the elders who then remained had unhappily lost their stations in the Truth,
and yet nominally retained their offices in the church.
These were stumbling blocks to the youth,
who were too apt to look at the example of such,
and to plead their inconsistent practices,
as an excuse for their own taking liberties in other respects.
Against these, and such like deceitful watchers and pretended labourers,
who had not kept the vineyard of their own hearts,
and yet dared to stretch forth their hands to the Lord`'s service,
I had sharply to testify:
and I sometimes was made an example of silence in the solemn assemblies.
There was also in this county a solid living number of Friends,
who were preachers of righteousness in their respective stations,
both by example and precept; with whose unity the Lord was pleased to favour me,
and who I trust will ever be near to my life,
in that holy bond which neither time nor death can dissolve.

After visiting Chester county, I became much indisposed,
and retired to the house of my kind friend John Morris, in Philadelphia county;
where--as at several times before had been the case,--I was affectionately received,
and the necessary endeavours were used for my recovery;
which the Lord was pleased so to bless,
that I was enabled in about two weeks to pursue my journey,
though in considerable weakness of body.
In this season of confinement and release from public labour,
the good Physician so favoured,
that although my body sustained considerable pain and weakness,
my mind rather gathered strength,
and was greatly encouraged in the hope of future preservation.

My dear companion Mary Peisley, came to me from Philadelphia,
who having visited almost all the meetings of Friends on the continent of America,
entertained hope of our soon embarking for our native lands;
but we had much more both to do and to suffer, before that hour came.
We met in wonted affection, and therein again parted the 2nd of the seventh month;
when I proceeded to visit some meetings in Philadelphia and Berks county,
where there seemed a promising prospect amongst the youth,
some of whom appeared to be advancing in rectitude of spirit and conduct,
at which my soul rejoiced; it being part of the fruits of that labour of love,
the Lord of the harvest had caused us to bestow upon them.
I had considerable freedom in the exercise of my
gift in this renewed visit to these places,
and again met my companion the 16th, at Stenton, near Philadelphia;
from which place we went in company to Philadelphia the 17th,
and from there to the quarterly meeting at Concord, in Chester county;
after which I proceeded to some other meetings in that county,
and returned to my companion at Philadelphia, the 19th of the eighth month.

Here she received the following letter:

[.signed-section-context-open]
Dudley, 9th of Second month, 1755.

[.salutation]
Dear Child,

Having this opportunity, I am willing to send you a few lines,
by which you may know that through divine favour I am as well in health as I can expect;
and at times witness a renewing of strength in the inward man; but, dear child,
it is through a daily watch.
I can find no safer way than a watchful state,
that many times prepares the heart for prayer, and helps to pray aright.
This is what I desire we may be found in,
and then I believe the Almighty will hear our prayers for each other;
as I am sensible he has done mine, and answered them in his own time,
for which my soul desires to dwell in true thankfulness to Him.

Dear child, I have little more to caution you of, than what I have done heretofore.
Be careful to discharge yourself faithfully in the requirings of the Lord,
and be sure take care of your health,
and then I am not without hope but we shall see each other again in his time.

My very dear love and your sister`'s to friend Pemberton and sons.
I am much obliged to them for their affectionate care towards you,
though have not wrote to acknowledge it.
As you know my deficiency in that respect,
would have you excuse it to them in the best manner you can.
Our dear love is to Samuel Fothergill, John Churchman, William Brown, Jonah Thompson,
and all inquiring friends that know us.

Now, dear child, with the salutation of endeared love to you,
I remain your tender and affectionate mother,

[.signed-section-signature]
Ann Payton.

From this time we were mostly together while in the country,
which was much longer than was agreeable to our natural inclinations,
for we were detained the winter;
being engaged in visiting the families of Friends in Philadelphia,
in conjunction with the Friends who were under appointment for that service;
in which important work we were frequently favoured by the wise Head of the church,
who directs,
that even "`Jerusalem shall be searched with candles;`" and
for that purpose illuminates the spirits of his servants,
and furnishes with doctrine suited to the states of those visited.

We took several turns in the country, to visit quarterly, monthly,
and particular meetings, and had good service for the Lord therein;
but in the meetings in Philadelphia were frequently bound in spirit,
being made to preach silence by example; which I believe had its use,
by instructing the people not to depend on instrumental ministry.

Towards the latter end of the winter, my dear companion became very much indisposed,
and continued so for several months;
in which time she was frequently prevented from attending meetings,
and sometimes confined to her room.
I gave her the strictest attendance I was capable of,
insomuch that with other exercises attending, my health was greatly affected,
and my spirits sunk to a degree of dejection I had never before known;
nevertheless I was so favoured as to be alive, and to be at times strong,
in my ministerial service, to the very conclusion of our stay in the country.

The following letter appears to have been written about this time.

[.signed-section-context-open]
Philadelphia, First month 10th, 1756.

[.salutation]
Dear Cousin,

From a principle of affection,
and an apprehension that you mayst desire to hear from me,
I am prompted to send you a line, though otherwise much unfurnished for writing,
being rather low and empty; but, through mercy, pretty quiet,
and not without hope of Divine preservation,
which is a blessing to be acknowledged with humble thankfulness,
and if favoured with the same through life, we ought to endeavour to be content,
although no great degree of Divine enjoyment be afforded us;
and honestly labour in the ability afforded in
the way which is cast up by a kind Providence,
trusting him for our reward, who is faithful,
and will bear up the heads of his depending children in their deepest exercises,
and in the end bless them with the fruition of glory.

And what if our trials through life are great, our temptations abundant,
and our labour and travel difficult and painful to nature? Will it not
furnish us with a more joyful song of praise to him that has supported,
and assisted to do the work which he required of us,
till he brought us to his everlasting kingdom? For my part, I see suffering, poverty,
etc. to be so consistent with our present state, and so good for us,
that my soul prays to be united to them as my proper portion;
yet to have the eye of my mind directed to Him, whose hand is full of blessings,
which he dispenses according to the necessities of his people.
I am ready to say, let Him do what he pleases with me,
if I am but in the Lord`'s hand it is enough.
We cannot be unhappy, unless the perverseness of our own will,
and the corruption of our nature make us so;
these I have seen to be the ground of a great part of our afflictions through life;
and that to bring us into order, and reduce us into the obedience of Christ,
we need these bitter baptisms, which we sometimes pass through,
previous to the knowledge of our duty.
This, in my view,
demonstrates our imperfection the glorified spirits
walk continually in the light of the Lord;
and while inhabiting these tabernacles of clay, let us remember,
we are taught to aspire after this state of perfection,
to do the will of God on earth as it is done in heaven a lesson,
which if we had fully learned,
there would not be so much reasoning and disputing with flesh and blood,
when the knowledge of our duty was clearly made known to us,
nor so much unwillingness to believe in the light.

In writing thus I feel a freedom of spirit, so that I am ready to query,
is there not a cause? I have thought myself of late like one almost lost to my friends,
yet I hope not so in reality.

Our stay in this country has been prolonged, I suppose, beyond our friends`' expectation,
but I hope not beyond our Master`'s time.
My companion joins in the salutation of dear love to you.
I am your affectionate cousin,

[.signed-section-signature]
Catherine Payton

And now, as it was our lots in the wise direction of Providence,
to be in the province of Pennsylvania,
at a time when the minds of Friends were more than commonly exercised,
on account of public or political affairs--by reason of the French
making encroachments on some of the British colonies--and some of the
Indian tribes having committed great outrages on their frontiers,
and murdered many of the back inhabitants;
the conduct of us who were concerned to labour for the
support of our peaceable Christian testimony,
was harshly censured by the unthinking multitude;
and by such of our own Society as were one with them in spirit;
who insinuated that we intruded into matters foreign to our proper business,
and were in part the cause of the continuation
of the calamities which attended the provinces,
through our testifying against the spirit of war,
and advising Friends to support our Christian testimony faithfully,
I think it not improper briefly to give some account of
the share I had in concerns of this nature.

On my coming to Philadelphia in the third month, 1755,
I understood the assembly was about to sit;
and the major part of its members being then under the profession of Truth,
on considering how difficult it would be for such to maintain our Christian testimony,
and to act consistently with what the people at
large thought was for the good of the province,
I was induced to propose a few weighty Friends having a
religious opportunity with such members of the assembly,
as made profession with us; wherein, perhaps,
Truth might open counsel suitable to the occasion,
and our sympathy with such as were concerned to
maintain its testimony might be manifested.

This meeting with the concurrence ofFriends, such an opportunity was obtained,
and I had the privilege of being at it;
and therein was concerned to testify against that spirit,
which from human considerations was for war,
and to strengthen the minds of Friends against leaning thereto.
Several times during those troubles,
I was concerned publicly to assert the consistency of
our peaceable principle with the gospel dispensation;
and once, if not oftener, to point out the consequence of Friends deviating therefrom,
which was remarkably fulfilled before I left the country.
This was no more than consistent with my office as a minister,
and my commission to that country, which was to preach Truth and righteousness,
and strengthen the hands of my brethren, against their opposers.
Both myself and companion were so clear of improperly
intermeddling with the affairs of government,
that we sometimes checked the torrent of conversation on that subject,
either by silent or verbal reproof; and but seldom so much as read their newspapers.

During the time of the people`'s being in so great confusion and distress,
on account of the Indian war, my mind was much exercised; but for several months,
I know not that I could at all, even secretly, petition the Almighty for their relief,
with any evidence of such a petition arising from the spring of Divine life.
But a little before a stop was put to their depredations,
my spirit was almost continually clothed with intercession,
that the Lord might be pleased to stay the sword;
and in two public meetings I was concerned in like manner;
and I did not hear that any mischief was done after that time,
by any Indians who had occasioned that disturbance, and a cessation of arms ensued.

I record this as an instance of Divine wisdom instructing his
servants to ask what it is pleasing to him to grant;
as well as restraining them from petitioning for what
might be exceedingly desirable to themselves,
before the proper time;
and I believe that if ministers thus kept under the government of that spirit of wisdom,
which gives liberty in the appointed season acceptably
to approach the throne of divine Grace,
it would be more evident that they asked in the name and spirit of Jesus,
by their prayer being answered.

I think it worth remarking, that the termination of this Indian war,
was at last effected by the peaceable interposition of Friends.
An Indian chief, with other Indians in friendship with Pennsylvania,
being occasionally in Philadelphia,
Friends obtained leave of the governor to have a conference with them;
in order to endeavour,
through their interference to bring about an accommodation
with the Indians now at war with the British colonies.
As we were admitted to attend this conference, I mention it.
It evinces the veneration the Indians retained for the memory of William Penn,
and for his pacific principles; and their great regard to Friends,
whom they styled his children.
Several of their women sat in this conference, who, for fixed solidity,
appeared to me like Roman matrons.
They scarcely moved, much less spoke, during the time it was held;
and there was a dignity in the behaviour and countenance of one of them,
that I cannot forget.
I was informed that they admit their most respected women into their counsels.

And here I remark,
that we were in Philadelphia at the time when the first soldiers that
had come there commissioned from the English government,
arrived at that city; under the command of general Braddock.
I said a cloud of darkness came with them.
The Lord had settled this colony by peaceable means,
he had hitherto protected it by his own Almighty arm, and it prospered greatly;
but henceforward disunion and disturbance prevailed and increased in it.
Our friend Samuel Fothergill, as well as we,
was strongly and affectionately engaged to promote peace,
and guard them against the event, which he feared would ensue,
and which in time followed.

Our stay in this country was considerably longer
than usual for Friends who visit it from Europe;
which was much in the cross to our natural inclination,
but quite in the unity of the sensible body of Friends;
who saw that we were industriously engaged in the service to which Truth had called us:
and whatever some loose spirits might suggest respecting our long absence from home,
I have this testimony in my conscience,
that since I have been engaged in the solemn service of the ministry,
I have ever endeavoured to accomplish the duties assigned me,
in as short time as I could;
being desirous that I might not afford occasion of censure to such,
as being unacquainted with the humbling weight of this service,
may conclude that we travelled for pleasure,
or to gratify a roving or curious disposition;
as well as that I might spend the spare time afforded
me in the exercise of my duty in my own family,
and examining the state of my mind; which, after returning from journeys of this kind,
as well as in going along, should be necessarily attended to:
and may I never be a servant whom Divine wisdom has made a keeper of his vineyard,
but who neglects the culture of his own heart.

My companion`'s service through the continent principally bended towards Friends,
yet was she at times clearly and livingly opened to others;
but my concern was mostly more general;
although in the provinces of Pennsylvania and the Jerseys,
wherein our Christian principles were pretty much known,
it was more particularly directed to my fellow members in Society;
who had perhaps been the less laboured with by ministers visiting them,
on account of meetings often being much mixed with other professors.
As we spent so much time in Philadelphia before we left the continent,
I had many times been much enlarged in the service appointed me,
both to Friends and others; and my companion, whom as a minister I preferred to myself,
had extraordinary service; but as is before hinted,
her bodily weakness prevented her attending meetings,
some of the latter part of the time we spent in it.
I may say without boasting,
that we were endeared to the weighty body of Friends in that city,
as well as in the other parts of the continent, and they were so to us.
And after having laboured among them more than two years and seven months,
we took a solemn leave in the love of the gospel,
of those present in a large quarterly meeting held at Philadelphia,
and left the city on the 5th of the sixth month, 1756.

We were accompanied by many Friends to Chester,
and were there Divinely favoured together the next day,
when we went on board a snow bound for Dublin,
in company with our dear friend Samuel Fothergill,
who was returning from his religious visit to Friends in America, and Abraham Farrington,
who was going on one to Friends in Europe.

There were passengers in the same vessel with us, Samuel Emlen, a Friend of Philadelphia,
and two other young men Friends, who were going to England by way of Ireland.

We had a very quick but stormy passage; being on board only thirty-four days,
and but twenty-six of them out of sight of land.
The sailors accounted it a very fine passage, but we suffered very much in it,
through the boisterous winds, and their consequences.
The wind being right aft, the water frequently dashed over into our cabin,
although our deadlights^
footnote:[boards put in to defend the cabin-windows in storms.]
were mostly kept up; and it ran much under my bed,
so as to render my lodging very uncomfortable; and,
being sea-sick and otherwise indisposed, I was at times sunk very low,
yet the hand of the Lord was near to sustain and comfort me.
Notwithstanding the stormy weather, we had several blessed meetings on the voyage,
at some of which the master and sailors were present,
unto whom Divine goodness was pleased to open suitable instruction.

England was now at war with France,
and by the account of some fishermen who came on board us in the Irish Channel,
we narrowly escaped being taken prisoners, as two privateers were seen in the Channel,
at the very time we should probably have met them,
had we not for some hours been forced back by a strong contrary wind,
the only one we had during the voyage, which appeared signally providential for us.

We lodged in Dublin at the house of our friend Samuel Judd,
who was uncle to my companion, which was formerly the habitation of my very worthy aunt,
Sarah Baker, whose services in the ministry, when resident in this city,
had endeared her to Friends, and her name was precious to those of the present day.

The 10th of the seventh month, we landed at Dublin; and the 25th,
after taking an affectionate leave of my dear companion and friends,
Samuel Fothergill and I took shipping for England,
and landed at Holyhead in Wales the 27th. Here we bought horses,
and reached Chester the 29th, where my friend Samuel Fothergill left me, and where,
accompanied by a young man, a Friend, I got home the 31st,
I was affectionately received by my dear mother, brother and sister,
who united in thankful acknowledgments of the Lord`'s mercy,
in restoring me to them and my native land.
I travelled one hundred and fifty-five miles from Holyhead in four days;
and had been absent from my mother`'s house three years, and upwards of one month.

I had noted having travelled upon the continent and islands,
upwards of eight thousand seven hundred and fifty miles, my companion not so much.
When I compare the fatigues, and the various inconveniences and hardships I sustained,
with my natural constitution, I cannot but admire,
that I did not entirely sink under them; and,
on considering the dangers attending the journey,
which were too numerous for me to particularize in the foregoing account of it,
I must thankfully acknowledge that the preserving sustaining hand of my heavenly Father,
was signally extended for my help and salvation.
May the humbling sense of his mercies and tender care, by me unmerited,
rest weightily and lastingly upon my spirit.
