== Chapter VI

[.chapter-synopsis]
* Goes to Holland on religious service
* Visits the few Friends there
* Letter to a young man
* attends meetings in Norfolk, Lincolnshire, and Yorkshire
* Returns home
* Letter to a person under religious exercises

I stayed a few days with my relations, and set forward,
with my dear brother and the before- mentioned Friends from Ireland,
for the yearly meeting at London.
In our way thereto we met our friends Samuel Fothergill and Abraham Farrington,
to whom I imparted my view of visiting Friends in Holland,
wherein they sympathized with me.
At London I laid my concern before the meeting for ministers and elders;
and it met the approbation of my friends,
and a suitable companion was prepared for me by my good Master, namely Sophia Hume,
of London.

It is worthy remarking, that when this journey was first presented to my mind,
this Friend was pointed out as a companion therein; yet had I not freedom to write,
or say any thing to her thereupon,
until I had thus proposed it for the consideration of Friends;
when I found that kind Providence had cared for me,
as she had for some time found her mind engaged to hold
herself in readiness to accompany some Friend on a journey,
though she knew not whom nor whereto, but on my mentioning my concern, saw both.
John Kendal, a Friend of Colchester, who could speak Dutch,
was engaged in love to accompany us.
Thus does the Lord mercifully provide all things necessary for such of his servants,
as are freely given up to run on his errands, and move simply by his directions.

The yearly meeting at London was overshadowed with the wing of Divine love.
I had some satisfactory service therein;
and on the 7th of the sixth month I went to Plaistow,
to visit my dear and ancient friend John Hayward;
and here I parted in much affection with my dear brother,
and with Samuel and Ann Fothergill.

The 9th, I went to Chelmsford, where I stayed until the 12th,
being in need of a little rest.
Here my companion Sophia Hume came to me, and we went together, with Abraham Farrington,
to the before-mentioned quarterly meetings held at Colchester, Woodbridge, and Norwich;
in all of which I was laboriously exercised,
and the hand of my heavenly Father was with me;
through which I was made strong in his cause,
and I hope the meetings ended to the honour of his worthy name.

Under a sense thereof, my spirit bowed in thankfulness to Him,
who clothes with strength for the battle,
and by his own right arm gets himself the victory:
unto whose service may my soul be bound forever!
We stayed about three weeks in Norwich, in which city there is a large body of Friends,
unto whom a powerful visitation of Divine love had latterly been extended;
through the prevalence whereof several natural members, or branches of our own Society,
had in a good degree submitted to the simplicity of the cross;
and others had been gathered to the immediate teachings of the Shepherd of Israel,
from other religious societies.
Several had appeared in public testimony,
for whom in an especial manner our spirits were exercised,
that they might honour God in their respective callings,
by an exemplary conduct and a living ministry.

I had much service amongst them in the openings of Divine wisdom and love,
wherein some of the dangers which attended them were pointed out.
I was also concerned, closely to reprove such as had sustained loss in the Truth,
by letting out their minds after terrestrial enjoyments,
and were seeking great things to themselves, whereby the Lord`'s work in them was marred.

From Norwich we went to Harwich, and on the 21st of the seventh month, 1757,
accompanied by John Kendal, went on board the packet bound for Helvoetsluys,
where we landed the next day.
There we took a carriage and went to the Briel, a pretty large town;
but I did not find that ever any of our Society resided therein,
and the people seemed very ignorant respecting us: for as we walked the streets,
offence was taken at our friend John Kendal, for not returning the customary salutation,
of putting off`" the hat in the same manner.

My spirit was very low on my arrival in this country,
on account of the difficulty I laboured under for lack of knowing the language.
Could either myself or my companion have spoken Dutch,
we might have explained to the man, who was an officer in the army,
our reasons for not returning his civility, for such it appeared to be;
and he was very much irritated at John Kendal`'s not noting it as such.

From the Briel we went in a boat to Rotterdam, which is a large city,
wherein there was formerly a meeting of Friends, and where still remains a meeting-house,
and there are a few who were educated among us;
but they had so little regard to the testimony of Truth and the welfare of their souls,
as entirely to neglect assembling to worship the Almighty;
yet were not content to profess with any other people.

We had no inclination to call upon any of these;
but having information that the meetinghouse was under
the care of persons who were the descendants of Friends,
we called at their house,
and desired that the meeting-house might be got in
readiness for us to have a meeting there at our return,
which one of them promised it should be.
He behaved civilly, but appeared very distant from the profession of his ancestors.

These persons were great tradesmen, had become rich,
and much in the grandeur of this world,
and were now of the society of the Menists or Baptists.

The next day we went in the trackscuyts, by way of Delft and Leyden,
in neither of which cities are any under our name, to Harlem,
where lived the person who used to interpret for Friends from England:
upon whom we called, but found him so enfeebled,
as to be entirely unfit for that service.
Here we were met by Sophia Vander Werf and her son John, from Amsterdam.
She was a woman of a sweet natural disposition, came amongst Friends by convincement,
and had received a gift in the ministry,
in the exercise of which I believe she was acceptable to Friends.
The young man had resided a considerable time in England;
he spoke English well for a Dutchman, and I looked towards him for an interpreter;
but although he appeared to have a sense of Truth,
I feared his being deep enough in the experimental work of it for that service:
so I said nothing to him, and proceeded to Amsterdam under some discouragement.
In this city, a lodging was provided for us by Friends, at the house of Abraham Herman,
which appeared the most suitable place for our reception of any belonging to them.
He with his wife received us kindly, and treated us so while we stayed with them.
It was seventh-day evening when we came to Amsterdam,
and before John Vander Werf left us,
I asked him whether he was willing to assist us as an interpreter;
but he modestly declined, pleading his unfitness for the service.
John Kendal also refused,
on account of his deficiency in the language to interpret in a public meeting,
although he could speak Dutch in the common course of conversation.

Under these discouraging circumstances I went to bed,
beseeching the Almighty to lay a concern upon some one to assist me.
When I arose in the morning, my spirit was low,
yet not doubtful of my being right in coming into this country.
In this state I went to meeting,
without any expectation of an interpreter being provided for me at that meeting;
and therefore rather expected to be silent therein.
The meeting was pretty large, but we were told, less than at some other times:
for although there are but few professing the Truth in this city,
it is customary for people of all religious societies, nations and qualities,
who come there on account of business or pleasure, to go to our meetings,
most of them doubtless from the motive of curiosity;
but the solidity of the countenance and demeanour of some present,
and the knowledge I afterwards had of them,
convinced me that they were actuated by a better motive.

In the forepart of the meeting,
my spirit was much exercised and broken under the consideration of having no interpreter;
yet supported in hope of the provision of Providence:
for it appeared to me inconsistent with Divine wisdom and mercy to bring me here,
and not to open the way for me to convey his will to the people.
After some time a Dutch Friend bore a short testimony; and soon after he sat down,
something arose in my mind,
by way of information to the people respecting our motives for coming amongst them;
and I was quickly favoured with strength to stand up,
intending to say that I had something to communicate to them,
which if any one present would interpret, I would impart;
but I was not obliged to proceed thus far, for upon seeing me rise,
John Vander Werf rose also, came and stood by me in the gallery,
and interpreted what I said to the present relief of my spirit,
and the satisfaction of such Friends present as understood both Dutch and English.

I found it so difficult to convey the doctrines of Truth in this way to the people,
that it appeared almost impossible to get relief of mind, or liberty of expression,
to that degree I had sometimes been favoured in my own tongue, I spoke a sentence,
and stopped for the interpreter to speak it after me;
and I was thankful that kind Providence had so
far answered my belief of his providing for me;
and was comforted in the hope that his blessing, which alone makes fruitful,
might be dropped upon my weak endeavours for the exaltation of his Truth.
The meeting ended in solemn supplication, in which exercise I had no interpreter,
John Vander Werf being unwilling to undertake that awful service.
Some present might understand English well enough to comprehend what I said; and others,
I believe, were sensible of the Divine power which overshadowed the meeting.

The afternoon meeting was neither so large, nor yet so satisfactory,
as that of the morning;
which I thought might be occasioned by a fellow- minister
withholding what Divine wisdom required to distribute;
whereby my service to the people appeared to be impeded, and the life of truth being low,
I said but little.
I left the meeting under some discouragement,
yet not without hope of being more at liberty before I left the city.

We stayed in and about Amsterdam till the 5th of the eighth month,
in all which time we had no meeting but in the city;
nor did it appear likely we should have many elsewhere in the country,
by reason of my interpreter being clerk to a merchant,
whose business did not admit of his being much absent, save on first-days.

In this time we had several pretty good opportunities with Friends and the people;
yet I seemed as an ambassador in bonds,
but laboured to be content in the present dispensation.

We were visited by several religious people,
with some of whom I felt a degree of union in the Truth;
but saw their loss in running after notions,
and not settling in the ground of true silence,
wherein the mind becomes established in rectitude:
and it appeared proper to set them an example therein;
and to be cautious of running into religious discourse, to which they are much addicted,
without feeling liberty for it in the Truth.
We visited a religious Menist, and had some satisfactory service in his family.

There are a number among that people who are near Christ`'s kingdom,
though not fully redeemed from inefficacious ceremonies,
and a dependence on instrumental ministry, or at least a fondness for it.

While at Amsterdam she wrote the following letter:

[.blurb]
=== To a young man in Ireland, who had been long under religious impressions.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Amsterdam, 1st of Eighth month, 1757.

Yours of the 5th ult.
I received yesterday, and with a degree of satisfaction have observed its contents;
although it seems to breathe the language of complaint,
or at least fear of falling short of the mark you have had in view,
and I hope are pressing after.
Although this is a state painful to nature, it is sometimes a state of greater safety,
and more directly pointing to perfection, than is that of ease,
or even of the aboundings of sensible consolations:
whereby some have been induced to conclude themselves
in a better and safer state than they really were,
and so have grown less watchful and diffident of their own judgment;
and spiritual pride and vain-glory have entered,
wherein they have boasted above their measure of experience;
and at last "`turned the grace of God into wantonness,`" and
their latter end has been far worse than their beginning.
But in the seasons of the withdrawings of Divine goodness,
the soul that is earnestly bent to obtain the kingdom of God,
which stands "`in righteousness`" as well as "`in peace and joy in the Holy
Spirit,`" is set upon searching what is the cause of its being thus deserted;
and so "`digs deep`" through the corruption of fallen nature,
and "`lays its foundation sure`" in the experience of
the purifying operation of the Spirit of Truth;
and against such it is that "`the gates of hell shall not
prevail:`" and that you and I may be of this happy number,
is the travail of my spirit.

It is most certain that our journey through life is as through a vale of tears,
wherein various will be our conflicts, and numerous our trials,
both inwardly and outwardly; but we have this encouraging promise left us,
that "`all shall work together for the good of such as truly love and fear God.`"
And as our hopes and desires are fixed on an infinitely better country,
the joys whereof are pure and eternally permanent,
let us not repine at the means used to secure them to us;
but with all possible cheerfulness take the cup
which Divine Providence hands forth to us,
as "`the cup of his salvation;`" and steadily endeavour for that mind,
wherewith the blessed Jesus was clothed, which says continually,
"`Your will be done;`" even in the bitter baptism of crucifixion,
which every true-born child of God must be partaker of;
and under the bitter pangs of death to the fallen nature, will have to cry out, "`My God,
my God, why have you forsaken me.`"
O! if this was the language of the Master, the immaculate Lamb of God, who knew no sin;
no wonder that it is the language of the servant, who has been defiled therewith;
and from which he must be washed,
before he can have part with the Son in his inheritance.
I have looked upon it as an infinite mercy to be led deep enough in humiliation,
to be stripped of all that has any appearance of what is good and excellent,
and to have this the secret language of the soul to Him who sees in secret,
"`I am a worm,
and no man:`" and although the consolatory portion of such as these may be sometimes hid,
or withheld for a season; yet they are sure, being in the hands of infinite Wisdom,
Truth and Mercy; who, in the wise appointment of his providence,
will give to his own what they stand in need of;
and when the days of fasting and humiliation are accomplished,
will assuredly "`bless the provision of Zion, and satisfy her poor with bread.`"

I thought when I last left Dublin, if I were in debt to any one in it,
it was to yourself Perhaps your letter may open a way for me to pay it;
although I do not remember that any thing of the above was upon my mind for you;
but a hint of advice seemed to bend toward you,
to beware with whom you enter into the covenant of friendship,
lest in the end you shouldest be wounded by their backslidings: and let me also add,
beware of looking out at the misconduct of Others, with a discouraging eye;
for although "`thousands may fall as by your side,
and tens of thousands as at your right hand,`" yet if you "`make the Most
High your refuge,`" by a steady and faithful obedience to his will,
he will preserve you.

Through mercy I am favoured with a good degree of health and peace in my going forward,
although the present concern wherein I am engaged is
attended with some discouraging circumstances,
yet I have faith that I am here in the appointment of heaven.

If Lucy Bradley and companion have not left Dublin before this comes to hand,
please to present my dear love to them;
and tell Lucy that I wrote her since I came to this city,
wherein I hinted my expectation of seeing York in my return home.

My love in that which is unchangeable strongly attends you,
and the tried remnant of spiritual Israel in your city and nation, who,
although they are few, are too numerous for me to particularise:
shall therefore give you a general commission to
present my love to such as you have freedom;
and conclude myself, Your well-wishing friend,

[.signed-section-signature]
Catherine Payton.

--

The 5th of the eighth month, we went in the trackscuyts, as far as Horn, towards Twisk,
our friend Sophia Vander Werf accompanying us.
At Horn we called on two religious Menists; the one a preacher amongst them,
who seemed more gathered into stillness than most of that persuasion,
and his wife near the Truth; the other much inclined to discourse on religious matters,
in whose family I found an engagement to leave a
short testimony to the benefit of silence,
which they appeared to receive well.
As we passed through the towns, we scattered some books setting forth our principles.

A Friend from Twisk met us here with a wagon, wherein we went home with him that evening.

At Twisk there is a small meeting of professors of Truth,
but we found them much in the mixture, and some of them so exalted in notion,
that it was hard fastening any solid doctrine upon them.
We were at two meetings with them, and several of the Menists;
both of which were exercising, that in the morning particularly so;
but I was comforted with an evidence that my service,
weak and imperfect as it appeared to me, was accepted of Him who employed me.
The afternoon meeting was more satisfactory, although laborious.
The Menist preacher before mentioned, with his wife and son, were with us,
in whose company we had a degree of satisfaction.
The next morning we procured a select opportunity with
most of the Friends belonging to the meeting,
at the house of a valuable woman Friend, whose circumstances demanded our sympathy;
she dwelling solitarily and having been many years confined through extreme weakness.
She was such a pattern of resignation and cheerful innocence, as I had rarely seen.
Her very countenance bespoke acquiescence with the allotment of Providence,
and not one complaining word dropped from her.
This meeting tended to the relief of our spirits,
and we took leave of the said Friend and others in love, and returned to Amsterdam again,
dispersing some books in our way; which was all we could do,
as our interpreter could not stay with us to have meetings in the towns.

On our return to Amsterdam,
we visited almost all who could be accounted members of our Society, in their families,
and attended the meetings on first and week-days, as they came in course, until the 21st:
in which time I had several good opportunities with the people of that city,
and the strangers who attended the meetings, and left it in peace.

One visit we paid in Amsterdam was so remarkable in its consequence, that I note it:
A man who was convinced of Truth, had a turbulent spirited wife,
who had violently opposed his going amongst Friends;
and after one meeting which he attended with us, railed much; nevertheless,
she sent us an invitation to sup with her, and it appeared best for us to accept it.
She provided handsomely for us, but seemed to be in a wrangling spirit.
She talked about dress being an indifferent matter; upon which I told her,
that the adorning of Christian women, should be that of a "`meek and quiet spirit,
which in the sight of God was of great price.`"
This struck and silenced her, and she afterwards behaved obligingly to us.

After we had paid this visit, her husband told us, that some time before,
as they were going to bed, she, being in a very bad temper, would not let him rest; and,
although he was in bed before her, I think he arose again.
She took up the bible, I suppose, to convince him of his errors,
and opened it upon this very text; which then so affected her,
that she condemned herself, kneeled down to pray for forgiveness,
and promised that she would never more treat him so improperly;
but she had not kept her promise, and the text being now revived in her remembrance,
it again affected her.
We were quite ignorant of the circumstance.

The 21st, we had a meeting at Harlem to good satisfaction.
We lodged at Isaac Van Westercappel`'s, who furnished us with a room to hold a meeting in,
and gave notice of it to the people.
He was descended from Friends by the mother`'s side,
but he himself never made profession with us.
He was exceedingly kind to us, and with his family,
appeared to be seeking after the best things.
In the evening we had the company of some seeking people,
most of them of the offspring of Friends,
with whom we had conversation upon religious subjects.

In our public meeting at this place, I was more at liberty in the exercise of my gift,
than had been usual with me in Holland; at which I afterwards admired,
being told that my interpreter was uncommonly
defective in rendering what I said into Dutch.
This circumstance sometimes revolved in my remembrance,
accompanied with some kind of doubt respecting my being so much at liberty to speak,
when what I delivered was not well interpreted to the people; but after some years,
a Friend of Norwich told me, that there was at that meeting a sensible man, a Jew,
who understood the English tongue well, who told him that he had attended the meeting,
and that my interpreter did not do me justice; but continued he, It was no matter,
as all she said was directed to me:`' and my friend added, that it so affected him,
that he believed he would freely interpret for me, should I ever lack his assistance.
This relation removed my before mentioned doubt,
for the word preached found its way to one mind,
for which in Divine wisdom it was appointed.

The 22nd, we parted with my interpreter John Vander Werf, for whom I was concerned,
and sympathised with him, as he was left almost alone, in regard to Friends,
and much exposed in the course of his business;
and from the affability and sprightliness of his disposition,
he appeared to be in much danger:
but I conceived hope in the sense of the extendings of
Divine goodness being singularly towards him.

We also took leave of our kind host, Isaac Van Westercappel,
and several of his family and friends in love and tenderness, and went to Rotterdam,
where his daughter Susanna Van Westercappel, a serious agreeable young woman,
and our friend Sophia Vander Werf accompanied us.
In our way, we distributed books to some people in the trackscuyts,
and the same evening had a meeting at Rotterdam with some people who understood English,
of which there are many, in that place.

The 23rd, our kind friends Sophia Vander Werf and Susanna Van Westercappel left us,
and we went to the Briel, and from there, the 24th, to Helvoetsluys.
In our way from Rotterdam to this place we met
with several persons who were going to England,
with whom we had much discourse concerning our religious principles,
I believe measurably to our mutual satisfaction.

One of them was a Swede, a Lutheran by profession;
he was favoured with a good understanding,
and had a mind susceptible of religious impressions;
although his conduct was not so uniformly exemplary as could have been desired.

On coming to Helvoetsluys, we found that the wind was against our sailing for England,
and that the inn was full of company,
many of whom were waiting for their passage to England:
so the landlord put us in a house which was ready furnished,
and we became a family to ourselves, being furnished with provisions from the inn.
The wind continuing contrary until the first-day of the week,
and there being in the place many people of various nations and stations who could
speak English--with the concurrence and assistance of our landlord and company,
we got our dining room well seated; and on the first-day morning held a meeting in it,
whereto the strangers pretty generally came.

I was favoured to declare the Truth amongst them, to the relief of my own spirit,
and I believe to the comfort and satisfaction of my companions; but the labour was hard,
through the unpreparedness of the hearts of some to receive,
and perhaps the lack of a sufficient knowledge of the language in others,
to understand the doctrines delivered.

The 29th in the evening, the wind turned in our favour, and continued so,
until about the middle of the next day;
but our captain would not put to sea without a pretty steady wind,
because of the French privateers: however, we went on board that day and set sail,
and the wind being very boisterous our jib-sail was soon rent;
and another packet boat going out with us, struck upon the Pales,
broke a hole in her side, and as the passengers said, was in danger of being lost.
The wind continuing to blow hard and contrary, we soon came to an anchor,
and the next morning returned back to Helvoetsluys; and the following day,
the 1st of the ninth month, we were favoured with a fair wind,
and arrived at Harwich the 2nd, in peace and thankfulness to the Almighty,
I had to admire his goodness,
in thus preserving and supporting my body and mind by sea and land,
and through all the exercises attendant on this journey,
amongst a people of a strange language.

Even our detention at Helvoetsluys appeared to be in the ordering of
Divine wisdom and mercy to the people there visited;
and in our select company we had frequent opportunities
of conversing upon edifying subjects;
some of our companions seeming willing to gain
information respecting Friends and their principles.

Once the subject of self-defence was started,
which they might probably think we could not invalidate;
but we were enabled to give a reason for dissenting from them in sentiment,
and on its being queried what we would do if attacked, and must either be killed,
or kill; I said, I could not say how I should act at such a juncture,
wherein nature might be improperly raised;
but that now being favoured with the hope of my immortal spirit`'s centering safely,
and knowing that a person who sought my life,
must be in an unfit state to enter Christ`'s holy kingdom, I should rather choose to die,
than plunge that soul into everlasting misery;
and should have greatly the advantage in being released from this state of trials.
They heard with attention, and the Swede with tears in his eyes, replied,
these are indeed sublime sentiments.`' We had been so long detained at Helvoetsluys,
that our money grew short, but the captain said we should have what we needed from him;
however, we had enough to pay our passage, and bear our expenses,
excepting the hire of our chaise to Colchester:
which we reached almost pennyless the 3rd,
and were affectionately received by John Kendal`'s mother, and other Friends.

After a short stay at Colchester, I went with my companion Sophia Hume to Kelvedon,
where we were favoured with a comfortable meeting with Friends, and parting in much love,
she went for London.
She had been to me a steady, affectionate, sympathising companion;
and although in this journey, not much engaged in public ministry,
she was very helpful in meetings, through a deep spiritual exercise;
and being endowed with a good understanding, both naturally and spiritually,
she was qualified to give an answer of "`her faith and the hope that was in
her:`" and I was often thankful to the bounteous Author of all my mercies,
for furnishing me with so suitable a companion.

From Kelvedon, I went without any companion, through several meetings, to Norwich,
where I was favoured in the service appointed me, but stayed there only a few days;
proceeding from there through some meetings in Lincolnshire,
to the quarterly meeting at York; where I again met with Abraham Farrington,
who with many more of my friends,
rejoiced at my being returned to my native land in peace and safety.

From York, I passed through several meetings in that county,
wherein the Lord was pleased to vary the dispensations of his wisdom,
by dipping me into a state of great suffering; which I could not get above,
but which I saw to be good,
near the close of a journey wherein I had been so eminently favoured;
as it tended to preserve me from clothing myself with the Lord`'s jewels,
and humbled my spirit to the very dust.
From Yorkshire I went to Manchester and Warrington,
where I regained a little liberty in the Truth,
and so proceeded to some meetings in Cheshire;
in one of which I thought I was raised higher, in the Divine life,
in the exercise of my gift, than I had been throughout the journey.
Thus does Divine wisdom abase and exalt at his pleasure, unto whom be glory, honour,
and praise ascribed, now and forever.

The 15th of the tenth month,
I got home to the mutual satisfaction of myself and relations; and,
notwithstanding my great fatigue, in a rather better state of health than when I left it;
and found my dear and aged mother well.
Here I also met my dear friend Lucy Bradley,
who was returning home from her visit to Friends in Ireland,
and our rejoicing one in another was mutual.

The 17th, we went together to our monthly meeting,
wherein I gave to Friends some account of my service and satisfaction in this journey;
and my spirit was much humbled in a sense of the providential
care and abundant loving-kindness of a merciful God,
variously displayed to this period of my life.

This winter I spent much about home, and amongst my relations: not in idleness,
for I was very closely engaged either in attending monthly or quarterly meetings,
or other services.

[.blurb]
=== Extract of a letter to a young man, under religious exercises.

[.embedded-content-document.letter]
--

[.salutation]
Esteemed Friend,

Yours of yesterday I just now received;
and am concerned to find by its contents,
that indisposition prevents your meeting us as proposed;
but as through faith and patience every affliction may be sanctified,
I cannot but hope the present may tend further to refine your
spirit and enlarge your understanding in Divine truths;
which are not always manifested in the hours of consolation,
but must be painfully felt in the depths of experience.

That beautifully strong expression in sacred writ,
that "`The Lord makes the clouds his chariot,`"
has of late often been revived in my remembrance;
with this illustration, that when a cloud is over us,
who have known and rejoiced in the light, it is good to stand still,
and hearken for that "`small still voice`" proceeding from it,
which alone can compose and settle the soul.

To be sure it is a necessary duty to search our hearts,
and not in so doing to evade the judgment of Truth;
but it is also well to guard against too hasty
conclusions of the causes and ends of exercises;
especially in an hour of weakness, wherein the old accuser is not lacking on his part,
to suggest the most painful apprehensions,
thereby to dispirit the mind that seeks to be freed from his insupportable yoke.

The new discovery you makest of the delusiveness of your thoughts,
affords me much satisfaction, as it gives good ground to hope,
that the Lord designs to lead you to a state of perfection, which few, very few,
have seen into; that is, an entire abdication of self,
even in its most pleasing and seemingly lawful appearances.

That of an ideal satisfaction in something seemingly good,
yet short of the Divine perfection, is an exercise which attends many,
and has prevailed against some,
at least to the diminution of that lustre which would have shone around them.
It is a favour so quickly to see into it, and having seen,
I hope you will endeavour to avoid it, and the Lord will help you.

There is no happiness here equal to perfect redemption from the world, its spirit,
and ourselves.
To have no hopes, no desires, but in the will of God,
is fully giving ourselves into his holy hand, and to be swallowed up of him,
though of this, for lack of Divine sensation, we may sometimes be ignorant.
Here methinks I almost hear you say, This is the state I long for, but it is distant,
very distant, from me.`' But is it not as of yesterday you saw into it,
and would you be perfect at once,
and enjoy a victory without a fight? This my
friend is the summit of the mount of perfection,
which you have lately begun to ascend,
and in your journey I sincerely wish you good speed;
and from the quietude which I at present feel about you,
I cannot but hope you are in the best of hands:
may a sense thereof be communicated in the most needful time.

[.signed-section-signature]
Catherine Payton

--
