== Chapter VII

[.chapter-synopsis]
* Attends the Yearly meetings in Wales, at Bristol, and London
* Embarks for Ireland
* Detained by contrary winds
* Returns home
* Epistle to Friends in Ireland
* Visits meetings in Oxfordshire and Northamptonshire
* Visits the meetings of Friends in Ireland
* Returns home und visits Derbyshire, Yorkshire and Lancashire
* Yearly meeting in London
* Colchester
* Woodbridge and Norwich
* Goes into Lincolnshire, Yorkshire, etc.
* Epistle to a Quarterly meeting
* death of her sister
* Religious services in London, etc.
* Attends the Yearly meetings in Wales and Lancashire
* Illness and death of her brother Henry

The 6th of the fourth month, 1758, I left home, to attend the yearly meetings of Wales,
Bristol, and London; in all which, especially the two first, I was Divinely favoured;
and returned home, in peace and thankfulness, in the fifth month.

Towards the fall of the year,
I attended our circular yearly meeting held at Kidderminster,
which was large and very satisfactory.
After this meeting, being inclined to visit some provincial meetings, etc. in Ireland,
I went with my dear friend Samuel Fothergill to Warrington,
and from there proceeded to Liverpool, in order to take shipping for Dublin;
but finding no vessel there ready to sail,
I sent to inquire whether any one was going from Parkgate; and the messenger returning,
said there was one, but that she would sail the next tide,
and that it was then too late to reach her.
I was pretty earnest to try, but some friends,
who I thought were acquainted with the time of the tide`'s turning,
dissuaded me from attempting it.

So I gave it up reluctantly,
fearing I should lose the opportunity of getting my passage in time for the meetings;
and I afterwards heard that the tide did not turn till
an hour after the time they said it would;
so had I gone, I might probably have reached the vessel in time.

I waited at Liverpool more than a week,
most of that time in almost constant expectation of sailing,
a vessel being soon ready to sail, but the wind was contrary.
At length I went on board, and we set sail with a fair wind,
but it quickly turned against us,
and we lay all night at anchor in a small harbour called Hoylake.

The wind blew hard,
and I esteemed it a singular favour that our captain was persuaded to lay at anchor;
for we might have been in imminent danger of perishing among the sand-banks,
had he stood out to sea; which I had some reason to believe he would have done,
had I not been on board; for I being set to a day in getting to Dublin,
in order to attend the province meetings, had requested him,
if there were not a probability of our making our passage in time,
to set me on shore somewhere in Great Britain; which he promised to do if he could.
The vessel being small and very full of passengers,
who in the night crowded into the cabin, it was so extremely close,
that I was much afflicted both in body and mind:
under which I sought for Divine direction respecting proceeding forward in the vessel,
should the wind prove favourable in the morning,
I thought I felt my mind turned to the shore,
and released from the weight of the journey, at least for the present;
therefore when it was light, I desired the captain to endeavour to put me on shore,
and he accordingly hung out a flag for a boat to come and take me; but none came,
and as the wind had again shifted in their favour,
and it appeared hazardous to send the ship`'s boat with me,
lest she should not return time enough for her sailing, I feared I must stay with them;
but unexpectedly the captain offered the boat and men,
provided I would be left on the beach with my saddle and clothes,
and let the men return to the vessel immediately; to which I agreed, and left the vessel,
under the probability of her making her passage.
A poor woman of Ireland who had no mind to proceed in her, went on shore with me, who,
with her little girl, carried my saddle, etc. about half a mile, to a public house,
where I breakfasted, and got a man and horses to take me to Liverpool.
I proceeded pensively, lest I should have missed my way in leaving the vessel;
yet I could commit my case to the Lord, who knew I had acted in simplicity.
In our way we saw the vessel under sail, just turning out of the harbour on her course.
When we reached Liverpool I was much fatigued, and low both in body and mind,
having slept little in the night;
but after some rest I attended the funeral of a child the same evening,
and in the meeting the Lord so favoured,
that my fears about leaving the vessel in a great degree vanished.

After meeting I found that the wind was turned against her,
and continued to blow very hard all that night;
and the next morning the vessel came back to Liverpool.
I stayed there the next day, and then returned to Warrington,
and was at the meetings at Penketh and Warrington the next day, and so proceeded home,
taking in my way there a meeting at Nantwich.

Although I had been thus disappointed,
I had reason to hope that my leaving home was not
without some fruit to others as well as to myself;
so that my soul had cause to bless the sacred name of Him,
who sanctifies every trial to his children.

The day I stayed at Liverpool,
I penned the rough draught of an Epistle to Friends in Ireland,
and after my return home transcribed and sent it.
The Epistle is as follows:

[.embedded-content-document.epistle]
--

[.blurb]
=== To Friends in Ireland.

[.salutation]
Dear Friends,

As I am prevented by contrary winds from paying a visit this fall,
to some of your Province meetings, etc.
(for which end I proceeded as far as Liverpool);
in the strength of that unfeigned love of the brethren which drew me from my home,
am I endeavouring to salute you by a few lines:
in hope the Divine wisdom and mercy may direct my pen,
to the present relief of my own spirit, and your help.

And first, dear friends, permit me to inform you,
that the lamentable state of our church, is almost continually before me.
This in yours as well as other countries,
has suffered greatly by the baneful prevalence of the spirit of this world; insomuch,
that too few have their hands clean and strong for the Lord`'s service;
or can see to extract the motes from the eyes of their brethren,
because of the beams which are in their own.
May not some of the instructors, and seemingly zealous in our Society,
be justly taxed with hypocrisy;
seeing while they cry against the reigning sins of others,
they are inattentive to their own? unto whom I would direct the
advice of Christ--"`Pluck first the beams out of your own eyes,
and then shall you see clearly to take the motes out of those of your brethren.`"

It is a sorrowful truth,
that even the garments of some of the priesthood
are spotted with the world and the flesh;
and they are therefore rendered unfit to minister before the Lord in that sacred office.
For whatever may have been their former experience of
the sanctifying operation of his Spirit;
or however clear may have been their call into his service; yet if, like Judas,
they have betrayed their Master for the pieces of silver, or, like Demas,
may in spirit have forsaken his family for the
love of the world in some of its alluring shapes,
theirs justly is the judgment passed upon Judas;
who being fallen from his station in the holy body of Christ,
was to lose his bishopric or part in the apostleship:
such being rendered unfit to give testimony to the life, sufferings,
death and resurrection of the holy Jesus, who did not retain it in their own experience.

Observe, brethren, the word retain.
It is not enough that we have once known the Lord,
but we must retain him in our knowledge, by the renewed baptisms of his holy Spirit:
and of some who did not choose to do so,
it is recorded that "`God gave them up to a reprobate mind,
to work those things which are not convenient.`"

And I believe there are in our day, who,
having deviated from the simplicity of Truth for sinister ends,
have gone wider and wider therefrom;
until their hearts are become so darkened that they call evil good, and good evil;
put darkness for light, and light for darkness;
and in their pursuits after worldly interests,
are obviously worshipping and serving the creature more than the Creator:
and yet these very persons would keep those seats,
and discharge those offices in the church, which were assigned them,
when in the days of childhood,
they were willing to follow the Lamb whithersoever he led them.

O! for these blind guides, is my soul pained; and that not only on their own account,
but that of others, who apprehending the law to proceed from their mouths,
(though they have in reality no right to take the word
of the Lord thereinto) and observing their conduct,
may be influenced by their example, and follow them as they follow the world.
It is needful, my beloved, to warn you,
as our Lord did the people respecting the Scribes and Pharisees, who,
notwithstanding they sat in Moses`' seat, and administered the law,
were not to be regarded as examples; lest, being led by the blind,
you perish with them in the ditch of error and perdition? When I sat down to write you,
I had no view of beginning with these disagreeable remarks,
but simply gave myself up to the direction of
that Wisdom which best dictates what to say,
and when to say it:
and although some may object to their being inserted in
an Epistle which points to a general exhortation,
I am convinced by undoubted experience,
and the example of some of the most eminently serviceable in the Lord`'s hand,
that Divine wisdom sometimes commands to reprove those that offend,
let them be of what class they may, before all, that others may learn to fear.
In the authority of Truth I dare assert that the time is come in our church,
when it is necessary that judgment should begin as at the house of God,
in the very highest classes of the Society; and till that is laid to the line,
and some therein are either reformed thereby or removed from those dignified stations,
there is little probability of the Lord`'s work being carried on to his own honour,
in the general, and the comfort of the faithful.
Oh! says my soul, that all who are concerned, or concern themselves therein,
would study to be quiet and mind their own business, which is to take heed to themselves;
for although the Holy Spirit may have once made some of them overseers of the flock,
they cannot properly take heed thereto, unless this is the case;
for being themselves loaded with a secret consciousness of guilt,
for worshipping of idols, some obviously, and some having them concealed under a precise,
formal, outside appearance and deportment, as in the skirts of their garments,
they dare not, no they cannot, search out the hidden things of Esau among the people,
nor administer judgment in righteousness, where it is obviously due.

Let me therefore, in the spirit of gospel meekness and charity,
which breathes for your salvation and enlargement in
all the gifts and fruits of the Holy Spirit,
exhort you who are of the foremost ranks, whether ministers, elders, overseers,
or heads of families, that you would solemnly look into yourselves;
and with an impartiality which ever accompanies those who are really
concerned for the establishment of the kingdom of Christ in themselves,
ask yourselves, individually.
In what am I lacking? O! my friends, was this the case with us all,
and did we patiently wait for the answer of Truth,
we should individually be humbled into a sense of our
shortness of that perfection whereunto we have been called,
and wherein many of us have believed;
and some would be so struck with the view of their idolatrous
revolting from the simple worship of the true and living God,
that they would go mourning many days in the bitterness of their souls;
and all would be animated to press after the mark for
the prize of their high calling in Christ,
which is redemption from the world, the flesh, and the devil.

The nearer we approach to this blessed and happy experience,
the more our hands will be strengthened in the Lord`'s work,
and the more we shall be enabled both by precept and
example to build one another up in the most holy faith,
and in those things which edify;
and our confidence in God who is the Perfecter of his saints will increase, that,
as he has mercifully begun a good work in us,
he will finish it to the praise of his own name.

It is impossible that self-examination by the light of Truth should hurt any of us,
and it may help all.
I therefore once more earnestly recommend it, as a means of our fulfilling this precept,
"`Purge out the old leaven,`" and of enabling us to keep the
feast "`not with the leaven of malice and wickedness,
but with the unleavened bread of sincerity and Truth.`"
I shall conclude my exhortation to you of these classes, with saying, Be faithful,
and then will you be comforted and of one mind,
and the God of peace will preside among you.
Amen, Now to you who, not being in any of the before-mentioned stations,
may therefore think yourselves more at liberty to gratify the desire of the carnal mind,
is my concern directed; with secret breathings to the Father of mercies,
that he may enable me so to point the word to your hearts,
that being made sensible of your own danger, you may flee for your lives,
from those bewitching vanities,
and false pleasures which have held your souls in bondage to the god of this world; who,
by many secret snares, and more obvious allurements,
seeks to entangle the minds of poor mortals,
and lead astray their affections from that inestimable Fountain of light, life,
and happiness, wherein is centred all true joy, both in time and in eternity.

Dearly beloved! for so in the bowels of gospel compassion I call you;
have you ever seriously considered that you have no continuing city here;
and that as your souls are immortal, it is the proper,
and ought to be the principal business of your lives, to seek for them a habitation,
suitable to their being and nature, wherein they may have a happy residence forever:
which is alone to be found in God,
who is the source and resource of his people? Now in
order that your souls may at last centre with God,
it is necessary that they should be made habitations for him
through the sanctifying operation of the Spirit of his Son,
which alone can render us who have been defiled with sin,
(and therefore unfitted for a residence with Him), fit objects of his favour.
Allow me therefore to ask you, and O! that you would ask yourselves,
what you have known of this work,
in your experience? Has the spirit of judgment and of burning done its
office in your hearts? Have you passed through the first Part of the work of
sanctification? I mean the Administration of condemnation for sin.
Have you been bowed under the testimony of the righteous Witness of God in your
conscience? Or have you not rather depressed and contemned this heavenly messenger;
not allowing it to tell you the Truth, or at least,
disbelieving the doctrine it preached,
because it did not countenance some of your actions? No,
have not some gone so far as to slay the "`two witnesses for
God,`" the internal evidence of his Spirit,
and the external testimony of his servants;
and are perhaps at this hour exulting in their victory,
and proclaiming to themselves peace; when alas! a day of fearfulness, amazement,
and unutterable anguish, awaits them, and is near when, if not sooner,
the curtains of mortality shall be drawn, and they shall see the Judge,
tremendous in majesty, and that righteous witness, which in time they slew,
raised in power, to testify against them for their rebellion,
and assert the justice of their exclusion from the realms of light and blessedness.

What effect this faint description of the day of judgment to the wicked,
and those who forget God, may have upon the minds of such, I know not;
but my heart being impressed with an awful sense of its certainty,
is animated to endeavour to wrest them from its eternal consequences,
by persuading them to bow in the day of God`'s merciful visitation to their souls,
and to kiss the Son lest he be angry, and they perish from the way of life and salvation,
before his wrath be kindled but a little.

Do not vainly and proudly imagine, that you are able to stem the force of Omnipotence,
He is, and will be King,
whether you are willing to allow him the right of sovereignty or not;
and his sacred laws of unchangeable truth,
are as manifest in the punishment of transgressors,
as in the reward of those that do well:
and O! if it were possible to convey to you a sense of that sweet peace, glory, and joy,
which are, and shall be, revealed to those who love and serve God,
you would be convinced that no punishment could be too great for such as,
by a contrary conduct, slight and cast away so great salvation and happiness.
But as no eye can see, nor heart conceive, the exceeding grace of God in Christ Jesus,
but such as have happily witnessed its sanctifying operations;
I cannot but invite you to "`Come, taste, and see, that the Lord is good,
and that his mercy endures forever.`"

It is true, that in the way to this attainment you must pass through judgment;
for Zion must be redeemed through judgment, and all the converts with righteousness,
and a portion of indignation and wrath, tribulation and anguish,
must (consistently with the law of Divine justice),
be administered to every soul that sins.
But this judgment when received in the day of God`'s merciful visitation,
is succeeded by such inexpressible peace and assurance of Divine favour,
as abundantly compensates for the pains it may have occasioned:
for of a truth the carnal "`eye has not seen, nor ear heard,
nor heart conceived,`" what good is in store for those
who manifest their love to God by their obedience.
Believe me, my beloved friends,
when I tell you that my heart is strongly engaged for your welfare,
as you stand in your various classes.
I feel much more for you than I can write, and would beseech you by the mercies of God,
as well as by his judgments,
that you would present the whole body of your affections unto him,
which is no more than your reasonable service.

Has he not dealt exceeding bountifully to some of you
of the things of this life? For what cause think you,
has he entrusted you with such abundance? Is it to gratify the lust of the eye,
and the pride of life? Is it to make you haughty, and assume a superiority over such as,
in this respect may be below yourselves, but who perhaps may, some of them,
be higher in the Divine favour? No, surely`':
but in order that you may improve this gift to his honour, the good of others,
and your own eternal advantage;
and may be humbled in a sense of the disproportion of your deserts to his mercies.
Has he not favoured some of you with superior natural abilities? And for what end,
but that you might be in a superior degree serviceable in his
hand? Has he not afforded to all a day of merciful visitation,
wherein he has by various means endeavoured to bring you into that fold of immortal rest,
wherein he causes his Flocks to feed and lie down beside the clear streams
of salvation? O says my soul! that you may consider his mercies,
and make a suitable return for them;
that the Most High may delight in the present generation,
and dwell among the people as in days past.
O! you of the rising generation, open the doors of your hearts to that Divine Visitant,
who has long stood thereat, and knocked for entrance.
Let him prepare them, and he will assuredly spread his table,
and admit you to be happy communicants thereat.

Think not that it is too early in life for you to look
steadily towards a future state of existence;
but consider, that the solemn message to summon you from works to rewards,
may be sent to you at an early and unexpected hour: and that it therefore behooves you,
to be prepared to meet the great Judge.
My heart is particularly engaged for your welfare,
and pained in the consideration how widely some of you
have deviated from that path of primitive simplicity,
wherein your worthy predecessors trod.
Let me therefore beseech you to seek for the "`Good old way`" of holiness,
and walk therein; that you may experimentally know the "`God of your fathers,
and serve him with a perfect heart and willing mind:`"
so will his blessing forever rest upon you,
which makes truly rich, and adds no sorrow therewith.

Let the cloud of witnesses to the power and unutterable riches of pure religion,
prevail with you to submit to its holy influence; that you may rightly understand,
and diligently pursue, the things that belong to your peace here and hereafter.
Let the examples of the righteous in all generations, let their peaceful lives,
let their happy conclusion, triumphing over death, hell, and the grave,
in a lively and full assurance of faith; let the solemn importance of time and eternity,
excite you while it is yet day, and light is upon your tabernacles, to improve it:
that you may be numbered among the wise,
who shall shine as the brightness of the firmament,
and may be instrumental to turn many to righteousness, and be as stars forever and ever.

The negligent and careless, the stout-hearted, and they that are far from righteousness,
may receive instruction from the event of the like-minded in all generations.
Such have not escaped the righteous judgments of the Almighty,
who has sealed it as a certain truth: "`Verily there is a reward for the righteous;
verily he is a God that judges in the earth.`"

And now, dear Friends,
as in plainness I have endeavoured to communicate what
has freely opened to the several classes among you,
I would warn all to beware of putting their proper portion far from them;
but let each examine, "`Is it I? Is it I?`" And let not the iniquities of others,
which some may observe to be struck at, tend to fix any in a state of self-security;
for assuredly every one must suffer for his own transgression.
Nor let those close hints which are pointed to some of the foremost rank,
be made use of to invalidate the testimony of such,
whom the Lord has preserved as "`watchmen upon your walls.`"
I know and am thankful that he has a remnant among you, of all ranks,
whom he has preserved near unto himself;
to whom my soul is united in the tribulations and rejoicings of the gospel;
and unto whom a salutation reaches forth, and seems expressed in my heart thus;
Brethren and sisters, be of good cheer, "`be patient,
and hope to the end:`" for the hand of that God whom you serve,
is stretched out for your help; and if you abide faithful to him,
in his own time he will crown your sufferings with rejoicing.

Finally, dearly beloved, farewell; and may the grace of our Lord Jesus Christ,
the love of God, and the fellowship of the Holy Spirit, be with you all, Amen.

[.signed-section-closing]
I am your friend and sister in the Truth,

[.signed-section-signature]
Catherine Payton

[.signed-section-context-close]
Dudley, 10th of Tenth month, 1758.

--

My mind settled in quiet after this disappointment, but my body had suffered so much,
that a little rest seemed necessary to repair my health;
and I entertained a hope of being at and about home this winter;
but Divine wisdom pointed out work for me elsewhere,
and my mind was resigned to follow his directions.
I left home in the twelfth month, and went to the quarterly meeting at Warwick,
where through much painful labour of spirit,
I was favoured to discharge the duty required of me,
to the relief of my own spirit and the satisfaction of experienced Friends.
From that place I went through several meetings in Oxfordshire and Northamptonshire,
to the quarterly meeting at Northampton;
and turning back to the monthly meeting at Banbury,
visited some other meetings in Oxfordshire,
and attended the quarterly meeting held at Oxford.
In all these services the supporting protecting arm of Divine goodness was near,
whereby I was conducted in safety,
though not without considerable danger from the badness of the roads.
I had one very dangerous fall from my horse,
but was mercifully preserved from any fracture.

The quarterly meeting at Oxford was attended by many of the students,
who mostly behaved well,
although the doctrine of Truth ran very closely and pointedly to them.
That Divine power with which they were too much unacquainted, bound down their spirits.
May it be praised forever.

From Oxford, I passed through several meetings wherein Truth favoured,
pretty directly for London;
where I stayed about five weeks visiting the meetings of Friends,
and attending other services as I was favoured with strength.

Sometimes, through a fear of exceeding, I apprehend I fell short of my commission,
and a degree of suffering followed; which was however less painful to me,
than what would have arisen from errors on the other hand.
I laboured and suffered much in this city,
and the state of my health was poor during my stay in it;
but through infinite mercy I left it in the enjoyment of a good degree of peace,
and returned home in the second month, 1759,
to the mutual rejoicing of myself and friends.
My friend Ann Fothergill and several others
accompanied me to some meetings in my way home,
and took me in their carriages; whose affectionate care in my weak state of health,
I commemorate with thankfulness to the ever bounteous Author of all my mercies.

The day after I got home, my dear mother was taken ill,
as was my brother a few days after, and the state of my own health was weak,
and some peculiar exercise attended me.

Some libertine spirits endeavoured to invalidate my character and service,
for no other cause than what appeared to me to be my duty.
This was an extremely trying season, but I hope in the end it was profitable,
and tended to establish my mind in a patient suffering of reproach,
and to guard me with caution that I might not
administer occasion for it to the adversaries of Truth.

I attended to services about home, as liberty and strength were afforded,
and became better in my health: my mother also recovered bravely,
but my brother continued in a very weak state.
In the fourth month I was obliged to leave him and my dear mother,
being drawn to attend the circular yearly meeting for the four northern counties,
which was this year held at Stockport in Cheshire.
It was very large, and signally attended with the`' humbling power of Truth;
and the Lord was pleased to make use of me and several other of his servants:
for which my soul worshipped before Him who humbles and exalts,
and in his unsearchable wisdom, does all things well.
I returned home,
and found my dear mother and brother much in the same state as I left them.

In the fifth month I again left home,
intending to attend our quarterly meeting at Evesham,
and so proceed to the yearly meeting at London.

My brother was so much recovered as to accompany me to the quarterly meeting,
from which he intended to return home;
but on our first day`'s journey he was taken very ill.
This brought a fresh exercise upon me,
under which I petitioned the Almighty that he would be pleased
to direct me how to act for the relief of my own mind,
and the discharge of that duty which I owed to an affectionate brother;
on whose account I intreated, that if he might be relieved,
the way for it might be pointed out under this exercise I proceeded to Evesham,
my brother still accompanying me, though very weak.
After the service of the quarterly meeting was over, my way opened to Worcester;
whereto my brother was persuaded to accompany me, and to take the advice of a physician,
who strongly pressed his going to Bath.
Upon considering the urgency of his case,
some of my friends with myself judged it best for him to proceed there directly,
as returning home first would but weaken him the more:
so I wrote an account of our determination to my dear mother and sister,
who acquiesced therein.
I also informed my brother and sister Young of my afflicting situation,
and requested that one of them would accompany him; and Providence so ordered it,
that my sister came prepared for the journey the day after I sent for her.
The next day, being the first of the week, we were favoured together by Divine goodness;
and the following morning we parted in much affection; they proceeded to Bath,
and I was at liberty to pursue my journey.
This had been to me an extremely exercising season,
from the great fear I was under of erring on either hand;
but I record it to the praise of Infinite goodness, who, in this critical juncture,
directed me to act for the help of my dear brother;
to whom my endeavours were signally blessed with success,
the Bath waters being rendered serviceable to him.

From Worcester I went to Coventry; and in the way had a meeting at Henly in Arden,
Warwickshire, in which place Friends have a meeting-house,
but none of our Society remained.

At Coventry, I met my friend Samuel Fothergill, who having been long indisposed,
I was rejoiced to see that it appeared likely he
would be again restored to the service of Truth.
We went, together with many Friends from the North of England, directly to London:
where I was favoured with strength to attend pretty
closely to the service of the yearly meeting,
and had full satisfaction that I was there in the direction of Divine wisdom.

From London I went to the quarterly meeting at Colchester,
and in my way there attended the first-day meeting at Coggeshall, which was large,
and favoured with the Divine presence.

I left Colchester before the concluding meeting,
being pressed in my mind to reach the quarterly meeting at Banbury in Oxfordshire, which,
with very hard travelling, I accomplished: I had some meetings in the way,
and was comforted in administering a little relief to some
poor souls who appeared ready to faint under their exercises.
After the quarterly meeting at Banbury, I went to that at Northampton,
much in the cross to my own will, being very desirous to get home,
considering the state of our family,
and that my own health was affected with very hard travelling, ministerial labour,
and exercise of mind.
But I did not lose my reward,
for I was favoured with strength sufficient for the service required,
went from Northampton in much peace and thankfulness, and reached home in two days after:
where I was gladly received by my dear aged mother and sister,
but my brother was not yet returned from Bath.
In the last fifteen days before I got home, I attended twenty-three meetings,
besides other services, and travelled on horseback.

The concern I had for Ireland reviving, I left home in the eighth month,
and with very hard travelling was favoured to visit
most of the meetings in that nation this fall,
and returned to England soon after the half-year`'s meeting in the eleventh month.
A religious young woman, Sarah Christie, not in the ministry,
accompanied ine through the greater part of the journey in Ireland.
I landed from Ireland at Whitehaven,
and went through the meetings in some parts of Cumberland, the Bishopric of Durham,
and the east side of Yorkshire;
and turned to the quarterly meeting for Westmoreland in the first month, 1760.
The weather being extremely sharp this winter,
and my health but poor through hard travelling, and taking cold, I suffered much in body;
but gracious Providence supported and carried me through the service required,
to the admiration of myself and others.
The weakness of my constitution appeared inadequate to so great a fatigue;
but I experienced that hand which employed me, to be strength in weakness:
salvation and power be ascribed thereto forever!
It appears the following letter was written about this time.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Third month 15th, 1760.

[.salutation]
Dear Cousin,

Previous to the receipt of your letter,
I had intelligence both of your illness and recovery.
I am thankful to providence for your restoration to health.

I never yet could believe that you were wrong in entering into the connection;
and therefore I trust, that He who constituted the union, will bless it to you both.
I am glad to find you can so readily obey the pointings of the Divine hand;
and that your husband so freely resigns you to its disposing.
No doubt nature will feel in these separations,
but as your happiness does not consist in the gratification of earthly desires,
but in doing and permitting the will of God, your union in that life which can never end,
will be increased by absence.

Your concern for my preservation from the snares of an unwearied adversary,
I take notice of, with thankfulness, and hope to join you therein.
I dare not presume upon my standing; feeling daily my weakness, and having, with sorrow,
to observe the failures of some who have been eminently favoured:
but if a strong desire to be detached from the world,
and fixed in the station which Heaven allots me, recommends to its notice,
I may be allowed to hope I shall be supported in
the midst of discouragements which attend.

After many painful baptisms,
(to some of which you are no stranger) every prospect of what may be allotted me,
is removed; and I am content to remain blind to the future, until the hour come,
wherein every determination of Providence is revealed.

My constitution seems to be shaken by the many engagements which await me,
both at home and abroad; but I am content, if this assurance remain,
that I am about my heavenly Father`'s business.
Please to remember me affectionately to friend Hammond, and believe me to be,
dear cousin, in the sympathy of the gospel, both in suffering and rejoicing,
your friend and companion,

[.signed-section-signature]
Catherine Payton

--

In the beginning of fourth month my sister Ann was married to Thomas Summerfield,
of Bloxham, Oxfordshire; and my brother, who accompanied her to her new habitation,
returned home very ill;
yet I could not be easy to omit the attendance of the
Welsh yearly meeting held this year at Oswestry,
and my sister Young kindly stayed with him and my mother in my absence.
The meeting was very large;
and I had good reason to believe I was there in the counsel of the Almighty.
I returned home in a little more than a week, where I found my brother yet unwell;
nevertheless I thought it right to leave him again in a few days,
being engaged to attend the yearly meetings of Bristol and London: which I did,
taking some meetings in my way.

The yearly meeting at London was large and very satisfactory,
except from some disturbance which was given to Friends meetings,
by some disorderly persons not in unity with them.
My strength in the discharge of my duty was mercifully renewed,
and an enlargedness of heart experienced towards my brethren.
I had left home through much difficulty, but was thankful that I had pressed through it;
and on my return,
I had reason to believe that kind Providence had made
up the loss of my company to my mother and brother;
for I found her cheerful, and him in better health.

I came home in the sixth month,
and stayed at or near it until the latter end of the eighth,
labouring as I found ability in the service of Truth,
and endeavouring to discharge my duty in domestic cares:
a greater weight whereof than heretofore rested upon me since my sister`'s marriage;
through which, and my brother`'s continued indisposition,
my way in leaving home was straitened;
Yet I know not that any clear manifestation of duty was omitted;
although sometimes it was discharged with difficulty.

My brother being somewhat better,
I left home in order to visit Friends meetings in Derbyshire,
some of the dales of Yorkshire, and part of Lancashire.
I was favoured to accomplish this journey in forty-eight days,
travelling in that time about seven hundred miles, and attending fifty-two meetings,
besides other services, often in Friends`' families,
by which hard labour my spirits were much exhausted, yet was not my health so impaired,
but that I hoped with rest it might be restored.

In this journey I had some satisfactory service among people not professing with us;
and some in towns where no meetings were held.

At Bradford in Lancashire,
some unthinking people and children disturbed our
meeting almost through the whole time of our holding it;
but some sober inquiring people attended it,
with whom we had reason to hope the testimony of Truth had place.
After the meeting, we had a satisfactory opportunity with some of them,
at the house of one that had lately joined Friends in that place.
Some Friends accompanied me in this service, namely, Jonathan Raine and his wife,
of Crawshay Booth meeting, Matthew Meller of Manchester, and several others;
from whom I parted in gospel love.

On my return home the 16th of the tenth month,
I had the satisfaction to find my dear mother well,
and my brother better than he had been.
The night before I came there, I had a fall from my horse,
but through mercy received no hurt.

The 17th of the eleventh month, I set out to attend our quarterly meeting at Worcester,
which was large and mercifully favoured with the Divine presence.
From there I went to Leominster to visit my sister Young and her family;
and spent a few days with them and Friends there profitably.
In my way home, accompanied by several Friends from Leominster,
I had a large meeting at Ludlow, ui which town there was only one that professed with us.

Several sober people were among those who attended this meeting;
and Divine goodness was pleased to favour with
opening the Truths of the gospel unto them.
I left the town that night, at which I was not quite easy,
not knowing but if I had stayed,
some inquiring people might have sought an opportunity of conversation.

I returned home the 27th, and found my mother tolerably well, on whose account,
in this absence from her, I had been concerned, considering her advanced age.

In the twelfth month, I went to the quarterly meeting at Warwick,
and from there to visit my sister in Oxfordshire; with whom I spent a few days,
visited some meetings in the neighbourhood; and proceeded to Oxford.
Many of the students and others not professing with us, came to the meeting;
towards whom Divine Wisdom was pleased to manifest his regard,
and some of them behaved soberly.
It was the time of the quarterly meeting.
In my return home, I attended at Long Compton the funeral of a religious young woman,
with whom I had been acquainted.
It proved a strengthening season in Divine love, which freely flowed towards the people.

From Long Compton I went to Chipping-Norton, Evesham, and Worcester,
stayed a few days among Friends there, and returned home through Evesham and Alcester.

I stayed about home until the 21st of the third month, 1761,
when I went to the quarterly meeting at Birmingham;
which was comfortable in a sense of the continued regard of lieaven;
but sorrowful in the apparent declension of some
professing with us from the life of Truth.

From Birmingham I proceeded to the quarterly
meeting for Nottinghamshire held at Mansfield,
which was small, few Friends residing in that county, I laboured among them in love,
and with strong desires for their help; and left them in a degree of peace,
though not without a doubt of having been rather short in discharging my duty.

From Mansfield, I went to Chesterfield, and had a meeting there,
to which came several from other meetings,
and we were favoured together in the Divine presence.
I then proceeded through some meetings in Yorkshire,
wherein I was strengthened to minister,
I hope to the satisfaction and comfort of honest-hearted Friends,
and to the relief of my own spirit.
I came to Lancaster the 9th of the fourth month,
in order to attend the quarterly meeting there.
Thus far on the journey I had travelled very hard,
and the day before I came to Lancaster,
having met with a very dangerous fall from my horse, whereby I hurt one my of arms,
so that I was unable to help myself, and was otherwise hurt,
it was hard for me to travel;
yet I was enabled to proceed forward the next afternoon in a chaise to Kendal;
and having attended the quarterly meeting there, proceeded to Appleby,
to the yearly meeting for the four northern counties,
which began the 12th. I carried my arm in a sling,
but in this time of weakness kind Providence furnished
me with a suitable companion to assist me,
namely, Christiana Hird of Yorkshire, of whose tender care and affectionate services,
I retain a grateful sense.

The yearly meeting at Appleby was attended by
many sober people from the adjacent country,
as well as by a large number of the inhabitants of the town;
and many of them were considerably affected by the testimony of Truth;
whereto they had been strangers.
Many had imbibed disagreeable sentiments respecting Friends and their principles;
but the Lord was pleased so to manifest his power among them,
that their prejudices were removed,
and a confession obtained to the truths which were freely preached among them.

Friends left the town rejoicing in the heavenly Father`'s love and goodness,
in thus favouring us, and exalting the testimony of Truth,
in a place wherein some of our worthy Friends in the beginning of our being a people,
had suffered deeply.
The 15th, Samuel Fothergill and myself had a meeting at Kirby Steven,
which was large and solid, many seeking people around the country attending it;
and the Lord was pleased to cause the gospel trumpet to
be sounded clearly and powerfully among them:
glory be to his Name forever!
I went accompanied by Christiana Hird,
with the Friends from Wenslydale into that quarter; had a meeting at Haws,
and the ensuing first-day attended the general meeting at Aysgarth, which was very large.
A light set of people frequently attending at that time of the year:
but the power of Truth was measurably over their spirits,
and I left the place in a good degree of peace.
I proceeded in visiting the meetings in this part of Yorkshire,
and having a view of going almost directly from that county,
to the yearly meeting at London,
and being desirous of getting clear of as many meetings therein as I could,
I continued to travel hard among the dales.
But my strength being much exhausted,
and some painful effects of my late fall continuing,
when I came to the house of my friend William Hird,
at Woodhouse (father to my kind companion), I rested for a few days,
and was treated with that tenderness which the state of my health required.

From hence, I went to Gildersome meeting, where I parted from Christiana Hird,
in love and sympathy; and went through several meetings in Yorkshire, to Nottingham.
I stayed at Nottingham over first-day, and attended two meetings there.
I was weak and much affected with a hoarseness,
yet had some service among Friends there, though not fully to the relief of my mind.

I left Nottingham on second-day, and reached London the 7th of the fifth month.
I was favoured with a good degree of peace,
and thankfulness to that good Hand which had
hitherto conducted and supported me in weakness.

The yearly meeting was large, and I hope profitable; although I did not think,
in the general, that instrumental ministry rose so high,
as it had done in some of those annual solemnities:
but Friends were comforted in the immediate sense of the continuance of Divine favour,
under which they separated; some perhaps, to meet no more in time.
Our friend Joseph White, from America,
having paid a religious visit to Friends in this nation, and being about to return home,
had a certificate from Friends at this meeting
of their unity with his services while here;
and John Stephenson and Robert Proud being under an engagement
of mind to visit Friends on the continent of America,
had certificates for that end.

My spirit rejoiced that I was enabled to attend this meeting;
and indeed I have seldom or ever attended the yearly meetings in London,
without peculiar edification,
although sometimes sufferings from various causes have fallen to my lot:
and I am persuaded that if Friends more generally gave
themselves up to attend that solemnity;
and when there, abode under the seasoning virtue of Truth,
they would be better qualified to labour in
their several stations and places of residence:
the weight of service devolving upon them there, would be brought home with them,
and a more fervent care would remain for maintaining
our Christian testimony in its various branches,
and stretching the line of discipline over such among us who walk disorderly.

The week after the yearly meeting I went to Plaistow,
and rested a few days with my friend John Hayward; and being a little recruited,
I proceeded, though in diffidence and fear (being often low in body,
as well as pressed with the weight of the service appointed me),
to the yearly meetings of Colchester, Woodbridge, and Norwich: in all of which,
through the strengthening hand of Divine mercy, I had good service.

From Norwich I passed through some meetings in Lincolnshire
and Yorkshire to the quarterly meeting at York,
which was at this time attended by many Friends from the several quarters of it;
and some Friends under appointment from the yearly meeting at London,
to visit monthly and quarterly meetings of Friends, were there; and I hope,
were serviceable, in inquiring into the general state of Friends,
exciting them to various duties, and endeavouring to strengthen the hedge of discipline.

From this meeting I proceeded, accompanied by Rachel Wilson and Margaret Raine,
to Leeds and Bradford,
and so to a large general meeting held annually in a barn at Bingley.
It was in a good degree satisfactory, many gospel Truths being opened to the people;
who behaved soberly, and many of them seemed well affected towards Friends.
After this meeting I proceeded towards the quarterly meeting at Lancaster,
and from that place,
accompanied by my friends Jonathan Raine and wife and Alexander Parkinson,
I went to Turton near Bolton, where several young men and others were under convincement.
Several Friends met us here,
and we had a favoured meeting with them and many of their neighbours;
rejoicing in the hope that the Shepherd of Israel would
gather to himself a people in that country.

There are none under our name near them,
which rendered the breaking forth of Truth among them a more
signal instance of the immediate efficacy of its Divine power.
May they be preserved humble, and dependent on that Hand, which alone can build up,
and "`establish on the most holy faith.`"

From Turton I went with my friends Jonathan
Raine and wife to their house near Rossendale,
and attended a large general meeting there the next day;
and proceeded to Manchester on second-day, and had a meeting there that evening.
On third-day, accompanied by two men Friends, I travelled hard;
and in the evening we missed our way over a moor,
which rendered it late in the night when we came to John Draycoat`'s in Derbyshire.
I had a fall from my mare, through her missing her step upon a narrow causeway,
but through mercy was preserved from hurt.
Next day I had a meeting at Furnace, and afterwards rode to Burton upon Trent,
and the ensuing day to Polesworth,
in order to attend the marriage of my cousins John Wilkins and Elizabeth Lythall,
which was solemnized at Badsley the next day,
and we were favoured together with the Lord`'s presence: blessed be his holy name!
The next day, being the 20th of the seventh month I reached home,
where I found my dear mother as well as could be expected for her age,
but my brother yet poorly.
I had now at several times visited Friends in Yorkshire pretty generally;
and had considerable service among people not professing with them.

After this journey my mind settled in peace and thankfulness,
having to look back upon it with deep gratitude to the Divine hand,
whereby I had been conducted, supported and encouraged to press forward,
although under considerable bodily weakness,
and some fears on account of the situation of my dear mother, etc.

But as my eye was preserved single to the Lord`'s service,
he cared lor those I had left for his name`'s sake,
and brought me home in a better state of health than I had left it,
notwithstanding I had travelled and laboured exceedingly hard;
having in fifteen weeks attended one hundred and seventeen meetings,
and travelled about one thousand two hundred and thirty miles;
nearly the whole on horseback.

The beginning of the eighth month, I attended the circular yearly meeting,
which was held at Bromyard in Herefordshire.
It was not so large, either of Friends or people of other societies,
as of late years had been usual,
nor did the life of Truth in the ministry rise to the height I have known it; yet,
upon the whole, Friends had cause to be thankful for the opportunity.

[.offset]
About this time she wrote the following Epistle:

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
To the Quarterly Men`'s meeting of Friends of +++________+++,

[.salutation]
Dear Friends,

It having lately been my lot to pass through your quarter,
and with sorrow to observe the declining state of the church therein,
I find my mind engaged to write a few lines to
you who may be accounted its ruling members;
to advise,
that you be careful to fill up the station of governors in all humility and honesty,
acquitting yourselves like men concerned for the cause of God.
And in order that each may find his hands made strong for the work,
let first a strict scrutiny be made into your own conduct,
to see how far you are purged from the abominations which are committed: for,
except those who are rulers in Israel, support their testimony by a circumspect conduct,
it seems to me impossible they should rule well.
For, not preserving a sense of the necessity of an entire purity subsisting in the church,
they will be apt to admit of things inconsistent with
the nature of that holy principle we profess;
and wink at, instead of reproving, the conduct of backsliders.
And, indeed, I see no right that a man who breaks the law himself,
has to sit in the seat of judgment.

He may plead the example of the Scribes and Pharisees,
but no Christian precept countenances such a practice:
for "`except our righteousness exceed theirs, we shall in no wise enter the kingdom.`"
And I think it may not be amiss,
in order to evince whether there be any resemblance between us and them,
to examine what their righteousness was.
It was only a bare external righteousness,
put or kept on with a base hypocritical design, to impose upon the people.
Spiritual pride was cloked under it.

They loved the places of chief presidency in the synagogues,
etc. and to be called of men, "`Rabbi;`" oppressed the distressed,
and neglected the weightiest matters of the`' law, namely, justice, mercy, and truth,
without which no right government can ever be administered.

They were not possessed of holiness, though they made "`broad their phylacteries,
and enlarged the borders of their garments.`"
How different to this is the character of a bishop^
footnote:[Or, as it may be translated, overseer.]
given by the apostle: "`He must be blameless, as the steward of God; not self-willed,
not soon angry, not given to wine, no striker, not given to filthy lucre;
but a lover of hospitality, a lover of good men, sober, just, holy, temperate;
holding forth the faithful word as he has been taught,
that he may be able by sound doctrine both to exhort and convince the gainsayers.`"

An excellent catalogue of necessary qualifications!
May both you and I covet to obtain them.
It seems to me that a great regulation is lacking among us,
and judgment must begin as at the sanctuary, before it can go on rightly.

The camp is shamefully defiled, and few fit to minister judgment in wisdom,
to the transgressors; which is very much lacking,
for "`weakness has reached to the head and the heart,`"
and insensibility seized many of the members.

Arise and shake yourselves, lest you perish with the multitude;
and being partakers of the sins of Babylon, you be also partakers in her plagues;
for I verily believe,
the Lord is on his way to try the foundations of the professors of his Truth,
that their deeds may be made manifest, whether they are wrought in God or not;
and the cause of his suffering seed will be espoused and pleaded,
and their wrongs redressed.

Alas! my friends, it will not do for us to have been once called and anointed of God.
Except we dwell under the teachings of that anointing,
and wait for renewed baptism to fit us for further service, we shall become dwarfish,
dry, and formal; and though to an injudicious eye we may appear as flourishing trees;
upon examination by a wise observer, good fruit will not be found upon us,
such as that its flavour will demonstrate that the tree has
its nourishment from the Eternal Fountain of life and wisdom.

Have a care, lest the world cast a mist before your eyes,
and hinder your keeping a sight of that transcendent excellency which is in the Truth;
which once engaged some of you to follow it,
with sincere desires to know your spirits leavened into its pure nature.
Remember the day of your espousals, and also, that, as says the apostle,
"`If any man drawback, my soul shall have no pleasure in him.`"

Let none judge that these lines proceed from a self-sufficiency in me;
for I think that I retain a just sense of my weakness,
and unfitness as a woman for such a service;
but I trust some of you know that the wind blows when and where it wishes.

I am, with the salutation of unfeigned love to the true seed of God among you,
sincerely desiring their preservation, and that the unfaithful may be warned in time,
and turn to the Lord in the day of his mercy, your friend and sister in the Truth,

[.signed-section-signature]
Catherine Payton

[.signed-section-context-close]
27th of 8th month, 1761.

--

N+++.+++ B. This Epistle may appear close and sharp, considering unto whom it was directed;
but there was sorrowful cause for it, in some individuals.

From this meeting I went to spend a day or two with my dear sister Young at Leominster,
which I esteemed a great favour, as it was the last time we spent together,
except near her last moments.
She was seized in the tenth month following with an indisposition,
which terminated in a violent inflammatory fever.

Her husband was then in the west of England, in company with some Friends,
on a religious visit to the monthly and quarterly
meetings of Friends in that part of the nation.
A messenger being sent to inform us of her illness, I went to her;
and was favoured to find her so sensible as to inform me that she was very easy in mind:
soon after which she grew delirious, and her senses were never more quite clear;
yet she once intimated that she was quiet, and hoped she had a quiet habitation.

She was a truly valuable woman, and doubtless her spirit entered into rest.
She died at the age of forty-five, after a life attended with various trials.
The loss to her family, her other relations, friends and neighbours, was great;
and the sorrow for it among all who were acquainted with her was general;
yet under a sense that our loss was her great gain,
it was mixed with joy in the hearts of her nearest relations and friends.

She left three children, and her sorrowful and very affectionate husband; who,
after he had information of her dangerous state, travelled hard to get home,
but did not reach it until after her corpse was interred.
My brother stayed at Leominster until he came there,
and I returned home to my dear mother and my sister`'s eldest daughter,
who was then at Dudley, a thoughtful child of about eleven years of age,
who had a very great affection for her mother.

I found them full as well as I expected,
considering my mother`'s great love for my sister,
who had been an extraordinary child to her; steadily sympathizing with,
and assisting her in her afflictions,
when she had no other child that was so capable of doing it.
But she was favoured with signal resignation to the Divine will,
which is doubtless right in taking away, as well as in giving.

My spirits had been supported beyond my expectation through this trial,
although my health appeared shaken by the fatigue attending it;
yet in less than two weeks, I set out for Bloxham to attend my sister Summerfield,
who was now my only surviving sister.
I attended Warwick meeting in my way;
and in the evening appointed one for the neighbours, which was large,
and crowned with Divine life and power, for which I was truly thankful.

After about two weeks stay I went for London,
having before I left home a certificate to visit Friends in that city.
I had several meetings in my way there among people not professing with us,
to satisfaction.
I stayed rather more than a month in London, and through diligent labour,
and considerable travail of spirit, left it easy in mind,
and returned home by my sister`'s.

The day I left her house the wind was very high.
I rode double, and when we came to the high uninclosed field-lands,
nearly upon a level with the summit of Edge hill, it was so extremely boisterous,
that myself and the man who rode before me, concluded it safest to alight; which we did,
under shelter of a short thorn-hedge, probably planted to afford shelter to sheep.
We saw a village, but had to cross the field to it.
The man held the horse by one hand, and I held by his other arm;
but the wind was so violently strong, that he rather dragged than led me,
for I stooped very low, being unable to stand against it.
I think it rained also while we crossed the field.
We got to a poor house of entertainment,
the covering of a building belonging to which was stripped off a little before we came;
and we stayed in it, not without fear, until the violence of the wind abated;
which it did in the afternoon, and we reached Eatington the same night.
I think this was the wind of which it was said,
that none had been so high since Eddystone lighthouse was blown down;
and our getting through it without hurt appeared providential.
It was a hurricane in the morning, yet it was tolerably calm in the evening.

I got home the 15th of first month, 1762, in a better state of health than I left it,
and was comforted to find our family tolerably well;
and I had great cause for thankfulness,
for the many mercies and preservations vouchsafed in this journey.

In the spring of this year I attended the northern and Welch yearly meetings;
the first held at Bolton in Lancashire, and that for Wales at Bala in Menonethshire.
That at Bolton was very large, and attended by many valuable ministers and Friends,
and a great number of sober inquiring people of other societies;
among whom the gospel-trumpet was sounded in Divine authority,
to the comfort of faithful Friends, and I hope,
to the instruction and awakening of many souls.
In my way from Bolton to Bala, in company with my friend Samuel Fothergill,
I attended the meeting at Chester on the first-day morning;
whereto many soberly behaved people of the town came,
and we were favoured with a comfortable tendering opportunity together.
From Chester we proceeded to Bala, in company with Isabella Middleton,
a ministering Friend from Ireland, and overtook Rachel Wilson and Christiana Hird,
before we got there.

The meeting at Bala was large, considering the part of the country it was held in:
the people behaved soberly,
and many of them were affected by the heart-tendering power of Truth.
We had a comfortable opportunity with a few that came in love to bid us farewell;
and left the place,
in full assurance of the extendings of Divine love to
the inhabitants of this poor part of the nation,
and thankfulness that we were accounted worthy to preach the gospel to them.
I returned home by Coalbrookdale,
and on the first-day was at a very large meeting at the New Dale,
wherein the Lord`'s power was exalted: blessed be his name forever!
I reached home the 4th of the fifth month, and found my mother and brother well as usual,
but my brother Henry, my father`'s son by a former wife, unwell,
with a disorder in his right leg; which terminated in a mortification,
and in something more than eight weeks his leg was taken off.
Our affliction through this circumstance was considerable;
for besides the care for his natural life, which was imminently in danger,
our concern for his immortal soul was great.
For having addicted himself to pleasure and to
the gratification of his natural appetites,
he had lost the simplicity of his education;
and because he would indulge himself in liberties which
he knew were inconsistent with the profession of Truth,
he threw it off; saying, he would not retain the name and be a reproach to the people.
He sometimes went to the church of England, not, as he said, from principle,
but because he would go somewhere.

When a youth, he was much humbled under the visitation of Divine love;
but when he arrived to mature age, he was drawn aside by vain company.
In this affliction he was favoured with a renewed visitation of heavenly favour;
under which he lamented his loss and fall, and remarked,
"`that it had been through keeping company,
and not that which is accounted the worst of company neither.`"
He had a long time allowed him to repent,
and in the forepart of his illness was penitent and much exercised in mind;
but being flattered with the hopes of life after his leg was cut off,
his thoughts appeared then to be too much occupied with its prospects-,
although not without some proposition of a reformation of conduct,
if his health should be restored.

In this situation I was obliged to leave him,
being engaged to attend the circular yearly meeting, which was held this year at Exeter.
My sister supplied my place in the family, and I went pretty directly to it,
attending the quarterly meeting at Gloucester, and two other meetings, in my way,
the Lord`'s power accompanying me.

The meeting at Exeter was much less than some of the like kind had been;
but was attended by some sober people, and by some high professors of religion,
whose foundations were struck at in the power of Truth,
the testimony whereof was measurably exalted.
The state of the members of our own Society was ministered to;
in some instances it was lamentable,
and tended greatly to lessen the weight of the testimony of Truth,
which had been at this time borne in the demonstration of its own spirit.

I proceeded from Exeter to the quarterly meeting in Somersetshire,
which was eminently crowned with Divine favour;
and I parted from Friends there in the comfortable sense of gospel fellowship,
and returned to Bristol, having several large and satisfactory meetings in the way there.

I spent a few days in Bristol, I hope profitably,
having renewed cause to believe that the Divine life was revived in some in that city,
although too many had fallen asleep as in the lap of this world.

From Bristol I went to the quarterly meeting for Herefordshire, held at Ross,
and so to Leominster; where I spent more than a week in my brother Young`'s family,
not idly, but caring for it;
and returned home to the mutual satisfaction of myself and my relations there.

I found my dear mother and brother tolerably well,
and my poor brother Henry appeared in some respects better, yet at times so languid,
that I doubted his continuing long in time.
My fears proved well founded, for his deplorable disorder seized his other foot,
and on the 15th of the twelfth month, 1762, he died;
having endured a long scene of inexpressible pain and affliction.
Agreeably to his own desire, his corpse was interred in Friends`' burying ground.

He was endowed with a good understanding and an engaging natural disposition,
and his person and manners were superior to many.
He was in his fifty-seventh year.

I think it worthy of commemoration,
that some time before he was seized with the disorder which terminated his life,
I had been earnestly solicitous that the Lord would bring him to a
sense of his apostatized state before he was taken out of time;
and constrain him to condemn that libertine spirit wherein he had so long indulged;
that his associates might not have cause so to triumph
as to invalidate the Christian testimonies.
These my desires were signally answered.
