== Chapter IX

[.chapter-synopsis]
* Visits to Gloucestershire and Somersetshire
* Attends the yearly meeting in London
* Religious engagements on the way home
* Visits meetings in Warwickshire, Worcesterhire, Shropshire, and Gloucestershire
* Attends several circular yearly meetings
* Meetings in Bedfordshire, and Devonshire
* Yearly meeting in London
* At Truro in Cornwall
* Remarks on Oratorios
* Death of her husband

For some time I had entertained a prospect of visiting
some meetings in Somersetshire and Gloucestershire,
and paying a particular visit to the families of Friends in Herefordshire.
I left home to accomplish this service, accompanied by my dear husband;
and on the 13th of the third month 1779, we met our friend Lydia Hawksworth,
who was concerned to accompany me therein, at Wellington.
The 14th, being the first of the week, we attended Friends' meeting at Spiceland;
and in the evening had a select opportunity with Friends at Wellington,
My husband then proceeded to Bristol on business: we industriously pursued our concern,
visiting many meetings that week; and on the 21st, first-day,
were met by my husband and my brother James Payton, at Puddimore meeting.
We went the same evening to Compton in Dorsetshire,
to visit our valuable friends Jonah Thomson and his son; spent the next day with them;
and in the evening had a meeting with their scholars
and others of the family and many of the neighbours,
in the school-room, which was a favoured season;
and we proceeded to Sherborn meeting on the 24th. Here my husband and brother left us,
and next morning we proceeded to Hollowtrow, had a meeting there in the afternoon,
went the same night to Pensford, next day to a meeting at Bolton,
from there to Chew Magna, and were at the first-day meeting held there on the 28th.

The 30th we had a meeting at Portshead, and crossed the Avon at Pill,
were at King's Weston meeting on the 31st;
from there went to those at Olveston and Thornbury, and from there to Worcester.
In these meetings in the counties of Somerset and Gloucester,
I was enabled to discharge my duty to my own humbling admiration,
and the edification of many who attended them.

The quarterly meeting for the county of Worcester being held at Worcester,
we attended it, and also two meetings with Friends of that city;
and on the 7th of the fourth month, went to Bramyard in Herefordshire,
where we were met by my brother Young and Thomas Waring of Leominster;
who united with us in the intended visit to the families of Friends in that county,
which we began at this place.
In this laborious and important service we were Divinely assisted.
My dear companion had a considerable and very acceptable share therein;
which was generally the case in family visits, and private opportunities,
although she was frequently silent in public meetings.
She was peculiarly gifted for these private services,
and when she did appear in public ministry, her service therein was very edifying,
and acceptable to Friends.
Having an intention to return to Bristol before the yearly meeting was held there,
we pursued this service with diligence, and on the 24th of the fourth month,
we paid our last visit.

My brother Young had accompanied us through the visit,
but Thomas Waring left us at Almelly on the 18th,
their company was acceptable and strengthening to us.

On the 25th (being first-day) we had a meeting at Shire Newton in Monmouthshire,
which was attended by many of the Welch people, and the few Friends in the neighbourhood,
and, I believe was an acceptable opportunity to them.
In the evening we had a meeting with Mary Powel of Chepstow and some others.
She was the only member of our Society residing in that town;
where a meeting of Friends was never settled.
Next morning, we proceeded to the New Passage,
but the boat being gone a few minutes before we reached it,
we were detained until the evening tide; but, through Divine mercy, we got safely over,
and reached Bristol about ten o'clock the same night.

My husband staid with me at Bristol until the yearly meeting there was ended,
which was large arid attended by many ministering Friends of this nation and America;
yet a large share of the public labour in the ministry fell to my lot,
at which I believe my brethren and sisters rejoiced;
for I was assisted to minister in the demonstration of the Spirit and with power;
and returned the praise due to Him who exalts and abases his servants,
as he knows is most conducive to his honour, and to their preservation.

I staid at Bristol to attend the marriage of two Friends with whom I was acquainted;
and then, accompanied by my husband, set out for London.

We attended a few meetings in our way,
and reached London about a week before the yearly meeting,
myself much spent with hard labour and exercise.
I was enabled to attend the meetings in course, during the sitting of the yearly meeting;
and after its conclusion, with my husband and friend Lydia Hawksworth,
proceeded to Calne in Wiltshire,
attended the meeting of Friends there in the morning of the first-day,
and had a public meeting at Chippenham, appointed to begin at six in the evening.

The meeting was large, and was a favoured opportunity;
the people not professing with us behaved with becoming seriousness,
and some of them were visibly affected.
It was long in gathering, which might occasion its being late before it concluded;
yet my inclination being strong to go to Melksham that night, we proceeded there.
Before we reached it, the family where we were to lodge were in bed,
but the master of it, my relation Thomas Fowler,
came down and received us with great kindness.

Next day my dear husband left us and went to Bristol and Swansea.
I had a view of visiting some places in the neighbourhood;
but my strength was exhausted too much to allow me to engage immediately upon service.
In the next night I was much indisposed, and in the morning sent for an apothecary,
who thought my disorder was the effects of a cold; but it proved a fever, which,
with the weakness attendant thereon,
confined me for some weeks with these my affectionate relations;
whose tender care and generous treatment of me, both now and at all times,
when my lot was cast under their hospitable roof, demands my grateful acknowledgement,
both of their kindness, and that of my heavenly Father;
whose mercy was at this time signally discovered in upholding my
enfeebled frame until I came to Friends by whom I was so well nursed,
and with whom my mind was so easy.
My affectionate companion continued also with me,
and tenderly assisted me until my fever went off.
My husband returned to me; but his business calling him home,
and my strength not being equal to so long a journey,
he left me to the care of my friends.
As my strength returned, my prospect of some service in the neighbourhood returned also,
and I ventured to the meeting at Bradford upon a first-day;
but my principal concern was to hold a public meeting at Trowbridge,
in which town no one resided who professed with Friends.
I went in weakness, accompanied by several Friends,
and appeared to a Friend of London who casually met me there so emaciated,
that when she returned home, she reported amongst Friends there,
that it appeared to her my labours were nearly accomplished.
We held a meeting in a large dining-room at the inn,
which was attended by many attentive well-behaved people;
and the testimony of Truth was exalted amongst them,
to the praise of Him who strengthens for every service in which he engages his servants.
I was that day made strong to declare of his wisdom and mercy,
and preach the doctrines of his Son Jesus Christ; and returned to Melksham in peace,
and with thankfulness for the assistance afforded in that memorable day's labour.
After this meeting, I was easy to return home; so,
accompanied by my companion and a Friend of Melksham, I left that place;
and got to a meeting held at Grenton in Somersetshire on first-day,
which was attended by many of the country people,
both of that place and its neighbourhood) and was a favoured opportunity.

There being a funeral at the public burying ground on the preceding evening,
our friends Beaven, with whom we lodged, gave notice, at my request,
of the meeting to the people who attended it, which occasioned it to be the larger.

In the afternoon we had a private opportunity with the Friends,
and next day proceeded to Wellington, and from there towards Oakhampton;
where we met my dear husband, to our mutual rejoicing and thankfulness,
with whom we proceeded to our quarterly meeting held at Looe, and from there home,
where we came in the early part of the seventh month.
As I had not preserved any minutes of my movements since the yearly meeting at London,
I could not insert dates.

The state of my health required rest, and I was favoured with it;
and having the company of my dear friend Hawksworth,
her attention was turned to assist in restoring my strength;
and as she also was in need of rest,
I hope she gained some advantage by accompanying me home;
although our quiet was disturbed in the eighth month,
by an alarm of the French and Spanish fleets being off`" Falmouth Harbour.

What their design was could not be known, but there they lay for some days,
the wind not permitting them to go up the channel; and as they did not attempt to land,
it was conjectured that their hostile views were towards Plymouth,
and the King's dock near that place.
Soon after they had sailed up the Channel, being in our week-day meeting,
with my mind retired to the Lord, under an exercise on account of the intended mischief,
it run through it, "`He sent forth lightnings and scattered them.`"
I think, as we returned home from meeting, the wind was rising, the sky soon lowered,
and a terrible storm gathered and discharged itself, with fierce lightning,
tremendous thunder, and violent rain;
which continued more or less through great part of the night,
and indeed the thunder until the next evening.
The fleets were, by the time the storm began, got near Plymouth;
and we heard that the commanders had deliberated about the business they had in view;
but the Lord,
who holds "`the winds in his fists,`" discharged
against them his terrible artillery so powerfully,
as to prevent their designs,
and obliged them to sheer off from our coasts in a shattered state.
O! what frequent occasions have Britons to "`praise the Lord
for his mercy,`" and wonderful interference in their favour!
but alas! though in words they acknowledge it,
the generality of them are not concerned to make those returns which he is calling for;
but continue in a course of conduct, and disposition of mind,
which dares his righteous judgments:
these will one day be poured forth upon the people of
this highly favoured but ungrateful nation,
unless they repent and turn from their manifold iniquity.

I choose here to mention a remark of a sensible inhabitant of the town of Helston,
upon this signal and memorable storm, so favourable to this nation.
He told me, that seeing it gathering, and having people at work on his harvest,
he hastened to direct their labours.
As he went, he made his observation on the wind,
etc. and I think he said that such was the confusion of the elements,
that he could not say from what point the wind blew; and he said in his mind,
This is no natural storm:' and indeed it proved to be signally providential,
and as such worthy of commemoration;
as is also a circumstance which happened in the town of Falmouth.
As soon as government had intelligence of the enemies lying in great force off that port,
ammunition was hastened for the garrison there.
The wagons halted in the market place, to which the sea comes up,
from where the inhabitants fetch sea-water for some uses.

A woman coming up with a bucket of water at the instant the ammunition wagons stopped,
observed that the axletree of one of them was on fire, and dashed her water upon it.
As the fire was on the side next the sea, if she had not discovered it,
it might have increased until it had blown up its dangerous loading;
and there being also a quantity of gun-powder in that part of the town,
the houses might have been much damaged, and some lives lost.

My dear friend Hawksworth left me in the latter end of this month, or early in the next;
and I was allowed to stay at and about home for the remainder of this year.

In the early part of the year 1780, I attended several large meetings in Cornwall,
held on account of marriages or funerals,
which were signally honoured with the Divine presence.
I also was at our quarterly meeting at Falmouth;
and on the 3rd of the fifth month my husband and I left
home to attend our annual solemnity in London.
In our way we had meetings at several places,
and called at Compton to pay our last visit to our beloved friend Jonah Thomson,
who was near the close of an honourable life.
We found his mind awfully collected, and waiting for his release from a pained body,
in certain hope of his spirit's being admitted into the saints' rest,
after having laboured many years in the work of the ministry.

In the younger part of my life, he had conducted himself towards me as a tender father;
and in my more advanced years, as an affectionate friend.
He had also a sincere regard to my husband, and as our affection was mutual,
our interview and farewell were affecting.

The yearly meeting at London was large and favoured by
the heavenly Master of the assemblies of his servants.
From London, we went, accompanied by our friend Lydia Hawksworth,
to a general meeting held annually at Weston in Buckinghamshire, and so to High Wycombe.
My husband returned to London, and Lydia Hawksworth and myself proceeded to Reading,
where we met a committee, who, by appointment of the yearly meeting,
were going to visit the meetings for discipline in Bristol.
We attended several meetings with them in our way to that city,
where we arrived on the 1st of the sixth month.

Before I left Cornwall, I had informed Friends of our monthly meeting,
that I was under an engagement of duty to attend the
quarterly meeting for Oxfordshire to be held at Banbury,
and to visit some meetings in Warwickshire, Worcestershire, Shropshire,
and Gloucestershire, also to attend the' circular yearly meeting to be held at Hereford;
wherewith they concurred.
And my friend Lydia Hawksworth being given up to accompany me,
I staid at and in the neighbourhood of Bristol, until the seventh month,
to afford her time to prepare for the journey.
We went to Worcester, and attended the meetings held there on the first and third days:
and from there proceeded to Evesham and Alcester.
Several of the town's people came to the meetings at Alcester,
and I was favoured to preach the everlasting gospel to them.
The same evening, we reached Eatington, were at the meeting there on the first-day,
whereto many Friends from an adjacent meeting came, at my request,
and I hope it was a profitable opportunity: we proceeded that evening to Banbury,
and to the house of Edward Stone, whose wife was nearly related to me,
and with her husband received and entertained us with affectionate kindness.

The quarterly meeting held at this place was a large and favoured solemnity;
and many people not professing with us attended the meetings,
to whom the gospel of life and salvation was preached
in the demonstration of the Divine spirit.
In the course of the meetings, a dangerous accident befel me.
In the womens' meeting-room was a gallery for ministering Friends, wherein my companion,
myself, and other Friends were seated.
Upon my rising to step farther, to make room for more, the floor gave way,
and I sunk with it; but I received but little hurt,
which might be esteemed a singular mercy, considering how I was situated in the fall.
Friends ought to be careful in examining these elevated seats in old meeting-houses.
This was not the only time I have been in danger through the neglect of it.

From Banbury we went to a meeting at Redway,
and to Warwick the 28th. We staid here with my dear sister Summerfield,
until the 4th of the eighth month, when we went to Shipton,
where the quarterly meeting for Worcestershire was held the next day,
at which were many Friends of that county,
who rejoiced to see me,' and we were favoured together in the Divine presence.
On the 6th, we had a meeting at Long Compton, which, although small,
was a favoured season.
The same evening we had a meeting at Tredington
at the house of our friend William Lambly,
whose family was the only one of Friends residing in that village.
His neighbours attended, but appeared so low in the knowledge of Divine truths,
that it was difficult to minister to them so as to be understood.

On the 7th, we returned to Warwick, and the 9th,
being the first of the week (accompanied by my sister),
attended a large meeting of Friends and other professors of religion,
held annually at Birkswell; and on the same evening went to Coventry.
We had a meeting there the 11th,
and in the remainder of the week had meetings at
several places amongst Friends of Warwickshire;
and on first-day, the 16th, were at a large meeting which is held annually at Atherston.
There I met many Friends from several counties,
amongst whom I had laboured and been conversant before my settling in Cornwall;
and we were favoured together with the merciful visitation of Divine love and life.
The 17th, we attended a monthly meeting for discipline held at Hartshill.
Here I left my sister,
who was so much indisposed as not to be able to accompany us
to the before-mentioned meeting at Atherston.

On the 18th, we went to the neighbourhood of Birmingham.
We attended the week-day meetings there in this week, and also those on the first-day,
I hope to the edification of many present, and visited several of our friends;
and on the 24th, were at a monthly meeting for discipline at Dudley.
The 25th, we had a large and good meeting at Wolverhampton;
and from there we went to Coalbrookdale, had a meeting there,
and proceeding to the meetings of Shrewsbury, and the Bank,
came back to Coalbrookdale meeting, first-day, the 29th.

The Lord's power and presence were evidently with us in our services in this quarter;
and after a solemn opportunity in our friend Abiah Darby's family,
at which some other Friends were present, we left it and returned to Dudley;
and I visited Friends in that quarter no more.
We staid with my dear brother until after the ensuing first-day,
when the meetings were large; as has been usual, when I have visited that place,
since my removal from it; my old neighbours pressing to the meetings,
more generally than when I resided amongst them: and many times has the Divine power,
and the testimony of Truth, been exalted; to the praise thereof,
and the convincement of many of the truth of the doctrine preached,
although but few have so "`believed unto righteousness,`"
as to make a public profession thereof.

Leaving Dudley, we had meetings at Stourbridge, Bewdley, and Bromsgrove:
that at Bewdley did not tend to relieve my mind,
being attended by very few of the town's people,
to whom we suppose proper notice had not been given.
On "`the next first-day we attended a large meeting which is held annually at Redditch;
and from there we went to Worcester, staid over the third-day's meeting there,
and proceeded to Camden to the funeral of a Friend;
then to a meeting at Stow in the Woold and to Cirencester,
and attended the meetings there on the first-day,
which was a day of memorable favour to some souls.

We visited the meetings of Nailworth, and paid a visit to my cousin M. Fowler,
at Minchin Hampton; from which we went to Sodbury, had a meeting there,
and proceeded to Bristol, where my dear husband was engaged in business:
and although I saw I must return into Gloucestershire,
I was pleased to be permitted to see him before his return into Cornwall.
From Bristol we went to the meetings at Frenchay and Thornbury on first-day,
and so to the quarterly meeting for Gloucestershire, held at Cheltenham.
As it was the season for drinking the water of this place,
many who were in it on that account, attended the public meeting,
unto whom the testimony of Truth was declared.
From Cheltenham we proceeded to Painswick, attended a large meeting,
held on account of the funeral of a Friend, which was a favoured opportunity,
and had also a meeting select with the Friends of that place.
I had a desire to have a meeting at Gloucester with the people not professing with us,
of which notice was given; and although it was not so large as I wished,
I had some open service amongst those who attended and behaved seriously.
We visited Friends at Tewksbury, and on the first-day,
had an appointed meeting at Stoke Orchard,
where formerly there had been an established meeting of Friends, returned to Tewksbury,
and next day went to Worcester.
From there my companion returned to Bristol,
being desirous to spend a little time at home before the yearly meeting at Hereford.

On the next first-day, being the 10th of the ninth month, I attended a large,
and I hope a serviceable, meeting at Stourport;
which was appointed and attended by John Townsend of London,
and Thomas Waring of Leominster;
and was the first meeting which had been held by Friends in that place.
My mind not being easy respecting Bewdley, I proposed to the before mentioned Friends,
to accompany me in a meeting there; which they being willing to do,
one was appointed to be held the next morning;
and although it was not so large as I expected, it was a favoured season,
and tended to the relief of my mind.

The 12th, John Townsend accompanied me to Droitwich,
where I desired to have a meeting with the town's people,
which proved a memorable season of Divine favour.
The 13th, I went to Bramyard, and the 14th attended the monthly meeting at Leominster,
and staid with my relations there until the 23rd. On the 21st,
the marriage of my niece Catherine Young, with George C. Fox of Falmouth, was solemnized;
and the meeting held upon the occasion was large,
and the testimony of Truth was exalted therein, to the Lord's praise.

From Leominster I proceeded to Hereford,
where I was met by my companion Lydia Hawksworth,
and many other ministering Friends and others,
assembled to attend the circular yearly meeting, which was a large, solemn,
and to myself and many other Friends, humbling season,
under the sense of the fresh extendings of Divine love and power towards Friends,
and the people of other religious societies.

How frequently is the assent of the judgement
given to the truths preached in our meetings,
by many who attend them, who do not profess with us!
But how few of these walk answerably to what they have been
convinced is consistent with the holy dispensation of Christ!
Alas! the cross appears too great to be taken up, even to gain an immortal crown.

But be it considered who it was that said, "`He that takes not up his cross,
and follows after me, is not worthy of me;`" and also, "`He that is ashamed of me,
and of my doctrine, of him will I be ashamed before my Father and his holy angels.`"
It is not only the unfaithfulness of many who have been born and educated amongst us,
but that of very many, who have been convinced of the truth of our religious principles,
which prevents the increase of our numbers.
There was a time when many people were weary of
worshipping in the outward courts of religion,
and could not content themselves with shadows of it,
and were willing to embrace the cross, that they might obtain the substance;
when many great and distinguished persons and characters,
bore testimony to the Truth as it is professed by us, as they were thereto called of God;
whose fight shone brightly,
and very conspicuously through their great and numerous sufferings,
for their "`testimony of a good conscience towards Him and men.`"
The present time is a season of ease,
and greater liberty to worship the Lord agreeably to the instruction of his pure Spirit;
but wherein many of the people are willing to hear,
but few are awfully inquiring "`What is Truth,`" with an earnest desire to know,
and sincere intention to follow it.
Pontius Pilate inquired,
"`What is Truth,`" but did not wait for an answer from the Light of Truth.
He was in part convinced of his power and purity,
yet he delivered him up to the Jews to be crucified,
lest his temporal interests should suffer, if he rescued him from their malice.
And we read,
"`that the same day Pilate and Herod were made friends,`
" who had before been at variance with each other.
Thus it has been, and is, with many who have been partly convinced what is Truth.
Temporal interests and pleasures have been preferred to a possession in the Truth;
and the joining with the world in persecuting Christ,
to the confessing of him before men.
The testimony of his servant is fulfilled in such;
"`whosoever will be a friend of the world, is the enemy of God.`"
These will one day see and lament their great loss.

May the Lord in his mercy rouse many of them to consider the
things which will make for their peace with him,
before they are forever hid from their eyes.
I believe there will come a shaking time in these favoured nations,
wherein the false rest of many will be disturbed,
and the judgements of the Lord being in the earth,
the inhabitants thereof will learn righteousness;
and many will be gathered from the barren mountains of an empty profession of religion,
and the desolate hills of formality, to sit under the teaching of Christ,
manifested by his Spirit in their souls,
and delight in the extendings of the wing of his love and power;
whereby they will be solaced, and sheltered in this state of probation,
and therefore sing salvation and strength thereto.

O! that those remaining under the name may be concerned to keep their lamps burnmg;
that they may attract the notice of those who in
that day will sincerely seek the way to Zion,
saying,
"`let us be joined unto the Lord in an everlasting covenant;`" that such may behold us,
as a chosen people of God, abiding in our tents, under the direction of our Holy Captain,
Christ Jesus: who raised us up to be a people,
that should bear an uniform testimony to his pure everlasting Truth.
He cleansed us from all the chaff and dross, which under a religious show,
remained amongst the professors of faith in Him;
as well as from all the fragments of the legal dispensation,
which with its ordinances and ceremonies were appointed to pass away,
when his pure spiritual dispensation of grace
and truth should be introduced and established.
He stripped us of that fragment of superstition
wherewith the nominal Christian church was,
and yet is in degree, clothed.
He abolished the false faiths and false trusts whereon many had depended;
and he clothed us with that true faith, which overcomes the world,
and is productive of fruits fit for his holy kingdom.
And will he allow us to become extinct as a peculiar family to himself? No, verily.
Although many of us are as "`degenerate plants of a
strange vine unto Him;`" he will return and visit them,
and some of these will be ingrafted into him; and others will be brought from far,
to seek an inheritance amongst them; and the Most High will acknowledge them,
as "`the branches of his planting, the work of his hands, in whom he will be glorified.`"

After taking an affectionate farewell of my friends at Hereford,
my companion and I went to Ross, had a meeting there, and to Bristol, where I left her;
and Ann Byrd accompanied me to Wellington.
We staid the morning meeting there on the first-day,
and went in the afternoon to Cllumpton;
had a religious opportunity with the Friends living there in the evening,
and early next morning went for Exeter;
in hope of getting there in time to go forward with the Friends from
that place to the quarterly meeting at Kingsbridge;
but they were gone, and we had to travel a lonely and long day's journey,
which was not accomplished without difficulty, and some danger,
it being late at night before we got to Kingsbridge.

Had not a young woman whom we met at Totness,
taken us into the chaise which she had hired,
there was little probability of getting there that night;
as no other chaise was to be had in the town, and the fleet lying in Torbay,
the officers were revelling at the inn;
so that we should have had but an uncomfortable time amongst them.
From Kingsbridge, I went to Plymouth, where I met my dear husband;
and after a meeting there, we proceeded home,
where we arrived the 9th of the tenth month.

I have the more particularly noted my proceedings in this journey,
because it was amongst my friends and others who
had heretofore so largely shared my labours:
and this being the last visit which I paid them so generally, it appeared to me singular,
that I should fall in with so many quarterly and annual meetings;
which afforded us an opportunity of seeing each other
more generally and repeatedly than we should have done,
had it not so happened:
and be it commemorated with humble thankfulness to the merciful Fountain of blessings,
that it was a season of signal favour to many of our spirits.

I had been laboriously exercised for more than five months in this journey,
and except in attending our monthly and quarterly meeting,
and occasional services about home, I was excused from travelling more in this year.
Indeed, I had for some time,
found my nature sinking under the load of exercises it had long sustained;
so that I did not go through services assigned me without many painful feelings,
but He who employed, supported me, to the praise of his ever worthy Name.

In the spring of the year 1781,
I wrote my brother Young to the following import:-- "`My mind
is so closed in regard to future prospects of duty,
that I am ready to conclude some family affliction may
prevent my moving far from home soon.`"
In this I was not mistaken; for soon after I wrote that letter I was seized with a cold,
the effects whereof became alarming; and after its load was removed from my lungs,
it fell upon my joints, which have gradually stiffened,
and baffled all medical application; so that I am become an entire cripple,
and my fingers are so contracted that my being
able to use my pen is admirable to my friends.
But although this is ultimately the consequence,
yet I have been enabled to struggle on for several years.

I was not so recovered as to appear equal to the fatigue of
attending the yearly meeting at London this year;
and my husband also was easy to abide at home,
where he was so dangerously attacked with a quinsy,
that it appeared he very narrowly escaped death.
His son was from home, and the weight of his critical situation,
together with the attention which was due to him,
bore heavily upon my weak body and spirits, and but that our cousin Frances James,
now Fox, was then with us, I know not how I should have sustained my fatigues.
She very tenderly and assiduously attended upon my husband,
and assisted me in this season of affliction;
which I note with thankfulness to that good Hand which furnished us with her help.
My husband's first wife was her mother's sister, and she being left an infant orphan,
my husband, with other relations, had cared for her, and a mutual affection subsisted;
so that her services were the more willingly lent, and pleasingly accepted.

When my husband's disorder was turned, he recovered strength but slowly,
and I continued weak,
yet I could not be easy to omit attending the circular yearly meeting,
which was this year held at South Molton in Devonshire.
My husband's health not admitting of his accompanying me,
my niece Fox was my only companion;
but being in our own chaise we got along the more easily and in safety to South Molton,
where we hoped to have met my brothers Payton and Young;
but in this we were afflictingly disappointed.
My brother's servant brought us intelligence,
that his master and my brother Young had come within one stage of Bristol,
where my brother Young was laid up extremely ill;
and of consequence my brother Payton was detained with him.
This was afflicting intelligence to us both; my niece, his daughter,
was sunk too low to proceed forward alone; and until the meeting closed,
no Friend could be expected to accompany her,
when my friend Hawksworth took her under her care.
She found her father extremely ill, and his case appeared for some time very dangerous,
yet it pleased Providence to restore him; but he was confined some weeks at the inn,
before it appeared safe for him to move forwards.

The people of South Molton very kindly welcomed Friends amongst them,
and freely opened their houses to receive such as could
not be accommodated with lodgings at the inns.
My friend Hawksworth and myself preferred lodging at a private house,
as our inn was likely to be very full of company;
and as we went to see a room at a considerable distance, a young clergyman joined us,
and appeared to interest himself in our being well accommodated.

He told us the people of the town were generally moderate and civil,
and seemed pleased that the meeting was appointed there.
We were kindly lodged near the inn.

The meeting was very large, and the people behaved soberly:
indeed many of them seemed prepared to receive, or at least hear, the testimony of Truth;
and the power of it so prevailed in the meeting as to bind down the spirits of others,
who might attend from no better motive than curiosity.
The spring of gospel ministry ran freely, and I, though so weak,
was enabled to take a large share in the labour.
Friends were comforted together,
and the faithful amongst them rejoiced in perceiving the extendings of the love of God,
both towards the members of our own Society, and those of other religious professions;
many of whose hearts were affected under the testimony delivered in the meetings.

I returned directly home, my friend A. Price accompanying me.
Here, and in the county, I continued for the winter, in a weak state of health,
and my dear husband tender, but mostly cheerful, which was his natural disposition.

I do not know that I have enjoyed one day's health since the spring of this year, which,
as I foresaw, was a year attended with much family affliction,
wherein our son Richard Phillips had a share before it terminated.

In the year 1782, I attended the Welch yearly meeting, which was held at Bridgenorth.
My husband accompanied me to Bristol, and Lydia Hawksworth went with me to Bridgenorth.
We went direct, only called and staid a short time with my brother,
and returned to the yearly meeting at Bristol, and from there to London.

When I went from Bristol to Bridgenorth, my husband went to Swansea,
and met me in London, to attend the yearly meeting there,
A general epidemic cold reigned during the sitting of the yearly meeting.
Many Friends were seized with it, but we were favoured to escape it,
until much of the service of the meetings was over.
We were both much indisposed, which detained us some time in London;
and when we were able to travel, we returned with our friend Lydia Hawksworth to Bristol,
and from there home.
We recovered strength to attend the circular yearly meeting,
which was held at Tamworth in the ninth month.

My weakness and contraction in my joints increasing, my husband consulted Dr. Ludlow,
a physician of note of Bristol, upon the case,
who ordered me medicine to take on the journey, which, being of an invigorating quality,
I thought helped to strengthen me to get through the fatigue of the journey,
and the exercise of the meeting;
although the principal help in the course of the labour
assigned me therein must be attributed to the Lord's power,
which is manifested in the weakness of his servants.
The meeting was large, both of Friends and those of other societies,
and crowned with the Divine presence.
The testimony of Truth was exalted, and faithful Friends were comforted,
in the sense of the continued extendings of the heavenly Father's
love to the various states of the members of our own Society,
as well as to other professors of religion.
Before the meeting was opened I had dislocated my left elbow,
by a fall down a steep and long flight of stairs,
and was obliged to carry my arm in a sling;
although I had to take so considerable a share of
active labour through the course of the meetings.

After their conclusion, we attended a meeting at Birmingham,
then spent a short time at Dudley, with my brother, and returned to Bristol,
where we again consulted Dr. Ludlow;
who advised me to try the effect of electricity on my contracted joints.
After I had continued some time under that operation, he ordered me to Bath,
to try the effect of pumping upon them,
at the same time continuing the medicines he had prescribed.
But all was without the desired effect; and indeed I believe the Doctor had but little.
hope in my case, for he intimated that I might probably become an entire cripple,
and live many years in that state; which has been my case.

1783.--My husband accompanied me to the yearly meeting at London.
Before I left home,
I had informed my friends that I was engaged to attend the yearly meetings of Colchester,
Woodbridge, and Norwich, which succeeded that at London;
and had obtained a certificate of their unity with me therein;
and my friend Lydia Hawksworth being under the like concern,
we left Bristol on the 28th of the fifth month,
accompanied by our friend Mary Were of Wellington.
We proceeded to Melksham and Salisbury, where we left Mary Were, and went to Poole,
attended the meetings there on first-day, 1st of the sixth month, and the 2nd,
met Mary Were at Ringwood, attended the monthly meeting there, and proceeded to Rumsey,
from there to Alton, attended the week-day meeting there on the 4th,
and went to Godalming, and the 5th to London.
On this day we intended to have fallen in with the week-day meeting at Esher;
but there being a funeral of a Friend at Kingston,
most of the Friends of Esher were gone to attend it; so we pressed on,
and got to the meeting a little after the time appointed;
and I hope it was well we were there.
We attended the quarterly meeting, and proceeded on our journey,
taking meetings in our way to the before-mentioned yearly meetings.

We also visited almost all the meetings in Norfolk,
then passed into Cambridgeshire and the Isle of Ely, visiting the meetings therein,
from there into Essex,
and after visiting several meetings which I had not before attended in that county,
turned back through Cambridgeshire to Huntingdon,
In this journey I sustained much labour both in body and spirit,
which was the more painful from my increased and increasing weakness;
which rendered it probable, as indeed it proved,
that this would be the last visit I should pay to Friends of those parts;
as it was also the first I had paid to many of the meetings which we attended.
I was however thankful that the good Shepherd influenced our
minds to visit so many of his sheep in those counties,
unto whom our spirits were united in gospel sympathy;
and we had also to bear the burden of the spirits of formal professors,
to whom the alarm was sounded, to awake out of sleep.
I had some public meetings in this journey to my satisfaction,
and I hope to the edification of many people attending them.
One of them was held at Cambridge; which I hope was serviceable,
although I was not favoured to rise in the exercise of the Divine gift bestowed upon me,
to that height I did when in that town many years ago.

That was indeed a singular time, and answered a singular end,
which was to convince a man who had contemned women's ministry in Christ's church,
of its weight, efficacy, and consistency with the gospel dispensation.
The same man, who did not live in the town, was invited to attend this meeting,
and he might therein hear gospel truths published,
and treated upon in a more argumentative way, than it was common for me to be engaged in.
The All-wise employer of true gospel ministers knows how to direct his servants,
both as to the matter,
and the manner wherein he intends it should be communicated to the people.
I have admired his wisdom and condescension therein,
when without forethought my speech has been accommodated to
the capacities of those to whom it was directed.
To such as were illiterate and ignorant, I have spoken in very low terms;
and to those of more understanding, in such as answered its level; while to the learned,
and those of superior natural abilities, I might say with the prophet,
"`The Lord God has given me the tongue of the
learned;`" although I had it not by education.
I have not lacked eloquence of speech, or strength of argument,
wherein to convey and enforce the doctrines given me preach; of which I could say,
as my Lord and Master did, "`My doctrines are not mine,
but his who sent me:`" and his love, life, and power, have accompanied them,
to the stopping of the mouths of gainsayers,
and convincing of the understandings of many,
of the rectitude and efficacy of "`the Truth as it is in Christ Jesus.`"
the depth and excellency of true gospel ministry!
The Lord's prophet in the prospect of it might well exclaim,
"`How beautiful upon the mountains are the feet of those who bring good tidings,
who publish peace, who publish salvation, who say unto Zion, Your God reigns!`"
These are not made so by human or literary acquirements;
but "`the Spirit from on high being poured upon
them,`" under its holy humbling influence,
they are enabled to minister,
and "`compare spiritual things with spiritual,`" or elucidate them by natural things,
as occasion may require, without forecast or premeditation; for they speak extempore,
as the Spirit gives utterance.
When the ministry in the general thus returns to its original dignity and simplicity,
an education at colleges will not be sought to qualify for it.
No, those who are accoutred for the service of Him "`who spoke as
never man spake,`" must be educated in his school,
and disciplined by his wisdom; whereby they are made able ministers of the new testament,
not of the letter, but of the spirit; for the letter kills, but the spirit gives life.

Thus have I, with many of my fellow-labourers,
been assisted to minister in the gospel of Christ;
and now in the close of a laborious day's work, I may commemorate the mercy, power,
and wisdom of Him who chooses whom he pleases for the various offices in his church.

He appoints, of both male and female, "`some apostles, some prophets, some evangelists,
and some pastors and teachers; for the perfecting of the saints,
for the work of the ministry, for the edifying of the body of Christ;
until his members come in the unity of the faith, and of the knowledge of the Son of God,
unto the measure of the stature of the fulness of Christ;
and may grow up into him in all things who is the Head,
from whom the whole body filly joined together
and compacted by that which every joint supplies,
according to its effectual working in the measure of every part,
makes increase of the body, unto the edifying of itself in love.`"
Then, there is the highest rejoicing in him the heavenly Teacher,
who fulfils his gracious promise, both to those who minister under him,
and to those who are not called to this awful service, "`Lo, I am with you always,
even to the end of the world!"

Unto him all true gospel ministers direct the people,
and endeavour to settle them under the teaching of his pure Spirit,
These disclaim the least degree of ability to labour availingly in his service,
except what flows from him, the fountain of Divine power, love, and life; and,
after they have done and suffered what he assigns them, sit down in the acknowledgement,
that "`what they are,
they are through his grace;`" and thanking him
that they have not received his grace in vain,
humbly confess they have done but their duty.
Thus from early youth, have I travelled and laboured,
that the saving knowledge of God may increase,
through experience of the prevalence of the power of his Son;
whereby the true believers in him become crucified to the world and the world unto them;
and being thus dead, are raised by him in newness of life,
to the praise and glory of God.
Freely I have received the knowledge of salvation through the
sanctifying operation of the Spirit of Christ;
and freely have I testified thereof,
and of God's universal love through his Son to mankind: for he would have none to perish,
but that all should be saved, and attain to the knowledge of his Truth.

My views, with those of others my fellow-labourers in the ministry, have,
in regard to ourselves,
been simply to obtain peace with God through an honest discharge of our duty;
and in respect to those unto whom we have freely ministered,
that they might be turned from darkness to light, and from the power of Satan unto God;
and be favoured with the experience of the remission of sins,
and obtaining a fixed inheritance amongst all those who are sanctified.
And we are not afraid to say, that the love of Christ has constrained us to minister,
unmixed with any temporal interested motive, or view of reward.
Through that love, we have been made willing to spend our temporal substance,
as well as our strength of body and of faculties, and to suffer many hardships; yes,
to leave what was dearest to us in nature,
and be accounted fools by the wise and prudent of this world;
some of whom have poured upon us contempt, but who professing themselves to be wise,
have manifested their foolishness; and by speaking evil of what they knew not,
have evidently been wise in their own conceits.

As to us, however we may have been favoured by the Lord,
who has accounted us worthy to have a part in this ministry,
and has at seasons clothed us as with a royal robe,
to the astonishment of even those who have had us in derision; all boasting is excluded,
by the pure humbling law of faith in Christ,
"`the wisdom and power of God,`" and we confess with his primitive ministers,
that we have nothing of our own to boast of but infirmities,
nor have we aught to glory in but his grace to help us;
through which we have been rendered equal to the arduous tasks assigned us;
and willing to turn from prospects the most pleasing to the natural mind,
and to endure crosses, tribulations, and the contempt of men, for his sake,
who so loved us as to die for us; and has mercifully called us by his grace,
to become heirs with him in the kingdom of his Father: and having done all,
we have nothing to trust in but the mercy of God, manifested in and through him;
and under a sense that all we can do to promote his honour is but little,
and that little communicated by his strength,
this is ultimately the language of our spirits; Not unto us, O Lord! not unto us,
but unto your ever worthy name, or power, be glory forever!
Amen.

From Cambridge, one of the seats of learning, I wish I could say of piety,
we proceeded to visit some other meetings in this quarter, and coming to Ives,
attended the funeral of Samuel Abbot, an elder of good report.
The meeting held upon the occasion was extremely crowded,
and many of the principal inhabitants of the town and neighbourhood attended it.
It was a season of awful solemnity, wherein the tide of gospel ministry rose high,
even to the overflowing the mounds of opposition;
and I believe the people were so humbled,
that many of them could join us in supplication and praise to the Lord,
who "`is glorious in holiness, fearful in praises, working wonders.`"
Hence we went (as before hinted) to Huntingdon, our friend John Abbot,
son to the friend whose funeral we had attended, accompanying us.
From Huntingdon we proceeded to Ampthill in Bedfordshire;
and in our way passed through Potton, intending, if it was convenient,
to lodge in that town, with one professing with us.
But alas! when we came there, we found the town, which the day before, had been,
it was said, one of the prettiest in the county, in ruins.
A terrible fire had raged all night, and was not then in some places quite extinguished.
Almost the whole of a principal street,
through which we walked (not without fear lest the chimneys,
or some other parts of the brick or stone-work left standing, should fall upon us),
and most of the houses in the market-place, were consumed.
The fire stopped at the next house to that which our friend had inhabited.

He had time to get his goods out, but had left them,
and with his wife was gone to another town where they had relations,
and through which we had to pass, and where, at an inn, we lodged at night,
our friend Abbot accompanying us.
The view of Potton and its inhabitants was truly pitiable:
the goods of the sufferers were scattered about round the town in the fields,
and some were watching them.
The countenances of some whom we saw in the streets were deeply marked with grief;
and the principal ovens being destroyed,
bread was to be fetched from a town some miles distant.

Our friend John Abbot was so touched with the countenance of one poor woman,
that after passing her, he turned back, and gave her something handsome;
but she probably knew not where to buy victuals if she needed it.
The principal inns being burned down or greatly injured,
we stopped at the house of an acquaintance of his,
in a part of the town which had escaped the fire, who readily gave us some refreshment;
and in return, we left with him, towards the present relief of the sufferers,
so much as excited his thankfulness.
The next morning we visited our friends who had fled from Potton, at their relation's;
and had a solemn religious opportunity with them and others present;
and proceeding to Ampthill, attended the first-day's meetings there.
From Ampthill, John Abbot returned home, and we went pretty directly to Melksham,
appointing some meetings in our way there.
Before I came there my strength was extremely exhausted,
and having a concern to attend the circular yearly
meeting to be held at Frome in Somersetshire,
it appeared necessary for me previously to take a little rest.
We therefore staid at Melksham with my affectionate
relations Elizabeth Fowler and her son and daughter,
her husband being now dead.
At Frome, I met with my dear brother James Payton, and many of my relations and friends,
and the Lord favoured us together with his presence.
The meetings were large, solemn, and eminently crowned with divine life and power,
wherein the gospel was preached by several ministers.
Nicholas Wain, from Pennsylvania, attended this meeting,
and had acceptable service therein.

I went directly home;
and in my way had a favoured meeting with Friends and
many others of the inhabitants of Exeter.
My niece Fox accompanied me from Frome to Truro, where my dear husband met me,
to our mutual thankfulness.
I do not recollect any thing more worth remarking in the remainder of this year,
wherein I continued weak, yet attended services about home as they occurred.

In the spring of the year 1784, my dear husband was much indisposed,
and from that time was frequently afflicted with a giddiness in his head;
yet he recovered so far as to attend the yearly meeting at London,
and I accompanied him in much weakness;
yet I had cause to be humbly thankful for the Divine aid vouchsafed to labour,
although I was unable to attend all the meetings
which were held in the course of that solemnity.

From London we went to Bristol, where my husband had business;
and as I had no inclination to stay in that city,
proceeded in company with M. and A. Moon, to Wellington.
From there I was accompanied by my dear friend Mary Were to William Byrd's at Uffculm;
at whose house we had a favoured meeting with the town's people,
and returned to Wellington; where I waited, until my husband came to me.
I was strongly impressed with a concern to pay a visit once more to
the few professing Truth in the north side of Devonshire,
as well as to hold some public meetings in some
of the towns which I had heretofore visited.

My husband knew of my having this prospect, but when he came to me at Wellington,
and saw how poorly I was, he almost feared for me,
and would have been pleased if I had been easy to accompany him directly home.

This however not being the case,
we went on the first-day to Friends meeting at Spiceland,
which was attended by a pretty many sober people, not professing with us;
and the Master of our assemblies favoured with suitable doctrine and counsel,
so that the truly righteous rejoiced together;
and under the sense of the arm of the Lord being
extended to help in the~ seasons of weakness,
we proceeded from this meeting to South Molton; and our friends Nicholas and Mary Were,
and William and Ann Byrd, accompanied us; as did also Thomas Melhuish of Taunton.
We appointed a meeting to be held there the next morning;
but the weather proving very wet, there was some doubt how it would be attended; however,
it was pretty large, and a solemn instructive season.

No one professing with us lived in this town,
nor had any meeting been appointed there since the circular meeting
was held there in 1781. But the remembrance and savour of that
solemnity might continue long upon the minds of religious persons.

We went that evening to Barnstaple, except T. Melhuish, who returned home,
and next day had a meeting there in the assembly-room, which was large, solemn,
and highly favoured with the Divine power and presence.
I was wonderfully assisted to publish gospel truths,
"`in the demonstration of the Spirit,
and with power;`" and it appeared that many who heard, understood and were affected,
amongst whom were some of the higher rank.
O! that such heavenly visitations might produce fruits
of righteousness answerable to the labour bestowed;
but alas! they are too frequently like water spilled upon a stone,
which although it wets the surface,
does not change the obdurate unfruitful nature of the stone;
and the rain which has descended upon it, is so quickly dried up,
that there remains no evidence of its having been watered.

Indeed the stone is, agreeable to its nature, unfruitful, and must remain so.
But what said the apostle unto those whose hearts were like ground, which,
although it was often watered,
brought forth nothing more profitable than briers and thorns, "`It is nigh unto cursing,
whose end is to be burned.`"
It is extremely dangerous trifling with the Lord's merciful visitation to the soul,
as time is uncertain: therefore those who hear,
have need to be concerned to obey the call of God to a renovation of mind and manners,
that their souls may live.

From Barnstaple, we went to Great Torrington,
and had a large and I hope serviceable meeting there,
although not so distinguishedly favoured as that of Barnstaple had been.
My dear friends A. Byrd and M. Were had acceptable
service in the before-mentioned meeting;
as well as in ministering to the few Friends who were scattered about the country,
who met us at one place or other; and we had private religious opportunities with them,
so that they were generally visited.
I was favoured with much freedom to speak to them in the love of Christ,
and therein to take my farewell of them; for this proved to be my last visit.
There were never many Friends settled on the north side of Devonshire.
I know not of a meetinghouse having been built in any town I have visited there;
yet a few, some of them having been gathered from other professions of religion,
were scattered about in this quarter, and held meetings at their houses.

W. Byrd and his wife left us at Torrington;
but Nicholas Were and his wife concluded to accompany us to Hatherly,
twelve miles farther,
where I had a desire to have a meeting and their
being so disposed proved very serviceable to us.

There having been a. large fair for cattle the day before we came to Hatherly,
and the farmers scarcely all gone from the place,
we found the inn in such disorder as to render it doubtful how we should lodge.
However, the landlady got clean linen, and our friends Were and ourselves got lodging;
but some men Friends who met us from Exon,
were obliged to shift for themselves as well as they could;
and a young woman who accompanied them was provided for with us.
The town was small, and in such a hurry, that it appeared a poor time to get a meeting.
The weather was also very wet on this and the next day;
but some of the town's people being informed of our view in coming,
interested themselves in procuring us a meeting place,
and we were furnished with one as commodious as we could expect.
Many assisted to seat a part of it; and the weather continuing wet,
prevented some of the inhabitants from going to their labour,
so that I know not but our meeting was the larger through that circumstance.
The people behaved well, many were content to stand,
and we were favoured with a solemn meeting amongst them.

No meeting had been held in this place for very many years;
so that most of our auditors appeared ignorant of our
religious principles and manner of worship;
but our visit was received with expressions of pleasure and gratitude by some,
and we left the place with thankful hearts,
each of us setting our faces homeward the same evening.
My health continued declining,
and my husband's complaint of giddiness returned pretty frequently.
We did not go far from home for the remainder of this year.

In 1785, my husband was inclined to attend the yearly meeting at London,
and desirous of my accompanying him.
I was so weighed down with painful sensations, and my joints so much contracted,
and he so subject to the giddiness in his head,
that I suggested to him the propriety of our considering
whether it was safe for us to venture upon such a journey:
to which he replied, that his mind was strongly drawn to the yearly meeting, and said,
that it would be the last he should attend.
In our way thereto we were at the meeting of Bridport on the first-day;
and I appointed a meeting at Andover, which was large,
and eminently favoured with the Divine power and presence.

Samuel Emlen and George Dillwyn, both of Philadelphia, attended this meeting;
but the principal share of the ministry rested upon me:
indeed I had long had a view to a meeting in this town,
and this proved to be the last time I passed through it.
When we reached London, I was in a very weak state,
but was enabled to attend the meetings in their course.
At the yearly meeting in the preceding year,
our men Friends had weightily considered the state of our women's yearly meeting;
and it appearing that it might become of more general service,
if the queries for women Friends,
which are answered from their monthly to their quarterly meetings,
were also answered from the quarterly to the yearly meeting of women,
they sent a minute to the quarterly and monthly meetings to that import;
and this year answers were sent from some quarterly meetings,
and women Friends attended as representatives.

But it being a new thing,
and the propriety or necessity of it not fully understood by all our women Friends,
an epistle was written,
setting forth the rise and use of the discipline established amongst us,
and encouraging women Friends to attend to their share of it.
As mothers of children and mistresses of families,
they have an extensive service to attend to,
and ought to be concerned so to discipline their families,
as to be able to answer the several queries relative to their situation.

My mind being drawn to visit the quarterly meeting of Hertfordshire,
I intimated it to my friend Elizabeth Talwyn of Bromley,
who kindly took me and my dear companion Lydia Hawksworth thereto in her coach;
and this was my farewell visit to Friends there.
As I knew that my husband as well as myself wished to
leave London as soon as we could with ease of mind,
I requested that notice might be sent to the
several meetings near to that of Chorley Wood,
that I hoped to be there on the next first-day,
and should be pleased to see as many as could meet me there.
The meeting-house was pretty full, it was a favoured season,
and the last meeting I had in that part of the kingdom.
That night we lodged with our friend Robert Eeles near Amersham,
by whom and his kind wife I had several times been affectionately entertained.
Next day we reached Banbury, had a meeting with Friends there, on the next morning,
and after taking an affectionate leave of my near relation S. Stone,
we proceeded that night to Warwick.
My sister received us affectionately,
though not without concern to see me so much enfeebled.

My joints were so contracted that it was become difficult for me to walk;
and throughout this journey I was assisted in dressing;
and my inward weakness was also very apparent,
so that it appeared probable that this might be our last interview.
I attended one meeting with Friends at Warwick,
wherein the Divine spring of gospel ministry was
opened to the refreshment of religious minds;
and, after taking my last personal farewell of my dear sister, we went to Coventry,
had an evening meeting there,
which was pretty generally attended by Friends and some
intelligent people not professing with us;
and the Lord favoured us together in a memorable degree.
The subjects given me to speak upon,
were the awfulness and importance of passing through time,
considering the consequences depending thereupon, and the solemnity of passing out of it,
even to the best of men.
For although such might be favoured with a well-grounded hope of
participating in "`the inheritance which is undefiled and fades not
away;`" and might rejoice at the approach of the hour of release from
the pains and solicitudes attendant in this probationary state;
it was a season, wherein, from the consideration of the purity of Christ's kingdom,
they might think it needful to examine whether their spirits were so clean,
as to be meet for admittance thereinto.
But to the wicked it was a terrible hour.
Many striking remarks, directed to several states, were given me to make;
and I was favoured to deliver them in concise, yet strong terms,
to the affecting the minds of many present: and thus, taking leave of that city,
we proceeded next day to Birmingham--attended the first-day meeting there,
and from there to Dudley.

We staid a few days with my brother attended one meeting there,
and another at Stourbridge, afterwards went to Worcester,
and were at the first-day meetings there.

As my case appeared alarming,
and some of my friends advised my making trial of Buxton water, my husband,
when we were at Birmingham, took the advice of a physician of note,
who did not choose to prescribe for me, nor encourage my going to Buxton;
but advised our calling at Bath, but cautioned me against drinking the waters,
or bathing, without taking further advice there:
so taking leave of our brother James Payton and Friends at Worcester,
we proceeded directly to Bath.
The advice I there had was to return home, drink the Bath water there, and pursue,
the course of medicine prescribed.

The weather was then too hot for me either to bathe, or drink the water there,
but it was left to further consideration whether I should return there in the fall.
Weak as I was, I had two meetings at Bath;
in one of which I had a strong and clear testimony directed to a state,
which in youth had been Divinely visited,
and made some advances in the path of self-denial; but in more advanced age,
had sought after worldly wisdom and knowledge,
and the friendship of those in that spirit, and had lost the heavenly dew of youth.
There was a person in the state described, in the meeting, who was much affected,
and died in a short time.
How does Divine mercy follow the backsliders from his holy commandment,
with the gracious call of "`Turn you, why will you die?"

From Bath we went to Bristol, where my husband had business, and where I left him,
and went to John Hipsley's at Congersbury--was
at the meeting of Claverham on the first-day,
and returning to Congersbury,
staid there until my husband's business permitted him to return home:
to which we went directly, myself in a feeble state,
but my husband appeared to be as well as when we left it.

After our return from London,
my husband's time and attention were very much engrossed by business,
relative to the mining interests in this county.
Some alteration in the course of the trade appeared necessary,
and as he had from his youth been engaged in the copper trade,
and was well acquainted with the state of it, both in the past and present times,
much regard was paid to his judgement,
by many who attended at the meetings held on the occasion:
and his solicitude for its settlement to the advantage of the labouring miners,
as well as for allowing the adventurers, and others engaged in the trade,
a prospect of a reasonable profit, was such,
that under the continued exertion of his faculties for several weeks,
his strength evidently declined.

The circular yearly meeting falling this year in Cornwall,
it had been at our spring quarterly meeting appointed to be held at Truro, the 7th,
8th and 9th of the eighth month,
which was several weeks earlier than it was customary to hold that meeting.
This had occasioned some demur in the minds of some Friends,
who doubted whether those of the distant counties might
be so generally at liberty to attend it,
as if it should be held in its usual course;
and some Friends gave a preference to another town for the meeting.
But my husband having attentively considered
when and where to fix this important solemnity,
under a concern that the All-wise Director would
deign to influence the minds of Friends therein,
was steady in his judgement that both the time and place proposed were right:
and the event showed that he was not mistaken.
He with other Friends were engaged in preparing accommodation for this meeting,
and the town's people were very ready to assist.
A large booth was erected to hold it in, and other places were procured,
if that should not be sufficient to contain the people.

I was yet in a feeble state,
and as it appeared to me improbable that the meeting would be
attended by so many ministers and Friends of religious weight,
from the distant counties constituting it, and other parts of the nation,
as in some past years,
my spirit was weighed down under a sense of the great importance of the service,
and the disproportion of my natural strength to the labour of so large meetings.

My faith was indeed ready to fail; but I cried unto the Lord, in the language of Samson,
if the testimony of His Truth might but be exalted through me as an instrument,
"`let me die,`" if it be your will,
in this great effort to overcome the Philistine nature in the people:
and this proved to be the last of those general meetings which I attended.
In the night before we went to Truro,
my dear husband was so much indisposed with the giddiness in his head,
that he proposed to me to go to Truro, and leave him to take an emetic,
which he hoped might ease his head, and to come to me the next morning.

I was reluctant to leave him behind me, and it was well I did not,
as the straining to vomit would probably have produced instant death.
He grew better towards mid-day, and accompanied me to Truro,
where we met with many of our friends,
and he regained his wonted cheerfulness and activity,
and was very serviceable during the course of the meetings,
in regulating the holding of them, settling the people,
and taking share in the care that nothing might happen
amongst our young people at the several inns,
which might tend to shade the testimony of that pure Truth, which we met to propagate,
from very distant parts of the nation.

The concourse of people, especially of those not professing with us, was very great,
and not a few of them of the higher rank.
Many came far to attend the meetings, and behaved with becoming decency,
consistently with so solemn an occasion.
The booth, though as large as a good voice could well extend over to be distinctly heard,
would not nearly contain the people;
so that Friends were obliged to hold a meeting in the
afternoons of the 7th and 8th in another place.

This consequently tended to divide the ministers to the several meetings, and,
as I had foreseen, much of the service of the meetings in the booth devolved upon me;
yet not so, but that some other ministers had an acceptable share therein.
The testimony of Truth was largely and freely declared,
and arose in its native dignity and clearness;
so that very many not professing with us assented to the truths preached.
The public meetings concluded on the 9th before dinner,
under the overshadowing wing of Divine love, life, and power.

The minds of many Friends were comfortably impressed with a sense of the continued
extendings of the heavenly Shepherd's care over us as a religious Society;
as well as of his condescension in causing his gospel call to go forth amongst others,
and they turned their faces homeward in the afternoon, in humble thankfulness.

Here I may observe, as it has occurred to me when attending those large general meetings,
how different in their nature and tendency these meetings are,
to those which are appointed by professing Christians for amusement,
wherein there is much noisy mirth, and unchristian jollity: and if in some of them,
the entertainments, in one part of the day, have an outward and pompous show of religion,
under the vain and false pretence of praising God with the voice,
accompanied with instruments of music,
in the repetition of some of the most sublime and instructive parts of scripture;
in another part of it, the Christian name is shamefully dishonoured, by the amusements,
which succeed what they call their sacred oratorios.
I have been shocked in the consideration, of the expressions of holy men of God,
who penned them as the Holy Spirit dictated them,
and some awful instructive historical parts of scripture,
becoming prostituted to the purpose of amusement;
and furnishing occasion for many nominal Christians to assemble,
to gratify their inclinations to pride, vanity and pompous appearances,
as well as in some instances, the practising of gross wickedness: insomuch,
that it may be said with truth, the Lord of purity abhors their religious mockery,
and their seemingly solemn meetings are iniquity; and as such,
an abomination in His holy eyes, who cannot be imposed upon by specious pretences,
nor bribed by donations given for distressed objects,
to withhold his righteous judgements; which will assuredly be executed,
in their appointed season, on "`all the proud, and those who work wickedness.`"
How different to these, I say again and without ostentation, are the meetings,
of which in the course of these memoirs I have so frequently
given an account! whereto many Friends resort,
from very distant places and at a very considerable expense,
with a view to the edifying of others by the pure doctrines
which may be freely preached in their public assemblies,
and by a conduct consistent with Christian morality and rectitude;
and with desires to be edified together in the presence of the Lord,
in whose presence there is life, and at whose right hand there are pleasures, sublime,
and everlastingly durable.

My spirit worships in the sense of the foretaste of them,
which I have experienced in the present state; and in the hope,
which cheers in the painful seasons and afflictive occurrences attendant thereon,
that finally, the immortal spirit will be solaced in the inestimable, and by it,
unmerited reward, which is appointed for the righteous, and is unmixed with sorrow.

From this, I hope not ill-timed, digression, I return to the 10th of the eighth month;
when several of the ministers who had attended
the meetings at Truro were at ours at Redruth;
amongst whom was my friend Hawksworth, who came with intent to spend some time with us,
in hope that we might be favoured together with a little rest both of body and mind,
which might tend to the recruiting our strength.
But alas! although this important solemnity was so well over,
and my dear husband's engagements in temporal concerns now sat comparatively light,
and we were cheered for two days,
the third evinced the instability of all human comforts.

On the 11th, our friend T. Bevington, of Worcester, came to pay us a short visit.
He expressed an inclination to have a meeting with the town's people;
and my husband going, as he was accustomed upon such occasions,
to inform some of them that a meeting would be held that evening,
was observed to do it with rather more than common solemnity and tenderness of spirit.
I hope the meeting was serviceable, and we spent the evening agreeably with our friends.

In the morning of the 12th, T. Bevington left this place pretty early,
and my dear husband arose before me in seemingly usual health, and ate some breakfast,
but was suddenly seized with an acute pain in his breast.
He came and found me dressing, and told me that the pain was extreme,
but said that he conceived it was only in the muscles, and might be rheumatic,
but that he could cover the spot affected with his finger.
He chose to undress and go into bed, and complained of cold.
I sent for an apothecary who apprehended no danger in his case,
and gave him a small dose of paregoric elixir,
which operated to quiet him and stupify his pain.
I left a servant with him, and got some breakfast,
and returning found him rather inclined to sleep, so,
having some family concerns to attend to, I left him again.
The maid who was left with him said he complained of a return of his pain,
and she soon perceived such an alteration as occasioned her to ring the bell violently,
on which my friend Lydia Hawksworth and I hastened to the chamber.
She came soon enough to see him draw his last breath;
but my lameness not permitting me to make so much speed,
and the maid preventing me from immediately approaching his bed-side,
I saw only a breathless corpse.

Thus ended the valuable life of my dearly beloved William Phillips,
in the manner he had repeatedly expressed a desire it might end, that is suddenly;
though not altogether unexpectedly by himself,
as may have been noticed by what I have noted before we set out on our late journey.
Pie intimated to me,
that his prospects in regard to service in the present state were much closed;
and that in respect to the future he had no cloud before him;
and he would speak of the solemn close with that ease that
discovered he expected no sting of conscience in his death:
but the reason he gave for wishing (in submission to
the Divine will) that it might be sudden,
was, that he had felt so little pain in passing through time,
until he had attained the common age of man,
that he doubted whether if tried with it in the awful season of death,
he should support it with that calm, patient dignity,
which graces the close of a Christian life.

By appearances upon his body when it was cold,
it was evident that a large blood vessel had broken in his breast;
although not the least indication of such an
event appeared by any discharge from the mouth,
while he was alive.

His desire of attending the meeting at Truro was gratified,
which had not been the case had it been held in its usual course.
Neither is it probable that I could have attended and laboured
therein with that strength of mind I was favoured to do,
had this important stroke been executed before that meeting:
for although I was preserved from sinking into a state of condemnable sorrow;
the shock attending it could not be sustained without
my already much enfeebled nature suffering by it.
We had lived in the tender endearing connection
of marriage somewhat more than thirteen years,
after a friendship of about three-and-twenty.
The tie of natural affection between us was strong,
arising from a similarity of sentiments,
which was strengthened by an infinitely higher connection.

Indeed he was a man who commanded love, esteem, and respect, from his numerous relations,
friends, and acquaintance, in their different ranks and stations.
He was extensively useful without priding himself with it,
and he commanded the assent of the judgement of those,
amongst whom he might be looked upon as a principal, in the transactions of business,
by sound reasoning rather than by overbearing.

Such was his public character, drawn, as far as it goes, not beyond the life,
though by his afflicted affectionate widow.
She also best knew his private virtues and engaging manners,
exemplified in his family connections, friendships, and the general tenor of his conduct;
and therefore may say, that he was a kind master, an affectionate father,
and a warm and steady friend; always ready to serve his relations, friends,
and neighbours, by advice, or as an executor, or referee in disputed cases.
An affectionately tender husband--ah,
me! how shall I delineate this part of his character i Bound
to me by the endearing ties of love and friendship,
heightened by religious sympathy, his respect as well as affection,
was apparent to our friends and acquaintance.
His abilities to assist me in my religious engagements were conspicuous;
for although he had no share in the ministerial labour, he was ready to promote it.
His natural temper, though quick, was soft and complaisant;
a man of exact order in his business, and strict economy even to minute circumstances;
yet prudently liberal in his expenses, and charitable to the poor.

In his religious character,
he was firmly fixed in his principles agreeably to his profession,
and concerned to act consistently with them; but, clothed with charity towards all men,
he rejoiced if a reformation of mind and manners was wrought amongst mankind,
whoever were the instruments of it.
His experience in the spirituality of religion was
deeper than even some of his friends might conceive;
as it was sometimes concealed under the veil of cheerfulness,
which predominated in his constitution; or secreted,
through his aversion to make any ostentatious show of it;
but when called up to some service in Christ's church,
it was evident that he had been instructed in his school.
His faith and trust in the Divine power, wisdom and providence, were strong;
which enabled him to sustain disappointment and worldly losses with firmness.
In this he was tried in some instances, to a degree which would have shaken many minds;
but he would say, If a part is gone, I have many mercies left to be thankful for;
and he therefore endeavoured to preserve his wonted calmness and cheerfulness.

[verse]
____
And when Death's solemn shaft with swiftness flew,
Prepar'd he stood, and no confusion knew;
Sudden the stroke, but peaceful was his end;
Angels his consorts, and his Lord his friend.
Belov'd and hononr'd, see, his spirit soars
To heavenly mansions, and his God adores.
____

If any peruse what I have written, who had but partial knowledge of him,
they may perhaps conclude me too abundant in encomiums upon him.
But there are who can subscribe to their truth,
and who might add their testimony to his worth and abilities as a man,
and a useful member of the community at large,
as well as an honourable one of the religious Society of Friends:
and if his descendants in the natural line, succeed him in that of virtue and piety,
they will value this attempt to delineate his character.

My dear brother was fast declining in his health.
He had lately received an alarm, by a stroke of the palsy, to trim his lamp,
unto which I hope he attended.
He was now in part recovered,
but in the succeeding spring was revisited by that distressing disorder,
which quickly terminated his life;
in the close whereof he was favoured with the cheering prospect of
his immortal spirit's centring in everlasting blessedness.
He was endowed with a very good natural understanding,
which in the latter part of his life was so much employed for
the assistance of his friends and neighbours,
both of the town and country wherein he resided,
that he had as much business in accommodating disputes about property,
and other acts of kind aid as his strength would well bear.
He died beloved, and his loss was regretted by both the rich and poor.

[dicrete.alt]
=== To a relation.

[.signed-section-context-open]
Redruth, 29th of Seventh month, 1793.

Although I have not written to you since the
commencement of your present sorrowful state,
you can not be ignorant of my sympathy with you;
and considering my increased debility for writing (of which I advised your mother),
I might have hoped that you would not have waited for
my doing it before you had addressed me:
if but with few lines, they would have been very acceptable; especially so,
if they had breathed a spirit of acquiescence
with the will of the All-wise disposer of events.
He knows best on what to lay his hand,
in order to facilitate his merciful designs respecting us;
and if he deprives us of what is most dear,
and which also may appear to be the most valuable and
beneficial to us of all his temporal gifts;
does he not therein speak this instructive language.
Set your affections on things which are in heaven,
and not on things which are upon the earth,
which must all pass away in their appointed season? They are only lent us as
temporary assistants or accommodations in our passage through time;
and although they may be rejoiced in and valued as his gifts,
they are not to be depended upon or loved beyond the appointed standard of his wisdom.
It is our interest as well as duty,
to hold them by the tenure wherewith he has entrusted us with them, that is,
to be returned at his call; which always ultimately comports with our real happiness,
if "`we look not at the things which are seen,`" which, however high we may prize them,
are but temporal; but steadily behold, with ardent desire of possessing,
"`those which are not seen,`" save with the eye of faith, "`which are eternal.`"
My principal concern for you is, that this eye may be opened widely in your soul;
that you may see and rightly estimate all possessions which are attainable by man; and,
beholding and contemplating the transcendent excellency of spiritual gifts,
may covet them earnestly.

This is the only allowable covetousness, and the mind being thus engaged,
becomes transformed from a state of nature to that of grace:
agreeably to the apostle's testimony and experience:
"`And we all beholding as in a glass, with open face, the glory of the Lord,
are changed into the same image, from glory to glory, even by the spirit of the Lord.`"

In this renewed state the will of the creature is so absorbed in the will of the Creator,
that its life is swallowed up in it;
and it does not wish to enjoy any thing which is not "`freely given
to it of God;`" whose inscrutable wisdom bounds its desires,
and under a sense that it knows not what is best, it refers all thereto,
and thus it comes to experience "`new heavens and a new earth`" to be created unto it,
"`wherein dwells righteousness;`" and it abundantly rejoices in that which God creates,
as it is sensible that "`he creates Jerusalem, the city of the solemnities of his saints,
a rejoicing, and her people a joy.`"

Dear _____, be not dejected at the present dispensation of affliction,
nor indulge reasoning upon causes or events,
of which your natural understanding is incompetent to judge.
Remember that "`the Lord has a way in the clouds, and a path in the thick darkness,
and his footsteps are not known;`" they cannot be fully comprehended by mortals.
How vain therefore is the query.
Why have you allowed this or that? Yes, is it not worse than vain,
if our temporal interests, pleasure, or convenience,
are put in competition with his will and wisdom? He can restore what he deprives of,
or compensate for it;
and often does so abundantly to those who sincerely desire
that the light and momentary afflictions may work for them a
far more exceeding and eternal weight of glory,
and tend to their increasing in the present state in
that superlative blessing which makes truly rich,
and is unmixed with sorrow.

I am persuaded you have seen this blessing, yes, have tasted of it; but remember,
this is not enough; you must attentively behold and consider its worth,
and your desire to attain it must be strong and steady.
If you possess it and hold it fast, then will you be enabled to say,
"`I will not be afraid of evil tidings,`" nor of the
consequence of the loss of temporal goods of any kind,
"`My heart is fixed, trusting in the Lord,`" who upholds his children,
and provides from one stage of life to another, what is fitting for their accommodations,
and most conducive to their acquiring that
inheritance which is incorruptible and undefiled:
whereon I earnestly desire your attention and affection may henceforward be so fixed,
that you may experience that what has happened, however afflicting to nature,
has worked together for your real permanent good.

I was almost afraid to write to you,
as it appeared like touching a sore which might be a little healed;
but I hope my pen has been directed to steer clear of adding to your pain.
I saw nothing of what I have communicated when I began to write.
Receive it as a kind intimation from the Father of mercies,
as well as the cordial advice,
and affectionate desire for your experiencing your mind to be
so stayed upon the Lord as to become settled in true peace,
of your sympathizing

[.signed-section-signature]
Catherine Phillips

[.asterism]
'''

[.signed-section-context-open]
To Redruth, Eleventh month 2nd, 1793.

[.salutation]
Dear friend,

For with that epithet I hope I may
address you in the spiritual relationship,
having felt an affectionate sympathy with and regard for you,
although our personal acquaintance has not been such as
might induce a very free expression of it.
But one of my chief joys in my debilitated state is,
the hearing or seeing that the children of the elect lady (
which the church of Christ may be styled) walk in the Truth;
and a principal evidence of my continuing a living member of that church,
is my retaining a love to the brethren.
Indeed, I hope that this love is increased in my state of weakness,
and my desires are strong that the plantation of God may be so watered, weeded, pruned,
and watched over, as that its plants may flourish and be fruitful,
according to their kind, and the uses he assigns them.
That all the trees and plants in his extensive garden may rejoice together,
because they experience the advantage arising
from their sheltering each other from storms,
and expediting each other's growth,
although it may in some instances appear to diminish
the spreading of some plants of large magnitude,
and which also may be deeply rooted.
Such must at times evince their humility and
true greatness by a willingness to be lopped,
that room be made for young valuable plants growing near them, to expand.

Indeed, I see occasion for old trees, in the spiritual plantation, to be pruned,
as well as young ones, if they continue fruitful in the different seasons of life;
if they will not abide it,
barrenness and a contemptible appearance awaits them in the closing stage of life,
though they have been fruitful in the earlier periods of it.

May all the Lord's plants desire that he may turn his hand upon them
as often as he sees it needful for their preservation,
that they may produce well flavoured fruit in that
proportion which he knows their root can bear.
Alas, what great occasion is there for this pruning work in our highly favoured Society.
How many wild shoots have been allowed to remain and grow,
even to the destruction of some promising trees;
shoots which have plenteously produced the fruits of the first nature,
although they may not have the appearance of the worst kind.
How heavy laden with fruits of worldly mindedness are some,
whose outward appearance is specious.

Pretended self-denial is in many instances self-gratification,
and their zeal is not according to knowledge.
These masked characters among us, it appears to me, do more hurt than open libertines;
they create a distrust of the whole body of our members,
brand us with the stigma of hypocrisy, and sorely wound the living remnant,
who mourn for offences they cannot remedy,
and lament the discouragement administered by them to tender infant plants in our garden.

But what says the divine inspector to those who see and lament
the state of these burdensome members? "`Take heed to
yourselves,`" and when your hearts and hands are cleansed,
arise and labour in my garden to remove such plants as
will not be restored to beauty and fruitfulness;
and wisely nurse and train up those who are willing to receive instruction;
endeavour to support the weak, to comfort the feeble minded, reprove, exhort,
rebuke with all long-suffering and meekness.
Thus may you be instrumental to work a reformation,
and your spirits will be replenished with divine peace and love,
which will compensate for all labours, sufferings,
and the loss of every temporal blessing wherewith you may be tried.

It appears clear to me,
that if our living brethren and sisters who are nut
called to labour publicly in word and doctrine,
solemnly attended to their share of this rectifying work,
it would tend to an increase of true spiritual unity and sympathy amongst us.
There are indeed but few experienced fathers whose minds are affectionately
exercised for the children's growth and preservations which is probably one cause
why there are not more of the rebellious children turned to the wisdom of the just.
Private judicious admonition and cautions are not duly administered,
or endeavours used to gather the youthful stragglers
under the sheltering wing of wise elders.
I am thankfully sensible, notwithstanding, that the Lord is at work amongst us,
and I believe he will work powerfully to the reducing of the wills of
some who have been educated in the profession of the truth,
to the obedience of sonship,
and others who have wandered upon the mountains will become inhabitants of the valleys,
and be settled under the government of Israel's Shepherd.

But even such as are seeking the way to Zion,
and are earnestly desirous to be everlastingly united to the Lord and his people,
need much attention and help; they have much to leave behind,
and many discouragements to encounter;
and I think I have seen that if Friends watched
over such as are looking towards us in wisdom,
with a desire to be helpers of their faith,
and endeavoured by honest labour to rectify their errors and defects,
more of these might be brought forward, and in time become an additional strength to us.
I had no view of penning the foregoing sentiments when I began to write to you,
but finding an inclination to reply to your acceptable letter of the 10th ult.,
I have ventured to communicate them, in hope that if they meet your own,
it may tend to strengthen your resolution to attend to your share of
any part of the work divine wisdom may assign you in his church.
It has pleased him to deprive you of one of his most valuable temporal blessings;
may it tend to your enlargement in spiritual gifts,
and increase of the highest enjoyments.

I observe your remark of the probability of this nation
sharing in a greater degree than it has yet done,
of the cup of trembling, of which a neighbouring one drinks so deeply.
As a religious body called to peace, we should study to promote it,
and how we may edify not only one another,
but those also who may differ from us in religious profession;
exampling them how they ought to demean themselves
consistently with the gospel of the prince of Peace;
and if suffering be our lot, either for our testimony of a good conscience,
or in sharing the calamities wherewith the nation may be visited,
to seek for strength to bear them consistently with the dignity of our high, holy,
and peaceable profession.

Had your business led you this way,
I should have been pleased to have seen you and
conversed with you in the love and freedom of Truth.
I am visited by some valuable friends,
yet at times conclude myself a solitary afflicted widow,
increasing in bodily infirmities,
and able to do but little to promote the cause of righteousness.
He who judges righteously only knows the cause of my late great affliction,
whereto my most affectionate friends were in a great measure Wind.
May the dispensation of his mercy and judgement be so sanctified to my spirit,
as to prepare it for admittance into his kingdom when
dislodged from this decrepit and much afflicted tabernacle.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Catherine Phillips

[.asterism]
'''

[discrete.alt]
=== To_______, who had been long in a distressed state of mind, from some tenets esteemed religious.

[.salutation]
Esteemed friend,

The sympathy I have repeatedly felt with
your exercised mind has raised earnest desires in mine,
that Divine goodness may vouchsafe more fully to open your understanding
into the "`work of righteousness,`" and so enlarge your experience therein,
that you may witness it to be "`peace,`" and the
effect of it "`quietness and assurance forever.`"

Many are the stratagems of the subtle adversary of our
happiness to prevent our attaining to this desirable state,
which are only manifested by the light of Truth;
whereunto I have wished your mind might be effectually turned,
and your dependence fixed solely upon the one sure everlasting Helper.
For while you are seeking after men for instruction, and a settlement in the true faith,
you will be liable to be tossed to and fro by
the various and opposite doctrines preached;
and though ever hearing,
may never come to the knowledge of the Truth in its native simplicity.
Permit me, therefore, in true love, to entreat you to cease from them,
and humbly to wait upon the unerring Teacher,
who can and will "`guide you into all Truth,`"
if you are disposed implicitly to follow him.

It appears to me more necessary now for you to seek after resignation to the Divine will,
than to search into comments upon points of doctrine: for until we attain to that state,
we are not likely to "`receive the kingdom of God as little children;`" who,
knowing nothing, are to be instructed from one point of knowledge and duty to another,
and are passive to the direction of their tutors.
Those who are resigned to the Father's will, are to know of the doctrines of the Son:
unto these they are marvellously opened and sealed, so that they can say they believe,
not because of the testimony of others, but have "`the witness in themselves"

that they are the doctrines of Truth; and thus believing, they enter into rest,
being certain that they have acquired the knowledge of the Truth;
and pressing forward under its influence,
they experience a gradual advancing to the "`stature of manhood in Christ.`"

It is this holy certainty I desire you may be partaker of,
with those who are building upon the ancient "`foundation of the
apostles and prophets;`" for such there are in the present time as
surely as there were in the primitive ages of the church;
who know Jesus Christ to be the "`chief corner stone,`" and build upon him,
and rejoice in him, as their leader, feeder, and instructor;
through whom they worship the Father in spirit and in truth;
and look up to Him in all afflictions and exercises, in humble confidence,
that as a tender father, he cares for them and will supply all their needs.

Thus it was, in the morning of our day as a people,
that many sincere souls who had long wandered upon the mountains of profession,
and been exercised in various forms of godliness, seeking rest,
but not finding it therein,
obtained a settlement in the Truth as it is now professed amongst us,
which they possessed, and rejoiced therein.
For although the public profession of it exposed them to many
and grievous sufferings both in person and estate;
as well as to the general contempt of the world,
whose customs and manners they were constrained to contradict,
by a conduct and behaviour directly opposite thereto;
they being devoted to suffering for the testimony of a good conscience,
were favoured with that true peace which the world cannot give;
and in noisome prisons livingly praised Him who had called them,
not only to believe in Christ and his doctrines, but to suffer for him.
Many of these have left faithful records of their sufferings, exercises,
and experiences of the merciful dealings of the Lord with their souls;
which may he as marks in the way to those who are sincerely
seeking the same city which was prepared for them,
and tend to strengthen their resolution to walk as they did; in holy self-denial,
in contempt of the world, and in reverence and fear of offending Him,
who had graciously manifested himself to them as a God of infinite loving-kindness.
His compassion, my friend, fails not; but all who will come may come,
and upon the terms of submission to his will,
experience Him to blot out their transgressions, and be a father unto them.
In Him is no variableness, neither shadow of turning:
and if we of the present generation cleave steadily to Him,
and are willing to die that we may live,
we may be witnesses in our day to his power and mercy, and have to tell unto others,
what he has done for our souls.

I herewith send you a collection of memoirs,
etc. of one who had been under various forms and professions of religion;
and was in no mean station in the several religious societies,
which in quest of real peace he left; whereof I request your candid perusal.
I was induced to this freedom by frequently remembering you,
as I lately read some of them, which seemed adapted to an exercised mind;
and hope you will construe it as intended for a help to
settle yours in a right engagement before the Lord;
unto whose wisdom I commend you, only desiring you may be baptized into that state,
wherein, with the Captain of our salvation, you may be able to say, "`Father,
glorify your name,`" by my entire submission to your will.

I hope you will not suppose from any of the foregoing observations,
that I confine the peculiar favour of God, to the members of our Society,
to the exclusion of others.
No, I believe that amongst all sorts of people,
"`those who fear God and work righteousness,
are accepted of Him:`" but as faithfulness agreeable to
knowledge is the terms of our acceptance,
it behoves us to seek earnestly for strength to do, as well as to be desirous to know,
the heavenly Father's will;
and whoever is thus sincerely exercised is likely to attain to his salvation.
I am sorrowfully sensible of the great declension there
is amongst us as a religious Society,
from primitive purity and love to God; nevertheless,
the principle of light and life we profess, is unchangeably the same;
and there are yet with us, who, moving under its influence,
rejoice in the manifestation thereof to their souls.
That others under the same profession should run counter thereto,
is no more than may be expected, though much to be lamented;
for as now many hold the profession from education,
and are born with passions like other men,
until those passions come under Divine restriction,
they will produce their natural fruits.

I conclude with desiring, that "`the God of all consolation,
who raised from the dead our Lord Jesus Christ,
the great and true Shepherd of his own sheep,`" may so manifest him as such to your soul,
that, "`hearing his voice,
you may follow Him,`" and arrive to such an establishment in
righteousness as to be favoured with true peace,
and sincerely subscribe myself your friend,

[.signed-section-signature]
Catherine Phillips
