[#testimony.style-blurb, short="Testimony"]
== A Testimony from the monthly meeting of Friends for the Western Division of Cornwall, held at Falmouth the 6th of the fourth month, 1795, concerning our late valued friend, Catherine Phillips, formerly Payton.

It appears, from accounts received, that she was born at Dudley in Worcestershire,
the 16th of the first month, 1726-7, old Stile.
Her parents, Henry and Ann Payton were honourable Friends; and he an approved minister,
who, when in health, was much from home in the discharge of his religious duties;
but for many of the latter years of his life was
confined to his chamber by a paralytic disorder:
so that the care of a large young family devolved mostly upon his wife,
a woman of eminent piety and prudence, whose anxious solicitude for,
and watchful attention to, her children,
they have often commemorated with filial tenderness.

Thus instructed by example and precept,
our beloved friend was early engaged "`to seek the Lord for her portion,
and to know the God of her fathers to be the lot of her inheritance.`"
And being much the companion of her afflicted father,
she was probably thereby preserved from many levities incident to youth,
as well as edified by his innocent conduct and virtues.
In this allotment she had also opportunity to cultivate a disposition for retirement,
so favourable to the growth of that good seed which the
heavenly Husbandman had sown in her heart.
Nevertheless, as she advanced in years,
she found the propensities of natural inclination and wisdom
strongly opposed to the manifestation of Divine grace;
and through the conversation of some whose minds were not sufficiently
guarded by that fear "`which preserves from the snares of death;`" together
with the introduction of books inconsistent with the simplicity of Truth,
her best interest was greatly endangered.
But it pleased Him whose gracious purpose it was to separate her to his service,
about the seventeenth year of her age, to renew the powerful visitation of his love;
and being favoured to see the station designed for her in the church militant,
she was made willing to endure the baptisms necessary to that end.

Under this trying dispensation she experienced the enemy of
her soul to be a subtle as well as an open enemy;
and earnest were her petitions,
that she might be enabled to centre so deep in the resignation of her own will,
as clearly to distinguish his deceptive voice from that of the true Shepherd;
and thus be preserved from stepping forth in her service, before the appointed time.
And this petition was no doubt granted by Him
who saw the integrity and dedication of her mind:
for having, as we believe, passed through this work of preparation,
the fruit produced was correspondently mature;
and her progress in religious experience and usefulness distinguishably eminent.
Her first public appearance was in supplication at Dudley meeting,
on the 10th of the second month, 1748, being then in the twenty-second year of her age;
and in the following year she entered upon her travels in the ministry,
which continued with little intermission until within about nine years of her decease;
during which latter space she was mostly confined at home by indisposition of body.
Besides repeatedly visiting most of the counties in England and Wales,
her travels extended to Ireland, Scotland, Holland, and the continent of America:
in the course of which, according to accounts received,
her labours amongst Friends and others were blessed to the convincement, edification,
and comfort of many.

In the year 1772,
she entered upon the marriage state with our late valued friend William Phillips,
and removed into Cornwall; where she was much engaged in religious labour,
as well for the spreading of the testimonies of Truth among strangers,
as in repairing the waste places in the Society:
being often zealously concerned for the support of our Christian discipline,
that irremediable cases which had been too much neglected, and were as stumbling-blocks,
might be removed out of the way of sober inquirers;
and particularly for the right establishment of women`'s meetings,
in which her service was considerable.

During her long confinement and illness,
a little before which time her tenderly affectionate
husband was suddenly removed from her by death,
she was often deeply tried;
yet had to testify that the Lord`'s hand was still at
times revealed for her support and preservation,
and that his "`wisdom is stamped on every dispensation of his providence.`"
And although it was not permitted her to behold much fruit of
her many arduous labours and secret baptisms amongst us,
we believe they have been blessed to some of us; and with regard to others,
we have a hope,
as the Lord often sees fit for wise ends to veil from the view
of his faithful labourers the extent of their usefulness,
that the good seed sown through the instrumentality of
this highly favoured servant will not be lost;
but in due season produce the desired increase to the praise of his own ever worthy Name.

Some time before her decease, she thus expressed herself;
"`I am going where the wicked cease from troubling, and the weary are at rest.
Oh, these souls of ours! that we should be willing to run the risk
of losing them for any of the enjoyments of this life.
I may say to you, follow me as I have followed Christ.
Beware of pride, and of the very ground of pride.`"
When under pressure of great bodily suffering, she said, "`this is a trial;
Lord God Almighty sanctify it to my soul.`"
To one present she said, "`My dear child,
the Lord God Almighty bless you in every respect; all things may be done,
and all things may be borne, through faith and faithfulness to the Author of all good.`"
A few days before her removal, being at dinner, one remarked how little she ate.
She replied, "`it will do its office as long as necessary;
and I am thankful that I feel no cloud;`" and, making a short pause, added,
"`I have received a recompense at the Lord`'s hand for sin:`" soon after which,
the fits which attended her in this illness returned,
and continued till about half an hour before she expired,
during which space she lay very quiet,
and drew her breath shorter and shorter to the last.
She died the 16th of the eighth month, 1794, in the sixty-eighth year of her age,
and forty-sixth of her ministry; and,
after a meeting of Friends and others of the neighbourhood held on the occasion,
was decently interred at Kea.

Read and approved in said meeting, and signed by Thomas W. Fox, Benjamin Wilkey,
Richard Scantlebury, William James, James Hamilton, Samuel Tregelles, Silvanus James,
Joseph Honeychurch, Robert W. Fox, William Jenkin, Richard Fox, George Fox,
Samuel Tregelles, Jr. John Hamilton, David Richards, Tabitha Fox, Sarah Tregelles,
Eleanor Richards, Catherine Fox, Frances Fox, Mary Fox, Jr. Grace Dennis,
Eliza C. Jennings, Elizabeth Hingston, Hannah Fox, Anna Fox, Anna Price, Sarah James,
Rebecca Tregelles, Eliza R. Fox, Mary Hingston, Jr. Mary J. Fox, Catherine Richards,
Catherine Hamilton, Cath.
Phillips Tregelles, Elizabeth Philp.

Read and approved in our quarterly meeting for Cornwall,
held at Falmouth the 7th of the fourth month, 1795, and signed in and on behalf thereof,
by George Fox, Clerk.

[.signed-section-signature]
Anna Fox, Clerk
